// <auto-generated>
//     This code was generated by TargCC
//     Generated for: ccvwComboList_c_Job (Command)
//     Generation date: 2025-12-16 10:51:36
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using MediatR;
using UpayCard.RiskManagement.Application.Common.Models;

namespace UpayCard.RiskManagement.Application.Features.CcvwComboListCJobs.Commands;

/// <summary>
/// Command to create a new ccvwComboList_c_Job.
/// </summary>
public record CreateCcvwComboListCJobCommand : IRequest<Result<int>>
{
    /// <summary>
    /// Gets or sets the TextNS.
    /// </summary>
    public string TextNS { get; init; }

    /// <summary>
    /// Gets or sets the Text.
    /// </summary>
    public string Text { get; init; }

}
