// <auto-generated>
//     This code was generated by TargCC API Generator.
//     Generator: Mapping Profile Generator
//     Table: ccvwComboList_MCCBReceiverForCustomer
//     Generated: 2025-12-17 17:47:22
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using System;
using System.Linq;
using AutoMapper;

namespace UpayCard.RiskManagement.Application.Mapping
{
    /// <summary>
    /// AutoMapper profile for CcvwComboListMCCBReceiverForCustomer entity mappings.
    /// </summary>
    public class CcvwComboListMCCBReceiverForCustomerMappingProfile : Profile
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CcvwComboListMCCBReceiverForCustomerMappingProfile"/> class.
        /// </summary>
        public CcvwComboListMCCBReceiverForCustomerMappingProfile()
        {
            // Entity to Response DTO
            CreateMap<CcvwComboListMCCBReceiverForCustomer, CcvwComboListMCCBReceiverForCustomerDto>()
                .ReverseMap();

            // CreateRequest to Entity
            CreateMap<CreateCcvwComboListMCCBReceiverForCustomerRequest, CcvwComboListMCCBReceiverForCustomer>()
                ;

            // UpdateRequest to Entity
            CreateMap<UpdateCcvwComboListMCCBReceiverForCustomerRequest, CcvwComboListMCCBReceiverForCustomer>()
                ;
        }
    }
}
