// <auto-generated>
//     This code was generated by TargCC API Generator.
//     Generator: Mapping Profile Generator
//     Table: ccvwComboList_CardActivationForCustomer
//     Generated: 2025-12-17 17:47:21
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using System;
using System.Linq;
using AutoMapper;

namespace UpayCard.RiskManagement.Application.Mapping
{
    /// <summary>
    /// AutoMapper profile for CcvwComboListCardActivationForCustomer entity mappings.
    /// </summary>
    public class CcvwComboListCardActivationForCustomerMappingProfile : Profile
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CcvwComboListCardActivationForCustomerMappingProfile"/> class.
        /// </summary>
        public CcvwComboListCardActivationForCustomerMappingProfile()
        {
            // Entity to Response DTO
            CreateMap<CcvwComboListCardActivationForCustomer, CcvwComboListCardActivationForCustomerDto>()
                .ReverseMap();

            // CreateRequest to Entity
            CreateMap<CreateCcvwComboListCardActivationForCustomerRequest, CcvwComboListCardActivationForCustomer>()
                ;

            // UpdateRequest to Entity
            CreateMap<UpdateCcvwComboListCardActivationForCustomerRequest, CcvwComboListCardActivationForCustomer>()
                ;
        }
    }
}
