// <auto-generated>
//     This code was generated by TargCC API Generator.
//     Generator: Mapping Profile Generator
//     Table: LimitationOverride
//     Generated: 2025-12-17 17:47:24
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using System;
using System.Linq;
using AutoMapper;

namespace UpayCard.RiskManagement.Application.Mapping
{
    /// <summary>
    /// AutoMapper profile for LimitationOverride entity mappings.
    /// </summary>
    public class LimitationOverrideMappingProfile : Profile
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LimitationOverrideMappingProfile"/> class.
        /// </summary>
        public LimitationOverrideMappingProfile()
        {
            // Entity to Response DTO
            CreateMap<LimitationOverride, LimitationOverrideDto>()
                .ReverseMap();

            // CreateRequest to Entity
            CreateMap<CreateLimitationOverrideRequest, LimitationOverride>()
                ;

            // UpdateRequest to Entity
            CreateMap<UpdateLimitationOverrideRequest, LimitationOverride>()
                ;
        }
    }
}
