// <auto-generated>
//     This code was generated by TargCC API Generator.
//     Generator: Mapping Profile Generator
//     Table: c_Permission
//     Generated: 2025-12-17 17:47:20
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using System;
using System.Linq;
using AutoMapper;

namespace UpayCard.RiskManagement.Application.Mapping
{
    /// <summary>
    /// AutoMapper profile for Permission entity mappings.
    /// </summary>
    public class PermissionMappingProfile : Profile
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PermissionMappingProfile"/> class.
        /// </summary>
        public PermissionMappingProfile()
        {
            // Entity to Response DTO
            CreateMap<Permission, PermissionDto>()
                .ReverseMap();

            // CreateRequest to Entity
            CreateMap<CreatePermissionRequest, Permission>()
                ;

            // UpdateRequest to Entity
            CreateMap<UpdatePermissionRequest, Permission>()
                ;
        }
    }
}
