// <auto-generated>
//     This code was generated by TargCC API Generator.
//     Generator: Mapping Profile Generator
//     Table: c_Process
//     Generated: 2025-12-17 17:47:20
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using System;
using System.Linq;
using AutoMapper;

namespace UpayCard.RiskManagement.Application.Mapping
{
    /// <summary>
    /// AutoMapper profile for Process entity mappings.
    /// </summary>
    public class ProcessMappingProfile : Profile
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProcessMappingProfile"/> class.
        /// </summary>
        public ProcessMappingProfile()
        {
            // Entity to Response DTO
            CreateMap<Process, ProcessDto>()
                .ReverseMap();

            // CreateRequest to Entity
            CreateMap<CreateProcessRequest, Process>()
                ;

            // UpdateRequest to Entity
            CreateMap<UpdateProcessRequest, Process>()
                ;
        }
    }
}
