// <auto-generated>
//     This code was generated by TargCC Shared Models Generator.
//     Generated: 2025-12-17 07:22:06
// </auto-generated>

namespace UpayCard.RiskManagement.Domain.Common;

/// <summary>
/// Represents a single filter criterion for dynamic filtering.
/// </summary>
public class FilterCriteria
{
    /// <summary>
    /// Gets or sets the field name to filter on.
    /// </summary>
    public string Field { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the filter operator to use.
    /// </summary>
    public FilterOperator Operator { get; set; }

    /// <summary>
    /// Gets or sets the value to filter by.
    /// </summary>
    public object? Value { get; set; }
}
