// <auto-generated>
//     This code was generated by TargCC
//     Generated for: ccvwComboList_TransactionLoadAccount (Handler)
//     Generation date: 2025-12-15 22:18:50
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using MediatR;
using Microsoft.Extensions.Logging;
using TargCC.Application.Common.Models;
using TargCC.Domain.Entities;
using TargCC.Domain.Interfaces;

namespace TargCC.Application.Features.ccvwComboList_TransactionLoadAccounts.Commands;

/// <summary>
/// Handles the CreateCcvwComboListTransactionLoadAccountCommand request.
/// </summary>
public class CreateCcvwComboListTransactionLoadAccountHandler : IRequestHandler<CreateCcvwComboListTransactionLoadAccountCommand, Result<int>>
{
    private readonly IccvwComboList_TransactionLoadAccountRepository _repository;
    private readonly ILogger<CreateCcvwComboListTransactionLoadAccountHandler> _logger;

    /// <summary>
    /// Initializes a new instance of the <see cref="CreateCcvwComboListTransactionLoadAccountHandler"/> class.
    /// </summary>
    public CreateCcvwComboListTransactionLoadAccountHandler(
        IccvwComboList_TransactionLoadAccountRepository repository,
        ILogger<CreateCcvwComboListTransactionLoadAccountHandler> logger)
    {
        _repository = repository ?? throw new ArgumentNullException(nameof(repository));
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
    }

    /// <inheritdoc/>
    public async Task<Result<int>> Handle(CreateCcvwComboListTransactionLoadAccountCommand request, CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(request);

        _logger.LogDebug("Creating new ccvwComboList_TransactionLoadAccount");

        try
        {
            var entity = new ccvwComboList_TransactionLoadAccount
            {
                TextNS = request.TextNS,
                Text = request.Text
            };

            await _repository.AddAsync(entity, cancellationToken);

            _logger.LogInformation("ccvwComboList_TransactionLoadAccount created successfully with ID: {Id}", entity.Id);

            return Result<int>.Success(entity.Id);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error creating ccvwComboList_TransactionLoadAccount");
            throw;
        }
    }
}
