// <auto-generated>
//     This code was generated by TargCC
//     Generated for: ImportTransactionLoadRow (Validator)
//     Generation date: 2025-12-17 08:49:59
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using FluentValidation;

namespace UpayCard.RiskManagement.Application.Features.ImportTransactionLoadRows.Commands;

/// <summary>
/// Validator for CreateImportTransactionLoadRowCommand.
/// </summary>
public class CreateImportTransactionLoadRowValidator : AbstractValidator<CreateImportTransactionLoadRowCommand>
{
    /// <summary>
    /// Initializes a new instance of the <see cref="CreateImportTransactionLoadRowValidator"/> class.
    /// </summary>
    public CreateImportTransactionLoadRowValidator()
    {
        RuleFor(x => x.CustomerPhoneNumber)
            .NotEmpty()
            .MaximumLength(50)
            .Matches(@"^[+]?[0-9\s\-().]{7,20}$");

        RuleFor(x => x.enmCurrency)
            .NotEmpty()
            .MaximumLength(4);

        RuleFor(x => x.CardCid)
            .NotEmpty()
            .MaximumLength(50);

        RuleFor(x => x.CardLast4Numbers)
            .NotEmpty()
            .MaximumLength(4);

        RuleFor(x => x.LoadReference)
            .MaximumLength(100);

        RuleFor(x => x.CustomerFirstName)
            .NotEmpty()
            .MaximumLength(100);

        RuleFor(x => x.CustomerLastName)
            .NotEmpty()
            .MaximumLength(100);

        RuleFor(x => x.CustomerIdentifier)
            .NotEmpty()
            .MaximumLength(104);

        RuleFor(x => x.DeletedBy)
            .MaximumLength(100);

    }
}
