// <auto-generated>
//     This code was generated by TargCC
//     Generated for: c_LoggedJob (Command)
//     Generation date: 2025-12-17 08:54:21
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using MediatR;
using UpayCard.RiskManagement.Application.Common.Models;

namespace UpayCard.RiskManagement.Application.Features.LoggedJobs.Commands;

/// <summary>
/// Command to create a new c_LoggedJob.
/// </summary>
public record CreateLoggedJobCommand : IRequest<Result<long>>
{
    /// <summary>
    /// Gets or sets the c_JobID.
    /// </summary>
    public long? c_JobID { get; init; }

    /// <summary>
    /// Gets or sets the WhenStarted.
    /// </summary>
    public DateTime? WhenStarted { get; init; }

    /// <summary>
    /// Gets or sets the ActivatingUser.
    /// </summary>
    public string ActivatingUser { get; init; }

    /// <summary>
    /// Gets or sets the LastRunBy.
    /// </summary>
    public string LastRunBy { get; init; }

    /// <summary>
    /// Gets or sets the ExecutionTimeSec.
    /// </summary>
    public int? ExecutionTimeSec { get; init; }

    /// <summary>
    /// Gets or sets the enmRunStatus_JobStatus.
    /// </summary>
    public string enmRunStatus_JobStatus { get; init; }

    /// <summary>
    /// Gets or sets the Remarks.
    /// </summary>
    public string Remarks { get; init; }

    /// <summary>
    /// Gets or sets the c_LoggedAlertID.
    /// </summary>
    public long? c_LoggedAlertID { get; init; }

    /// <summary>
    /// Gets or sets the SuccessCount.
    /// </summary>
    public int? SuccessCount { get; init; }

    /// <summary>
    /// Gets or sets the FailureCount.
    /// </summary>
    public int? FailureCount { get; init; }

    /// <summary>
    /// Gets or sets the DeletedBy.
    /// </summary>
    public string DeletedBy { get; init; }

    /// <summary>
    /// Gets or sets the DeletedOn.
    /// </summary>
    public DateTime? DeletedOn { get; init; }

    /// <summary>
    /// Gets or sets the UpdatingLoginID.
    /// </summary>
    public long? UpdatingLoginID { get; init; }

}
