// <copyright file="SharedModelsGenerator.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

namespace TargCC.Core.Generators.Common;

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;

/// <summary>
/// Generates shared model classes used across all entities for pagination and filtering.
/// Creates common infrastructure classes like PagedResult, PaginationParams, etc.
/// </summary>
public class SharedModelsGenerator
{
    private static readonly Action<ILogger, int, Exception?> LogGeneratedSharedModels =
        LoggerMessage.Define<int>(
            LogLevel.Information,
            new EventId(1, nameof(LogGeneratedSharedModels)),
            "Generated {Count} shared model files");

    private readonly ILogger<SharedModelsGenerator> _logger;

    /// <summary>
    /// Initializes a new instance of the <see cref="SharedModelsGenerator"/> class.
    /// </summary>
    /// <param name="logger">Logger instance.</param>
    public SharedModelsGenerator(ILogger<SharedModelsGenerator> logger)
    {
        ArgumentNullException.ThrowIfNull(logger);
        _logger = logger;
    }

    /// <summary>
    /// Generates all shared model classes for a project.
    /// </summary>
    /// <param name="namespace">The root namespace for the project.</param>
    /// <returns>A dictionary mapping file names to their content.</returns>
    public async Task<Dictionary<string, string>> GenerateAllAsync(string @namespace)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(@namespace);

        return await Task.Run(() =>
        {
            var files = new Dictionary<string, string>
            {
                ["PagedResult.cs"] = GeneratePagedResult(@namespace),
                ["PaginationParams.cs"] = GeneratePaginationParams(@namespace),
                ["FilterOperator.cs"] = GenerateFilterOperator(@namespace),
                ["FilterCriteria.cs"] = GenerateFilterCriteria(@namespace),
                ["Result.cs"] = GenerateResult(@namespace)
            };

            LogGeneratedSharedModels(_logger, files.Count, null);

            return files;
        }).ConfigureAwait(false);
    }

    /// <summary>
    /// Generates the PagedResult class used for paginated API responses.
    /// </summary>
    /// <param name="namespace">The root namespace.</param>
    /// <returns>The generated PagedResult class code.</returns>
    private static string GeneratePagedResult(string @namespace)
    {
        var sb = new StringBuilder();

        // File header
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//     This code was generated by TargCC Shared Models Generator.");
        sb.AppendLine(CultureInfo.InvariantCulture, $"//     Generated: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();

        // Namespace and usings
        sb.AppendLine(CultureInfo.InvariantCulture, $"namespace {@namespace}.Domain.Common;");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();

        // Class documentation
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Represents a paginated result set with metadata.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("/// <typeparam name=\"T\">The type of items in the result set.</typeparam>");
        sb.AppendLine("public class PagedResult<T>");
        sb.AppendLine("{");

        // Items property
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Gets or sets the list of items in the current page.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public List<T> Items { get; set; } = new List<T>();");
        sb.AppendLine();

        // TotalCount property
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Gets or sets the total number of items across all pages.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public int TotalCount { get; set; }");
        sb.AppendLine();

        // Page property
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Gets or sets the current page number (1-based).");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public int Page { get; set; }");
        sb.AppendLine();

        // PageSize property
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Gets or sets the number of items per page.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public int PageSize { get; set; }");
        sb.AppendLine();

        // TotalPages computed property
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Gets the total number of pages.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public int TotalPages => PageSize > 0 ? (int)Math.Ceiling(TotalCount / (double)PageSize) : 0;");
        sb.AppendLine();

        // HasPreviousPage computed property
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Gets a value indicating whether there is a previous page.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public bool HasPreviousPage => Page > 1;");
        sb.AppendLine();

        // HasNextPage computed property
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Gets a value indicating whether there is a next page.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public bool HasNextPage => Page < TotalPages;");

        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Generates the PaginationParams class for pagination parameters.
    /// </summary>
    /// <param name="namespace">The root namespace.</param>
    /// <returns>The generated PaginationParams class code.</returns>
    private static string GeneratePaginationParams(string @namespace)
    {
        var sb = new StringBuilder();

        // File header
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//     This code was generated by TargCC Shared Models Generator.");
        sb.AppendLine(CultureInfo.InvariantCulture, $"//     Generated: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();

        // Namespace
        sb.AppendLine(CultureInfo.InvariantCulture, $"namespace {@namespace}.Domain.Common;");
        sb.AppendLine();

        // Class documentation
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Common pagination parameters used across all queries.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public class PaginationParams");
        sb.AppendLine("{");

        // Page property
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Gets or sets the page number (1-based). Default is 1.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public int Page { get; set; } = 1;");
        sb.AppendLine();

        // PageSize property
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Gets or sets the number of items per page. Default is 100.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public int PageSize { get; set; } = 100;");
        sb.AppendLine();

        // SortBy property
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Gets or sets the field name to sort by. Default is null (use default sorting).");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public string? SortBy { get; set; }");
        sb.AppendLine();

        // SortDirection property
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Gets or sets the sort direction ('asc' or 'desc'). Default is 'asc'.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public string SortDirection { get; set; } = \"asc\";");

        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Generates the FilterOperator enum for filter operations.
    /// </summary>
    /// <param name="namespace">The root namespace.</param>
    /// <returns>The generated FilterOperator enum code.</returns>
    private static string GenerateFilterOperator(string @namespace)
    {
        var sb = new StringBuilder();

        // File header
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//     This code was generated by TargCC Shared Models Generator.");
        sb.AppendLine(CultureInfo.InvariantCulture, $"//     Generated: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();

        // Namespace
        sb.AppendLine(CultureInfo.InvariantCulture, $"namespace {@namespace}.Domain.Common;");
        sb.AppendLine();

        // Enum documentation
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Defines the available filter operators for dynamic filtering.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public enum FilterOperator");
        sb.AppendLine("{");

        // Enum values with documentation
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Exact equality comparison.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    Equals,");
        sb.AppendLine();

        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Inequality comparison.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    NotEquals,");
        sb.AppendLine();

        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// String contains comparison (case-insensitive).");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    Contains,");
        sb.AppendLine();

        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// String starts with comparison.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    StartsWith,");
        sb.AppendLine();

        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// String ends with comparison.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    EndsWith,");
        sb.AppendLine();

        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Greater than comparison.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    GreaterThan,");
        sb.AppendLine();

        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Greater than or equal comparison.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    GreaterThanOrEqual,");
        sb.AppendLine();

        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Less than comparison.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    LessThan,");
        sb.AppendLine();

        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Less than or equal comparison.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    LessThanOrEqual,");
        sb.AppendLine();

        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Value is in a list of values.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    In,");
        sb.AppendLine();

        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Value is not in a list of values.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    NotIn,");
        sb.AppendLine();

        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Value is null.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    IsNull,");
        sb.AppendLine();

        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Value is not null.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    IsNotNull,");
        sb.AppendLine();

        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Value is between two values (inclusive).");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    Between");

        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Generates the FilterCriteria class for dynamic filtering.
    /// </summary>
    /// <param name="namespace">The root namespace.</param>
    /// <returns>The generated FilterCriteria class code.</returns>
    private static string GenerateFilterCriteria(string @namespace)
    {
        var sb = new StringBuilder();

        // File header
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//     This code was generated by TargCC Shared Models Generator.");
        sb.AppendLine(CultureInfo.InvariantCulture, $"//     Generated: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();

        // Namespace
        sb.AppendLine(CultureInfo.InvariantCulture, $"namespace {@namespace}.Domain.Common;");
        sb.AppendLine();

        // Class documentation
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Represents a single filter criterion for dynamic filtering.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public class FilterCriteria");
        sb.AppendLine("{");

        // Field property
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Gets or sets the field name to filter on.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public string Field { get; set; } = string.Empty;");
        sb.AppendLine();

        // Operator property
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Gets or sets the filter operator to use.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public FilterOperator Operator { get; set; }");
        sb.AppendLine();

        // Value property
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Gets or sets the value to filter by.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public object? Value { get; set; }");

        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Generates the Result class used for operation results with success/failure handling.
    /// </summary>
    /// <param name="namespace">The root namespace.</param>
    /// <returns>The generated Result class code.</returns>
    private static string GenerateResult(string @namespace)
    {
        var sb = new StringBuilder();

        // File header
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//     This code was generated by TargCC Shared Models Generator.");
        sb.AppendLine(CultureInfo.InvariantCulture, $"//     Generated: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();

        // Namespace and usings
        sb.AppendLine(CultureInfo.InvariantCulture, $"namespace {@namespace}.Application.Common.Models;");
        sb.AppendLine();

        // Result class (non-generic)
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Represents the result of an operation without return data.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public class Result");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Initializes a new instance of the <see cref=\"Result\"/> class.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    protected Result(bool isSuccess, string? error)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (isSuccess && error != null)");
        sb.AppendLine("            throw new InvalidOperationException(\"A successful result cannot have an error message.\");");
        sb.AppendLine("        if (!isSuccess && error == null)");
        sb.AppendLine("            throw new InvalidOperationException(\"A failed result must have an error message.\");");
        sb.AppendLine();
        sb.AppendLine("        IsSuccess = isSuccess;");
        sb.AppendLine("        Error = error;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Gets a value indicating whether the operation was successful.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public bool IsSuccess { get; init; }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Gets a value indicating whether the operation failed.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public bool IsFailure => !IsSuccess;");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Gets the error message if the operation failed; otherwise, null.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public string? Error { get; init; }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Creates a successful result.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static Result Success() => new (true, null);");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Creates a failed result with an error message.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static Result Failure(string error) => new (false, error);");
        sb.AppendLine("}");
        sb.AppendLine();

        // Result<T> class (generic)
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Represents the result of an operation with return data.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("/// <typeparam name=\"T\">The type of data returned by the operation.</typeparam>");
        sb.AppendLine("public class Result<T> : Result");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Initializes a new instance of the <see cref=\"Result{T}\"/> class.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    private Result(bool isSuccess, T? value, string? error) : base(isSuccess, error)");
        sb.AppendLine("    {");
        sb.AppendLine("        Value = value;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Gets the value returned by the operation if successful; otherwise, default value.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public T? Value { get; init; }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Creates a successful result with a value.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static Result<T> Success(T value) => new (true, value, null);");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Creates a failed result with an error message.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static new Result<T> Failure(string error) => new (false, default, error);");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
