// <auto-generated>
//     This code was generated by TargCC Component Generator.
//     Table: Lead
//     Generated: 2025-12-11 14:19:36
// </auto-generated>

import React, { useEffect } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { useForm } from 'react-hook-form';
import { TextField, Button, Box, Alert, CircularProgress, Select, MenuItem, FormControl, InputLabel, Checkbox, FormControlLabel } from '@mui/material';
import { useLead, useCreateLead, useUpdateLead } from '../../hooks/useLead';
import type { CreateLeadRequest, UpdateLeadRequest } from '../../types/Lead.types';


export const LeadForm: React.FC = () => {
  const navigate = useNavigate();
  const { id } = useParams<{ id: string }>();
  const leadId = id && id !== 'new' ? Number(id) : undefined;
  const isEdit = !!leadId;

  const { data: existingLead, isPending: isLoadingEntity } = useLead(leadId || null);

  const {
    register,
    handleSubmit,
    reset,
    formState: { errors },
  } = useForm<CreateLeadRequest>({
    defaultValues: {
    },
  });

  // Update form when data loads
  useEffect(() => {
    if (existingLead) {
      reset(existingLead);
    }
  }, [existingLead, reset]);

  const { mutate: createEntity, isPending: isCreating } = useCreateLead();
  const { mutate: updateEntity, isPending: isUpdating } = useUpdateLead();

  const isSubmitting = isCreating || isUpdating;

  const onSubmit = (data: CreateLeadRequest) => {
    if (isEdit && leadId) {
      updateEntity(
        { id: leadId, data: data as UpdateLeadRequest },
        { onSuccess: () => navigate('/leads') }
      );
    } else {
      createEntity(data, { onSuccess: () => navigate('/leads') });
    }
  };

  if (isEdit && isLoadingEntity) {
    return <CircularProgress />;
  }

  return (
    <Box component="form" onSubmit={handleSubmit(onSubmit)} sx={{ maxWidth: 600 }}>
      <FormControlLabel
        control={<Checkbox {...register('tableNameLead')} />}
        label="TableNameLead"
      />

      <TextField
        label="LkpLeadOrigin"
        type="text"
        fullWidth
        margin="normal"
        {...register('lkpLeadOrigin', { maxLength: { value: 50, message: 'Maximum length is 50' } })}
        error={!!errors.lkpLeadOrigin}
        helperText={errors.lkpLeadOrigin?.message}
      />

      <TextField
        label="FirstName"
        type="text"
        fullWidth
        margin="normal"
        {...register('firstName', { maxLength: { value: 100, message: 'Maximum length is 100' } })}
        error={!!errors.firstName}
        helperText={errors.firstName?.message}
      />

      <TextField
        label="LastName"
        type="text"
        fullWidth
        margin="normal"
        {...register('lastName', { maxLength: { value: 100, message: 'Maximum length is 100' } })}
        error={!!errors.lastName}
        helperText={errors.lastName?.message}
      />

      <TextField
        label="Email"
        type="text"
        fullWidth
        margin="normal"
        {...register('email', { maxLength: { value: 50, message: 'Maximum length is 50' }, pattern: { value: /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i, message: 'Invalid email address' } })}
        error={!!errors.email}
        helperText={errors.email?.message}
      />

      <TextField
        label="CellPhone"
        type="text"
        fullWidth
        margin="normal"
        {...register('cellPhone', { maxLength: { value: 50, message: 'Maximum length is 50' }, pattern: { value: /^[0-9+\-()\s]+$/, message: 'Invalid phone number' } })}
        error={!!errors.cellPhone}
        helperText={errors.cellPhone?.message}
      />

      <TextField
        label="Subject"
        type="text"
        fullWidth
        margin="normal"
        {...register('subject', { maxLength: { value: 100, message: 'Maximum length is 100' } })}
        error={!!errors.subject}
        helperText={errors.subject?.message}
      />

      <TextField
        label="Message"
        type="text"
        fullWidth
        margin="normal"
        {...register('message', {  })}
        error={!!errors.message}
        helperText={errors.message?.message}
      />

      <TextField
        label="Comment"
        fullWidth
        margin="normal"
        {...register('comment', {  })}
        error={!!errors.comment}
        helperText={errors.comment?.message}
      />

      <TextField
        label="WhenOpened"
        type="date"
        fullWidth
        margin="normal"
        InputLabelProps={{ shrink: true }}
        {...register('whenOpened', { maxLength: { value: 10, message: 'Maximum length is 10' } })}
        error={!!errors.whenOpened}
        helperText={errors.whenOpened?.message}
      />

      <TextField
        label="EnmStatus"
        type="text"
        fullWidth
        margin="normal"
        {...register('enmStatus', { maxLength: { value: 50, message: 'Maximum length is 50' } })}
        error={!!errors.enmStatus}
        helperText={errors.enmStatus?.message}
      />

      <TextField
        label="WhenStatusChanged"
        type="date"
        fullWidth
        margin="normal"
        InputLabelProps={{ shrink: true }}
        {...register('whenStatusChanged', { maxLength: { value: 10, message: 'Maximum length is 10' } })}
        error={!!errors.whenStatusChanged}
        helperText={errors.whenStatusChanged?.message}
      />

      <TextField
        label="DeletedBy"
        type="text"
        fullWidth
        margin="normal"
        {...register('deletedBy', { maxLength: { value: 100, message: 'Maximum length is 100' } })}
        error={!!errors.deletedBy}
        helperText={errors.deletedBy?.message}
      />

      <TextField
        label="DeletedOn"
        type="date"
        fullWidth
        margin="normal"
        InputLabelProps={{ shrink: true }}
        {...register('deletedOn', { maxLength: { value: 8, message: 'Maximum length is 8' } })}
        error={!!errors.deletedOn}
        helperText={errors.deletedOn?.message}
      />

      <TextField
        label="UpdatingLoginID"
        type="number"
        fullWidth
        margin="normal"
        {...register('updatingLoginID', { maxLength: { value: 8, message: 'Maximum length is 8' } })}
        error={!!errors.updatingLoginID}
        helperText={errors.updatingLoginID?.message}
      />



      <Box sx={{ mt: 2, display: 'flex', gap: 2 }}>
        <Button type="submit" variant="contained" disabled={isSubmitting}>
          {isEdit ? 'Update' : 'Create'}
        </Button>
        <Button variant="outlined" onClick={() => navigate('/leads')}>
          Cancel
        </Button>
      </Box>
    </Box>
  );
};

