// <auto-generated>
//     This code was generated by TargCC
//     Generated for: c_Job (Handler)
//     Generation date: 2025-12-15 22:18:47
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using MediatR;
using Microsoft.Extensions.Logging;
using TargCC.Application.Common.Models;
using TargCC.Domain.Entities;
using TargCC.Domain.Interfaces;

namespace TargCC.Application.Features.c_Jobs.Commands;

/// <summary>
/// Handles the CreateJobCommand request.
/// </summary>
public class CreateJobHandler : IRequestHandler<CreateJobCommand, Result<int>>
{
    private readonly Ic_JobRepository _repository;
    private readonly ILogger<CreateJobHandler> _logger;

    /// <summary>
    /// Initializes a new instance of the <see cref="CreateJobHandler"/> class.
    /// </summary>
    public CreateJobHandler(
        Ic_JobRepository repository,
        ILogger<CreateJobHandler> logger)
    {
        _repository = repository ?? throw new ArgumentNullException(nameof(repository));
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
    }

    /// <inheritdoc/>
    public async Task<Result<int>> Handle(CreateJobCommand request, CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(request);

        _logger.LogDebug("Creating new c_Job");

        try
        {
            var entity = new c_Job
            {
                TableName_c_Job = request.TableName_c_Job,
                lkpJob = request.lkpJob,
                lkpJobRunner = request.lkpJobRunner,
                Description = request.Description,
                Instructions = request.Instructions,
                enmJobType = request.enmJobType,
                WhenToRun = request.WhenToRun,
                CyclicCount = request.CyclicCount,
                SendNotificationOnSuccess = request.SendNotificationOnSuccess,
                SendAlarmOnMissed = request.SendAlarmOnMissed,
                TimeOutSec = request.TimeOutSec,
                Active = request.Active,
                ActivatingUser = request.ActivatingUser,
                NextRunTime = request.NextRunTime,
                LastRunTime = request.LastRunTime,
                enmJobStatus = request.enmJobStatus,
                WarningMailSent = request.WarningMailSent,
                IsManaged = request.IsManaged,
                LastRunBy = request.LastRunBy,
                AddedBy = request.AddedBy,
                AddedOn = request.AddedOn,
                ChangedBy = request.ChangedBy,
                ChangedOn = request.ChangedOn,
                DeletedBy = request.DeletedBy,
                DeletedOn = request.DeletedOn,
                UpdatingLoginID = request.UpdatingLoginID
            };

            await _repository.AddAsync(entity, cancellationToken);

            _logger.LogInformation("c_Job created successfully with ID: {Id}", entity.Id);

            return Result<int>.Success(entity.Id);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error creating c_Job");
            throw;
        }
    }
}
