// <auto-generated>
//     This code was generated by TargCC.Core.Generators v2.0
//     Generated from table: dbo.c_Enumeration
//     Generation date: 2025-12-17 21:45:20
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

namespace UpayCard.RiskManagement.Domain.Interfaces;

using UpayCard.RiskManagement.Domain.Entities;

/// <summary>
/// Repository interface for Enumeration entity data access operations.
/// </summary>
/// <remarks>
/// <para>
/// This interface defines the contract for data access operations on the Enumeration entity.
/// It follows the Repository pattern and is implemented in the Infrastructure layer.
/// </para>
/// <para>
/// <strong>Implementation:</strong> See <c>EnumerationRepository</c> in Infrastructure layer.
/// </para>
/// </remarks>
public interface IEnumerationRepository
{
    /// <summary>
    /// Gets a Enumeration entity by its primary key.
    /// </summary>
    /// <param name="id">The primary key value.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The Enumeration entity if found; otherwise, null.</returns>
    System.Threading.Tasks.Task<Enumeration?> GetByIdAsync(int id, CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets all Enumeration entities with optional filtering and paging.
    /// </summary>
    /// <param name="skip">Number of entities to skip (for paging).</param>
    /// <param name="take">Number of entities to take (for paging).</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>Collection of Enumeration entities.</returns>
    System.Threading.Tasks.Task<IEnumerable<Enumeration>> GetAllAsync(int? skip = null, int? take = null, CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets filtered Enumeration entities based on indexed columns.
    /// </summary>
    /// <param name="enumType">Filter by EnumType (optional).</param>
    /// <param name="enumValue">Filter by EnumValue (optional).</param>
    /// <param name="skip">Number of entities to skip (for paging).</param>
    /// <param name="take">Number of entities to take (for paging).</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>Collection of filtered Enumeration entities.</returns>
    System.Threading.Tasks.Task<IEnumerable<Enumeration>> GetFilteredAsync(string? enumType = null, string? enumValue = null, int? skip = null, int? take = null, CancellationToken cancellationToken = default);

    /// <summary>
    /// Adds a new Enumeration entity to the database.
    /// </summary>
    /// <param name="entity">The Enumeration entity to add.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>A task representing the asynchronous operation.</returns>
    System.Threading.Tasks.Task AddAsync(Enumeration entity, CancellationToken cancellationToken = default);

    /// <summary>
    /// Updates an existing Enumeration entity in the database.
    /// </summary>
    /// <param name="entity">The Enumeration entity to update.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>A task representing the asynchronous operation.</returns>
    System.Threading.Tasks.Task UpdateAsync(Enumeration entity, CancellationToken cancellationToken = default);

    /// <summary>
    /// Deletes a Enumeration entity from the database.
    /// </summary>
    /// <param name="id">The primary key value of the entity to delete.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>A task representing the asynchronous operation.</returns>
    System.Threading.Tasks.Task DeleteAsync(int id, CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets a Enumeration entity by EnumType and EnumValue.
    /// </summary>
    /// <param name="enumType">The EnumType value to search for.</param>
    /// <param name="enumValue">The EnumValue value to search for.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The Enumeration entity if found; otherwise, null.</returns>
    System.Threading.Tasks.Task<Enumeration?> GetByEnumTypeAndEnumValueAsync(string enumType, string enumValue, CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets all Enumeration entities matching the specified EnumType.
    /// </summary>
    /// <param name="enumType">The EnumType value to filter by.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>Collection of Enumeration entities matching the criteria.</returns>
    System.Threading.Tasks.Task<IEnumerable<Enumeration>> GetByEnumTypeAsync(string enumType, CancellationToken cancellationToken = default);

    /// <summary>
    /// Checks if a Enumeration entity exists with the specified primary key.
    /// </summary>
    /// <param name="id">The primary key value to check.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>True if the entity exists; otherwise, false.</returns>
    System.Threading.Tasks.Task<bool> ExistsAsync(int id, CancellationToken cancellationToken = default);
}
