// <auto-generated>
//     This code was generated by TargCC.Core.Generators v2.0
//     Generated from table: dbo.c_JobAlertRecipient
//     Generation date: 2025-12-11 11:52:10
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

namespace UpayCard.RiskManagement.Domain.Interfaces;

using UpayCard.RiskManagement.Domain.Entities;

/// <summary>
/// Repository interface for JobAlertRecipient entity data access operations.
/// </summary>
/// <remarks>
/// <para>
/// This interface defines the contract for data access operations on the JobAlertRecipient entity.
/// It follows the Repository pattern and is implemented in the Infrastructure layer.
/// </para>
/// <para>
/// <strong>Implementation:</strong> See <c>JobAlertRecipientRepository</c> in Infrastructure layer.
/// </para>
/// </remarks>
public interface IJobAlertRecipientRepository
{
    /// <summary>
    /// Gets a JobAlertRecipient entity by its primary key.
    /// </summary>
    /// <param name="id">The primary key value.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The JobAlertRecipient entity if found; otherwise, null.</returns>
    Task<JobAlertRecipient?> GetByIdAsync(long id, CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets all JobAlertRecipient entities with optional filtering and paging.
    /// </summary>
    /// <param name="skip">Number of entities to skip (for paging).</param>
    /// <param name="take">Number of entities to take (for paging).</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>Collection of JobAlertRecipient entities.</returns>
    Task<IEnumerable<JobAlertRecipient>> GetAllAsync(int? skip = null, int? take = null, CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets filtered JobAlertRecipient entities based on indexed columns.
    /// </summary>
    /// <param name="c_JobID">Filter by c_JobID (optional).</param>
    /// <param name="c_UserID">Filter by c_UserID (optional).</param>
    /// <param name="enmJobAlertType">Filter by enmJobAlertType (optional).</param>
    /// <param name="skip">Number of entities to skip (for paging).</param>
    /// <param name="take">Number of entities to take (for paging).</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>Collection of filtered JobAlertRecipient entities.</returns>
    Task<IEnumerable<JobAlertRecipient>> GetFilteredAsync(long? c_JobID = null, long? c_UserID = null, string? enmJobAlertType = null, int? skip = null, int? take = null, CancellationToken cancellationToken = default);

    /// <summary>
    /// Adds a new JobAlertRecipient entity to the database.
    /// </summary>
    /// <param name="entity">The JobAlertRecipient entity to add.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>A task representing the asynchronous operation.</returns>
    Task AddAsync(JobAlertRecipient entity, CancellationToken cancellationToken = default);

    /// <summary>
    /// Updates an existing JobAlertRecipient entity in the database.
    /// </summary>
    /// <param name="entity">The JobAlertRecipient entity to update.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>A task representing the asynchronous operation.</returns>
    Task UpdateAsync(JobAlertRecipient entity, CancellationToken cancellationToken = default);

    /// <summary>
    /// Deletes a JobAlertRecipient entity from the database.
    /// </summary>
    /// <param name="id">The primary key value of the entity to delete.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>A task representing the asynchronous operation.</returns>
    Task DeleteAsync(long id, CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets all JobAlertRecipient entities matching the specified c_JobID.
    /// </summary>
    /// <param name="c_JobID">The c_JobID value to filter by.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>Collection of JobAlertRecipient entities matching the criteria.</returns>
    Task<IEnumerable<JobAlertRecipient>> GetByc_JobIDAsync(long c_JobID, CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets all JobAlertRecipient entities matching the specified c_UserID.
    /// </summary>
    /// <param name="c_UserID">The c_UserID value to filter by.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>Collection of JobAlertRecipient entities matching the criteria.</returns>
    Task<IEnumerable<JobAlertRecipient>> GetByc_UserIDAsync(long c_UserID, CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets all JobAlertRecipient entities matching the specified enmJobAlertType.
    /// </summary>
    /// <param name="enmJobAlertType">The enmJobAlertType value to filter by.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>Collection of JobAlertRecipient entities matching the criteria.</returns>
    Task<IEnumerable<JobAlertRecipient>> GetByenmJobAlertTypeAsync(string enmJobAlertType, CancellationToken cancellationToken = default);

    /// <summary>
    /// Checks if a JobAlertRecipient entity exists with the specified primary key.
    /// </summary>
    /// <param name="id">The primary key value to check.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>True if the entity exists; otherwise, false.</returns>
    Task<bool> ExistsAsync(long id, CancellationToken cancellationToken = default);
}
