// <auto-generated>
//     This code was generated by TargCC.Core.Generators v2.0
//     Generated from table: dbo.c_LoggedAlert
//     Generation date: 2025-12-15 13:53:26
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

namespace UpayCard.RiskManagement.Domain.Interfaces;

using UpayCard.RiskManagement.Domain.Entities;

/// <summary>
/// Repository interface for LoggedAlert entity data access operations.
/// </summary>
/// <remarks>
/// <para>
/// This interface defines the contract for data access operations on the LoggedAlert entity.
/// It follows the Repository pattern and is implemented in the Infrastructure layer.
/// </para>
/// <para>
/// <strong>Implementation:</strong> See <c>LoggedAlertRepository</c> in Infrastructure layer.
/// </para>
/// </remarks>
public interface ILoggedAlertRepository
{
    /// <summary>
    /// Gets a LoggedAlert entity by its primary key.
    /// </summary>
    /// <param name="id">The primary key value.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The LoggedAlert entity if found; otherwise, null.</returns>
    System.Threading.Tasks.Task<LoggedAlert?> GetByIdAsync(long id, CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets all LoggedAlert entities with optional filtering and paging.
    /// </summary>
    /// <param name="skip">Number of entities to skip (for paging).</param>
    /// <param name="take">Number of entities to take (for paging).</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>Collection of LoggedAlert entities.</returns>
    System.Threading.Tasks.Task<IEnumerable<LoggedAlert>> GetAllAsync(int? skip = null, int? take = null, CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets filtered LoggedAlert entities based on indexed columns.
    /// </summary>
    /// <param name="callingApplication">Filter by CallingApplication (optional).</param>
    /// <param name="dateOccurred">Filter by clc_DateOccurred (optional).</param>
    /// <param name="faultNumber">Filter by FaultNumber (optional).</param>
    /// <param name="enmFaultSeverity_FaultSeverity">Filter by enmFaultSeverity_FaultSeverity (optional).</param>
    /// <param name="enmFaultType_FaultType">Filter by enmFaultType_FaultType (optional).</param>
    /// <param name="c_LoggedLoginID">Filter by c_LoggedLoginID (optional).</param>
    /// <param name="monthOccurred">Filter by clc_MonthOccurred (optional).</param>
    /// <param name="systemName">Filter by SystemName (optional).</param>
    /// <param name="timeOccurred">Filter by TimeOccurred (optional).</param>
    /// <param name="affectedUserID">Filter by AffectedUserID (optional).</param>
    /// <param name="skip">Number of entities to skip (for paging).</param>
    /// <param name="take">Number of entities to take (for paging).</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>Collection of filtered LoggedAlert entities.</returns>
    System.Threading.Tasks.Task<IEnumerable<LoggedAlert>> GetFilteredAsync(string? callingApplication = null, DateTime? dateOccurred = null, int? faultNumber = null, string? enmFaultSeverity_FaultSeverity = null, string? enmFaultType_FaultType = null, long? c_LoggedLoginID = null, DateTime? monthOccurred = null, string? systemName = null, DateTime? timeOccurred = null, long? affectedUserID = null, int? skip = null, int? take = null, CancellationToken cancellationToken = default);

    /// <summary>
    /// Adds a new LoggedAlert entity to the database.
    /// </summary>
    /// <param name="entity">The LoggedAlert entity to add.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>A task representing the asynchronous operation.</returns>
    System.Threading.Tasks.Task AddAsync(LoggedAlert entity, CancellationToken cancellationToken = default);

    /// <summary>
    /// Updates an existing LoggedAlert entity in the database.
    /// </summary>
    /// <param name="entity">The LoggedAlert entity to update.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>A task representing the asynchronous operation.</returns>
    System.Threading.Tasks.Task UpdateAsync(LoggedAlert entity, CancellationToken cancellationToken = default);

    /// <summary>
    /// Deletes a LoggedAlert entity from the database.
    /// </summary>
    /// <param name="id">The primary key value of the entity to delete.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>A task representing the asynchronous operation.</returns>
    System.Threading.Tasks.Task DeleteAsync(long id, CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets all LoggedAlert entities matching the specified CallingApplication.
    /// </summary>
    /// <param name="callingApplication">The CallingApplication value to filter by.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>Collection of LoggedAlert entities matching the criteria.</returns>
    System.Threading.Tasks.Task<IEnumerable<LoggedAlert>> GetByCallingApplicationAsync(string callingApplication, CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets all LoggedAlert entities matching the specified clc_DateOccurred.
    /// </summary>
    /// <param name="dateOccurred">The DateOccurred value to filter by.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>Collection of LoggedAlert entities matching the criteria.</returns>
    System.Threading.Tasks.Task<IEnumerable<LoggedAlert>> GetByDateOccurredAsync(DateTime dateOccurred, CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets all LoggedAlert entities matching the specified FaultNumber.
    /// </summary>
    /// <param name="faultNumber">The FaultNumber value to filter by.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>Collection of LoggedAlert entities matching the criteria.</returns>
    System.Threading.Tasks.Task<IEnumerable<LoggedAlert>> GetByFaultNumberAsync(int faultNumber, CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets all LoggedAlert entities matching the specified enmFaultSeverity_FaultSeverity.
    /// </summary>
    /// <param name="enmFaultSeverity_FaultSeverity">The enmFaultSeverity_FaultSeverity value to filter by.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>Collection of LoggedAlert entities matching the criteria.</returns>
    System.Threading.Tasks.Task<IEnumerable<LoggedAlert>> GetByenmFaultSeverity_FaultSeverityAsync(string enmFaultSeverity_FaultSeverity, CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets all LoggedAlert entities matching the specified enmFaultType_FaultType.
    /// </summary>
    /// <param name="enmFaultType_FaultType">The enmFaultType_FaultType value to filter by.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>Collection of LoggedAlert entities matching the criteria.</returns>
    System.Threading.Tasks.Task<IEnumerable<LoggedAlert>> GetByenmFaultType_FaultTypeAsync(string enmFaultType_FaultType, CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets all LoggedAlert entities matching the specified enmFaultType_FaultType and enmFaultSeverity_FaultSeverity.
    /// </summary>
    /// <param name="enmFaultType_FaultType">The enmFaultType_FaultType value to filter by.</param>
    /// <param name="enmFaultSeverity_FaultSeverity">The enmFaultSeverity_FaultSeverity value to filter by.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>Collection of LoggedAlert entities matching the criteria.</returns>
    System.Threading.Tasks.Task<IEnumerable<LoggedAlert>> GetByenmFaultType_FaultTypeAndenmFaultSeverity_FaultSeverityAsync(string enmFaultType_FaultType, string enmFaultSeverity_FaultSeverity, CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets all LoggedAlert entities matching the specified c_LoggedLoginID.
    /// </summary>
    /// <param name="c_LoggedLoginID">The c_LoggedLoginID value to filter by.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>Collection of LoggedAlert entities matching the criteria.</returns>
    System.Threading.Tasks.Task<IEnumerable<LoggedAlert>> GetByc_LoggedLoginIDAsync(long c_LoggedLoginID, CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets all LoggedAlert entities matching the specified clc_MonthOccurred.
    /// </summary>
    /// <param name="monthOccurred">The MonthOccurred value to filter by.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>Collection of LoggedAlert entities matching the criteria.</returns>
    System.Threading.Tasks.Task<IEnumerable<LoggedAlert>> GetByMonthOccurredAsync(DateTime monthOccurred, CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets all LoggedAlert entities matching the specified SystemName.
    /// </summary>
    /// <param name="systemName">The SystemName value to filter by.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>Collection of LoggedAlert entities matching the criteria.</returns>
    System.Threading.Tasks.Task<IEnumerable<LoggedAlert>> GetBySystemNameAsync(string systemName, CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets all LoggedAlert entities matching the specified TimeOccurred.
    /// </summary>
    /// <param name="timeOccurred">The TimeOccurred value to filter by.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>Collection of LoggedAlert entities matching the criteria.</returns>
    System.Threading.Tasks.Task<IEnumerable<LoggedAlert>> GetByTimeOccurredAsync(DateTime timeOccurred, CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets all LoggedAlert entities matching the specified TimeOccurred and enmFaultType_FaultType and enmFaultSeverity_FaultSeverity.
    /// </summary>
    /// <param name="timeOccurred">The TimeOccurred value to filter by.</param>
    /// <param name="enmFaultType_FaultType">The enmFaultType_FaultType value to filter by.</param>
    /// <param name="enmFaultSeverity_FaultSeverity">The enmFaultSeverity_FaultSeverity value to filter by.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>Collection of LoggedAlert entities matching the criteria.</returns>
    System.Threading.Tasks.Task<IEnumerable<LoggedAlert>> GetByTimeOccurredAndenmFaultType_FaultTypeAndenmFaultSeverity_FaultSeverityAsync(DateTime timeOccurred, string enmFaultType_FaultType, string enmFaultSeverity_FaultSeverity, CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets all LoggedAlert entities matching the specified AffectedUserID.
    /// </summary>
    /// <param name="affectedUserID">The AffectedUserID value to filter by.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>Collection of LoggedAlert entities matching the criteria.</returns>
    System.Threading.Tasks.Task<IEnumerable<LoggedAlert>> GetByAffectedUserIDAsync(long affectedUserID, CancellationToken cancellationToken = default);

    // ======================================
    // Master-Detail Views (Related Data)
    // ======================================

    /// <summary>
    /// Fetches all c_loggedjobs for the specified c_loggedalert.
    /// </summary>
    /// <param name="c_LoggedAlertId">The c_LoggedAlert ID.</param>
    /// <param name="skip">Number of records to skip (for pagination).</param>
    /// <param name="take">Number of records to take (for pagination).</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>A collection of LoggedJob entities.</returns>
    System.Threading.Tasks.Task<IEnumerable<LoggedJob>> Getc_LoggedJobsAsync(long c_LoggedAlertId, int? skip = null, int? take = null, CancellationToken cancellationToken = default);

    /// <summary>
    /// Fetches all cardorderfromissuers for the specified c_loggedalert.
    /// </summary>
    /// <param name="c_LoggedAlertId">The c_LoggedAlert ID.</param>
    /// <param name="skip">Number of records to skip (for pagination).</param>
    /// <param name="take">Number of records to take (for pagination).</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>A collection of CardOrderFromIssuer entities.</returns>
    System.Threading.Tasks.Task<IEnumerable<CardOrderFromIssuer>> GetCardOrderFromIssuersAsync(long c_LoggedAlertId, int? skip = null, int? take = null, CancellationToken cancellationToken = default);

    /// <summary>
    /// Fetches all importtransactionloadrows for the specified c_loggedalert.
    /// </summary>
    /// <param name="c_LoggedAlertId">The c_LoggedAlert ID.</param>
    /// <param name="skip">Number of records to skip (for pagination).</param>
    /// <param name="take">Number of records to take (for pagination).</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>A collection of ImportTransactionLoadRow entities.</returns>
    System.Threading.Tasks.Task<IEnumerable<ImportTransactionLoadRow>> GetImportTransactionLoadRowsAsync(long c_LoggedAlertId, int? skip = null, int? take = null, CancellationToken cancellationToken = default);

    /// <summary>
    /// Fetches all newcardrequests for the specified c_loggedalert.
    /// </summary>
    /// <param name="c_LoggedAlertId">The c_LoggedAlert ID.</param>
    /// <param name="skip">Number of records to skip (for pagination).</param>
    /// <param name="take">Number of records to take (for pagination).</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>A collection of NewCardRequest entities.</returns>
    System.Threading.Tasks.Task<IEnumerable<NewCardRequest>> GetNewCardRequestsAsync(long c_LoggedAlertId, int? skip = null, int? take = null, CancellationToken cancellationToken = default);

    /// <summary>
    /// Fetches all newcardrequestapis for the specified c_loggedalert.
    /// </summary>
    /// <param name="c_LoggedAlertId">The c_LoggedAlert ID.</param>
    /// <param name="skip">Number of records to skip (for pagination).</param>
    /// <param name="take">Number of records to take (for pagination).</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>A collection of NewCardRequestAPI entities.</returns>
    System.Threading.Tasks.Task<IEnumerable<NewCardRequestAPI>> GetNewCardRequestAPIsAsync(long c_LoggedAlertId, int? skip = null, int? take = null, CancellationToken cancellationToken = default);

    /// <summary>
    /// Fetches all requestedtransactions for the specified c_loggedalert.
    /// </summary>
    /// <param name="c_LoggedAlertId">The c_LoggedAlert ID.</param>
    /// <param name="skip">Number of records to skip (for pagination).</param>
    /// <param name="take">Number of records to take (for pagination).</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>A collection of RequestedTransaction entities.</returns>
    System.Threading.Tasks.Task<IEnumerable<RequestedTransaction>> GetRequestedTransactionsAsync(long c_LoggedAlertId, int? skip = null, int? take = null, CancellationToken cancellationToken = default);

    /// <summary>
    /// Fetches all transactionloads for the specified c_loggedalert.
    /// </summary>
    /// <param name="c_LoggedAlertId">The c_LoggedAlert ID.</param>
    /// <param name="skip">Number of records to skip (for pagination).</param>
    /// <param name="take">Number of records to take (for pagination).</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>A collection of TransactionLoad entities.</returns>
    System.Threading.Tasks.Task<IEnumerable<TransactionLoad>> GetTransactionLoadsAsync(long c_LoggedAlertId, int? skip = null, int? take = null, CancellationToken cancellationToken = default);

    /// <summary>
    /// Checks if a LoggedAlert entity exists with the specified primary key.
    /// </summary>
    /// <param name="id">The primary key value to check.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>True if the entity exists; otherwise, false.</returns>
    System.Threading.Tasks.Task<bool> ExistsAsync(long id, CancellationToken cancellationToken = default);
}
