// <auto-generated>
//     This code was generated by TargCC.Core.Generators v2.0
//     Generated from table: dbo.ccvwComboList_CardClub
//     Generation date: 2025-12-11 21:58:10
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

namespace UpayCard.RiskManagement.Domain.Interfaces;

using UpayCard.RiskManagement.Domain.Entities;

/// <summary>
/// Repository interface for CcvwComboListCardClub entity data access operations.
/// </summary>
/// <remarks>
/// <para>
/// This interface defines the contract for data access operations on the CcvwComboListCardClub entity.
/// It follows the Repository pattern and is implemented in the Infrastructure layer.
/// </para>
/// <para>
/// <strong>Implementation:</strong> See <c>CcvwComboListCardClubRepository</c> in Infrastructure layer.
/// </para>
/// </remarks>
public interface ICcvwComboListCardClubRepository
{
    /// <summary>
    /// Gets a CcvwComboListCardClub entity by its primary key.
    /// </summary>
    /// <param name="id">The primary key value.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The CcvwComboListCardClub entity if found; otherwise, null.</returns>
    System.Threading.Tasks.Task<CcvwComboListCardClub?> GetByIdAsync(long id, CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets all CcvwComboListCardClub entities with optional filtering and paging.
    /// </summary>
    /// <param name="skip">Number of entities to skip (for paging).</param>
    /// <param name="take">Number of entities to take (for paging).</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>Collection of CcvwComboListCardClub entities.</returns>
    System.Threading.Tasks.Task<IEnumerable<CcvwComboListCardClub>> GetAllAsync(int? skip = null, int? take = null, CancellationToken cancellationToken = default);

    /// <summary>
    /// Checks if a CcvwComboListCardClub entity exists with the specified primary key.
    /// </summary>
    /// <param name="id">The primary key value to check.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>True if the entity exists; otherwise, false.</returns>
    System.Threading.Tasks.Task<bool> ExistsAsync(long id, CancellationToken cancellationToken = default);
}
