// <auto-generated>
//     This code was generated by TargCC.Core.Generators v2.0
//     Generated from table: dbo.ccvwComboList_RiskEvent
//     Generation date: 2025-12-11 13:48:46
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

namespace UpayCard.RiskManagement.Domain.Interfaces;

using UpayCard.RiskManagement.Domain.Entities;

/// <summary>
/// Repository interface for CcvwComboListRiskEvent entity data access operations.
/// </summary>
/// <remarks>
/// <para>
/// This interface defines the contract for data access operations on the CcvwComboListRiskEvent entity.
/// It follows the Repository pattern and is implemented in the Infrastructure layer.
/// </para>
/// <para>
/// <strong>Implementation:</strong> See <c>CcvwComboListRiskEventRepository</c> in Infrastructure layer.
/// </para>
/// </remarks>
public interface ICcvwComboListRiskEventRepository
{
    /// <summary>
    /// Gets a CcvwComboListRiskEvent entity by its primary key.
    /// </summary>
    /// <param name="id">The primary key value.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The CcvwComboListRiskEvent entity if found; otherwise, null.</returns>
    Task<CcvwComboListRiskEvent?> GetByIdAsync(long id, CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets all CcvwComboListRiskEvent entities with optional filtering and paging.
    /// </summary>
    /// <param name="skip">Number of entities to skip (for paging).</param>
    /// <param name="take">Number of entities to take (for paging).</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>Collection of CcvwComboListRiskEvent entities.</returns>
    Task<IEnumerable<CcvwComboListRiskEvent>> GetAllAsync(int? skip = null, int? take = null, CancellationToken cancellationToken = default);

    /// <summary>
    /// Checks if a CcvwComboListRiskEvent entity exists with the specified primary key.
    /// </summary>
    /// <param name="id">The primary key value to check.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>True if the entity exists; otherwise, false.</returns>
    Task<bool> ExistsAsync(long id, CancellationToken cancellationToken = default);
}
