// <auto-generated>
//     This code was generated by TargCC.Core.Generators v2.0
//     Generated from table: dbo.ExchangeRate
//     Generation date: 2025-12-15 22:55:58
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

namespace UpayCard.RiskManagement.Domain.Interfaces;

using UpayCard.RiskManagement.Domain.Entities;

/// <summary>
/// Repository interface for ExchangeRate entity data access operations.
/// </summary>
/// <remarks>
/// <para>
/// This interface defines the contract for data access operations on the ExchangeRate entity.
/// It follows the Repository pattern and is implemented in the Infrastructure layer.
/// </para>
/// <para>
/// <strong>Implementation:</strong> See <c>ExchangeRateRepository</c> in Infrastructure layer.
/// </para>
/// </remarks>
public interface IExchangeRateRepository
{
    /// <summary>
    /// Gets a ExchangeRate entity by its primary key.
    /// </summary>
    /// <param name="id">The primary key value.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The ExchangeRate entity if found; otherwise, null.</returns>
    System.Threading.Tasks.Task<ExchangeRate?> GetByIdAsync(long id, CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets all ExchangeRate entities with optional filtering and paging.
    /// </summary>
    /// <param name="skip">Number of entities to skip (for paging).</param>
    /// <param name="take">Number of entities to take (for paging).</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>Collection of ExchangeRate entities.</returns>
    System.Threading.Tasks.Task<IEnumerable<ExchangeRate>> GetAllAsync(int? skip = null, int? take = null, CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets filtered ExchangeRate entities based on indexed columns.
    /// </summary>
    /// <param name="enmCurrency">Filter by enmCurrency (optional).</param>
    /// <param name="skip">Number of entities to skip (for paging).</param>
    /// <param name="take">Number of entities to take (for paging).</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>Collection of filtered ExchangeRate entities.</returns>
    System.Threading.Tasks.Task<IEnumerable<ExchangeRate>> GetFilteredAsync(string? enmCurrency = null, int? skip = null, int? take = null, CancellationToken cancellationToken = default);

    /// <summary>
    /// Adds a new ExchangeRate entity to the database.
    /// </summary>
    /// <param name="entity">The ExchangeRate entity to add.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>A task representing the asynchronous operation.</returns>
    System.Threading.Tasks.Task AddAsync(ExchangeRate entity, CancellationToken cancellationToken = default);

    /// <summary>
    /// Updates an existing ExchangeRate entity in the database.
    /// </summary>
    /// <param name="entity">The ExchangeRate entity to update.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>A task representing the asynchronous operation.</returns>
    System.Threading.Tasks.Task UpdateAsync(ExchangeRate entity, CancellationToken cancellationToken = default);

    /// <summary>
    /// Deletes a ExchangeRate entity from the database.
    /// </summary>
    /// <param name="id">The primary key value of the entity to delete.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>A task representing the asynchronous operation.</returns>
    System.Threading.Tasks.Task DeleteAsync(long id, CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets a ExchangeRate entity by enmCurrency.
    /// </summary>
    /// <param name="enmCurrency">The enmCurrency value to search for.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The ExchangeRate entity if found; otherwise, null.</returns>
    System.Threading.Tasks.Task<ExchangeRate?> GetByenmCurrencyAsync(string enmCurrency, CancellationToken cancellationToken = default);

    /// <summary>
    /// Checks if a ExchangeRate entity exists with the specified primary key.
    /// </summary>
    /// <param name="id">The primary key value to check.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>True if the entity exists; otherwise, false.</returns>
    System.Threading.Tasks.Task<bool> ExistsAsync(long id, CancellationToken cancellationToken = default);
}
