// <auto-generated>
//     This code was generated by TargCC.Core.Generators v2.0
//     Generated from table: dbo.vwReportDistributorObligoBalance
//     Generation date: 2025-12-17 09:02:41
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

namespace UpayCard.RiskManagement.Domain.Interfaces;

using UpayCard.RiskManagement.Domain.Entities;

/// <summary>
/// Repository interface for VwReportDistributorObligoBalance entity data access operations.
/// </summary>
/// <remarks>
/// <para>
/// This interface defines the contract for data access operations on the VwReportDistributorObligoBalance entity.
/// It follows the Repository pattern and is implemented in the Infrastructure layer.
/// </para>
/// <para>
/// <strong>Implementation:</strong> See <c>VwReportDistributorObligoBalanceRepository</c> in Infrastructure layer.
/// </para>
/// </remarks>
public interface IVwReportDistributorObligoBalanceRepository
{
    /// <summary>
    /// Gets a VwReportDistributorObligoBalance entity by its primary key.
    /// </summary>
    /// <param name="id">The primary key value.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The VwReportDistributorObligoBalance entity if found; otherwise, null.</returns>
    System.Threading.Tasks.Task<VwReportDistributorObligoBalance?> GetByIdAsync(long id, CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets all VwReportDistributorObligoBalance entities with optional filtering and paging.
    /// </summary>
    /// <param name="skip">Number of entities to skip (for paging).</param>
    /// <param name="take">Number of entities to take (for paging).</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>Collection of VwReportDistributorObligoBalance entities.</returns>
    System.Threading.Tasks.Task<IEnumerable<VwReportDistributorObligoBalance>> GetAllAsync(int? skip = null, int? take = null, CancellationToken cancellationToken = default);

    /// <summary>
    /// Checks if a VwReportDistributorObligoBalance entity exists with the specified primary key.
    /// </summary>
    /// <param name="id">The primary key value to check.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>True if the entity exists; otherwise, false.</returns>
    System.Threading.Tasks.Task<bool> ExistsAsync(long id, CancellationToken cancellationToken = default);
}
