// <auto-generated>
//     This code was generated by TargCC
//     Generated for: RiskRuleLog (Command)
//     Generation date: 2025-12-17 08:54:26
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using MediatR;
using UpayCard.RiskManagement.Application.Common.Models;

namespace UpayCard.RiskManagement.Application.Features.RiskRuleLogs.Commands;

/// <summary>
/// Command to create a new RiskRuleLog.
/// </summary>
public record CreateRiskRuleLogCommand : IRequest<Result<long>>
{
    /// <summary>
    /// Gets or sets the TableName_RiskRuleLog.
    /// </summary>
    public bool? TableName_RiskRuleLog { get; init; }

    /// <summary>
    /// Gets or sets the RiskRuleID.
    /// </summary>
    public long RiskRuleID { get; init; }

    /// <summary>
    /// Gets or sets the ChangeType.
    /// </summary>
    public string ChangeType { get; init; } = string.Empty;

    /// <summary>
    /// Gets or sets the FieldName.
    /// </summary>
    public string FieldName { get; init; }

    /// <summary>
    /// Gets or sets the OldValue.
    /// </summary>
    public string OldValue { get; init; }

    /// <summary>
    /// Gets or sets the NewValue.
    /// </summary>
    public string NewValue { get; init; }

    /// <summary>
    /// Gets or sets the ChangeReason.
    /// </summary>
    public string ChangeReason { get; init; }

    /// <summary>
    /// Gets or sets the UpdatingLoginID.
    /// </summary>
    public long? UpdatingLoginID { get; init; }

}
