// <auto-generated>
//     This code was generated by TargCC.Core.Generators v2.0
//     Generated from table: dbo.GovtReport99
//     Generation date: 2025-12-17 08:54:25
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

namespace UpayCard.RiskManagement.Infrastructure.Repositories;

using System.Data;
using System.Threading;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using UpayCard.RiskManagement.Domain.Entities;
using UpayCard.RiskManagement.Domain.Interfaces;

/// <summary>
/// Repository implementation for GovtReport99 entity data access operations.
/// </summary>
/// <remarks>
/// <para>
/// This repository provides data access for the GovtReport99 entity using Dapper
/// for stored procedure calls. All operations are async and support cancellation.
/// </para>
/// </remarks>
public class GovtReport99Repository : IGovtReport99Repository
{
    private readonly IDbConnection _connection;
    private readonly ILogger<GovtReport99Repository> _logger;

    /// <summary>
    /// Initializes a new instance of the <see cref="GovtReport99Repository"/> class.
    /// </summary>
    /// <param name="connection">Database connection for Dapper operations.</param>
    /// <param name="logger">Logger for tracking repository operations.</param>
    public GovtReport99Repository(IDbConnection connection, ILogger<GovtReport99Repository> logger)
    {
        _connection = connection ?? throw new ArgumentNullException(nameof(connection));
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
    }

    /// <inheritdoc/>
    public async System.Threading.Tasks.Task<GovtReport99?> GetByIdAsync(long id, CancellationToken cancellationToken = default)
    {
        _logger.LogDebug("Getting GovtReport99 by ID: {Id}", id);

        try
        {
            var result = await _connection.QueryFirstOrDefaultAsync<GovtReport99>(
                "SP_GetGovtReport99ByID",
                new { ID = id },
                commandType: CommandType.StoredProcedure);

            _logger.LogDebug("GovtReport99 found: {Found}", result != null);
            return result;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error getting GovtReport99 by ID: {Id}", id);
            throw;
        }
    }

    /// <inheritdoc/>
    public async System.Threading.Tasks.Task<IEnumerable<GovtReport99>> GetAllAsync(int? skip = null, int? take = null, CancellationToken cancellationToken = default)
    {
        _logger.LogDebug("Getting all GovtReport99 entities. Skip: {Skip}, Take: {Take}", skip, take);

        try
        {
            var result = await _connection.QueryAsync<GovtReport99>(
                "SP_GetAllGovtReport99s",
                new { Skip = skip, Take = take },
                commandType: CommandType.StoredProcedure);

            _logger.LogDebug("Retrieved {Count} GovtReport99 entities", result.Count());
            return result;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error getting all GovtReport99 entities");
            throw;
        }
    }

    /// <inheritdoc/>
    public async System.Threading.Tasks.Task<IEnumerable<GovtReport99>> GetFilteredAsync(long? govtReport00ID = null, int? skip = null, int? take = null, CancellationToken cancellationToken = default)
    {
        _logger.LogDebug("Getting filtered GovtReport99 entities");

        try
        {
            var parameters = new {
                GovtReport00ID = govtReport00ID,
                Skip = skip,
                Take = take
            };

            var result = await _connection.QueryAsync<GovtReport99>(
                "SP_GetFilteredGovtReport99s",
                parameters,
                commandType: CommandType.StoredProcedure);

            _logger.LogDebug("Retrieved {Count} filtered GovtReport99 entities", result.Count());
            return result;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error getting filtered GovtReport99 entities");
            throw;
        }
    }

    /// <inheritdoc/>
    public async System.Threading.Tasks.Task AddAsync(GovtReport99 entity, CancellationToken cancellationToken = default)
    {
        if (entity == null)
        {
            throw new ArgumentNullException(nameof(entity));
        }

        _logger.LogDebug("Adding new GovtReport99");

        try
        {
            var parameters = new DynamicParameters();
            parameters.Add("@TableName_GovtReport99", entity.TableName_GovtReport99);
            parameters.Add("@GovtReport00ID", entity.GovtReport00ID);
            parameters.Add("@ReporterNumber", entity.ReporterNumber);
            parameters.Add("@ReporterIDNumber", entity.ReporterIDNumber);
            parameters.Add("@ReportYear", entity.ReportYear);
            parameters.Add("@ReportNumber", entity.ReportNumber);
            parameters.Add("@RecordType", entity.RecordType);
            parameters.Add("@ReportMonth", entity.ReportMonth);
            parameters.Add("@NumberOfRowsIn10", entity.NumberOfRowsIn10);
            parameters.Add("@NumberOfRowsIn30", entity.NumberOfRowsIn30);
            parameters.Add("@NumberOfRowsIn40", entity.NumberOfRowsIn40);
            parameters.Add("@DeletedBy", entity.DeletedBy);
            parameters.Add("@DeletedOn", entity.DeletedOn);
            parameters.Add("@UpdatingLoginID", entity.UpdatingLoginID);
            parameters.Add("@AddedBy", entity.AddedBy);

            await _connection.ExecuteAsync(
                "SP_AddGovtReport99",
                parameters,
                commandType: CommandType.StoredProcedure);

            _logger.LogInformation("GovtReport99 added successfully");
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error adding GovtReport99");
            throw;
        }
    }

    /// <inheritdoc/>
    public async System.Threading.Tasks.Task UpdateAsync(GovtReport99 entity, CancellationToken cancellationToken = default)
    {
        if (entity == null)
        {
            throw new ArgumentNullException(nameof(entity));
        }

        _logger.LogDebug("Updating GovtReport99 with ID: {Id}", entity.ID);

        try
        {
            var parameters = new DynamicParameters();
            parameters.Add("@ID", entity.ID);
            parameters.Add("@TableName_GovtReport99", entity.TableName_GovtReport99);
            parameters.Add("@GovtReport00ID", entity.GovtReport00ID);
            parameters.Add("@ReporterNumber", entity.ReporterNumber);
            parameters.Add("@ReporterIDNumber", entity.ReporterIDNumber);
            parameters.Add("@ReportYear", entity.ReportYear);
            parameters.Add("@ReportNumber", entity.ReportNumber);
            parameters.Add("@RecordType", entity.RecordType);
            parameters.Add("@ReportMonth", entity.ReportMonth);
            parameters.Add("@NumberOfRowsIn10", entity.NumberOfRowsIn10);
            parameters.Add("@NumberOfRowsIn30", entity.NumberOfRowsIn30);
            parameters.Add("@NumberOfRowsIn40", entity.NumberOfRowsIn40);
            parameters.Add("@DeletedBy", entity.DeletedBy);
            parameters.Add("@DeletedOn", entity.DeletedOn);
            parameters.Add("@UpdatingLoginID", entity.UpdatingLoginID);
            parameters.Add("@ChangedBy", entity.ChangedBy);

            await _connection.ExecuteAsync(
                "SP_UpdateGovtReport99",
                parameters,
                commandType: CommandType.StoredProcedure);

            _logger.LogInformation("GovtReport99 updated successfully. ID: {Id}", entity.ID);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error updating GovtReport99 with ID: {Id}", entity.ID);
            throw;
        }
    }

    /// <inheritdoc/>
    public async System.Threading.Tasks.Task DeleteAsync(long id, CancellationToken cancellationToken = default)
    {
        _logger.LogDebug("Deleting GovtReport99 with ID: {Id}", id);

        try
        {
            await _connection.ExecuteAsync(
                "SP_DeleteGovtReport99",
                new { ID = id },
                commandType: CommandType.StoredProcedure);

            _logger.LogInformation("GovtReport99 deleted successfully. ID: {Id}", id);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error deleting GovtReport99 with ID: {Id}", id);
            throw;
        }
    }

    /// <inheritdoc/>
    public async System.Threading.Tasks.Task<GovtReport99?> GetByGovtReport00IDAsync(long govtReport00ID, CancellationToken cancellationToken = default)
    {
        _logger.LogDebug("Getting GovtReport99 by GovtReport00ID");

        try
        {
            var result = await _connection.QueryFirstOrDefaultAsync<GovtReport99>(
                "SP_GetGovtReport99ByGovtReport00ID",
                new { GovtReport00ID = govtReport00ID },
                commandType: CommandType.StoredProcedure);

            _logger.LogDebug("GovtReport99 found: {Found}", result != null);
            return result;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error getting GovtReport99 by GovtReport00ID");
            throw;
        }
    }

    /// <inheritdoc/>
    public async Task<bool> ExistsAsync(long id, CancellationToken cancellationToken = default)
    {
        _logger.LogDebug("Checking if GovtReport99 exists with ID: {Id}", id);

        try
        {
            var result = await _connection.QueryFirstOrDefaultAsync<GovtReport99>(
                "SP_GetGovtReport99ByID",
                new { ID = id },
                commandType: CommandType.StoredProcedure);

            bool exists = result != null;
            _logger.LogDebug("GovtReport99 exists: {Exists}", exists);
            return exists;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error checking if GovtReport99 exists. ID: {Id}", id);
            throw;
        }
    }
}
