// <auto-generated>
//     This code was generated by TargCC.Core.Generators v2.0
//     Generated from table: dbo.vwReportWalletTransfer
//     Generation date: 2025-12-15 09:25:40
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

namespace UpayCard.RiskManagement.Infrastructure.Repositories;

using System.Data;
using System.Threading;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using UpayCard.RiskManagement.Domain.Entities;
using UpayCard.RiskManagement.Domain.Interfaces;

/// <summary>
/// Repository implementation for VwReportWalletTransfer entity data access operations.
/// </summary>
/// <remarks>
/// <para>
/// This repository provides data access for the VwReportWalletTransfer entity using Dapper
/// for stored procedure calls. All operations are async and support cancellation.
/// </para>
/// </remarks>
public class VwReportWalletTransferRepository : IVwReportWalletTransferRepository
{
    private readonly IDbConnection _connection;
    private readonly ILogger<VwReportWalletTransferRepository> _logger;

    /// <summary>
    /// Initializes a new instance of the <see cref="VwReportWalletTransferRepository"/> class.
    /// </summary>
    /// <param name="connection">Database connection for Dapper operations.</param>
    /// <param name="logger">Logger for tracking repository operations.</param>
    public VwReportWalletTransferRepository(IDbConnection connection, ILogger<VwReportWalletTransferRepository> logger)
    {
        _connection = connection ?? throw new ArgumentNullException(nameof(connection));
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
    }

    /// <inheritdoc/>
    public async System.Threading.Tasks.Task<VwReportWalletTransfer?> GetByIdAsync(long id, CancellationToken cancellationToken = default)
    {
        _logger.LogDebug("Getting VwReportWalletTransfer by ID: {Id}", id);

        try
        {
            var result = await _connection.QueryFirstOrDefaultAsync<VwReportWalletTransfer>(
                "SP_GetVwReportWalletTransferByID",
                new { ID = id },
                commandType: CommandType.StoredProcedure);

            _logger.LogDebug("VwReportWalletTransfer found: {Found}", result != null);
            return result;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error getting VwReportWalletTransfer by ID: {Id}", id);
            throw;
        }
    }

    /// <inheritdoc/>
    public async System.Threading.Tasks.Task<IEnumerable<VwReportWalletTransfer>> GetAllAsync(int? skip = null, int? take = null, CancellationToken cancellationToken = default)
    {
        _logger.LogDebug("Getting all VwReportWalletTransfer entities. Skip: {Skip}, Take: {Take}", skip, take);

        try
        {
            var result = await _connection.QueryAsync<VwReportWalletTransfer>(
                "SP_GetAllVwReportWalletTransfers",
                new { Skip = skip, Take = take },
                commandType: CommandType.StoredProcedure);

            _logger.LogDebug("Retrieved {Count} VwReportWalletTransfer entities", result.Count());
            return result;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error getting all VwReportWalletTransfer entities");
            throw;
        }
    }

    /// <inheritdoc/>
    public async Task<bool> ExistsAsync(long id, CancellationToken cancellationToken = default)
    {
        _logger.LogDebug("Checking if VwReportWalletTransfer exists with ID: {Id}", id);

        try
        {
            var result = await _connection.QueryFirstOrDefaultAsync<VwReportWalletTransfer>(
                "SP_GetVwReportWalletTransferByID",
                new { ID = id },
                commandType: CommandType.StoredProcedure);

            bool exists = result != null;
            _logger.LogDebug("VwReportWalletTransfer exists: {Exists}", exists);
            return exists;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error checking if VwReportWalletTransfer exists. ID: {Id}", id);
            throw;
        }
    }
}
