// <auto-generated>
//     This code was generated by TargCC.Core.Generators v2.0
//     Generated from table: dbo.vwReportDistributorObligoBalanceData
//     Generation date: 2025-12-17 20:20:36
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

namespace UpayCard.RiskManagement.Infrastructure.Repositories;

using System.Data;
using System.Threading;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.Logging;
using UpayCard.RiskManagement.Domain.Entities;
using UpayCard.RiskManagement.Domain.Interfaces;

/// <summary>
/// Repository implementation for vwReportDistributorObligoBalanceData entity data access operations.
/// </summary>
/// <remarks>
/// <para>
/// This repository provides data access for the vwReportDistributorObligoBalanceData entity using Dapper
/// for stored procedure calls. All operations are async and support cancellation.
/// </para>
/// </remarks>
public class vwReportDistributorObligoBalanceDataRepository : IvwReportDistributorObligoBalanceDataRepository
{
    private readonly IDbConnection _connection;
    private readonly ILogger<vwReportDistributorObligoBalanceDataRepository> _logger;

    /// <summary>
    /// Initializes a new instance of the <see cref="vwReportDistributorObligoBalanceDataRepository"/> class.
    /// </summary>
    /// <param name="connection">Database connection for Dapper operations.</param>
    /// <param name="logger">Logger for tracking repository operations.</param>
    public vwReportDistributorObligoBalanceDataRepository(IDbConnection connection, ILogger<vwReportDistributorObligoBalanceDataRepository> logger)
    {
        _connection = connection ?? throw new ArgumentNullException(nameof(connection));
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
    }

    /// <inheritdoc/>
    public async System.Threading.Tasks.Task<vwReportDistributorObligoBalanceData?> GetByIdAsync(long id, CancellationToken cancellationToken = default)
    {
        _logger.LogDebug("Getting vwReportDistributorObligoBalanceData by ID: {Id}", id);

        try
        {
            var result = await _connection.QueryFirstOrDefaultAsync<vwReportDistributorObligoBalanceData>(
                "SP_GetvwReportDistributorObligoBalanceDataByID",
                new { ID = id },
                commandType: CommandType.StoredProcedure);

            _logger.LogDebug("vwReportDistributorObligoBalanceData found: {Found}", result != null);
            return result;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error getting vwReportDistributorObligoBalanceData by ID: {Id}", id);
            throw;
        }
    }

    /// <inheritdoc/>
    public async System.Threading.Tasks.Task<IEnumerable<vwReportDistributorObligoBalanceData>> GetAllAsync(int? skip = null, int? take = null, CancellationToken cancellationToken = default)
    {
        _logger.LogDebug("Getting all vwReportDistributorObligoBalanceData entities. Skip: {Skip}, Take: {Take}", skip, take);

        try
        {
            var result = await _connection.QueryAsync<vwReportDistributorObligoBalanceData>(
                "SP_GetAllvwReportDistributorObligoBalanceDatas",
                new { Skip = skip, Take = take },
                commandType: CommandType.StoredProcedure);

            _logger.LogDebug("Retrieved {Count} vwReportDistributorObligoBalanceData entities", result.Count());
            return result;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error getting all vwReportDistributorObligoBalanceData entities");
            throw;
        }
    }

    /// <inheritdoc/>
    public async Task<bool> ExistsAsync(long id, CancellationToken cancellationToken = default)
    {
        _logger.LogDebug("Checking if vwReportDistributorObligoBalanceData exists with ID: {Id}", id);

        try
        {
            var result = await _connection.QueryFirstOrDefaultAsync<vwReportDistributorObligoBalanceData>(
                "SP_GetvwReportDistributorObligoBalanceDataByID",
                new { ID = id },
                commandType: CommandType.StoredProcedure);

            bool exists = result != null;
            _logger.LogDebug("vwReportDistributorObligoBalanceData exists: {Exists}", exists);
            return exists;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error checking if vwReportDistributorObligoBalanceData exists. ID: {Id}", id);
            throw;
        }
    }
}
