// <auto-generated>
//     This code was generated by TargCC
//     Generated for: Fee (Handler)
//     Generation date: 2025-12-18 08:11:21
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using MediatR;
using Microsoft.Extensions.Logging;
using UpayCard.RiskManagement.Application.Common.Models;
using UpayCard.RiskManagement.Domain.Entities;
using UpayCard.RiskManagement.Domain.Interfaces;

namespace UpayCard.RiskManagement.Application.Features.Fees.Commands;

/// <summary>
/// Handles the CreateFeeCommand request.
/// </summary>
public class CreateFeeHandler : IRequestHandler<CreateFeeCommand, Result<long>>
{
    private readonly IFeeRepository _repository;
    private readonly ILogger<CreateFeeHandler> _logger;

    /// <summary>
    /// Initializes a new instance of the <see cref="CreateFeeHandler"/> class.
    /// </summary>
    public CreateFeeHandler(
        IFeeRepository repository,
        ILogger<CreateFeeHandler> logger)
    {
        _repository = repository ?? throw new ArgumentNullException(nameof(repository));
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
    }

    /// <inheritdoc/>
    public async Task<Result<long>> Handle(CreateFeeCommand request, CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(request);

        _logger.LogDebug("Creating new Fee");

        try
        {
            var entity = new Fee
            {
                TableName_Fee = request.TableName_Fee,
                DefaultAmt = request.DefaultAmt,
                DefaultPctOfTrigger = request.DefaultPctOfTrigger,
                DeletedBy = request.DeletedBy,
                DeletedOn = request.DeletedOn,
                UpdatingLoginID = request.UpdatingLoginID,
                DefaultMax = request.DefaultMax,
                DefaultMin = request.DefaultMin
            };

            await _repository.AddAsync(entity, cancellationToken);

            _logger.LogInformation("Fee created successfully with ID: {Id}", entity.ID);

            return Result<long>.Success(entity.ID);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error creating Fee");
            throw;
        }
    }
}
