// <auto-generated>
//     This code was generated by TargCC
//     Generated for: ccvwComboList_Limitation (Handler)
//     Generation date: 2025-12-17 09:08:24
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using AutoMapper;
using MediatR;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using UpayCard.RiskManagement.Application.Common.Interfaces;
using UpayCard.RiskManagement.Application.Common.Models;
using UpayCard.RiskManagement.Application.DTOs;
using UpayCard.RiskManagement.Domain.Common;
using UpayCard.RiskManagement.Domain.Entities;
using UpayCard.RiskManagement.Domain.Interfaces;

namespace UpayCard.RiskManagement.Application.Features.ccvwComboList_Limitations.Queries;

/// <summary>
/// Handles the GetCcvwComboListLimitationsQuery request with server-side filtering, sorting, and pagination.
/// </summary>
public class GetCcvwComboListLimitationsHandler : IRequestHandler<GetCcvwComboListLimitationsQuery, Result<PagedResult<CcvwComboListLimitationDto>>>
{
    private readonly IApplicationDbContext _context;
    private readonly IMapper _mapper;
    private readonly ILogger<GetCcvwComboListLimitationsHandler> _logger;

    /// <summary>
    /// Initializes a new instance of the <see cref="GetCcvwComboListLimitationsHandler"/> class.
    /// </summary>
    public GetCcvwComboListLimitationsHandler(
        IApplicationDbContext context,
        IMapper mapper,
        ILogger<GetCcvwComboListLimitationsHandler> logger)
    {
        _context = context ?? throw new ArgumentNullException(nameof(context));
        _mapper = mapper ?? throw new ArgumentNullException(nameof(mapper));
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
    }

    /// <inheritdoc/>
    public async Task<Result<PagedResult<CcvwComboListLimitationDto>>> Handle(GetCcvwComboListLimitationsQuery request, CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(request);

        _logger.LogDebug("Getting ccvwComboList_Limitations - Page: {Page}, Size: {Size}, SortBy: {SortBy}", request.Page, request.PageSize, request.SortBy);

        try
        {
            var query = _context.CcvwComboListLimitations.AsQueryable();

            // Apply filters
            query = ApplyFilters(query, request.Filters);

            // Get total count BEFORE pagination
            var totalCount = await query.CountAsync(cancellationToken);

            // Apply sorting
            query = ApplySorting(query, request.SortBy, request.SortDirection);

            // Apply pagination
            query = query
                .Skip((request.Page - 1) * request.PageSize)
                .Take(request.PageSize);

            var entities = await query.ToListAsync(cancellationToken);
            var dtos = _mapper.Map<List<CcvwComboListLimitationDto>>(entities);

            var result = new PagedResult<CcvwComboListLimitationDto>
            {
                Items = dtos,
                TotalCount = totalCount,
                Page = request.Page,
                PageSize = request.PageSize
            };

            _logger.LogDebug("Successfully retrieved {Count} of {Total} ccvwComboList_Limitations", dtos.Count, totalCount);

            return Result<PagedResult<CcvwComboListLimitationDto>>.Success(result);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error retrieving ccvwComboList_Limitations");
            throw;
        }
    }

    private static IQueryable<CcvwComboListLimitation> ApplyFilters(IQueryable<CcvwComboListLimitation> query, CcvwComboListLimitationFilters? filters)
    {
        if (filters == null)
        {
            return query;
        }

        // TODO: Add filter logic based on table columns
        // Example:
        // if (!string.IsNullOrEmpty(filters.Name))
        // {
        //     query = query.Where(e => e.Name.Contains(filters.Name));
        // }

        return query;
    }

    private static IQueryable<CcvwComboListLimitation> ApplySorting(IQueryable<CcvwComboListLimitation> query, string? sortBy, string? sortDirection)
    {
        if (string.IsNullOrEmpty(sortBy))
        {
            return query.OrderBy(e => e.ID); // Default sort
        }

        var isDescending = sortDirection?.ToLower() == "desc";

        // TODO: Add sorting logic based on table columns
        return sortBy.ToLower() switch
        {
            "id" => isDescending ? query.OrderByDescending(e => e.ID) : query.OrderBy(e => e.ID),
            // Add more sortable columns here
            _ => query.OrderBy(e => e.ID) // Default to ID if unknown field
        };
    }
}
