// <auto-generated>
//     This code was generated by TargCC API Generator.
//     Generator: API Controller Generator
//     Table: ccvwComboList_TransactionLoadForCard
//     Generated: 2025-12-11 11:52:12
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using UpayCard.Domain.Entities;
using UpayCard.Domain.Interfaces;

namespace UpayCard.RiskManagement.API.Controllers
{
    /// <summary>
    /// API controller for CcvwComboListTransactionLoadForCard entities.
    /// </summary>
    [ApiController]
    [Route("api/[controller]")]
    [Produces("application/json")]
    public class CcvwComboListTransactionLoadForCardsController : ControllerBase
    {
        private readonly ICcvwComboListTransactionLoadForCardRepository _repository;
        
        private readonly ILogger<CcvwComboListTransactionLoadForCardsController> _logger;

        /// <summary>
        /// Initializes a new instance of the <see cref="CcvwComboListTransactionLoadForCardsController"/> class.
        /// </summary>
        /// <param name="repository">Repository for CcvwComboListTransactionLoadForCard.</param>
        /// <param name="logger">Logger instance.</param>
        public CcvwComboListTransactionLoadForCardsController(
            ICcvwComboListTransactionLoadForCardRepository repository,
            ILogger<CcvwComboListTransactionLoadForCardsController> logger)
        {
            _repository = repository ?? throw new ArgumentNullException(nameof(repository));
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }

        /// <summary>
        /// Gets a CcvwComboListTransactionLoadForCard by ID.
        /// </summary>
        /// <param name="id">The entity ID.</param>
        /// <returns>The CcvwComboListTransactionLoadForCard entity.</returns>
        [HttpGet("{id}")]
        [ProducesResponseType(typeof(CcvwComboListTransactionLoadForCard), 200)]
        [ProducesResponseType(404)]
        public async Task<ActionResult<CcvwComboListTransactionLoadForCard>> GetById(int id)
        {
            var entity = await _repository.GetByIdAsync(id).ConfigureAwait(false);
            if (entity == null)
            {
                return NotFound();
            }

            return Ok(entity);
        }

        /// <summary>
        /// Gets all CcvwComboListTransactionLoadForCards.
        /// </summary>
        /// <returns>Collection of CcvwComboListTransactionLoadForCard entities.</returns>
        [HttpGet]
        [ProducesResponseType(typeof(IEnumerable<CcvwComboListTransactionLoadForCard>), 200)]
        public async Task<ActionResult<IEnumerable<CcvwComboListTransactionLoadForCard>>> GetAll()
        {
            var entities = await _repository.GetAllAsync().ConfigureAwait(false);
            return Ok(entities);
        }


    }
}
