// <auto-generated>
//     This code was generated by TargCC API Generator.
//     Generator: API Controller Generator
//     Table: ccvwComboList_NewCardRequestAPIForDistributor
//     Generated: 2025-12-11 11:52:12
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using UpayCard.Domain.Entities;
using UpayCard.Domain.Interfaces;

namespace UpayCard.RiskManagement.API.Controllers
{
    /// <summary>
    /// API controller for CcvwComboListNewCardRequestAPIForDistributor entities.
    /// </summary>
    [ApiController]
    [Route("api/[controller]")]
    [Produces("application/json")]
    public class CcvwComboListNewCardRequestAPIForDistributorsController : ControllerBase
    {
        private readonly ICcvwComboListNewCardRequestAPIForDistributorRepository _repository;
        
        private readonly ILogger<CcvwComboListNewCardRequestAPIForDistributorsController> _logger;

        /// <summary>
        /// Initializes a new instance of the <see cref="CcvwComboListNewCardRequestAPIForDistributorsController"/> class.
        /// </summary>
        /// <param name="repository">Repository for CcvwComboListNewCardRequestAPIForDistributor.</param>
        /// <param name="logger">Logger instance.</param>
        public CcvwComboListNewCardRequestAPIForDistributorsController(
            ICcvwComboListNewCardRequestAPIForDistributorRepository repository,
            ILogger<CcvwComboListNewCardRequestAPIForDistributorsController> logger)
        {
            _repository = repository ?? throw new ArgumentNullException(nameof(repository));
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }

        /// <summary>
        /// Gets a CcvwComboListNewCardRequestAPIForDistributor by ID.
        /// </summary>
        /// <param name="id">The entity ID.</param>
        /// <returns>The CcvwComboListNewCardRequestAPIForDistributor entity.</returns>
        [HttpGet("{id}")]
        [ProducesResponseType(typeof(CcvwComboListNewCardRequestAPIForDistributor), 200)]
        [ProducesResponseType(404)]
        public async Task<ActionResult<CcvwComboListNewCardRequestAPIForDistributor>> GetById(int id)
        {
            var entity = await _repository.GetByIdAsync(id).ConfigureAwait(false);
            if (entity == null)
            {
                return NotFound();
            }

            return Ok(entity);
        }

        /// <summary>
        /// Gets all CcvwComboListNewCardRequestAPIForDistributors.
        /// </summary>
        /// <returns>Collection of CcvwComboListNewCardRequestAPIForDistributor entities.</returns>
        [HttpGet]
        [ProducesResponseType(typeof(IEnumerable<CcvwComboListNewCardRequestAPIForDistributor>), 200)]
        public async Task<ActionResult<IEnumerable<CcvwComboListNewCardRequestAPIForDistributor>>> GetAll()
        {
            var entities = await _repository.GetAllAsync().ConfigureAwait(false);
            return Ok(entities);
        }


    }
}
