// <auto-generated>
//     This code was generated by TargCC API Generator.
//     Generator: API Controller Generator
//     Table: ccvwComboList_CardActivationForDistributor
//     Generated: 2025-12-11 21:18:53
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using UpayCard.RiskManagement.Domain.Entities;
using UpayCard.RiskManagement.Domain.Interfaces;

namespace UpayCard.RiskManagement.API.Controllers
{
    /// <summary>
    /// API controller for CcvwComboListCardActivationForDistributor entities.
    /// </summary>
    [ApiController]
    [Route("api/[controller]")]
    [Produces("application/json")]
    public class CcvwComboListCardActivationForDistributorsController : ControllerBase
    {
        private readonly ICcvwComboListCardActivationForDistributorRepository _repository;
        
        private readonly ILogger<CcvwComboListCardActivationForDistributorsController> _logger;

        /// <summary>
        /// Initializes a new instance of the <see cref="CcvwComboListCardActivationForDistributorsController"/> class.
        /// </summary>
        /// <param name="repository">Repository for CcvwComboListCardActivationForDistributor.</param>
        /// <param name="logger">Logger instance.</param>
        public CcvwComboListCardActivationForDistributorsController(
            ICcvwComboListCardActivationForDistributorRepository repository,
            ILogger<CcvwComboListCardActivationForDistributorsController> logger)
        {
            _repository = repository ?? throw new ArgumentNullException(nameof(repository));
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }

        /// <summary>
        /// Gets a CcvwComboListCardActivationForDistributor by ID.
        /// </summary>
        /// <param name="id">The entity ID.</param>
        /// <returns>The CcvwComboListCardActivationForDistributor entity.</returns>
        [HttpGet("{id}")]
        [ProducesResponseType(typeof(CcvwComboListCardActivationForDistributor), 200)]
        [ProducesResponseType(404)]
        public async System.Threading.Tasks.Task<ActionResult<CcvwComboListCardActivationForDistributor>> GetById(long id)
        {
            var entity = await _repository.GetByIdAsync(id).ConfigureAwait(false);
            if (entity == null)
            {
                return NotFound();
            }

            return Ok(entity);
        }

        /// <summary>
        /// Gets all CcvwComboListCardActivationForDistributors.
        /// </summary>
        /// <returns>Collection of CcvwComboListCardActivationForDistributor entities.</returns>
        [HttpGet]
        [ProducesResponseType(typeof(IEnumerable<CcvwComboListCardActivationForDistributor>), 200)]
        public async System.Threading.Tasks.Task<ActionResult<IEnumerable<CcvwComboListCardActivationForDistributor>>> GetAll()
        {
            var entities = await _repository.GetAllAsync().ConfigureAwait(false);
            return Ok(entities);
        }


    }
}
