// <auto-generated>
//     This code was generated by TargCC API Generator.
//     Generator: API Controller Generator
//     Table: CustomerClub
//     Generated: 2025-12-17 21:32:14
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using UpayCard.RiskManagement.Application.Common.Models;
using UpayCard.RiskManagement.Application.DTOs;
using UpayCard.RiskManagement.Application.Features.CustomerClubs.Queries;
using UpayCard.RiskManagement.Domain.Common;
using UpayCard.RiskManagement.Domain.Entities;
using UpayCard.RiskManagement.Domain.Interfaces;

namespace UpayCard.RiskManagement.API.Controllers
{
    /// <summary>
    /// API controller for CustomerClub entities.
    /// </summary>
    [ApiController]
    [Route("api/[controller]")]
    [Produces("application/json")]
    public class CustomerClubsController : ControllerBase
    {
        private readonly ICustomerClubRepository _repository;
        private readonly IMediator _mediator;
        private readonly ILogger<CustomerClubsController> _logger;

        /// <summary>
        /// Initializes a new instance of the <see cref="CustomerClubsController"/> class.
        /// </summary>
        /// <param name="repository">Repository for CustomerClub.</param>
        /// <param name="mediator">MediatR instance for sending queries.</param>
        /// <param name="logger">Logger instance.</param>
        public CustomerClubsController(
            ICustomerClubRepository repository,
            IMediator mediator,
            ILogger<CustomerClubsController> logger)
        {
            _repository = repository ?? throw new ArgumentNullException(nameof(repository));
            _mediator = mediator ?? throw new ArgumentNullException(nameof(mediator));
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }

        /// <summary>
        /// Gets a CustomerClub by ID.
        /// </summary>
        /// <param name="id">The entity ID.</param>
        /// <returns>The CustomerClub entity.</returns>
        [HttpGet("{id}")]
        [ProducesResponseType(typeof(CustomerClub), 200)]
        [ProducesResponseType(404)]
        public async System.Threading.Tasks.Task<ActionResult<CustomerClub>> GetById(long id)
        {
            var entity = await _repository.GetByIdAsync(id).ConfigureAwait(false);
            if (entity == null)
            {
                return NotFound();
            }

            return Ok(entity);
        }

        /// <summary>
        /// Gets all CustomerClubs with server-side filtering, sorting, and pagination.
        /// </summary>
        /// <param name="filters">Optional filters to apply.</param>
        /// <param name="page">Page number (1-based). Default is 1.</param>
        /// <param name="pageSize">Number of items per page. Default is 100.</param>
        /// <param name="sortBy">Field to sort by. Default is "Id".</param>
        /// <param name="sortDirection">Sort direction (asc/desc). Default is "asc".</param>
        /// <returns>Paginated result of CustomerClub DTOs.</returns>
        [HttpGet]
        [ProducesResponseType(typeof(PagedResult<CustomerClubDto>), 200)]
        public async System.Threading.Tasks.Task<ActionResult<PagedResult<CustomerClubDto>>> GetAll(
            [FromQuery] CustomerClubFilters? filters,
            [FromQuery] int page = 1,
            [FromQuery] int pageSize = 100,
            [FromQuery] string? sortBy = "Id",
            [FromQuery] string sortDirection = "asc")
        {
            var query = new GetCustomerClubsQuery
            {
                Filters = filters,
                Page = page,
                PageSize = pageSize,
                SortBy = sortBy,
                SortDirection = sortDirection
            };

            var result = await _mediator.Send(query).ConfigureAwait(false);

            return result.IsSuccess ? Ok(result.Value) : Problem(result.Error);
        }

        /// <summary>
        /// Gets filtered CustomerClubs based on indexed columns.
        /// </summary>
        /// <param name="appsFlyerFlag">Filter by AppsFlyerFlag.</param>
        /// <param name="clubName">Filter by ClubName.</param>
        /// <param name="isRoot">Filter by IsRoot.</param>
        /// <param name="useForUnassignedBusinessCustomer">Filter by UseForUnassignedBusinessCustomer.</param>
        /// <param name="useForUnassignedCustomer">Filter by UseForUnassignedCustomer.</param>
        /// <param name="skip">Number of records to skip for pagination.</param>
        /// <param name="take">Number of records to take for pagination.</param>
        /// <returns>Collection of filtered CustomerClub entities.</returns>
        [HttpGet("filter")]
        [ProducesResponseType(typeof(IEnumerable<CustomerClub>), 200)]
        public async System.Threading.Tasks.Task<ActionResult<IEnumerable<CustomerClub>>> GetFiltered([FromQuery] string? appsFlyerFlag = null, [FromQuery] string? clubName = null, [FromQuery] bool? isRoot = null, [FromQuery] bool? useForUnassignedBusinessCustomer = null, [FromQuery] bool? useForUnassignedCustomer = null, [FromQuery] int? skip = null, [FromQuery] int? take = null)
        {
            var entities = await _repository.GetFilteredAsync(appsFlyerFlag, clubName, isRoot, useForUnassignedBusinessCustomer, useForUnassignedCustomer, skip, take, CancellationToken.None).ConfigureAwait(false);
            return Ok(entities);
        }

        /// <summary>
        /// Gets all CUSTOMERS for a specific CUSTOMERCLUB.
        /// </summary>
        /// <param name="id">The parent entity ID.</param>
        /// <param name="skip">Number of records to skip for pagination.</param>
        /// <param name="take">Number of records to take for pagination.</param>
        /// <returns>Collection of Customer entities.</returns>
        [HttpGet("{id}/CUSTOMERS")]
        [ProducesResponseType(typeof(IEnumerable<Customer>), 200)]
        [ProducesResponseType(404)]
        public async System.Threading.Tasks.Task<ActionResult<IEnumerable<Customer>>> GetCustomers(int id, [FromQuery] int? skip = null, [FromQuery] int? take = null)
        {
            // Verify parent exists
            var parent = await _repository.GetByIdAsync(id).ConfigureAwait(false);
            if (parent == null)
            {
                return NotFound();
            }

            var CUSTOMERS = await _repository.GetCustomersAsync(id, skip, take).ConfigureAwait(false);
            return Ok(CUSTOMERS);
        }

        /// <summary>
        /// Gets all FEEOVERRIDES for a specific CUSTOMERCLUB.
        /// </summary>
        /// <param name="id">The parent entity ID.</param>
        /// <param name="skip">Number of records to skip for pagination.</param>
        /// <param name="take">Number of records to take for pagination.</param>
        /// <returns>Collection of FeeOverride entities.</returns>
        [HttpGet("{id}/FEEOVERRIDES")]
        [ProducesResponseType(typeof(IEnumerable<FeeOverride>), 200)]
        [ProducesResponseType(404)]
        public async System.Threading.Tasks.Task<ActionResult<IEnumerable<FeeOverride>>> GetFeeOverrides(int id, [FromQuery] int? skip = null, [FromQuery] int? take = null)
        {
            // Verify parent exists
            var parent = await _repository.GetByIdAsync(id).ConfigureAwait(false);
            if (parent == null)
            {
                return NotFound();
            }

            var FEEOVERRIDES = await _repository.GetFeeOverridesAsync(id, skip, take).ConfigureAwait(false);
            return Ok(FEEOVERRIDES);
        }

        /// <summary>
        /// Gets all LIMITATIONOVERRIDES for a specific CUSTOMERCLUB.
        /// </summary>
        /// <param name="id">The parent entity ID.</param>
        /// <param name="skip">Number of records to skip for pagination.</param>
        /// <param name="take">Number of records to take for pagination.</param>
        /// <returns>Collection of LimitationOverride entities.</returns>
        [HttpGet("{id}/LIMITATIONOVERRIDES")]
        [ProducesResponseType(typeof(IEnumerable<LimitationOverride>), 200)]
        [ProducesResponseType(404)]
        public async System.Threading.Tasks.Task<ActionResult<IEnumerable<LimitationOverride>>> GetLimitationOverrides(int id, [FromQuery] int? skip = null, [FromQuery] int? take = null)
        {
            // Verify parent exists
            var parent = await _repository.GetByIdAsync(id).ConfigureAwait(false);
            if (parent == null)
            {
                return NotFound();
            }

            var LIMITATIONOVERRIDES = await _repository.GetLimitationOverridesAsync(id, skip, take).ConfigureAwait(false);
            return Ok(LIMITATIONOVERRIDES);
        }

        /// <summary>
        /// Creates a new CustomerClub.
        /// </summary>
        /// <param name="entity">The {entityNameForDocs} to create.</param>
        /// <returns>The created CustomerClub.</returns>
        [HttpPost]
        [ProducesResponseType(typeof(CustomerClub), 201)]
        [ProducesResponseType(400)]
        public async System.Threading.Tasks.Task<ActionResult<CustomerClub>> Create([FromBody] CustomerClub entity)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            await _repository.AddAsync(entity).ConfigureAwait(false);
            return CreatedAtAction(nameof(GetById), new { id = entity.ID }, entity);
        }

        /// <summary>
        /// Updates an existing CustomerClub.
        /// </summary>
        /// <param name="id">The entity ID.</param>
        /// <param name="entity">The updated {entityNameForDocs}.</param>
        /// <returns>The updated CustomerClub.</returns>
        [HttpPut("{id}")]
        [ProducesResponseType(typeof(CustomerClub), 200)]
        [ProducesResponseType(404)]
        [ProducesResponseType(400)]
        public async System.Threading.Tasks.Task<ActionResult<CustomerClub>> Update(long id, [FromBody] CustomerClub entity)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var existing = await _repository.GetByIdAsync(id).ConfigureAwait(false);
            if (existing == null)
            {
                return NotFound();
            }

            entity.ID = id; // Ensure ID matches route
            await _repository.UpdateAsync(entity).ConfigureAwait(false);
            return Ok(entity);
        }

        /// <summary>
        /// Deletes a CustomerClub.
        /// </summary>
        /// <param name="id">The entity ID.</param>
        /// <returns>No content.</returns>
        [HttpDelete("{id}")]
        [ProducesResponseType(204)]
        [ProducesResponseType(404)]
        public async Task<IActionResult> Delete(long id)
        {
            var existing = await _repository.GetByIdAsync(id).ConfigureAwait(false);
            if (existing == null)
            {
                return NotFound();
            }

            await _repository.DeleteAsync(id).ConfigureAwait(false);
            return NoContent();
        }
    }
}
