// <auto-generated>
//     This code was generated by TargCC API Generator.
//     Generator: API Controller Generator
//     Table: CustomerKYC
//     Generated: 2025-12-15 13:53:29
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using UpayCard.RiskManagement.Domain.Entities;
using UpayCard.RiskManagement.Domain.Interfaces;

namespace UpayCard.RiskManagement.API.Controllers
{
    /// <summary>
    /// API controller for CustomerKYC entities.
    /// </summary>
    [ApiController]
    [Route("api/[controller]")]
    [Produces("application/json")]
    public class CustomerKYCsController : ControllerBase
    {
        private readonly ICustomerKYCRepository _repository;
        
        private readonly ILogger<CustomerKYCsController> _logger;

        /// <summary>
        /// Initializes a new instance of the <see cref="CustomerKYCsController"/> class.
        /// </summary>
        /// <param name="repository">Repository for CustomerKYC.</param>
        /// <param name="logger">Logger instance.</param>
        public CustomerKYCsController(
            ICustomerKYCRepository repository,
            ILogger<CustomerKYCsController> logger)
        {
            _repository = repository ?? throw new ArgumentNullException(nameof(repository));
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }

        /// <summary>
        /// Gets a CustomerKYC by ID.
        /// </summary>
        /// <param name="id">The entity ID.</param>
        /// <returns>The CustomerKYC entity.</returns>
        [HttpGet("{id}")]
        [ProducesResponseType(typeof(CustomerKYC), 200)]
        [ProducesResponseType(404)]
        public async System.Threading.Tasks.Task<ActionResult<CustomerKYC>> GetById(long id)
        {
            var entity = await _repository.GetByIdAsync(id).ConfigureAwait(false);
            if (entity == null)
            {
                return NotFound();
            }

            return Ok(entity);
        }

        /// <summary>
        /// Gets all CustomerKYCs.
        /// </summary>
        /// <returns>Collection of CustomerKYC entities.</returns>
        [HttpGet]
        [ProducesResponseType(typeof(IEnumerable<CustomerKYC>), 200)]
        public async System.Threading.Tasks.Task<ActionResult<IEnumerable<CustomerKYC>>> GetAll()
        {
            var entities = await _repository.GetAllAsync().ConfigureAwait(false);
            return Ok(entities);
        }

        /// <summary>
        /// Gets filtered CustomerKYCs based on indexed columns.
        /// </summary>
        /// <param name="customerID">Filter by CustomerID.</param>
        /// <param name="skip">Number of records to skip for pagination.</param>
        /// <param name="take">Number of records to take for pagination.</param>
        /// <returns>Collection of filtered CustomerKYC entities.</returns>
        [HttpGet("filter")]
        [ProducesResponseType(typeof(IEnumerable<CustomerKYC>), 200)]
        public async System.Threading.Tasks.Task<ActionResult<IEnumerable<CustomerKYC>>> GetFiltered([FromQuery] int? customerID = null, [FromQuery] int? skip = null, [FromQuery] int? take = null)
        {
            var entities = await _repository.GetFilteredAsync(customerID, skip, take, CancellationToken.None).ConfigureAwait(false);
            return Ok(entities);
        }

        /// <summary>
        /// Creates a new CustomerKYC.
        /// </summary>
        /// <param name="entity">The {entityNameForDocs} to create.</param>
        /// <returns>The created CustomerKYC.</returns>
        [HttpPost]
        [ProducesResponseType(typeof(CustomerKYC), 201)]
        [ProducesResponseType(400)]
        public async System.Threading.Tasks.Task<ActionResult<CustomerKYC>> Create([FromBody] CustomerKYC entity)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            await _repository.AddAsync(entity).ConfigureAwait(false);
            return CreatedAtAction(nameof(GetById), new { id = entity.ID }, entity);
        }

        /// <summary>
        /// Updates an existing CustomerKYC.
        /// </summary>
        /// <param name="id">The entity ID.</param>
        /// <param name="entity">The updated {entityNameForDocs}.</param>
        /// <returns>The updated CustomerKYC.</returns>
        [HttpPut("{id}")]
        [ProducesResponseType(typeof(CustomerKYC), 200)]
        [ProducesResponseType(404)]
        [ProducesResponseType(400)]
        public async System.Threading.Tasks.Task<ActionResult<CustomerKYC>> Update(long id, [FromBody] CustomerKYC entity)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var existing = await _repository.GetByIdAsync(id).ConfigureAwait(false);
            if (existing == null)
            {
                return NotFound();
            }

            entity.ID = id; // Ensure ID matches route
            await _repository.UpdateAsync(entity).ConfigureAwait(false);
            return Ok(entity);
        }

        /// <summary>
        /// Deletes a CustomerKYC.
        /// </summary>
        /// <param name="id">The entity ID.</param>
        /// <returns>No content.</returns>
        [HttpDelete("{id}")]
        [ProducesResponseType(204)]
        [ProducesResponseType(404)]
        public async Task<IActionResult> Delete(long id)
        {
            var existing = await _repository.GetByIdAsync(id).ConfigureAwait(false);
            if (existing == null)
            {
                return NotFound();
            }

            await _repository.DeleteAsync(id).ConfigureAwait(false);
            return NoContent();
        }
    }
}
