// <auto-generated>
//     This code was generated by TargCC API Generator.
//     Generator: API Controller Generator
//     Table: c_MFA
//     Generated: 2025-12-11 22:10:35
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using UpayCard.RiskManagement.Domain.Entities;
using UpayCard.RiskManagement.Domain.Interfaces;

namespace UpayCard.RiskManagement.API.Controllers
{
    /// <summary>
    /// API controller for Mfa entities.
    /// </summary>
    [ApiController]
    [Route("api/[controller]")]
    [Produces("application/json")]
    public class MfasController : ControllerBase
    {
        private readonly IMfaRepository _repository;
        
        private readonly ILogger<MfasController> _logger;

        /// <summary>
        /// Initializes a new instance of the <see cref="MfasController"/> class.
        /// </summary>
        /// <param name="repository">Repository for Mfa.</param>
        /// <param name="logger">Logger instance.</param>
        public MfasController(
            IMfaRepository repository,
            ILogger<MfasController> logger)
        {
            _repository = repository ?? throw new ArgumentNullException(nameof(repository));
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }

        /// <summary>
        /// Gets a Mfa by ID.
        /// </summary>
        /// <param name="id">The entity ID.</param>
        /// <returns>The Mfa entity.</returns>
        [HttpGet("{id}")]
        [ProducesResponseType(typeof(Mfa), 200)]
        [ProducesResponseType(404)]
        public async System.Threading.Tasks.Task<ActionResult<Mfa>> GetById(long id)
        {
            var entity = await _repository.GetByIdAsync(id).ConfigureAwait(false);
            if (entity == null)
            {
                return NotFound();
            }

            return Ok(entity);
        }

        /// <summary>
        /// Gets all Mfas.
        /// </summary>
        /// <returns>Collection of Mfa entities.</returns>
        [HttpGet]
        [ProducesResponseType(typeof(IEnumerable<Mfa>), 200)]
        public async System.Threading.Tasks.Task<ActionResult<IEnumerable<Mfa>>> GetAll()
        {
            var entities = await _repository.GetAllAsync().ConfigureAwait(false);
            return Ok(entities);
        }

        /// <summary>
        /// Gets filtered Mfas based on indexed columns.
        /// </summary>
        /// <param name="cellOrEmail">Filter by CellOrEmail.</param>
        /// <param name="skip">Number of records to skip for pagination.</param>
        /// <param name="take">Number of records to take for pagination.</param>
        /// <returns>Collection of filtered Mfa entities.</returns>
        [HttpGet("filter")]
        [ProducesResponseType(typeof(IEnumerable<Mfa>), 200)]
        public async System.Threading.Tasks.Task<ActionResult<IEnumerable<Mfa>>> GetFiltered([FromQuery] string? cellOrEmail = null, [FromQuery] int? skip = null, [FromQuery] int? take = null)
        {
            var entities = await _repository.GetFilteredAsync(cellOrEmail, skip, take, CancellationToken.None).ConfigureAwait(false);
            return Ok(entities);
        }

        /// <summary>
        /// Creates a new Mfa.
        /// </summary>
        /// <param name="entity">The {entityNameForDocs} to create.</param>
        /// <returns>The created Mfa.</returns>
        [HttpPost]
        [ProducesResponseType(typeof(Mfa), 201)]
        [ProducesResponseType(400)]
        public async System.Threading.Tasks.Task<ActionResult<Mfa>> Create([FromBody] Mfa entity)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            await _repository.AddAsync(entity).ConfigureAwait(false);
            return CreatedAtAction(nameof(GetById), new { id = entity.ID }, entity);
        }

        /// <summary>
        /// Updates an existing Mfa.
        /// </summary>
        /// <param name="id">The entity ID.</param>
        /// <param name="entity">The updated {entityNameForDocs}.</param>
        /// <returns>The updated Mfa.</returns>
        [HttpPut("{id}")]
        [ProducesResponseType(typeof(Mfa), 200)]
        [ProducesResponseType(404)]
        [ProducesResponseType(400)]
        public async System.Threading.Tasks.Task<ActionResult<Mfa>> Update(long id, [FromBody] Mfa entity)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var existing = await _repository.GetByIdAsync(id).ConfigureAwait(false);
            if (existing == null)
            {
                return NotFound();
            }

            entity.ID = id; // Ensure ID matches route
            await _repository.UpdateAsync(entity).ConfigureAwait(false);
            return Ok(entity);
        }

        /// <summary>
        /// Deletes a Mfa.
        /// </summary>
        /// <param name="id">The entity ID.</param>
        /// <returns>No content.</returns>
        [HttpDelete("{id}")]
        [ProducesResponseType(204)]
        [ProducesResponseType(404)]
        public async Task<IActionResult> Delete(long id)
        {
            var existing = await _repository.GetByIdAsync(id).ConfigureAwait(false);
            if (existing == null)
            {
                return NotFound();
            }

            await _repository.DeleteAsync(id).ConfigureAwait(false);
            return NoContent();
        }
    }
}
