// <auto-generated>
//     This code was generated by TargCC API Generator.
//     Generator: API Controller Generator
//     Table: c_UserPermission
//     Generated: 2025-12-17 08:54:22
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using UpayCard.RiskManagement.Application.Common.Models;
using UpayCard.RiskManagement.Application.Features.UserPermissions.Queries;
using UpayCard.RiskManagement.Domain.Common;
using UpayCard.RiskManagement.Domain.Entities;
using UpayCard.RiskManagement.Domain.Interfaces;

namespace UpayCard.RiskManagement.API.Controllers
{
    /// <summary>
    /// API controller for UserPermission entities.
    /// </summary>
    [ApiController]
    [Route("api/[controller]")]
    [Produces("application/json")]
    public class UserPermissionsController : ControllerBase
    {
        private readonly IUserPermissionRepository _repository;
        private readonly IMediator _mediator;
        private readonly ILogger<UserPermissionsController> _logger;

        /// <summary>
        /// Initializes a new instance of the <see cref="UserPermissionsController"/> class.
        /// </summary>
        /// <param name="repository">Repository for UserPermission.</param>
        /// <param name="mediator">MediatR instance for sending queries.</param>
        /// <param name="logger">Logger instance.</param>
        public UserPermissionsController(
            IUserPermissionRepository repository,
            IMediator mediator,
            ILogger<UserPermissionsController> logger)
        {
            _repository = repository ?? throw new ArgumentNullException(nameof(repository));
            _mediator = mediator ?? throw new ArgumentNullException(nameof(mediator));
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }

        /// <summary>
        /// Gets a UserPermission by ID.
        /// </summary>
        /// <param name="id">The entity ID.</param>
        /// <returns>The UserPermission entity.</returns>
        [HttpGet("{id}")]
        [ProducesResponseType(typeof(UserPermission), 200)]
        [ProducesResponseType(404)]
        public async System.Threading.Tasks.Task<ActionResult<UserPermission>> GetById(long id)
        {
            var entity = await _repository.GetByIdAsync(id).ConfigureAwait(false);
            if (entity == null)
            {
                return NotFound();
            }

            return Ok(entity);
        }

        /// <summary>
        /// Gets all UserPermissions with server-side filtering, sorting, and pagination.
        /// </summary>
        /// <param name="filters">Optional filters to apply.</param>
        /// <param name="page">Page number (1-based). Default is 1.</param>
        /// <param name="pageSize">Number of items per page. Default is 100.</param>
        /// <param name="sortBy">Field to sort by. Default is "Id".</param>
        /// <param name="sortDirection">Sort direction (asc/desc). Default is "asc".</param>
        /// <returns>Paginated result of UserPermission DTOs.</returns>
        [HttpGet]
        [ProducesResponseType(typeof(PagedResult<UserPermissionDto>), 200)]
        public async System.Threading.Tasks.Task<ActionResult<PagedResult<UserPermissionDto>>> GetAll(
            [FromQuery] UserPermissionFilters? filters,
            [FromQuery] int page = 1,
            [FromQuery] int pageSize = 100,
            [FromQuery] string? sortBy = "Id",
            [FromQuery] string sortDirection = "asc")
        {
            var query = new GetUserPermissionsQuery
            {
                Filters = filters,
                Page = page,
                PageSize = pageSize,
                SortBy = sortBy,
                SortDirection = sortDirection
            };

            var result = await _mediator.Send(query).ConfigureAwait(false);

            return result.IsSuccess ? Ok(result.Value) : Problem(result.Error);
        }

        /// <summary>
        /// Gets filtered UserPermissions based on indexed columns.
        /// </summary>
        /// <param name="c_UserID">Filter by c_UserID.</param>
        /// <param name="applicationName">Filter by ApplicationName.</param>
        /// <param name="skip">Number of records to skip for pagination.</param>
        /// <param name="take">Number of records to take for pagination.</param>
        /// <returns>Collection of filtered UserPermission entities.</returns>
        [HttpGet("filter")]
        [ProducesResponseType(typeof(IEnumerable<UserPermission>), 200)]
        public async System.Threading.Tasks.Task<ActionResult<IEnumerable<UserPermission>>> GetFiltered([FromQuery] int? c_UserID = null, [FromQuery] string? applicationName = null, [FromQuery] int? skip = null, [FromQuery] int? take = null)
        {
            var entities = await _repository.GetFilteredAsync(c_UserID, applicationName, skip, take, CancellationToken.None).ConfigureAwait(false);
            return Ok(entities);
        }

        /// <summary>
        /// Creates a new UserPermission.
        /// </summary>
        /// <param name="entity">The {entityNameForDocs} to create.</param>
        /// <returns>The created UserPermission.</returns>
        [HttpPost]
        [ProducesResponseType(typeof(UserPermission), 201)]
        [ProducesResponseType(400)]
        public async System.Threading.Tasks.Task<ActionResult<UserPermission>> Create([FromBody] UserPermission entity)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            await _repository.AddAsync(entity).ConfigureAwait(false);
            return CreatedAtAction(nameof(GetById), new { id = entity.ID }, entity);
        }

        /// <summary>
        /// Updates an existing UserPermission.
        /// </summary>
        /// <param name="id">The entity ID.</param>
        /// <param name="entity">The updated {entityNameForDocs}.</param>
        /// <returns>The updated UserPermission.</returns>
        [HttpPut("{id}")]
        [ProducesResponseType(typeof(UserPermission), 200)]
        [ProducesResponseType(404)]
        [ProducesResponseType(400)]
        public async System.Threading.Tasks.Task<ActionResult<UserPermission>> Update(long id, [FromBody] UserPermission entity)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var existing = await _repository.GetByIdAsync(id).ConfigureAwait(false);
            if (existing == null)
            {
                return NotFound();
            }

            entity.ID = id; // Ensure ID matches route
            await _repository.UpdateAsync(entity).ConfigureAwait(false);
            return Ok(entity);
        }

        /// <summary>
        /// Deletes a UserPermission.
        /// </summary>
        /// <param name="id">The entity ID.</param>
        /// <returns>No content.</returns>
        [HttpDelete("{id}")]
        [ProducesResponseType(204)]
        [ProducesResponseType(404)]
        public async Task<IActionResult> Delete(long id)
        {
            var existing = await _repository.GetByIdAsync(id).ConfigureAwait(false);
            if (existing == null)
            {
                return NotFound();
            }

            await _repository.DeleteAsync(id).ConfigureAwait(false);
            return NoContent();
        }
    }
}
