// <auto-generated>
//     This code was generated by TargCC API Generator.
//     Generator: API Controller Generator
//     Table: vwReportCustomerCreditCardTransactionsData
//     Generated: 2025-12-15 13:53:30
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using UpayCard.RiskManagement.Domain.Entities;
using UpayCard.RiskManagement.Domain.Interfaces;

namespace UpayCard.RiskManagement.API.Controllers
{
    /// <summary>
    /// API controller for VwReportCustomerCreditCardTransactionsData entities.
    /// </summary>
    [ApiController]
    [Route("api/[controller]")]
    [Produces("application/json")]
    public class VwReportCustomerCreditCardTransactionsDatasController : ControllerBase
    {
        private readonly IVwReportCustomerCreditCardTransactionsDataRepository _repository;
        
        private readonly ILogger<VwReportCustomerCreditCardTransactionsDatasController> _logger;

        /// <summary>
        /// Initializes a new instance of the <see cref="VwReportCustomerCreditCardTransactionsDatasController"/> class.
        /// </summary>
        /// <param name="repository">Repository for VwReportCustomerCreditCardTransactionsData.</param>
        /// <param name="logger">Logger instance.</param>
        public VwReportCustomerCreditCardTransactionsDatasController(
            IVwReportCustomerCreditCardTransactionsDataRepository repository,
            ILogger<VwReportCustomerCreditCardTransactionsDatasController> logger)
        {
            _repository = repository ?? throw new ArgumentNullException(nameof(repository));
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }

        /// <summary>
        /// Gets a VwReportCustomerCreditCardTransactionsData by ID.
        /// </summary>
        /// <param name="id">The entity ID.</param>
        /// <returns>The VwReportCustomerCreditCardTransactionsData entity.</returns>
        [HttpGet("{id}")]
        [ProducesResponseType(typeof(VwReportCustomerCreditCardTransactionsData), 200)]
        [ProducesResponseType(404)]
        public async System.Threading.Tasks.Task<ActionResult<VwReportCustomerCreditCardTransactionsData>> GetById(long id)
        {
            var entity = await _repository.GetByIdAsync(id).ConfigureAwait(false);
            if (entity == null)
            {
                return NotFound();
            }

            return Ok(entity);
        }

        /// <summary>
        /// Gets all VwReportCustomerCreditCardTransactionsDatas.
        /// </summary>
        /// <returns>Collection of VwReportCustomerCreditCardTransactionsData entities.</returns>
        [HttpGet]
        [ProducesResponseType(typeof(IEnumerable<VwReportCustomerCreditCardTransactionsData>), 200)]
        public async System.Threading.Tasks.Task<ActionResult<IEnumerable<VwReportCustomerCreditCardTransactionsData>>> GetAll()
        {
            var entities = await _repository.GetAllAsync().ConfigureAwait(false);
            return Ok(entities);
        }


    }
}
