// <auto-generated>
//     This code was generated by TargCC API Generator.
//     Generator: API Controller Generator
//     Table: vwReportLoadTransferToDistributorData
//     Generated: 2025-12-15 20:38:16
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using UpayCard.RiskManagement.Domain.Common;
using UpayCard.RiskManagement.Domain.Entities;
using UpayCard.RiskManagement.Domain.Interfaces;

namespace UpayCard.RiskManagement.API.Controllers
{
    /// <summary>
    /// API controller for VwReportLoadTransferToDistributorData entities.
    /// </summary>
    [ApiController]
    [Route("api/[controller]")]
    [Produces("application/json")]
    public class VwReportLoadTransferToDistributorDatasController : ControllerBase
    {
        private readonly IVwReportLoadTransferToDistributorDataRepository _repository;
        
        private readonly ILogger<VwReportLoadTransferToDistributorDatasController> _logger;

        /// <summary>
        /// Initializes a new instance of the <see cref="VwReportLoadTransferToDistributorDatasController"/> class.
        /// </summary>
        /// <param name="repository">Repository for VwReportLoadTransferToDistributorData.</param>
        /// <param name="logger">Logger instance.</param>
        public VwReportLoadTransferToDistributorDatasController(
            IVwReportLoadTransferToDistributorDataRepository repository,
            ILogger<VwReportLoadTransferToDistributorDatasController> logger)
        {
            _repository = repository ?? throw new ArgumentNullException(nameof(repository));
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }

        /// <summary>
        /// Gets a VwReportLoadTransferToDistributorData by ID.
        /// </summary>
        /// <param name="id">The entity ID.</param>
        /// <returns>The VwReportLoadTransferToDistributorData entity.</returns>
        [HttpGet("{id}")]
        [ProducesResponseType(typeof(VwReportLoadTransferToDistributorData), 200)]
        [ProducesResponseType(404)]
        public async System.Threading.Tasks.Task<ActionResult<VwReportLoadTransferToDistributorData>> GetById(long id)
        {
            var entity = await _repository.GetByIdAsync(id).ConfigureAwait(false);
            if (entity == null)
            {
                return NotFound();
            }

            return Ok(entity);
        }

        /// <summary>
        /// Gets all VwReportLoadTransferToDistributorDatas with server-side filtering, sorting, and pagination.
        /// </summary>
        /// <param name="filters">Optional filters to apply.</param>
        /// <param name="page">Page number (1-based). Default is 1.</param>
        /// <param name="pageSize">Number of items per page. Default is 100.</param>
        /// <param name="sortBy">Field to sort by. Default is "Id".</param>
        /// <param name="sortDirection">Sort direction (asc/desc). Default is "asc".</param>
        /// <returns>Paginated result of VwReportLoadTransferToDistributorData entities.</returns>
        [HttpGet]
        [ProducesResponseType(typeof(PagedResult<VwReportLoadTransferToDistributorData>), 200)]
        public async System.Threading.Tasks.Task<ActionResult<PagedResult<VwReportLoadTransferToDistributorData>>> GetAll(
            [FromQuery] VwReportLoadTransferToDistributorDataFilters? filters,
            [FromQuery] int page = 1,
            [FromQuery] int pageSize = 100,
            [FromQuery] string? sortBy = "Id",
            [FromQuery] string sortDirection = "asc")
        {
            var query = new GetVwReportLoadTransferToDistributorDatasQuery
            {
                Filters = filters,
                Page = page,
                PageSize = pageSize,
                SortBy = sortBy,
                SortDirection = sortDirection
            };

            var result = await _mediator.Send(query).ConfigureAwait(false);

            return result.IsSuccess ? Ok(result.Value) : Problem(result.Error);
        }


    }
}
