// <auto-generated>
//     This code was generated by TargCC
//     Generated for: ccvwComboList_UIText (Handler)
//     Generation date: 2025-12-15 22:18:50
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using MediatR;
using Microsoft.Extensions.Logging;
using TargCC.Application.Common.Models;
using TargCC.Domain.Entities;
using TargCC.Domain.Interfaces;

namespace TargCC.Application.Features.ccvwComboList_UITexts.Commands;

/// <summary>
/// Handles the CreateCcvwComboListUITextCommand request.
/// </summary>
public class CreateCcvwComboListUITextHandler : IRequestHandler<CreateCcvwComboListUITextCommand, Result<int>>
{
    private readonly IccvwComboList_UITextRepository _repository;
    private readonly ILogger<CreateCcvwComboListUITextHandler> _logger;

    /// <summary>
    /// Initializes a new instance of the <see cref="CreateCcvwComboListUITextHandler"/> class.
    /// </summary>
    public CreateCcvwComboListUITextHandler(
        IccvwComboList_UITextRepository repository,
        ILogger<CreateCcvwComboListUITextHandler> logger)
    {
        _repository = repository ?? throw new ArgumentNullException(nameof(repository));
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
    }

    /// <inheritdoc/>
    public async Task<Result<int>> Handle(CreateCcvwComboListUITextCommand request, CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(request);

        _logger.LogDebug("Creating new ccvwComboList_UIText");

        try
        {
            var entity = new ccvwComboList_UIText
            {
                TextNS = request.TextNS,
                Text = request.Text
            };

            await _repository.AddAsync(entity, cancellationToken);

            _logger.LogInformation("ccvwComboList_UIText created successfully with ID: {Id}", entity.Id);

            return Result<int>.Success(entity.Id);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error creating ccvwComboList_UIText");
            throw;
        }
    }
}
