// <auto-generated>
//     This code was generated by TargCC UI Generator.
//     Generator: TypeScriptTypes
//     Table: ccvwComboList_CardForOwningDistributor
//     Generated: 2025-12-17 08:24:00
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

/**
 * CcvwComboListCardForOwningDistributor entity interface.
 * Generated from table: ccvwComboList_CardForOwningDistributor
 */
export interface CcvwComboListCardForOwningDistributor {
  id: number;
  parentID?: number;
  textNS?: string;
  text: string;
}


/**
 * Create CcvwComboListCardForOwningDistributor request interface.
 */
export interface CreateCcvwComboListCardForOwningDistributorRequest {
  parentID?: number;
  textNS?: string;
  text: string;
}


/**
 * Update CcvwComboListCardForOwningDistributor request interface.
 */
export interface UpdateCcvwComboListCardForOwningDistributorRequest extends CreateCcvwComboListCardForOwningDistributorRequest {
  id: number;
}


/**
 * CcvwComboListCardForOwningDistributor filters for querying.
 */
export interface CcvwComboListCardForOwningDistributorFilters {
  id?: number;
  parentID?: number;
  textNS?: string;
  text?: string;
  page?: number;
  pageSize?: number;
  sortBy?: string;
  sortDirection?: 'asc' | 'desc';
}

