// <auto-generated>
//     This code was generated by TargCC UI Generator.
//     Generator: TypeScriptTypes
//     Table: ccvwComboList_c_Role
//     Generated: 2025-12-16 10:51:37
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

/**
 * CcvwComboListCRole entity interface.
 * Generated from table: ccvwComboList_c_Role
 */
export interface CcvwComboListCRole {
  id: number;
  textNS?: string;
  text?: string;
}


/**
 * Create CcvwComboListCRole request interface.
 */
export interface CreateCcvwComboListCRoleRequest {
  textNS?: string;
  text?: string;
}


/**
 * Update CcvwComboListCRole request interface.
 */
export interface UpdateCcvwComboListCRoleRequest extends CreateCcvwComboListCRoleRequest {
  id: number;
}


/**
 * CcvwComboListCRole filters for querying.
 */
export interface CcvwComboListCRoleFilters {
  id?: number;
  textNS?: string;
  text?: string;
  page?: number;
  pageSize?: number;
  sortBy?: string;
  sortDirection?: 'asc' | 'desc';
}

