// <auto-generated>
//     This code was generated by TargCC UI Generator.
//     Generator: TypeScriptTypes
//     Table: ccvwComboList_MCCBReceiverForCustomer
//     Generated: 2025-12-16 10:13:19
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

/**
 * CcvwComboListMCCBReceiverForCustomer entity interface.
 * Generated from table: ccvwComboList_MCCBReceiverForCustomer
 */
export interface CcvwComboListMCCBReceiverForCustomer {
  id: number;
  parentID: number;
  textNS?: string;
  text?: string;
}


/**
 * Create CcvwComboListMCCBReceiverForCustomer request interface.
 */
export interface CreateCcvwComboListMCCBReceiverForCustomerRequest {
  parentID: number;
  textNS?: string;
  text?: string;
}


/**
 * Update CcvwComboListMCCBReceiverForCustomer request interface.
 */
export interface UpdateCcvwComboListMCCBReceiverForCustomerRequest extends CreateCcvwComboListMCCBReceiverForCustomerRequest {
  id: number;
}


/**
 * CcvwComboListMCCBReceiverForCustomer filters for querying.
 */
export interface CcvwComboListMCCBReceiverForCustomerFilters {
  id?: number;
  parentID?: number;
  textNS?: string;
  text?: string;
  page?: number;
  pageSize?: number;
  sortBy?: string;
  sortDirection?: 'asc' | 'desc';
}

