// <auto-generated>
//     This code was generated by TargCC UI Generator.
//     Generator: TypeScriptTypes
//     Table: ccvwComboList_ImportTransactionLoadForInitiatedByUser
//     Generated: 2025-12-17 21:11:14
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

/**
 * CcvwComboListImportTransactionLoadForInitiatedByUser entity interface.
 * Generated from table: ccvwComboList_ImportTransactionLoadForInitiatedByUser
 */
export interface CcvwComboListImportTransactionLoadForInitiatedByUser {
  id: number;
  parentID?: number;
  textNS?: string;
  text?: string;
}


/**
 * Create CcvwComboListImportTransactionLoadForInitiatedByUser request interface.
 */
export interface CreateCcvwComboListImportTransactionLoadForInitiatedByUserRequest {
  parentID?: number;
  textNS?: string;
  text?: string;
}


/**
 * Update CcvwComboListImportTransactionLoadForInitiatedByUser request interface.
 */
export interface UpdateCcvwComboListImportTransactionLoadForInitiatedByUserRequest extends CreateCcvwComboListImportTransactionLoadForInitiatedByUserRequest {
  id: number;
}


/**
 * CcvwComboListImportTransactionLoadForInitiatedByUser filters for querying.
 */
export interface CcvwComboListImportTransactionLoadForInitiatedByUserFilters {
  id?: number;
  parentID?: number;
  textNS?: string;
  text?: string;
  page?: number;
  pageSize?: number;
  sortBy?: string;
  sortDirection?: 'asc' | 'desc';
}

