// <auto-generated>
//     This code was generated by TargCC UI Generator.
//     Generator: TypeScriptTypes
//     Table: ccvwComboList_CustomerCreditCard
//     Generated: 2025-12-17 12:56:55
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

/**
 * CcvwComboListCustomerCreditCard entity interface.
 * Generated from table: ccvwComboList_CustomerCreditCard
 */
export interface CcvwComboListCustomerCreditCard {
  id: number;
  textNS?: string;
  text?: string;
}


/**
 * Create CcvwComboListCustomerCreditCard request interface.
 */
export interface CreateCcvwComboListCustomerCreditCardRequest {
  textNS?: string;
  text?: string;
}


/**
 * Update CcvwComboListCustomerCreditCard request interface.
 */
export interface UpdateCcvwComboListCustomerCreditCardRequest extends CreateCcvwComboListCustomerCreditCardRequest {
  id: number;
}


/**
 * CcvwComboListCustomerCreditCard filters for querying.
 */
export interface CcvwComboListCustomerCreditCardFilters {
  id?: number;
  textNS?: string;
  text?: string;
  page?: number;
  pageSize?: number;
  sortBy?: string;
  sortDirection?: 'asc' | 'desc';
}

