// <auto-generated>
//     This code was generated by TargCC UI Generator.
//     Generator: TypeScriptTypes
//     Table: c_Enumeration
//     Generated: 2025-12-15 22:04:07
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

/**
 * Enumeration entity interface.
 * Generated from table: c_Enumeration
 */
export interface Enumeration {
  id: number;
  isSystem?: boolean;
  enumType?: string;
  enumValue?: string;
  locText?: string;
  tableNameCEnumeration?: boolean;
  deletedBy?: string;
  deletedOn?: Date;
  updatingLoginID?: number;
  // Audit fields
  readonly addedBy?: number;
  readonly addedOn?: Date;
  readonly changedBy?: number;
  readonly changedOn?: Date;
}


/**
 * Create Enumeration request interface.
 */
export interface CreateEnumerationRequest {
  isSystem?: boolean;
  enumType?: string;
  enumValue?: string;
  locText?: string;
  tableNameCEnumeration?: boolean;
  deletedBy?: string;
  deletedOn?: Date;
  updatingLoginID?: number;
}


/**
 * Update Enumeration request interface.
 */
export interface UpdateEnumerationRequest extends CreateEnumerationRequest {
  id: number;
}


/**
 * Enumeration filters for querying.
 */
export interface EnumerationFilters {
  id?: number;
  enumType?: string;
  enumValue?: string;
  locText?: string;
  deletedBy?: string;
  deletedOnFrom?: Date;
  deletedOnTo?: Date;
  page?: number;
  pageSize?: number;
  sortBy?: string;
  sortDirection?: 'asc' | 'desc';
}

