// <auto-generated>
//     This code was generated by TargCC UI Generator.
//     Generator: TypeScriptTypes
//     Table: ExternalCustomer
//     Generated: 2025-12-16 10:02:27
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

/**
 * ExternalCustomer entity interface.
 * Generated from table: ExternalCustomer
 */
export interface ExternalCustomer {
  tableNameExternalCustomer?: boolean;
  id: number;
  customerID: number;
  enmExternalService: string;
  externalCustomerIdentifier?: string;
  readonly dateCreated: Date;
  whenCustomerDetailsUpdatedAtExternalService?: Date;
  whenDocumentationRecdFromExternalService?: Date;
  enmExternalCustomerStatus?: string;
  statusDescription?: string;
  lastLoggedAlertID?: number;
  comments?: string;
  whenLastUsed?: Date;
  deletedBy?: string;
  deletedOn?: Date;
  updatingLoginID?: number;
  // Audit fields
  readonly addedBy?: number;
  readonly addedOn?: Date;
  readonly changedBy?: number;
  readonly changedOn?: Date;
}


/**
 * Create ExternalCustomer request interface.
 */
export interface CreateExternalCustomerRequest {
  tableNameExternalCustomer?: boolean;
  customerID: number;
  enmExternalService: string;
  externalCustomerIdentifier?: string;
  whenCustomerDetailsUpdatedAtExternalService?: Date;
  whenDocumentationRecdFromExternalService?: Date;
  enmExternalCustomerStatus?: string;
  statusDescription?: string;
  lastLoggedAlertID?: number;
  comments?: string;
  whenLastUsed?: Date;
  deletedBy?: string;
  deletedOn?: Date;
  updatingLoginID?: number;
}


/**
 * Update ExternalCustomer request interface.
 */
export interface UpdateExternalCustomerRequest extends CreateExternalCustomerRequest {
  id: number;
}


/**
 * ExternalCustomer filters for querying.
 */
export interface ExternalCustomerFilters {
  id?: number;
  customerID?: number;
  enmExternalService?: string;
  externalCustomerIdentifier?: string;
  enmExternalCustomerStatus?: string;
  dateCreatedFrom?: Date;
  dateCreatedTo?: Date;
  whenCustomerDetailsUpdatedAtExternalServiceFrom?: Date;
  whenCustomerDetailsUpdatedAtExternalServiceTo?: Date;
  page?: number;
  pageSize?: number;
  sortBy?: string;
  sortDirection?: 'asc' | 'desc';
}

