// <auto-generated>
//     This code was generated by TargCC UI Generator.
//     Generator: TypeScriptTypes
//     Table: GovtReportDefinition
//     Generated: 2025-12-16 08:57:49
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

/**
 * GovtReportDefinition entity interface.
 * Generated from table: GovtReportDefinition
 */
export interface GovtReportDefinition {
  tableNameGovtReportDefinition: boolean;
  governmentReportMinimumAmount?: number;
  reporterGovernmentID?: string;
  reportCode?: string;
  branchNumber?: string;
  reporterName?: string;
  reporterAddress01?: string;
  reporterAddress02?: string;
  phoneNumber?: string;
  phoneNumber2?: string;
  fax?: string;
  fileDescription?: string;
  versionNumber?: string;
  reportApproverName?: string;
  reportApproverGovtID?: string;
  reportBankNumber?: string;
  reportBankBranchNumber?: string;
  reportBankCountryCode?: string;
  reportBankName?: string;
  reportBankAddress?: string;
  reportBankAccountNumber?: string;
  updatingLoginID?: number;
}


/**
 * Create GovtReportDefinition request interface.
 */
export interface CreateGovtReportDefinitionRequest {
  governmentReportMinimumAmount?: number;
  reporterGovernmentID?: string;
  reportCode?: string;
  branchNumber?: string;
  reporterName?: string;
  reporterAddress01?: string;
  reporterAddress02?: string;
  phoneNumber?: string;
  phoneNumber2?: string;
  fax?: string;
  fileDescription?: string;
  versionNumber?: string;
  reportApproverName?: string;
  reportApproverGovtID?: string;
  reportBankNumber?: string;
  reportBankBranchNumber?: string;
  reportBankCountryCode?: string;
  reportBankName?: string;
  reportBankAddress?: string;
  reportBankAccountNumber?: string;
  updatingLoginID?: number;
}


/**
 * Update GovtReportDefinition request interface.
 */
export interface UpdateGovtReportDefinitionRequest extends CreateGovtReportDefinitionRequest {
  tableNameGovtReportDefinition: boolean;
}


/**
 * GovtReportDefinition filters for querying.
 */
export interface GovtReportDefinitionFilters {
  governmentReportMinimumAmount?: number;
  reporterGovernmentID?: string;
  reportCode?: string;
  branchNumber?: string;
  reporterName?: string;
  page?: number;
  pageSize?: number;
  sortBy?: string;
  sortDirection?: 'asc' | 'desc';
}

