// <auto-generated>
//     This code was generated by TargCC UI Generator.
//     Generator: TypeScriptTypes
//     Table: ImportTransactionLoad
//     Generated: 2025-12-17 21:11:16
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

/**
 * ImportTransactionLoad entity interface.
 * Generated from table: ImportTransactionLoad
 */
export interface ImportTransactionLoad {
  tableNameImportTransactionLoad?: boolean;
  id: number;
  distributorID: number;
  whenInitialized: Date;
  initiatedByUserID?: number;
  whenCompleted?: Date;
  loadsRequested?: number;
  loadsApproved?: number;
  comments?: string;
  deletedBy?: string;
  deletedOn?: Date;
  updatingLoginID?: number;
  // Audit fields
  readonly addedBy?: number;
  readonly addedOn?: Date;
  readonly changedBy?: number;
  readonly changedOn?: Date;
}


/**
 * Create ImportTransactionLoad request interface.
 */
export interface CreateImportTransactionLoadRequest {
  tableNameImportTransactionLoad?: boolean;
  distributorID: number;
  whenInitialized: Date;
  initiatedByUserID?: number;
  whenCompleted?: Date;
  loadsRequested?: number;
  loadsApproved?: number;
  comments?: string;
  deletedBy?: string;
  deletedOn?: Date;
  updatingLoginID?: number;
}


/**
 * Update ImportTransactionLoad request interface.
 */
export interface UpdateImportTransactionLoadRequest extends CreateImportTransactionLoadRequest {
  id: number;
}


/**
 * ImportTransactionLoad filters for querying.
 */
export interface ImportTransactionLoadFilters {
  id?: number;
  distributorID?: number;
  initiatedByUserID?: number;
  loadsRequested?: number;
  loadsApproved?: number;
  whenInitializedFrom?: Date;
  whenInitializedTo?: Date;
  whenCompletedFrom?: Date;
  whenCompletedTo?: Date;
  page?: number;
  pageSize?: number;
  sortBy?: string;
  sortDirection?: 'asc' | 'desc';
}

