// <auto-generated>
//     This code was generated by TargCC UI Generator.
//     Generator: TypeScriptTypes
//     Table: mnvwComboList_CustomerWithPhoneAndIdentifier
//     Generated: 2025-12-15 13:53:30
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

/**
 * MnvwComboListCustomerWithPhoneAndIdentifier entity interface.
 * Generated from table: mnvwComboList_CustomerWithPhoneAndIdentifier
 */
export interface MnvwComboListCustomerWithPhoneAndIdentifier {
  id: number;
  textNS?: string;
  text?: string;
}


/**
 * Create MnvwComboListCustomerWithPhoneAndIdentifier request interface.
 */
export interface CreateMnvwComboListCustomerWithPhoneAndIdentifierRequest {
  textNS?: string;
  text?: string;
}


/**
 * Update MnvwComboListCustomerWithPhoneAndIdentifier request interface.
 */
export interface UpdateMnvwComboListCustomerWithPhoneAndIdentifierRequest extends CreateMnvwComboListCustomerWithPhoneAndIdentifierRequest {
  id: number;
}


/**
 * MnvwComboListCustomerWithPhoneAndIdentifier filters for querying.
 */
export interface MnvwComboListCustomerWithPhoneAndIdentifierFilters {
  id?: number;
  textNS?: string;
  text?: string;
  page?: number;
  pageSize?: number;
  sortBy?: string;
  sortDirection?: 'asc' | 'desc';
}

