// <auto-generated>
//     This code was generated by TargCC UI Generator.
//     Generator: TypeScriptTypes
//     Table: vwCustomerSecurityStatusCheckData
//     Generated: 2025-12-16 09:26:48
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

/**
 * VwCustomerSecurityStatusCheckData entity interface.
 * Generated from table: vwCustomerSecurityStatusCheckData
 */
export interface VwCustomerSecurityStatusCheckData {
  id?: number;
  customerID: number;
  customerName: string;
  customerIdentifier: string;
  customerPhone?: string;
  customerEmail?: string;
  enmCustomerType?: string;
  enmSecurityTier?: string;
  isBusiness?: boolean;
  walletBalanceWorking?: number;
  totalTransferredToWallet?: number;
  totalTransferredToWallet6Months?: number;
  totalTransferredToWallet1Month?: number;
  hasSignedServiceRequest?: boolean;
}


/**
 * Create VwCustomerSecurityStatusCheckData request interface.
 */
export interface CreateVwCustomerSecurityStatusCheckDataRequest {
  customerID: number;
  customerName: string;
  customerIdentifier: string;
  customerPhone?: string;
  customerEmail?: string;
  enmCustomerType?: string;
  enmSecurityTier?: string;
  isBusiness?: boolean;
  walletBalanceWorking?: number;
  totalTransferredToWallet?: number;
  totalTransferredToWallet6Months?: number;
  totalTransferredToWallet1Month?: number;
  hasSignedServiceRequest?: boolean;
}


/**
 * Update VwCustomerSecurityStatusCheckData request interface.
 */
export interface UpdateVwCustomerSecurityStatusCheckDataRequest extends CreateVwCustomerSecurityStatusCheckDataRequest {
  id: number;
}


/**
 * VwCustomerSecurityStatusCheckData filters for querying.
 */
export interface VwCustomerSecurityStatusCheckDataFilters {
  id?: number;
  customerID?: number;
  customerName?: string;
  customerIdentifier?: string;
  customerPhone?: string;
  page?: number;
  pageSize?: number;
  sortBy?: string;
  sortDirection?: 'asc' | 'desc';
}

