// <auto-generated>
//     This code was generated by TargCC UI Generator.
//     Generator: TypeScriptTypes
//     Table: vwReportCustomerWalletBalanceForLawyer
//     Generated: 2025-12-17 09:08:28
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

/**
 * VwReportCustomerWalletBalanceForLawyer entity interface.
 * Generated from table: vwReportCustomerWalletBalanceForLawyer
 */
export interface VwReportCustomerWalletBalanceForLawyer {
  id?: number;
  customerID?: number;
  effectiveDate?: Date;
  presentRawBalance?: number;
  enmCustomerType?: string;
}


/**
 * Create VwReportCustomerWalletBalanceForLawyer request interface.
 */
export interface CreateVwReportCustomerWalletBalanceForLawyerRequest {
  customerID?: number;
  effectiveDate?: Date;
  presentRawBalance?: number;
  enmCustomerType?: string;
}


/**
 * Update VwReportCustomerWalletBalanceForLawyer request interface.
 */
export interface UpdateVwReportCustomerWalletBalanceForLawyerRequest extends CreateVwReportCustomerWalletBalanceForLawyerRequest {
  id: number;
}


/**
 * VwReportCustomerWalletBalanceForLawyer filters for querying.
 */
export interface VwReportCustomerWalletBalanceForLawyerFilters {
  id?: number;
  customerID?: number;
  presentRawBalance?: number;
  enmCustomerType?: string;
  effectiveDateFrom?: Date;
  effectiveDateTo?: Date;
  page?: number;
  pageSize?: number;
  sortBy?: string;
  sortDirection?: 'asc' | 'desc';
}

