// <auto-generated>
//     This code was generated by TargCC UI Generator.
//     Generator: ReactHooks
//     Table: ccvwComboList_CustomerCardTransactionForCustomer
//     Generated: 2025-12-17 17:47:21
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

import { useQuery } from '@tanstack/react-query';
import { ccvwComboListCustomerCardTransactionForCustomerApi } from '../api/ccvwComboListCustomerCardTransactionForCustomerApi';
import type { UseEntityOptions } from '../types/common.types';
import type { CcvwComboListCustomerCardTransactionForCustomerFilters } from '../types/CcvwComboListCustomerCardTransactionForCustomer.types';

type UseCcvwComboListCustomerCardTransactionForCustomerOptions = UseEntityOptions<CcvwComboListCustomerCardTransactionForCustomerFilters>;

/**
 * Hook to fetch all CcvwComboListCustomerCardTransactionForCustomers with server-side filtering, sorting, and pagination.
 */
export const useCcvwComboListCustomerCardTransactionForCustomers = (options?: UseCcvwComboListCustomerCardTransactionForCustomerOptions) => {
  return useQuery({
    queryKey: ['ccvwComboListCustomerCardTransactionForCustomers', options],
    queryFn: () => ccvwComboListCustomerCardTransactionForCustomerApi.getAll(options),
    enabled: options?.enabled !== false,
    staleTime: 30000, // 30 seconds
  });
};


