// <auto-generated>
//     This code was generated by TargCC UI Generator.
//     Generator: ReactHooks
//     Table: ccvwComboList_CardOrderByDistributorForOrderedByUser
//     Generated: 2025-12-11 20:26:14
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { ccvwComboListCardOrderByDistributorForOrderedByUserApi } from '../api/ccvwComboListCardOrderByDistributorForOrderedByUserApi';
import type {
  CcvwComboListCardOrderByDistributorForOrderedByUser,
  CcvwComboListCardOrderByDistributorForOrderedByUserFilters,
} from '../types/CcvwComboListCardOrderByDistributorForOrderedByUser.types';

/**
 * Hook to fetch all CcvwComboListCardOrderByDistributorForOrderedByUsers with optional filters.
 */
export const useCcvwComboListCardOrderByDistributorForOrderedByUsers = (filters?: CcvwComboListCardOrderByDistributorForOrderedByUserFilters) => {
  return useQuery({
    queryKey: ['ccvwComboListCardOrderByDistributorForOrderedByUsers', filters],
    queryFn: () => ccvwComboListCardOrderByDistributorForOrderedByUserApi.getAll(filters),
  });
};


