// <auto-generated>
//     This code was generated by TargCC UI Generator.
//     Generator: ReactHooks
//     Table: ccvwComboList_c_Enumeration
//     Generated: 2025-12-11 13:48:44
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { ccvwComboListCEnumerationApi } from '../api/ccvwComboListCEnumerationApi';
import type {
  CcvwComboListCEnumeration,
  CcvwComboListCEnumerationFilters,
} from '../types/CcvwComboListCEnumeration.types';

/**
 * Hook to fetch all CcvwComboListCEnumerations with optional filters.
 */
export const useCcvwComboListCEnumerations = (filters?: CcvwComboListCEnumerationFilters) => {
  return useQuery({
    queryKey: ['ccvwComboListCEnumerations', filters],
    queryFn: () => ccvwComboListCEnumerationApi.getAll(filters),
  });
};


