// <auto-generated>
//     This code was generated by TargCC UI Generator.
//     Generator: ReactHooks
//     Table: ccvwComboList_c_SystemDefault
//     Generated: 2025-12-11 21:58:10
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { ccvwComboListCSystemDefaultApi } from '../api/ccvwComboListCSystemDefaultApi';
import type {
  CcvwComboListCSystemDefault,
  CcvwComboListCSystemDefaultFilters,
} from '../types/CcvwComboListCSystemDefault.types';

/**
 * Hook to fetch all CcvwComboListCSystemDefaults with optional filters.
 */
export const useCcvwComboListCSystemDefaults = (filters?: CcvwComboListCSystemDefaultFilters) => {
  return useQuery({
    queryKey: ['ccvwComboListCSystemDefaults', filters],
    queryFn: () => ccvwComboListCSystemDefaultApi.getAll(filters),
  });
};


