// <auto-generated>
//     This code was generated by TargCC UI Generator.
//     Generator: ReactHooks
//     Table: ccvwComboList_CardActivationForCustomer
//     Generated: 2025-12-11 11:52:11
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { ccvwComboListCardActivationForCustomerApi } from '../api/ccvwComboListCardActivationForCustomerApi';
import type {
  CcvwComboListCardActivationForCustomer,
  CcvwComboListCardActivationForCustomerFilters,
} from '../types/CcvwComboListCardActivationForCustomer.types';

/**
 * Hook to fetch all CcvwComboListCardActivationForCustomers with optional filters.
 */
export const useCcvwComboListCardActivationForCustomers = (filters?: CcvwComboListCardActivationForCustomerFilters) => {
  return useQuery({
    queryKey: ['ccvwComboListCardActivationForCustomers', filters],
    queryFn: () => ccvwComboListCardActivationForCustomerApi.getAll(filters),
  });
};


