// <auto-generated>
//     This code was generated by TargCC UI Generator.
//     Generator: ReactHooks
//     Table: ccvwComboList_CardActivationForDistributor
//     Generated: 2025-12-11 20:26:14
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { ccvwComboListCardActivationForDistributorApi } from '../api/ccvwComboListCardActivationForDistributorApi';
import type {
  CcvwComboListCardActivationForDistributor,
  CcvwComboListCardActivationForDistributorFilters,
} from '../types/CcvwComboListCardActivationForDistributor.types';

/**
 * Hook to fetch all CcvwComboListCardActivationForDistributors with optional filters.
 */
export const useCcvwComboListCardActivationForDistributors = (filters?: CcvwComboListCardActivationForDistributorFilters) => {
  return useQuery({
    queryKey: ['ccvwComboListCardActivationForDistributors', filters],
    queryFn: () => ccvwComboListCardActivationForDistributorApi.getAll(filters),
  });
};


