// <auto-generated>
//     This code was generated by TargCC UI Generator.
//     Generator: ReactHooks
//     Table: ccvwComboList_EntityRiskColor
//     Generated: 2025-12-17 12:56:55
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

import { useQuery } from '@tanstack/react-query';
import { ccvwComboListEntityRiskColorApi } from '../api/ccvwComboListEntityRiskColorApi';
import type { UseEntityOptions } from '../types/common.types';
import type { CcvwComboListEntityRiskColorFilters } from '../types/CcvwComboListEntityRiskColor.types';

type UseCcvwComboListEntityRiskColorOptions = UseEntityOptions<CcvwComboListEntityRiskColorFilters>;

/**
 * Hook to fetch all CcvwComboListEntityRiskColors with server-side filtering, sorting, and pagination.
 */
export const useCcvwComboListEntityRiskColors = (options?: UseCcvwComboListEntityRiskColorOptions) => {
  return useQuery({
    queryKey: ['ccvwComboListEntityRiskColors', options],
    queryFn: () => ccvwComboListEntityRiskColorApi.getAll(options),
    enabled: options?.enabled !== false,
    staleTime: 30000, // 30 seconds
  });
};


