// <auto-generated>
//     This code was generated by TargCC UI Generator.
//     Generator: ReactHooks
//     Table: ccvwComboList_RiskRuleLog
//     Generated: 2025-12-15 13:53:28
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

import { useQuery } from '@tanstack/react-query';
import { ccvwComboListRiskRuleLogApi } from '../api/ccvwComboListRiskRuleLogApi';
import type { CcvwComboListRiskRuleLogFilters } from '../types/CcvwComboListRiskRuleLog.types';

/**
 * Hook to fetch all CcvwComboListRiskRuleLogs with optional filters.
 */
export const useCcvwComboListRiskRuleLogs = (filters?: CcvwComboListRiskRuleLogFilters) => {
  return useQuery({
    queryKey: ['ccvwComboListRiskRuleLogs', filters],
    queryFn: () => ccvwComboListRiskRuleLogApi.getAll(filters),
  });
};


