// <auto-generated>
//     This code was generated by TargCC UI Generator.
//     Generator: ReactHooks
//     Table: DistributorObligo
//     Generated: 2025-12-17 20:20:33
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { distributorObligoApi } from '../api/distributorObligoApi';
import type { UseEntityOptions } from '../types/common.types';
import type { CreateDistributorObligoRequest, UpdateDistributorObligoRequest, DistributorObligoFilters } from '../types/DistributorObligo.types';

type UseDistributorObligoOptions = UseEntityOptions<DistributorObligoFilters>;

/**
 * Hook to fetch single DistributorObligo by ID.
 */
export const useDistributorObligo = (id: number | null) => {
  return useQuery({
    queryKey: ['distributorObligo', id],
    queryFn: () => distributorObligoApi.getById(id!),
    enabled: id !== null,
  });
};


/**
 * Hook to fetch all DistributorObligos with server-side filtering, sorting, and pagination.
 */
export const useDistributorObligos = (options?: UseDistributorObligoOptions) => {
  return useQuery({
    queryKey: ['distributorObligos', options],
    queryFn: () => distributorObligoApi.getAll(options),
    enabled: options?.enabled !== false,
    staleTime: 30000, // 30 seconds
  });
};


/**
 * Hook to create DistributorObligo.
 */
export const useCreateDistributorObligo = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: (data: CreateDistributorObligoRequest) => distributorObligoApi.create(data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['distributorObligos'] });
    },
  });
};


/**
 * Hook to update DistributorObligo.
 */
export const useUpdateDistributorObligo = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: ({ id, data }: { id: number; data: UpdateDistributorObligoRequest }) =>
      distributorObligoApi.update(id, data),
    onSuccess: (_, variables) => {
      queryClient.invalidateQueries({ queryKey: ['distributorObligo', variables.id] });
      queryClient.invalidateQueries({ queryKey: ['distributorObligos'] });
    },
  });
};


/**
 * Hook to delete DistributorObligo.
 */
export const useDeleteDistributorObligo = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: (id: number) => distributorObligoApi.delete(id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['distributorObligos'] });
    },
  });
};


