// <auto-generated>
//     This code was generated by TargCC UI Generator.
//     Generator: ReactHooks
//     Table: GovtReportPayment
//     Generated: 2025-12-16 18:22:30
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { govtReportPaymentApi } from '../api/govtReportPaymentApi';
import type { UseEntityOptions } from '../types/common.types';
import type { CreateGovtReportPaymentRequest, UpdateGovtReportPaymentRequest, GovtReportPaymentFilters } from '../types/GovtReportPayment.types';

type UseGovtReportPaymentOptions = UseEntityOptions<GovtReportPaymentFilters>;

/**
 * Hook to fetch single GovtReportPayment by ID.
 */
export const useGovtReportPayment = (id: number | null) => {
  return useQuery({
    queryKey: ['govtReportPayment', id],
    queryFn: () => govtReportPaymentApi.getById(id!),
    enabled: id !== null,
  });
};


/**
 * Hook to fetch all GovtReportPayments with server-side filtering, sorting, and pagination.
 */
export const useGovtReportPayments = (options?: UseGovtReportPaymentOptions) => {
  return useQuery({
    queryKey: ['govtReportPayments', options],
    queryFn: () => govtReportPaymentApi.getAll(options),
    enabled: options?.enabled !== false,
    staleTime: 30000, // 30 seconds
  });
};


/**
 * Hook to create GovtReportPayment.
 */
export const useCreateGovtReportPayment = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: (data: CreateGovtReportPaymentRequest) => govtReportPaymentApi.create(data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['govtReportPayments'] });
    },
  });
};


/**
 * Hook to update GovtReportPayment.
 */
export const useUpdateGovtReportPayment = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: ({ id, data }: { id: number; data: UpdateGovtReportPaymentRequest }) =>
      govtReportPaymentApi.update(id, data),
    onSuccess: (_, variables) => {
      queryClient.invalidateQueries({ queryKey: ['govtReportPayment', variables.id] });
      queryClient.invalidateQueries({ queryKey: ['govtReportPayments'] });
    },
  });
};


/**
 * Hook to delete GovtReportPayment.
 */
export const useDeleteGovtReportPayment = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: (id: number) => govtReportPaymentApi.delete(id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['govtReportPayments'] });
    },
  });
};


