// <auto-generated>
//     This code was generated by TargCC UI Generator.
//     Generator: ReactHooks
//     Table: c_Mail
//     Generated: 2025-12-17 07:22:06
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { mailApi } from '../api/mailApi';
import type { UseEntityOptions } from '../types/common.types';
import type { CreateMailRequest, UpdateMailRequest, MailFilters } from '../types/Mail.types';

type UseMailOptions = UseEntityOptions<MailFilters>;

/**
 * Hook to fetch single Mail by ID.
 */
export const useMail = (id: number | null) => {
  return useQuery({
    queryKey: ['mail', id],
    queryFn: () => mailApi.getById(id!),
    enabled: id !== null,
  });
};


/**
 * Hook to fetch all Mails with server-side filtering, sorting, and pagination.
 */
export const useMails = (options?: UseMailOptions) => {
  return useQuery({
    queryKey: ['mails', options],
    queryFn: () => mailApi.getAll(options),
    enabled: options?.enabled !== false,
    staleTime: 30000, // 30 seconds
  });
};


/**
 * Hook to create Mail.
 */
export const useCreateMail = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: (data: CreateMailRequest) => mailApi.create(data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['mails'] });
    },
  });
};


/**
 * Hook to update Mail.
 */
export const useUpdateMail = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: ({ id, data }: { id: number; data: UpdateMailRequest }) =>
      mailApi.update(id, data),
    onSuccess: (_, variables) => {
      queryClient.invalidateQueries({ queryKey: ['mail', variables.id] });
      queryClient.invalidateQueries({ queryKey: ['mails'] });
    },
  });
};


/**
 * Hook to delete Mail.
 */
export const useDeleteMail = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: (id: number) => mailApi.delete(id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['mails'] });
    },
  });
};


