// <auto-generated>
//     This code was generated by TargCC UI Generator.
//     Generator: ReactHooks
//     Table: MCCBTransaction
//     Generated: 2025-12-11 11:52:13
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { mCCBTransactionApi } from '../api/mCCBTransactionApi';
import type {
  MCCBTransaction,
  CreateMCCBTransactionRequest,
  UpdateMCCBTransactionRequest,
  MCCBTransactionFilters,
} from '../types/MCCBTransaction.types';
import type { MCCBSecurityCheck } from '../types/MCCBSecurityCheck.types';

/**
 * Hook to fetch single MCCBTransaction by ID.
 */
export const useMCCBTransaction = (id: number | null) => {
  return useQuery({
    queryKey: ['mCCBTransaction', id],
    queryFn: () => mCCBTransactionApi.getById(id!),
    enabled: id !== null,
  });
};


/**
 * Hook to fetch all MCCBTransactions with optional filters.
 */
export const useMCCBTransactions = (filters?: MCCBTransactionFilters) => {
  return useQuery({
    queryKey: ['mCCBTransactions', filters],
    queryFn: () => mCCBTransactionApi.getAll(filters),
  });
};


/**
 * Hook to fetch mCCBSecurityChecks for a specific MCCBTRANSACTION.
 */
export const useMCCBTransactionMCCBSecurityChecks = (
  mCCBTransactionId: number | null,
  skip?: number,
  take?: number
) => {
  return useQuery({
    queryKey: ['mCCBTransaction', mCCBTransactionId, 'mCCBSecurityChecks', skip, take],
    queryFn: () => mCCBTransactionApi.getMCCBSecurityChecks(mCCBTransactionId!, skip, take),
    enabled: mCCBTransactionId !== null,
  });
};

/**
 * Hook to create MCCBTransaction.
 */
export const useCreateMCCBTransaction = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: (data: CreateMCCBTransactionRequest) => mCCBTransactionApi.create(data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['mCCBTransactions'] });
    },
  });
};


/**
 * Hook to update MCCBTransaction.
 */
export const useUpdateMCCBTransaction = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: ({ id, data }: { id: number; data: UpdateMCCBTransactionRequest }) =>
      mCCBTransactionApi.update(id, data),
    onSuccess: (_, variables) => {
      queryClient.invalidateQueries({ queryKey: ['mCCBTransaction', variables.id] });
      queryClient.invalidateQueries({ queryKey: ['mCCBTransactions'] });
    },
  });
};


/**
 * Hook to delete MCCBTransaction.
 */
export const useDeleteMCCBTransaction = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: (id: number) => mCCBTransactionApi.delete(id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['mCCBTransactions'] });
    },
  });
};


