// <auto-generated>
//     This code was generated by TargCC UI Generator.
//     Generator: ReactHooks
//     Table: MCCBParticipant
//     Generated: 2025-12-16 18:22:30
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { mCCBParticipantApi } from '../api/mCCBParticipantApi';
import type { UseEntityOptions } from '../types/common.types';
import type { CreateMCCBParticipantRequest, UpdateMCCBParticipantRequest, MCCBParticipantFilters } from '../types/MCCBParticipant.types';

type UseMCCBParticipantOptions = UseEntityOptions<MCCBParticipantFilters>;

/**
 * Hook to fetch single MCCBParticipant by ID.
 */
export const useMCCBParticipant = (id: number | null) => {
  return useQuery({
    queryKey: ['mCCBParticipant', id],
    queryFn: () => mCCBParticipantApi.getById(id!),
    enabled: id !== null,
  });
};


/**
 * Hook to fetch all MCCBParticipants with server-side filtering, sorting, and pagination.
 */
export const useMCCBParticipants = (options?: UseMCCBParticipantOptions) => {
  return useQuery({
    queryKey: ['mCCBParticipants', options],
    queryFn: () => mCCBParticipantApi.getAll(options),
    enabled: options?.enabled !== false,
    staleTime: 30000, // 30 seconds
  });
};


/**
 * Hook to create MCCBParticipant.
 */
export const useCreateMCCBParticipant = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: (data: CreateMCCBParticipantRequest) => mCCBParticipantApi.create(data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['mCCBParticipants'] });
    },
  });
};


/**
 * Hook to update MCCBParticipant.
 */
export const useUpdateMCCBParticipant = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: ({ id, data }: { id: number; data: UpdateMCCBParticipantRequest }) =>
      mCCBParticipantApi.update(id, data),
    onSuccess: (_, variables) => {
      queryClient.invalidateQueries({ queryKey: ['mCCBParticipant', variables.id] });
      queryClient.invalidateQueries({ queryKey: ['mCCBParticipants'] });
    },
  });
};


/**
 * Hook to delete MCCBParticipant.
 */
export const useDeleteMCCBParticipant = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: (id: number) => mCCBParticipantApi.delete(id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['mCCBParticipants'] });
    },
  });
};


