// <auto-generated>
//     This code was generated by TargCC UI Generator.
//     Generator: ReactHooks
//     Table: OneTimeLink
//     Generated: 2025-12-17 17:47:24
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { oneTimeLinkApi } from '../api/oneTimeLinkApi';
import type { UseEntityOptions } from '../types/common.types';
import type { CreateOneTimeLinkRequest, UpdateOneTimeLinkRequest, OneTimeLinkFilters } from '../types/OneTimeLink.types';

type UseOneTimeLinkOptions = UseEntityOptions<OneTimeLinkFilters>;

/**
 * Hook to fetch single OneTimeLink by ID.
 */
export const useOneTimeLink = (id: number | null) => {
  return useQuery({
    queryKey: ['oneTimeLink', id],
    queryFn: () => oneTimeLinkApi.getById(id!),
    enabled: id !== null,
  });
};


/**
 * Hook to fetch all OneTimeLinks with server-side filtering, sorting, and pagination.
 */
export const useOneTimeLinks = (options?: UseOneTimeLinkOptions) => {
  return useQuery({
    queryKey: ['oneTimeLinks', options],
    queryFn: () => oneTimeLinkApi.getAll(options),
    enabled: options?.enabled !== false,
    staleTime: 30000, // 30 seconds
  });
};


/**
 * Hook to create OneTimeLink.
 */
export const useCreateOneTimeLink = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: (data: CreateOneTimeLinkRequest) => oneTimeLinkApi.create(data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['oneTimeLinks'] });
    },
  });
};


/**
 * Hook to update OneTimeLink.
 */
export const useUpdateOneTimeLink = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: ({ id, data }: { id: number; data: UpdateOneTimeLinkRequest }) =>
      oneTimeLinkApi.update(id, data),
    onSuccess: (_, variables) => {
      queryClient.invalidateQueries({ queryKey: ['oneTimeLink', variables.id] });
      queryClient.invalidateQueries({ queryKey: ['oneTimeLinks'] });
    },
  });
};


/**
 * Hook to delete OneTimeLink.
 */
export const useDeleteOneTimeLink = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: (id: number) => oneTimeLinkApi.delete(id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['oneTimeLinks'] });
    },
  });
};


