// <auto-generated>
//     This code was generated by TargCC UI Generator.
//     Generator: ReactHooks
//     Table: c_Process
//     Generated: 2025-12-11 14:19:33
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { processApi } from '../api/processApi';
import type {
  Process,
  CreateProcessRequest,
  UpdateProcessRequest,
  ProcessFilters,
} from '../types/Process.types';
import type { Permission } from '../types/Permission.types';

/**
 * Hook to fetch single Process by ID.
 */
export const useProcess = (id: number | null) => {
  return useQuery({
    queryKey: ['process', id],
    queryFn: () => processApi.getById(id!),
    enabled: id !== null,
  });
};


/**
 * Hook to fetch all Processs with optional filters.
 */
export const useProcesss = (filters?: ProcessFilters) => {
  return useQuery({
    queryKey: ['processs', filters],
    queryFn: () => processApi.getAll(filters),
  });
};


/**
 * Hook to fetch permissions for a specific PROCESS.
 */
export const useProcessPermissions = (
  processId: number | null,
  skip?: number,
  take?: number
) => {
  return useQuery({
    queryKey: ['process', processId, 'permissions', skip, take],
    queryFn: () => processApi.getPermissions(processId!, skip, take),
    enabled: processId !== null,
  });
};

/**
 * Hook to create Process.
 */
export const useCreateProcess = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: (data: CreateProcessRequest) => processApi.create(data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['processs'] });
    },
  });
};


/**
 * Hook to update Process.
 */
export const useUpdateProcess = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: ({ id, data }: { id: number; data: UpdateProcessRequest }) =>
      processApi.update(id, data),
    onSuccess: (_, variables) => {
      queryClient.invalidateQueries({ queryKey: ['process', variables.id] });
      queryClient.invalidateQueries({ queryKey: ['processs'] });
    },
  });
};


/**
 * Hook to delete Process.
 */
export const useDeleteProcess = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: (id: number) => processApi.delete(id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['processs'] });
    },
  });
};


