// <auto-generated>
//     This code was generated by TargCC UI Generator.
//     Generator: ReactHooks
//     Table: Task
//     Generated: 2025-12-17 21:37:05
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { taskApi } from '../api/taskApi';
import type { UseEntityOptions } from '../types/common.types';
import type { CreateTaskRequest, UpdateTaskRequest, TaskFilters } from '../types/Task.types';

type UseTaskOptions = UseEntityOptions<TaskFilters>;

/**
 * Hook to fetch single Task by ID.
 */
export const useTask = (id: number | null) => {
  return useQuery({
    queryKey: ['task', id],
    queryFn: () => taskApi.getById(id!),
    enabled: id !== null,
  });
};


/**
 * Hook to fetch all Tasks with server-side filtering, sorting, and pagination.
 */
export const useTasks = (options?: UseTaskOptions) => {
  return useQuery({
    queryKey: ['tasks', options],
    queryFn: () => taskApi.getAll(options),
    enabled: options?.enabled !== false,
    staleTime: 30000, // 30 seconds
  });
};


/**
 * Hook to create Task.
 */
export const useCreateTask = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: (data: CreateTaskRequest) => taskApi.create(data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['tasks'] });
    },
  });
};


/**
 * Hook to update Task.
 */
export const useUpdateTask = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: ({ id, data }: { id: number; data: UpdateTaskRequest }) =>
      taskApi.update(id, data),
    onSuccess: (_, variables) => {
      queryClient.invalidateQueries({ queryKey: ['task', variables.id] });
      queryClient.invalidateQueries({ queryKey: ['tasks'] });
    },
  });
};


/**
 * Hook to delete Task.
 */
export const useDeleteTask = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: (id: number) => taskApi.delete(id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['tasks'] });
    },
  });
};


