// <auto-generated>
//     This code was generated by TargCC UI Generator.
//     Generator: ReactHooks
//     Table: vwReportToChanger
//     Generated: 2025-12-15 13:48:34
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

import { useQuery } from '@tanstack/react-query';
import { vwReportToChangerApi } from '../api/vwReportToChangerApi';

/**
 * Hook to fetch all VwReportToChangers with optional filters.
 */
export const useVwReportToChangers = (filters?: VwReportToChangerFilters) => {
  return useQuery({
    queryKey: ['vwReportToChangers', filters],
    queryFn: () => vwReportToChangerApi.getAll(filters),
  });
};


