// <auto-generated>
//     This code was generated by TargCC UI Generator.
//     Generator: ReactHooks
//     Table: vwReportDistributorObligoBalanceData
//     Generated: 2025-12-15 13:53:31
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

import { useQuery } from '@tanstack/react-query';
import { vwReportDistributorObligoBalanceDataApi } from '../api/vwReportDistributorObligoBalanceDataApi';
import type { VwReportDistributorObligoBalanceDataFilters } from '../types/VwReportDistributorObligoBalanceData.types';

/**
 * Hook to fetch all VwReportDistributorObligoBalanceDatas with optional filters.
 */
export const useVwReportDistributorObligoBalanceDatas = (filters?: VwReportDistributorObligoBalanceDataFilters) => {
  return useQuery({
    queryKey: ['vwReportDistributorObligoBalanceDatas', filters],
    queryFn: () => vwReportDistributorObligoBalanceDataApi.getAll(filters),
  });
};


