// <auto-generated>
//     This code was generated by TargCC UI Generator.
//     Generator: ReactHooks
//     Table: vwCustomerSecurityStatusCheck
//     Generated: 2025-12-15 13:48:33
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

import { useQuery } from '@tanstack/react-query';
import { vwCustomerSecurityStatusCheckApi } from '../api/vwCustomerSecurityStatusCheckApi';

/**
 * Hook to fetch all VwCustomerSecurityStatusChecks with optional filters.
 */
export const useVwCustomerSecurityStatusChecks = (filters?: VwCustomerSecurityStatusCheckFilters) => {
  return useQuery({
    queryKey: ['vwCustomerSecurityStatusChecks', filters],
    queryFn: () => vwCustomerSecurityStatusCheckApi.getAll(filters),
  });
};


