// <auto-generated>
//     This code was generated by TargCC
//     Generated for: ccvwComboList_CardActivationForDistributor (Handler)
//     Generation date: 2025-12-15 22:18:48
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using MediatR;
using Microsoft.Extensions.Logging;
using TargCC.Application.Common.Models;
using TargCC.Domain.Entities;
using TargCC.Domain.Interfaces;

namespace TargCC.Application.Features.ccvwComboList_CardActivationForDistributors.Commands;

/// <summary>
/// Handles the CreateCcvwComboListCardActivationForDistributorCommand request.
/// </summary>
public class CreateCcvwComboListCardActivationForDistributorHandler : IRequestHandler<CreateCcvwComboListCardActivationForDistributorCommand, Result<int>>
{
    private readonly IccvwComboList_CardActivationForDistributorRepository _repository;
    private readonly ILogger<CreateCcvwComboListCardActivationForDistributorHandler> _logger;

    /// <summary>
    /// Initializes a new instance of the <see cref="CreateCcvwComboListCardActivationForDistributorHandler"/> class.
    /// </summary>
    public CreateCcvwComboListCardActivationForDistributorHandler(
        IccvwComboList_CardActivationForDistributorRepository repository,
        ILogger<CreateCcvwComboListCardActivationForDistributorHandler> logger)
    {
        _repository = repository ?? throw new ArgumentNullException(nameof(repository));
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
    }

    /// <inheritdoc/>
    public async Task<Result<int>> Handle(CreateCcvwComboListCardActivationForDistributorCommand request, CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(request);

        _logger.LogDebug("Creating new ccvwComboList_CardActivationForDistributor");

        try
        {
            var entity = new ccvwComboList_CardActivationForDistributor
            {
                ParentID = request.ParentID,
                TextNS = request.TextNS,
                Text = request.Text
            };

            await _repository.AddAsync(entity, cancellationToken);

            _logger.LogInformation("ccvwComboList_CardActivationForDistributor created successfully with ID: {Id}", entity.Id);

            return Result<int>.Success(entity.Id);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error creating ccvwComboList_CardActivationForDistributor");
            throw;
        }
    }
}
