// <auto-generated>
//     This code was generated by TargCC
//     Generated for: Multiple (Validator)
//     Generation date: 2025-12-17 14:47:41
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using FluentValidation;
using UpayCard.RiskManagement.Application.Features.ccvwComboList_c_AlertMessages.Queries;

namespace UpayCard.RiskManagement.Application.Features.ccvwComboList_c_AlertMessages.Queries;

/// <summary>
/// Validator for GetCcvwComboListCAlertMessagesQuery.
/// </summary>
public class GetCcvwComboListCAlertMessagesValidator : AbstractValidator<GetCcvwComboListCAlertMessagesQuery>
{
    /// <summary>
    /// Initializes a new instance of the <see cref="GetCcvwComboListCAlertMessagesValidator"/> class.
    /// </summary>
    public GetCcvwComboListCAlertMessagesValidator()
    {
        RuleFor(x => x.Page)
            .GreaterThan(0)
            .WithMessage("Page number must be greater than 0.");

        RuleFor(x => x.PageSize)
            .InclusiveBetween(1, 100)
            .WithMessage("Page size must be between 1 and 100.");
    }
}
