// <auto-generated>
//     This code was generated by TargCC
//     Generated for: GovtReportDefinition (Handler)
//     Generation date: 2025-12-15 22:55:58
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using MediatR;
using Microsoft.Extensions.Logging;
using UpayCard.RiskManagement.Application.Common.Models;
using UpayCard.RiskManagement.Domain.Entities;
using UpayCard.RiskManagement.Domain.Interfaces;

namespace UpayCard.RiskManagement.Application.Features.GovtReportDefinitions.Commands;

/// <summary>
/// Handles the CreateGovtReportDefinitionCommand request.
/// </summary>
public class CreateGovtReportDefinitionHandler : IRequestHandler<CreateGovtReportDefinitionCommand, Result<int>>
{
    private readonly IGovtReportDefinitionRepository _repository;
    private readonly ILogger<CreateGovtReportDefinitionHandler> _logger;

    /// <summary>
    /// Initializes a new instance of the <see cref="CreateGovtReportDefinitionHandler"/> class.
    /// </summary>
    public CreateGovtReportDefinitionHandler(
        IGovtReportDefinitionRepository repository,
        ILogger<CreateGovtReportDefinitionHandler> logger)
    {
        _repository = repository ?? throw new ArgumentNullException(nameof(repository));
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
    }

    /// <inheritdoc/>
    public async Task<Result<int>> Handle(CreateGovtReportDefinitionCommand request, CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(request);

        _logger.LogDebug("Creating new GovtReportDefinition");

        try
        {
            var entity = new GovtReportDefinition
            {
                TableName_GovtReportDefinition = request.TableName_GovtReportDefinition,
                GovernmentReportMinimumAmount = request.GovernmentReportMinimumAmount,
                ReporterGovernmentID = request.ReporterGovernmentID,
                ReportCode = request.ReportCode,
                BranchNumber = request.BranchNumber,
                ReporterName = request.ReporterName,
                ReporterAddress01 = request.ReporterAddress01,
                ReporterAddress02 = request.ReporterAddress02,
                PhoneNumber = request.PhoneNumber,
                PhoneNumber2 = request.PhoneNumber2,
                Fax = request.Fax,
                FileDescription = request.FileDescription,
                VersionNumber = request.VersionNumber,
                ReportApproverName = request.ReportApproverName,
                ReportApproverGovtID = request.ReportApproverGovtID,
                ReportBankNumber = request.ReportBankNumber,
                ReportBankBranchNumber = request.ReportBankBranchNumber,
                ReportBankCountryCode = request.ReportBankCountryCode,
                ReportBankName = request.ReportBankName,
                ReportBankAddress = request.ReportBankAddress,
                ReportBankAccountNumber = request.ReportBankAccountNumber,
                ChangedBy = request.ChangedBy,
                ChangedOn = request.ChangedOn,
                UpdatingLoginID = request.UpdatingLoginID
            };

            await _repository.AddAsync(entity, cancellationToken);

            _logger.LogInformation("GovtReportDefinition created successfully with ID: {Id}", entity.Id);

            return Result<int>.Success(entity.Id);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error creating GovtReportDefinition");
            throw;
        }
    }
}
