// <auto-generated>
//     This code was generated by TargCC
//     Generated for: vwReportWalletTransferData (Validator)
//     Generation date: 2025-12-17 08:03:55
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using FluentValidation;

namespace UpayCard.RiskManagement.Application.Features.VwReportWalletTransferDatas.Commands;

/// <summary>
/// Validator for CreateVwReportWalletTransferDataCommand.
/// </summary>
public class CreateVwReportWalletTransferDataValidator : AbstractValidator<CreateVwReportWalletTransferDataCommand>
{
    /// <summary>
    /// Initializes a new instance of the <see cref="CreateVwReportWalletTransferDataValidator"/> class.
    /// </summary>
    public CreateVwReportWalletTransferDataValidator()
    {
        RuleFor(x => x.enmBackofficeTransactionType)
            .NotEmpty()
            .MaximumLength(50);

        RuleFor(x => x.enmType_WalletTransactionType)
            .MaximumLength(50);

        RuleFor(x => x.enmAccountOwner)
            .NotEmpty()
            .MaximumLength(50);

        RuleFor(x => x.Description)
            .MaximumLength(200);

        RuleFor(x => x.Reference)
            .MaximumLength(100);

        RuleFor(x => x.RequestingUser)
            .NotEmpty()
            .MaximumLength(100);

        RuleFor(x => x.CodeForInvoice)
            .NotEmpty()
            .MaximumLength(300);

        RuleFor(x => x.Comments)
            .MaximumLength(198);

        RuleFor(x => x.CardLast4Numbers)
            .MaximumLength(50);

    }
}
