// <auto-generated>
//     This code was generated by TargCC
//     Generated for: c_ObjectTranslation (Validator)
//     Generation date: 2025-12-16 10:02:24
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using FluentValidation;

namespace UpayCard.RiskManagement.Application.Features.c_ObjectTranslations.Commands;

/// <summary>
/// Validator for CreateObjectTranslationCommand.
/// </summary>
public class CreateObjectTranslationValidator : AbstractValidator<CreateObjectTranslationCommand>
{
    /// <summary>
    /// Initializes a new instance of the <see cref="CreateObjectTranslationValidator"/> class.
    /// </summary>
    public CreateObjectTranslationValidator()
    {
        RuleFor(x => x.enmLanguage)
            .NotEmpty()
            .MaximumLength(10);

        RuleFor(x => x.Text)
            .NotEmpty();

        RuleFor(x => x.AddedBy)
            .NotEmpty()
            .MaximumLength(100);

        RuleFor(x => x.ChangedBy)
            .MaximumLength(100);

        RuleFor(x => x.DeletedBy)
            .MaximumLength(100);

        RuleFor(x => x.InstanceUniqueText)
            .MaximumLength(1000);

    }
}
