// <auto-generated>
//     This code was generated by TargCC Component Generator.
//     Table: Order
//     Generated: 2025-12-08 11:08:42
// </auto-generated>

import React from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { Box, Typography, Button, CircularProgress, Alert, Card, CardContent, Grid } from '@mui/material';
import { Edit as EditIcon, Delete as DeleteIcon, ArrowBack as ArrowBackIcon } from '@mui/icons-material';
import { DataGrid, GridColDef } from '@mui/x-data-grid';
import { useOrder, useDeleteOrder } from '../../hooks/useOrder';
import { useOrderOrderItems } from '../../hooks/useOrder';
import type { Order } from '../../types/Order.types';
import type { OrderItem } from '../../types/OrderItem.types';


export const OrderDetail: React.FC = () => {
  const navigate = useNavigate();
  const { id } = useParams<{ id: string }>();
  const { data: entity, isLoading, error } = useOrder(id ? parseInt(id, 10) : null);
  const { mutate: deleteEntity } = useDeleteOrder();
  const { data: orderItems, isLoading: orderItemsLoading } = useOrderOrderItems(id ? parseInt(id, 10) : null);

  const handleDelete = () => {
    if (confirm('Are you sure you want to delete this item?')) {
      deleteEntity(parseInt(id!, 10), {
        onSuccess: () => navigate('/orders'),
      });
    }
  };

  if (isLoading) {
    return <CircularProgress />;
  }

  if (error || !entity) {
    return <Alert severity="error">Failed to load order</Alert>;
  }

  return (
    <Box sx={{ maxWidth: 800 }}>
      <Box sx={{ mb: 2, display: 'flex', gap: 2 }}>
        <Button
          variant="outlined"
          startIcon={<ArrowBackIcon />}
          onClick={() => navigate('/orders')}
        >
          Back
        </Button>
        <Button
          variant="contained"
          startIcon={<EditIcon />}
          onClick={() => navigate(`/orders/${id}/edit`)}
        >
          Edit
        </Button>
        <Button
          variant="outlined"
          color="error"
          startIcon={<DeleteIcon />}
          onClick={handleDelete}
        >
          Delete
        </Button>
      </Box>

      <Card>
        <CardContent>
          <Typography variant="h5" component="h2" gutterBottom>
            Order Details
          </Typography>
      <Grid container spacing={2}>
        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            Id
          </Typography>
          <Typography variant="body1">
            {entity.id}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            CustomerID
          </Typography>
          <Typography variant="body1">
            {entity.customerID}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            OrderDate
          </Typography>
          <Typography variant="body1">
            {new Date(entity.orderDate).toLocaleDateString()}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            TotalAmount
          </Typography>
          <Typography variant="body1">
            {entity.totalAmount?.toFixed(2) ?? 'N/A'}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            Status
          </Typography>
          <Typography variant="body1">
            {entity.status}
          </Typography>
        </Grid>

      </Grid>

        </CardContent>
      </Card>

      <Card sx={{ mt: 2 }}>
        <CardContent>
          <Typography variant="h6" gutterBottom>
            OrderItems
          </Typography>
          <Box sx={{ height: 400, width: '100%' }}>
            <DataGrid
              rows={orderItems || []}
              columns={[
                { field: 'id', headerName: 'Id', width: 100 },
                { field: 'orderID', headerName: 'OrderID', width: 100 },
                { field: 'productID', headerName: 'ProductID', width: 100 },
                { field: 'quantity', headerName: 'Quantity', width: 100 },
                { field: 'unitPrice', headerName: 'UnitPrice', width: 150 },
              ]}
              loading={orderItemsLoading}
              pageSizeOptions={[5, 10, 25]}
              initialState={{
                pagination: { paginationModel: { pageSize: 5 } },
              }}
            />
          </Box>
        </CardContent>
      </Card>
    </Box>
  );
};

