// <auto-generated>
//     This code was generated by TargCC
//     Generated for: ccvwComboList_c_Table (Validator)
//     Generation date: 2025-12-16 08:57:46
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using FluentValidation;

namespace UpayCard.RiskManagement.Application.Features.ccvwComboList_c_Tables.Commands;

/// <summary>
/// Validator for CreateCcvwComboListCTableCommand.
/// </summary>
public class CreateCcvwComboListCTableValidator : AbstractValidator<CreateCcvwComboListCTableCommand>
{
    /// <summary>
    /// Initializes a new instance of the <see cref="CreateCcvwComboListCTableValidator"/> class.
    /// </summary>
    public CreateCcvwComboListCTableValidator()
    {
        RuleFor(x => x.TextNS)
            .MaximumLength(404);

        RuleFor(x => x.Text)
            .MaximumLength(50);

    }
}
