namespace TargCC.Core.Generators.Repositories;

using System.Globalization;
using System.Text;
using Microsoft.Extensions.Logging;
using TargCC.Core.Generators.Common;
using TargCC.Core.Interfaces.Models;

/// <summary>
/// Generates repository implementation code from database table metadata using Dapper and Stored Procedures.
/// </summary>
/// <remarks>
/// <para>
/// This generator creates concrete repository classes that implement the repository interfaces.
/// The generated code uses Dapper for efficient data access via stored procedures, includes
/// proper error handling, logging, and follows best practices for async/await patterns.
/// </para>
/// <para>
/// <strong>Generated Class Structure:</strong>
/// </para>
/// <code>
/// public class CustomerRepository : ICustomerRepository
/// {
///     private readonly IDbConnection _connection;
///     private readonly ILogger&lt;CustomerRepository&gt; _logger;
///
///     public CustomerRepository(IDbConnection connection, ILogger&lt;CustomerRepository&gt; logger)
///     {
///         _connection = connection ?? throw new ArgumentNullException(nameof(connection));
///         _logger = logger ?? throw new ArgumentNullException(nameof(logger));
///     }
///
///     // CRUD implementations...
/// }
/// </code>
/// </remarks>
public class RepositoryGenerator : IRepositoryGenerator
{
    // LoggerMessage delegates for high performance logging
    private static readonly Action<ILogger, string, Exception?> LogGeneratingRepository =
        LoggerMessage.Define<string>(
            LogLevel.Information,
            new EventId(1, nameof(GenerateAsync)),
            "Generating repository implementation for table: {TableName}");

    private static readonly Action<ILogger, string, Exception?> LogRepositoryGenerated =
        LoggerMessage.Define<string>(
            LogLevel.Information,
            new EventId(2, nameof(GenerateAsync)),
            "Successfully generated repository implementation for table: {TableName}");

    private readonly ILogger<RepositoryGenerator> _logger;

    /// <summary>
    /// Initializes a new instance of the <see cref="RepositoryGenerator"/> class.
    /// </summary>
    /// <param name="logger">Logger for tracking generation process.</param>
    public RepositoryGenerator(ILogger<RepositoryGenerator> logger)
    {
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
    }

    /// <inheritdoc/>
    public async Task<string> GenerateAsync(Table table, string rootNamespace = "YourApp")
    {
        ArgumentNullException.ThrowIfNull(table);

        if (table.PrimaryKeyColumns == null || table.PrimaryKeyColumns.Count == 0)
        {
            throw new InvalidOperationException($"Table '{table.Name}' must have a primary key defined.");
        }

        LogGeneratingRepository(_logger, table.Name, null);

        var sb = new StringBuilder();

        // Add file header
        GenerateFileHeader(sb, table);

        // Add using statements
        GenerateUsings(sb, rootNamespace);

        // Start class
        StartClass(sb, table);

        // Generate fields
        GenerateFields(sb, table);

        // Generate constructor
        GenerateConstructor(sb, table);

        // Generate CRUD methods
        GenerateGetByIdAsync(sb, table);
        GenerateGetAllAsync(sb, table);
        GenerateAddAsync(sb, table);
        GenerateUpdateAsync(sb, table);
        GenerateDeleteAsync(sb, table);

        // Generate index-based query methods
        GenerateIndexBasedMethods(sb, table);

        // Generate aggregate methods if needed
        GenerateUpdateAggregatesAsync(sb, table);

        // Generate helper methods
        GenerateExistsAsync(sb, table);

        // Close class
        CloseClass(sb);

        LogRepositoryGenerated(_logger, table.Name, null);

        return await Task.FromResult(sb.ToString());
    }

    /// <summary>
    /// Generates the file header with XML documentation.
    /// </summary>
    private static void GenerateFileHeader(StringBuilder sb, Table table)
    {
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine(CultureInfo.InvariantCulture, $"//     This code was generated by TargCC.Core.Generators v2.0");
        sb.AppendLine(CultureInfo.InvariantCulture, $"//     Generated from table: {table.FullName}");
        sb.AppendLine(CultureInfo.InvariantCulture, $"//     Generation date: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine("//");
        sb.AppendLine("//     Changes to this file may cause incorrect behavior and will be lost if");
        sb.AppendLine("//     the code is regenerated.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
    }

    /// <summary>
    /// Generates using statements.
    /// </summary>
    private static void GenerateUsings(StringBuilder sb, string rootNamespace)
    {
        sb.AppendLine(CultureInfo.InvariantCulture, $"namespace {rootNamespace}.Infrastructure.Repositories;");
        sb.AppendLine();
        sb.AppendLine("using System.Data;");
        sb.AppendLine("using Dapper;");
        sb.AppendLine("using Microsoft.Extensions.Logging;");
        sb.AppendLine(CultureInfo.InvariantCulture, $"using {rootNamespace}.Domain.Entities;");
        sb.AppendLine(CultureInfo.InvariantCulture, $"using {rootNamespace}.Domain.Interfaces;");
        sb.AppendLine();
    }

    /// <summary>
    /// Starts the class declaration with XML documentation.
    /// </summary>
    private static void StartClass(StringBuilder sb, Table table)
    {
        string entityName = table.Name;
        string className = $"{entityName}Repository";
        string interfaceName = $"I{entityName}Repository";

        sb.AppendLine("/// <summary>");
        sb.AppendLine(CultureInfo.InvariantCulture, $"/// Repository implementation for {entityName} entity data access operations.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("/// <remarks>");
        sb.AppendLine("/// <para>");
        sb.AppendLine(CultureInfo.InvariantCulture, $"/// This repository provides data access for the {entityName} entity using Dapper");
        sb.AppendLine("/// for stored procedure calls. All operations are async and support cancellation.");
        sb.AppendLine("/// </para>");
        sb.AppendLine("/// </remarks>");
        sb.AppendLine(CultureInfo.InvariantCulture, $"public class {className} : {interfaceName}");
        sb.AppendLine("{");
    }

    /// <summary>
    /// Generates private fields.
    /// </summary>
    private static void GenerateFields(StringBuilder sb, Table table)
    {
        string entityName = table.Name;

        sb.AppendLine("    private readonly IDbConnection _connection;");
        sb.AppendLine(CultureInfo.InvariantCulture, $"    private readonly ILogger<{entityName}Repository> _logger;");
        sb.AppendLine();
    }

    /// <summary>
    /// Generates constructor.
    /// </summary>
    private static void GenerateConstructor(StringBuilder sb, Table table)
    {
        string entityName = table.Name;
        string className = $"{entityName}Repository";

        sb.AppendLine("    /// <summary>");
        sb.AppendLine(CultureInfo.InvariantCulture, $"    /// Initializes a new instance of the <see cref=\"{className}\"/> class.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"connection\">Database connection for Dapper operations.</param>");
        sb.AppendLine("    /// <param name=\"logger\">Logger for tracking repository operations.</param>");
        sb.AppendLine(CultureInfo.InvariantCulture, $"    public {className}(IDbConnection connection, ILogger<{className}> logger)");
        sb.AppendLine("    {");
        sb.AppendLine("        _connection = connection ?? throw new ArgumentNullException(nameof(connection));");
        sb.AppendLine("        _logger = logger ?? throw new ArgumentNullException(nameof(logger));");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>
    /// Generates GetByIdAsync method.
    /// </summary>
    private static void GenerateGetByIdAsync(StringBuilder sb, Table table)
    {
        string entityName = table.Name;
        var pkColumn = table.Columns.Find(c => c.IsPrimaryKey);

        if (pkColumn == null)
        {
            return;
        }

        string pkType = CodeGenerationHelpers.GetCSharpType(pkColumn.DataType);
        string spName = $"SP_Get{entityName}ByID";

        sb.AppendLine("    /// <inheritdoc/>");
        sb.AppendLine(CultureInfo.InvariantCulture, $"    public async Task<{entityName}?> GetByIdAsync({pkType} id, CancellationToken cancellationToken = default)");
        sb.AppendLine("    {");
        sb.AppendLine(CultureInfo.InvariantCulture, $"        _logger.LogDebug(\"Getting {entityName} by ID: {{Id}}\", id);");
        sb.AppendLine();
        sb.AppendLine("        try");
        sb.AppendLine("        {");
        sb.AppendLine(CultureInfo.InvariantCulture, $"            var result = await _connection.QueryFirstOrDefaultAsync<{entityName}>(");
        sb.AppendLine(CultureInfo.InvariantCulture, $"                \"{spName}\",");
        sb.AppendLine("                new { ID = id },");
        sb.AppendLine("                commandType: CommandType.StoredProcedure);");
        sb.AppendLine();
        sb.AppendLine(CultureInfo.InvariantCulture, $"            _logger.LogDebug(\"{entityName} found: {{Found}}\", result != null);");
        sb.AppendLine("            return result;");
        sb.AppendLine("        }");
        sb.AppendLine("        catch (Exception ex)");
        sb.AppendLine("        {");
        sb.AppendLine(CultureInfo.InvariantCulture, $"            _logger.LogError(ex, \"Error getting {entityName} by ID: {{Id}}\", id);");
        sb.AppendLine("            throw;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>
    /// Generates GetAllAsync method.
    /// </summary>
    private static void GenerateGetAllAsync(StringBuilder sb, Table table)
    {
        string entityName = table.Name;
        string spName = $"SP_GetAll{entityName}s";

        sb.AppendLine("    /// <inheritdoc/>");
        sb.AppendLine(CultureInfo.InvariantCulture, $"    public async Task<IEnumerable<{entityName}>> GetAllAsync(int? skip = null, int? take = null, CancellationToken cancellationToken = default)");
        sb.AppendLine("    {");
        sb.AppendLine(CultureInfo.InvariantCulture,  $"        _logger.LogDebug(\"Getting all {entityName} entities. Skip: {{Skip}}, Take: {{Take}}\", skip, take);");
        sb.AppendLine();
        sb.AppendLine("        try");
        sb.AppendLine("        {");
        sb.AppendLine(CultureInfo.InvariantCulture, $"            var result = await _connection.QueryAsync<{entityName}>(");
        sb.AppendLine(CultureInfo.InvariantCulture, $"                \"{spName}\",");
        sb.AppendLine("                new { Skip = skip, Take = take },");
        sb.AppendLine("                commandType: CommandType.StoredProcedure);");
        sb.AppendLine();
        sb.AppendLine(CultureInfo.InvariantCulture, $"            _logger.LogDebug(\"Retrieved {{Count}} {entityName} entities\", result.Count());");
        sb.AppendLine("            return result;");
        sb.AppendLine("        }");
        sb.AppendLine("        catch (Exception ex)");
        sb.AppendLine("        {");
        sb.AppendLine(CultureInfo.InvariantCulture, $"            _logger.LogError(ex, \"Error getting all {entityName} entities\");");
        sb.AppendLine("            throw;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>
    /// Generates AddAsync method.
    /// </summary>
    private static void GenerateAddAsync(StringBuilder sb, Table table)
    {
        string entityName = table.Name;
        string spName = $"SP_Add{entityName}";

        sb.AppendLine("    /// <inheritdoc/>");
        sb.AppendLine(CultureInfo.InvariantCulture, $"    public async Task AddAsync({entityName} entity, CancellationToken cancellationToken = default)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (entity == null)");
        sb.AppendLine("        {");
        sb.AppendLine("            throw new ArgumentNullException(nameof(entity));");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine(CultureInfo.InvariantCulture, $"        _logger.LogDebug(\"Adding new {entityName}\");");
        sb.AppendLine();
        sb.AppendLine("        try");
        sb.AppendLine("        {");
        sb.AppendLine(CultureInfo.InvariantCulture, $"            await _connection.ExecuteAsync(");
        sb.AppendLine(CultureInfo.InvariantCulture, $"                \"{spName}\",");
        sb.AppendLine("                entity,");
        sb.AppendLine("                commandType: CommandType.StoredProcedure);");
        sb.AppendLine();
        sb.AppendLine(CultureInfo.InvariantCulture, $"            _logger.LogInformation(\"{entityName} added successfully\");");
        sb.AppendLine("        }");
        sb.AppendLine("        catch (Exception ex)");
        sb.AppendLine("        {");
        sb.AppendLine(CultureInfo.InvariantCulture, $"            _logger.LogError(ex, \"Error adding {entityName}\");");
        sb.AppendLine("            throw;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>
    /// Generates UpdateAsync method.
    /// </summary>
    private static void GenerateUpdateAsync(StringBuilder sb, Table table)
    {
        string entityName = table.Name;
        string spName = $"SP_Update{entityName}";
        var pkColumn = table.Columns.Find(c => c.IsPrimaryKey);

        if (pkColumn == null)
        {
            return;
        }

        sb.AppendLine("    /// <inheritdoc/>");
        sb.AppendLine(CultureInfo.InvariantCulture, $"    public async Task UpdateAsync({entityName} entity, CancellationToken cancellationToken = default)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (entity == null)");
        sb.AppendLine("        {");
        sb.AppendLine("            throw new ArgumentNullException(nameof(entity));");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine(CultureInfo.InvariantCulture, $"        _logger.LogDebug(\"Updating {entityName} with ID: {{Id}}\", entity.ID);");
        sb.AppendLine();
        sb.AppendLine("        try");
        sb.AppendLine("        {");
        sb.AppendLine(CultureInfo.InvariantCulture, $"            await _connection.ExecuteAsync(");
        sb.AppendLine(CultureInfo.InvariantCulture, $"                \"{spName}\",");
        sb.AppendLine("                entity,");
        sb.AppendLine("                commandType: CommandType.StoredProcedure);");
        sb.AppendLine();
        sb.AppendLine(CultureInfo.InvariantCulture, $"            _logger.LogInformation(\"{entityName} updated successfully. ID: {{Id}}\", entity.ID);");
        sb.AppendLine("        }");
        sb.AppendLine("        catch (Exception ex)");
        sb.AppendLine("        {");
        sb.AppendLine(CultureInfo.InvariantCulture, $"            _logger.LogError(ex, \"Error updating {entityName} with ID: {{Id}}\", entity.ID);");
        sb.AppendLine("            throw;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>
    /// Generates DeleteAsync method.
    /// </summary>
    private static void GenerateDeleteAsync(StringBuilder sb, Table table)
    {
        string entityName = table.Name;
        string spName = $"SP_Delete{entityName}";
        var pkColumn = table.Columns.Find(c => c.IsPrimaryKey);

        if (pkColumn == null)
        {
            return;
        }

        string pkType = CodeGenerationHelpers.GetCSharpType(pkColumn.DataType);

        sb.AppendLine("    /// <inheritdoc/>");
        sb.AppendLine(CultureInfo.InvariantCulture, $"    public async Task DeleteAsync({pkType} id, CancellationToken cancellationToken = default)");
        sb.AppendLine("    {");
        sb.AppendLine(CultureInfo.InvariantCulture, $"        _logger.LogDebug(\"Deleting {entityName} with ID: {{Id}}\", id);");
        sb.AppendLine();
        sb.AppendLine("        try");
        sb.AppendLine("        {");
        sb.AppendLine(CultureInfo.InvariantCulture, $"            await _connection.ExecuteAsync(");
        sb.AppendLine(CultureInfo.InvariantCulture, $"                \"{spName}\",");
        sb.AppendLine("                new { ID = id },");
        sb.AppendLine("                commandType: CommandType.StoredProcedure);");
        sb.AppendLine();
        sb.AppendLine(CultureInfo.InvariantCulture, $"            _logger.LogInformation(\"{entityName} deleted successfully. ID: {{Id}}\", id);");
        sb.AppendLine("        }");
        sb.AppendLine("        catch (Exception ex)");
        sb.AppendLine("        {");
        sb.AppendLine(CultureInfo.InvariantCulture, $"            _logger.LogError(ex, \"Error deleting {entityName} with ID: {{Id}}\", id);");
        sb.AppendLine("            throw;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>
    /// Generates index-based query methods.
    /// </summary>
    private static void GenerateIndexBasedMethods(StringBuilder sb, Table table)
    {
        if (table.Indexes == null || table.Indexes.Count == 0)
        {
            return;
        }

        string entityName = table.Name;

        // Process each non-primary key index
        foreach (var index in table.Indexes.Where(i => !i.IsPrimaryKey))
        {
            if (index.ColumnNames == null || index.ColumnNames.Count == 0)
            {
                continue;
            }

            GenerateSingleIndexMethod(sb, table, index, entityName);
        }
    }

    /// <summary>
    /// Generates a single index-based query method.
    /// </summary>
    private static void GenerateSingleIndexMethod(StringBuilder sb, Table table, Index index, string entityName)
    {
        // Build method name and SP name
        string methodName = CodeGenerationHelpers.BuildMethodName("GetBy", index.ColumnNames);
        string spName = $"SP_Get{entityName}By{string.Join("And", index.ColumnNames.Select(CodeGenerationHelpers.SanitizeColumnName))}";

        // Build parameters
        var (paramList, paramDictStr) = BuildIndexMethodParameters(table, index);

        // Generate method signature and body
        GenerateIndexMethodImplementation(sb, entityName, methodName, spName, index, paramList, paramDictStr);
    }

    /// <summary>
    /// Builds parameter list and dictionary string for an index method.
    /// </summary>
    private static (string paramList, string paramDictStr) BuildIndexMethodParameters(Table table, Index index)
    {
        var parameters = new List<string>();
        var paramDict = new List<string>();

        foreach (var columnName in index.ColumnNames)
        {
            var column = table.Columns.Find(c => c.Name == columnName);
            if (column != null)
            {
                string paramType = CodeGenerationHelpers.GetCSharpType(column.DataType);
                string paramName = CodeGenerationHelpers.ToCamelCase(
                    CodeGenerationHelpers.SanitizeColumnName(columnName));
                string columnNameSanitized = CodeGenerationHelpers.SanitizeColumnName(columnName);

                parameters.Add($"{paramType} {paramName}");

                // FIX: Change from dictionary syntax to property syntax
                paramDict.Add($"{columnNameSanitized} = {paramName}");
            }
        }

        return (string.Join(", ", parameters), string.Join(", ", paramDict));
    }

    /// <summary>
    /// Generates the method implementation (signature + body) for an index method.
    /// </summary>
    private static void GenerateIndexMethodImplementation(
     StringBuilder sb,
     string entityName,
     string methodName,
     string spName,
     Index index,
     string paramList,
     string paramDictStr)
    {
        sb.AppendLine("    /// <inheritdoc/>");

        // Method signature
        if (index.IsUnique)
        {
            sb.AppendLine(CultureInfo.InvariantCulture, $"    public async Task<{entityName}?> {methodName}Async({paramList}, CancellationToken cancellationToken = default)");
        }
        else
        {
            sb.AppendLine(CultureInfo.InvariantCulture, $"    public async Task<IEnumerable<{entityName}>> {methodName}Async({paramList}, CancellationToken cancellationToken = default)");
        }

        sb.AppendLine("    {");
        sb.AppendLine(CultureInfo.InvariantCulture, $"        _logger.LogDebug(\"Getting {entityName} by {string.Join(", ", index.ColumnNames)}\");");
        sb.AppendLine();
        sb.AppendLine("        try");
        sb.AppendLine("        {");

        // Dapper call
        if (index.IsUnique)
        {
            sb.AppendLine(CultureInfo.InvariantCulture, $"            var result = await _connection.QueryFirstOrDefaultAsync<{entityName}>(");
        }
        else
        {
            sb.AppendLine(CultureInfo.InvariantCulture, $"            var result = await _connection.QueryAsync<{entityName}>(");
        }

        sb.AppendLine(CultureInfo.InvariantCulture, $"                \"{spName}\",");
        sb.AppendLine(CultureInfo.InvariantCulture, $"                new {{ {paramDictStr} }},");
        sb.AppendLine("                commandType: CommandType.StoredProcedure);");
        sb.AppendLine();

        // Logging
        if (index.IsUnique)
        {
            sb.AppendLine(CultureInfo.InvariantCulture, $"            _logger.LogDebug(\"{entityName} found: {{Found}}\", result != null);");
        }
        else
        {
            sb.AppendLine(CultureInfo.InvariantCulture, $"            _logger.LogDebug(\"Retrieved {{Count}} {entityName} entities\", result.Count());");
        }

        sb.AppendLine("            return result;");
        sb.AppendLine("        }");
        sb.AppendLine("        catch (Exception ex)");
        sb.AppendLine("        {");
        sb.AppendLine(CultureInfo.InvariantCulture, $"            _logger.LogError(ex, \"Error getting {entityName} by {string.Join(", ", index.ColumnNames)}\");");
        sb.AppendLine("            throw;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>
    /// Generates UpdateAggregatesAsync method for tables with agg_ columns.
    /// </summary>
    private static void GenerateUpdateAggregatesAsync(StringBuilder sb, Table table)
    {
        // Find aggregate columns using LINQ
        var aggColumns = table.Columns
            .Where(c => c.Name.StartsWith("agg_", StringComparison.OrdinalIgnoreCase))
            .ToList();

        if (aggColumns.Count == 0)
        {
            return;
        }

        string entityName = table.Name;
        string spName = $"SP_Update{entityName}Aggregates";
        var pkColumn = table.Columns.Find(c => c.IsPrimaryKey);

        if (pkColumn == null)
        {
            return;
        }

        string pkType = CodeGenerationHelpers.GetCSharpType(pkColumn.DataType);

        // Build parameter list
        var parameters = new List<string> { $"{pkType} id" };
        var paramDict = new List<string> { "ID = id" };

        foreach (var column in aggColumns)
        {
            string paramType = CodeGenerationHelpers.GetCSharpType(column.DataType);
            string paramName = CodeGenerationHelpers.ToCamelCase(
                CodeGenerationHelpers.SanitizeColumnName(column.Name));
            string columnNameSanitized = CodeGenerationHelpers.SanitizeColumnName(column.Name);

            parameters.Add($"{paramType} {paramName}");

            // FIX: Change from dictionary syntax to property syntax
            paramDict.Add($"{columnNameSanitized} = {paramName}");
        }

        string paramList = string.Join(", ", parameters);
        string paramDictStr = string.Join(", ", paramDict);

        sb.AppendLine("    /// <inheritdoc/>");
        sb.AppendLine(CultureInfo.InvariantCulture, $"    public async Task UpdateAggregatesAsync({paramList}, CancellationToken cancellationToken = default)");
        sb.AppendLine("    {");
        sb.AppendLine(CultureInfo.InvariantCulture, $"        _logger.LogDebug(\"Updating {entityName} aggregates for ID: {{Id}}\", id);");
        sb.AppendLine();
        sb.AppendLine("        try");
        sb.AppendLine("        {");
        sb.AppendLine($"            await _connection.ExecuteAsync(");
        sb.AppendLine(CultureInfo.InvariantCulture, $"                \"{spName}\",");
        sb.AppendLine(CultureInfo.InvariantCulture, $"                new {{ {paramDictStr} }},");  // ✅ FIXED - now generates: new { ID = id, ... }
        sb.AppendLine("                commandType: CommandType.StoredProcedure);");
        sb.AppendLine();
        sb.AppendLine(CultureInfo.InvariantCulture, $"            _logger.LogInformation(\"{entityName} aggregates updated successfully. ID: {{Id}}\", id);");
        sb.AppendLine("        }");
        sb.AppendLine("        catch (Exception ex)");
        sb.AppendLine("        {");
        sb.AppendLine(CultureInfo.InvariantCulture, $"            _logger.LogError(ex, \"Error updating {entityName} aggregates. ID: {{Id}}\", id);");
        sb.AppendLine("            throw;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>
    /// Generates ExistsAsync method.
    /// </summary>
    private static void GenerateExistsAsync(StringBuilder sb, Table table)
    {
        string entityName = table.Name;
        var pkColumn = table.Columns.Find(c => c.IsPrimaryKey);

        if (pkColumn == null)
        {
            return;
        }

        string pkType = CodeGenerationHelpers.GetCSharpType(pkColumn.DataType);
        string spName = $"SP_Get{entityName}ByID";

        sb.AppendLine("    /// <inheritdoc/>");
        sb.AppendLine(CultureInfo.InvariantCulture, $"    public async Task<bool> ExistsAsync({pkType} id, CancellationToken cancellationToken = default)");
        sb.AppendLine("    {");
        sb.AppendLine(CultureInfo.InvariantCulture, $"        _logger.LogDebug(\"Checking if {entityName} exists with ID: {{Id}}\", id);");
        sb.AppendLine();
        sb.AppendLine("        try");
        sb.AppendLine("        {");
        sb.AppendLine(CultureInfo.InvariantCulture, $"            var result = await _connection.QueryFirstOrDefaultAsync<{entityName}>(");
        sb.AppendLine(CultureInfo.InvariantCulture, $"                \"{spName}\",");
        sb.AppendLine("                new { ID = id },");
        sb.AppendLine("                commandType: CommandType.StoredProcedure);");
        sb.AppendLine();
        sb.AppendLine("            bool exists = result != null;");
        sb.AppendLine(CultureInfo.InvariantCulture, $"            _logger.LogDebug(\"{entityName} exists: {{Exists}}\", exists);");
        sb.AppendLine("            return exists;");
        sb.AppendLine("        }");
        sb.AppendLine("        catch (Exception ex)");
        sb.AppendLine("        {");
        sb.AppendLine(CultureInfo.InvariantCulture, $"            _logger.LogError(ex, \"Error checking if {entityName} exists. ID: {{Id}}\", id);");
        sb.AppendLine("            throw;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
    }

    /// <summary>
    /// Closes the class declaration.
    /// </summary>
    private static void CloseClass(StringBuilder sb)
    {
        sb.AppendLine("}");
    }
}
