// <auto-generated>
//     This code was generated by TargCC.Core.Generators.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;

namespace UpayCard.RiskManagement.Domain.Entities
{
    /// <summary>
    /// Entity class for c_ObjectTranslation table.
    /// Generated: 2025-12-16 09:26:42
    /// </summary>
    [Table("c_ObjectTranslation")]
    public partial class ObjectTranslation
    {
        #region Properties

        // Primary Key(s)
        /// <summary>
        /// Gets or sets the ID.
        /// </summary>
        [Column("ID")]
        [Key]
        public long ID { get; set; }

        // Regular Properties
        /// <summary>
        /// Gets or sets the TableName_c_ObjectTranslation.
        /// </summary>
        [Column("TableName_c_ObjectTranslation")]
        public bool? TableName_c_ObjectTranslation { get; set; }
        /// <summary>
        /// Gets or sets the c_ObjectToTranslateID.
        /// </summary>
        [Column("c_ObjectToTranslateID")]
        [Required]
        public long c_ObjectToTranslateID { get; set; }
        /// <summary>
        /// Gets or sets the Instance.
        /// </summary>
        [Column("Instance")]
        public long? Instance { get; set; }
        /// <summary>
        /// Business logic field (read-only on client).
        /// </summary>
        [Column("DefaultText")]
        public string DefaultTextBL { get; internal set; }
        /// <summary>
        /// Enum value for enmLanguage.
        /// </summary>
        [Column("enmLanguage")]
        public string enmLanguage { get; set; }

        /// <summary>
        /// Enum representation of enmLanguage.
        /// </summary>
        [NotMapped]
        public int enmLanguageEnum { get; set; }
        /// <summary>
        /// Gets or sets the Text.
        /// </summary>
        [Column("Text")]
        [Required]
        [MaxLength(int.MaxValue)]
        public string Text { get; set; }
        /// <summary>
        /// Gets or sets the DeletedBy.
        /// </summary>
        [Column("DeletedBy")]
        [MaxLength(100)]
        public string DeletedBy { get; set; }
        /// <summary>
        /// Gets or sets the DeletedOn.
        /// </summary>
        [Column("DeletedOn")]
        public DateTime? DeletedOn { get; set; }
        /// <summary>
        /// Gets or sets the UpdatingLoginID.
        /// </summary>
        [Column("UpdatingLoginID")]
        public long? UpdatingLoginID { get; set; }
        /// <summary>
        /// Gets or sets the InstanceUniqueText.
        /// </summary>
        [Column("InstanceUniqueText")]
        [MaxLength(1000)]
        public string InstanceUniqueText { get; set; }

        // Audit Properties
        /// <summary>
        /// Gets or sets the AddedBy.
        /// </summary>
        [Column("AddedBy")]
        [Required]
        [MaxLength(100)]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public string AddedBy { get; private set; }
        /// <summary>
        /// Gets or sets the AddedOn.
        /// </summary>
        [Column("AddedOn")]
        [Required]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public DateTime AddedOn { get; private set; } = DateTime.Now;
        /// <summary>
        /// Gets or sets the ChangedBy.
        /// </summary>
        [Column("ChangedBy")]
        [MaxLength(100)]
        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public string ChangedBy { get; private set; }
        /// <summary>
        /// Gets or sets the ChangedOn.
        /// </summary>
        [Column("ChangedOn")]
        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public DateTime? ChangedOn { get; private set; } = DateTime.Now;

        #endregion

        #region Constructors

        /// <summary>
        /// Initializes a new instance of the <see cref="ObjectTranslation"/> class.
        /// </summary>
        public ObjectTranslation()
        {
            this.AddedOn = DateTime.Now;
        }

        #endregion

        #region Methods

        /// <summary>
        /// Returns a string representation of this ObjectTranslation.
        /// </summary>
        public override string ToString()
        {
            return $"ObjectTranslation #{ID}";
        }

        /// <summary>
        /// Creates a shallow copy of this ObjectTranslation.
        /// </summary>
        public ObjectTranslation Clone()
        {
            return new ObjectTranslation
            {
                TableName_c_ObjectTranslation = this.TableName_c_ObjectTranslation,
                c_ObjectToTranslateID = this.c_ObjectToTranslateID,
                Instance = this.Instance,
                enmLanguage = this.enmLanguage,
                Text = this.Text,
                DeletedBy = this.DeletedBy,
                DeletedOn = this.DeletedOn,
                UpdatingLoginID = this.UpdatingLoginID,
                InstanceUniqueText = this.InstanceUniqueText
            };
        }

        /// <summary>
        /// Determines whether the specified object is equal to this ObjectTranslation.
        /// </summary>
        public override bool Equals(object obj)
        {
            if (obj is not ObjectTranslation other)
                return false;

            if (this.ID > 0 && other.ID > 0)
                return this.ID == other.ID;

            return base.Equals(obj);
        }

        /// <summary>
        /// Returns a hash code for this instance.
        /// </summary>
        public override int GetHashCode()
        {
            return this.ID > 0 ? this.ID.GetHashCode() : 0;
        }

        #endregion
    }
}
