// <auto-generated>
//     This code was generated by TargCC.Core.Generators.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;

namespace UpayCard.RiskManagement.Domain.Entities
{
    /// <summary>
    /// Entity class for ccvwComboList_Card table.
    /// Generated: 2025-12-11 11:52:11
    /// </summary>
    [Table("ccvwComboList_Card")]
    public partial class CcvwComboListCard
    {
        #region Properties

        // Regular Properties
        /// <summary>
        /// Gets or sets the ID.
        /// </summary>
        [Column("ID")]
        [Required]
        public long ID { get; set; }
        /// <summary>
        /// Gets or sets the TextNS.
        /// </summary>
        [Column("TextNS")]
        [MaxLength(404)]
        public string TextNS { get; set; }
        /// <summary>
        /// Gets or sets the Text.
        /// </summary>
        [Column("Text")]
        [Required]
        [MaxLength(55)]
        public string Text { get; set; }

        #endregion

        #region Constructors

        /// <summary>
        /// Initializes a new instance of the <see cref="CcvwComboListCard"/> class.
        /// </summary>
        public CcvwComboListCard()
        {
        }

        #endregion

        #region Methods

        /// <summary>
        /// Returns a string representation of this CcvwComboListCard.
        /// </summary>
        public override string ToString()
        {
            return $"CcvwComboListCard";
        }

        /// <summary>
        /// Creates a shallow copy of this CcvwComboListCard.
        /// </summary>
        public CcvwComboListCard Clone()
        {
            return new CcvwComboListCard
            {
                ID = this.ID,
                TextNS = this.TextNS,
                Text = this.Text
            };
        }

        /// <summary>
        /// Determines whether the specified object is equal to this CcvwComboListCard.
        /// </summary>
        public override bool Equals(object obj)
        {
            if (obj is not CcvwComboListCard other)
                return false;


            return base.Equals(obj);
        }

        /// <summary>
        /// Returns a hash code for this instance.
        /// </summary>
        public override int GetHashCode()
        {
            return base.GetHashCode();
        }

        #endregion
    }
}
