// <auto-generated>
//     This code was generated by TargCC.Core.Generators.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;

namespace UpayCard.RiskManagement.Domain.Entities
{
    /// <summary>
    /// Entity class for GovtReport99 table.
    /// Generated: 2025-12-17 14:36:06
    /// </summary>
    [Table("GovtReport99")]
    public partial class GovtReport99
    {
        #region Properties

        // Primary Key(s)
        /// <summary>
        /// Gets or sets the ID.
        /// </summary>
        [Column("ID")]
        [Key]
        public long ID { get; set; }

        // Regular Properties
        /// <summary>
        /// Gets or sets the TableName_GovtReport99.
        /// </summary>
        [Column("TableName_GovtReport99")]
        public bool? TableName_GovtReport99 { get; set; }
        /// <summary>
        /// Gets or sets the GovtReport00ID.
        /// </summary>
        [Column("GovtReport00ID")]
        public long? GovtReport00ID { get; set; }
        /// <summary>
        /// Gets or sets the ReporterNumber.
        /// </summary>
        [Column("ReporterNumber")]
        [MaxLength(15)]
        public string ReporterNumber { get; set; }
        /// <summary>
        /// Gets or sets the ReporterIDNumber.
        /// </summary>
        [Column("ReporterIDNumber")]
        [MaxLength(15)]
        public string ReporterIDNumber { get; set; }
        /// <summary>
        /// Gets or sets the ReportYear.
        /// </summary>
        [Column("ReportYear")]
        [MaxLength(4)]
        public string ReportYear { get; set; }
        /// <summary>
        /// Gets or sets the ReportNumber.
        /// </summary>
        [Column("ReportNumber")]
        public long? ReportNumber { get; set; }
        /// <summary>
        /// Gets or sets the RecordType.
        /// </summary>
        [Column("RecordType")]
        [MaxLength(2)]
        public string RecordType { get; set; }
        /// <summary>
        /// Gets or sets the ReportMonth.
        /// </summary>
        [Column("ReportMonth")]
        [MaxLength(8)]
        public string ReportMonth { get; set; }
        /// <summary>
        /// Gets or sets the NumberOfRowsIn10.
        /// </summary>
        [Column("NumberOfRowsIn10")]
        [MaxLength(8)]
        public string NumberOfRowsIn10 { get; set; }
        /// <summary>
        /// Gets or sets the NumberOfRowsIn30.
        /// </summary>
        [Column("NumberOfRowsIn30")]
        [MaxLength(8)]
        public string NumberOfRowsIn30 { get; set; }
        /// <summary>
        /// Gets or sets the NumberOfRowsIn40.
        /// </summary>
        [Column("NumberOfRowsIn40")]
        [MaxLength(8)]
        public string NumberOfRowsIn40 { get; set; }
        /// <summary>
        /// Gets or sets the DeletedBy.
        /// </summary>
        [Column("DeletedBy")]
        [MaxLength(100)]
        public string DeletedBy { get; set; }
        /// <summary>
        /// Gets or sets the DeletedOn.
        /// </summary>
        [Column("DeletedOn")]
        public DateTime? DeletedOn { get; set; }
        /// <summary>
        /// Gets or sets the UpdatingLoginID.
        /// </summary>
        [Column("UpdatingLoginID")]
        public long? UpdatingLoginID { get; set; }

        // Audit Properties
        /// <summary>
        /// Gets or sets the AddedBy.
        /// </summary>
        [Column("AddedBy")]
        [Required]
        [MaxLength(100)]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public string AddedBy { get; private set; }
        /// <summary>
        /// Gets or sets the AddedOn.
        /// </summary>
        [Column("AddedOn")]
        [Required]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public DateTime AddedOn { get; private set; } = DateTime.Now;
        /// <summary>
        /// Gets or sets the ChangedBy.
        /// </summary>
        [Column("ChangedBy")]
        [MaxLength(100)]
        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public string ChangedBy { get; private set; }
        /// <summary>
        /// Gets or sets the ChangedOn.
        /// </summary>
        [Column("ChangedOn")]
        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public DateTime? ChangedOn { get; private set; } = DateTime.Now;

        #endregion

        #region Constructors

        /// <summary>
        /// Initializes a new instance of the <see cref="GovtReport99"/> class.
        /// </summary>
        public GovtReport99()
        {
            this.AddedOn = DateTime.Now;
        }

        #endregion

        #region Methods

        /// <summary>
        /// Returns a string representation of this GovtReport99.
        /// </summary>
        public override string ToString()
        {
            return $"GovtReport99 #{ID}";
        }

        /// <summary>
        /// Creates a shallow copy of this GovtReport99.
        /// </summary>
        public GovtReport99 Clone()
        {
            return new GovtReport99
            {
                TableName_GovtReport99 = this.TableName_GovtReport99,
                GovtReport00ID = this.GovtReport00ID,
                ReporterNumber = this.ReporterNumber,
                ReporterIDNumber = this.ReporterIDNumber,
                ReportYear = this.ReportYear,
                ReportNumber = this.ReportNumber,
                RecordType = this.RecordType,
                ReportMonth = this.ReportMonth,
                NumberOfRowsIn10 = this.NumberOfRowsIn10,
                NumberOfRowsIn30 = this.NumberOfRowsIn30,
                NumberOfRowsIn40 = this.NumberOfRowsIn40,
                DeletedBy = this.DeletedBy,
                DeletedOn = this.DeletedOn,
                UpdatingLoginID = this.UpdatingLoginID
            };
        }

        /// <summary>
        /// Determines whether the specified object is equal to this GovtReport99.
        /// </summary>
        public override bool Equals(object obj)
        {
            if (obj is not GovtReport99 other)
                return false;

            if (this.ID > 0 && other.ID > 0)
                return this.ID == other.ID;

            return base.Equals(obj);
        }

        /// <summary>
        /// Returns a hash code for this instance.
        /// </summary>
        public override int GetHashCode()
        {
            return this.ID > 0 ? this.ID.GetHashCode() : 0;
        }

        #endregion
    }
}
