// <auto-generated>
//     This code was generated by TargCC.Core.Generators.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;

namespace UpayCard.RiskManagement.Domain.Entities
{
    /// <summary>
    /// Entity class for sysdiagrams table.
    /// Generated: 2025-12-15 13:48:33
    /// </summary>
    [Table("sysdiagrams")]
    public partial class Sysdiagrams
    {
        #region Properties

        // Primary Key(s)
        /// <summary>
        /// Gets or sets the diagram_id.
        /// </summary>
        [Column("diagram_id")]
        [Key]
        public int diagram_id { get; set; }

        // Regular Properties
        /// <summary>
        /// Gets or sets the name.
        /// </summary>
        [Column("name")]
        [Required]
        public object name { get; set; }
        /// <summary>
        /// Gets or sets the principal_id.
        /// </summary>
        [Column("principal_id")]
        [Required]
        public int principal_id { get; set; }
        /// <summary>
        /// Gets or sets the version.
        /// </summary>
        [Column("version")]
        public int? version { get; set; }
        /// <summary>
        /// Gets or sets the definition.
        /// </summary>
        [Column("definition")]
        public byte[] definition { get; set; }

        #endregion

        #region Constructors

        /// <summary>
        /// Initializes a new instance of the <see cref="Sysdiagrams"/> class.
        /// </summary>
        public Sysdiagrams()
        {
        }

        #endregion

        #region Methods

        /// <summary>
        /// Returns a string representation of this Sysdiagrams.
        /// </summary>
        public override string ToString()
        {
            return $"Sysdiagrams #{diagram_id}: {name}";
        }

        /// <summary>
        /// Creates a shallow copy of this Sysdiagrams.
        /// </summary>
        public Sysdiagrams Clone()
        {
            return new Sysdiagrams
            {
                name = this.name,
                principal_id = this.principal_id,
                version = this.version,
                definition = this.definition
            };
        }

        /// <summary>
        /// Determines whether the specified object is equal to this Sysdiagrams.
        /// </summary>
        public override bool Equals(object obj)
        {
            if (obj is not Sysdiagrams other)
                return false;

            if (this.diagram_id > 0 && other.diagram_id > 0)
                return this.diagram_id == other.diagram_id;

            return base.Equals(obj);
        }

        /// <summary>
        /// Returns a hash code for this instance.
        /// </summary>
        public override int GetHashCode()
        {
            return this.diagram_id > 0 ? this.diagram_id.GetHashCode() : 0;
        }

        #endregion
    }
}
