// <auto-generated>
//     This code was generated by TargCC.Core.Generators.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;

namespace UpayCard.RiskManagement.Domain.Entities
{
    /// <summary>
    /// Entity class for vwCustomerSecurityStatusCheck table.
    /// Generated: 2025-12-17 12:56:58
    /// </summary>
    [Table("vwCustomerSecurityStatusCheck")]
    public partial class VwCustomerSecurityStatusCheck
    {
        #region Properties

        // Regular Properties
        /// <summary>
        /// Gets or sets the ID.
        /// </summary>
        [Column("ID")]
        public long? ID { get; set; }
        /// <summary>
        /// Gets or sets the CustomerID.
        /// </summary>
        [Column("CustomerID")]
        public long? CustomerID { get; set; }
        /// <summary>
        /// Gets or sets the CustomerName.
        /// </summary>
        [Column("CustomerName")]
        [MaxLength(140)]
        public string CustomerName { get; set; }
        /// <summary>
        /// Gets or sets the CustomerIdentifier.
        /// </summary>
        [Column("CustomerIdentifier")]
        [MaxLength(50)]
        public string CustomerIdentifier { get; set; }
        /// <summary>
        /// Gets or sets the CustomerPhone.
        /// </summary>
        [Column("CustomerPhone")]
        [MaxLength(50)]
        public string CustomerPhone { get; set; }
        /// <summary>
        /// Gets or sets the CustomerEmail.
        /// </summary>
        [Column("CustomerEmail")]
        [MaxLength(50)]
        public string CustomerEmail { get; set; }
        /// <summary>
        /// Enum value for enmCustomerType.
        /// </summary>
        [Column("enmCustomerType")]
        public string enmCustomerType { get; set; }

        /// <summary>
        /// Enum representation of enmCustomerType.
        /// </summary>
        [NotMapped]
        public int enmCustomerTypeEnum { get; set; }
        /// <summary>
        /// Enum value for enmSecurityTier.
        /// </summary>
        [Column("enmSecurityTier")]
        public string enmSecurityTier { get; set; }

        /// <summary>
        /// Enum representation of enmSecurityTier.
        /// </summary>
        [NotMapped]
        public int enmSecurityTierEnum { get; set; }
        /// <summary>
        /// Gets or sets the IsBusiness.
        /// </summary>
        [Column("IsBusiness")]
        public bool? IsBusiness { get; set; }
        /// <summary>
        /// Gets or sets the WalletBalanceWorking.
        /// </summary>
        [Column("WalletBalanceWorking")]
        public decimal? WalletBalanceWorking { get; set; }
        /// <summary>
        /// Gets or sets the TotalTransferredToWallet.
        /// </summary>
        [Column("TotalTransferredToWallet")]
        public decimal? TotalTransferredToWallet { get; set; }
        /// <summary>
        /// Gets or sets the TotalTransferredToWallet6Months.
        /// </summary>
        [Column("TotalTransferredToWallet6Months")]
        public decimal? TotalTransferredToWallet6Months { get; set; }
        /// <summary>
        /// Gets or sets the TotalTransferredToWallet1Month.
        /// </summary>
        [Column("TotalTransferredToWallet1Month")]
        public decimal? TotalTransferredToWallet1Month { get; set; }
        /// <summary>
        /// Gets or sets the HasSignedServiceRequest.
        /// </summary>
        [Column("HasSignedServiceRequest")]
        public bool? HasSignedServiceRequest { get; set; }

        #endregion

        #region Constructors

        /// <summary>
        /// Initializes a new instance of the <see cref="VwCustomerSecurityStatusCheck"/> class.
        /// </summary>
        public VwCustomerSecurityStatusCheck()
        {
        }

        #endregion

        #region Methods

        /// <summary>
        /// Returns a string representation of this VwCustomerSecurityStatusCheck.
        /// </summary>
        public override string ToString()
        {
            return $"VwCustomerSecurityStatusCheck";
        }

        /// <summary>
        /// Creates a shallow copy of this VwCustomerSecurityStatusCheck.
        /// </summary>
        public VwCustomerSecurityStatusCheck Clone()
        {
            return new VwCustomerSecurityStatusCheck
            {
                ID = this.ID,
                CustomerID = this.CustomerID,
                CustomerName = this.CustomerName,
                CustomerIdentifier = this.CustomerIdentifier,
                CustomerPhone = this.CustomerPhone,
                CustomerEmail = this.CustomerEmail,
                enmCustomerType = this.enmCustomerType,
                enmSecurityTier = this.enmSecurityTier,
                IsBusiness = this.IsBusiness,
                WalletBalanceWorking = this.WalletBalanceWorking,
                TotalTransferredToWallet = this.TotalTransferredToWallet,
                TotalTransferredToWallet6Months = this.TotalTransferredToWallet6Months,
                TotalTransferredToWallet1Month = this.TotalTransferredToWallet1Month,
                HasSignedServiceRequest = this.HasSignedServiceRequest
            };
        }

        /// <summary>
        /// Determines whether the specified object is equal to this VwCustomerSecurityStatusCheck.
        /// </summary>
        public override bool Equals(object obj)
        {
            if (obj is not VwCustomerSecurityStatusCheck other)
                return false;


            return this.CustomerEmail == other.CustomerEmail;
        }

        /// <summary>
        /// Returns a hash code for this instance.
        /// </summary>
        public override int GetHashCode()
        {
            return base.GetHashCode();
        }

        #endregion
    }
}
