// <auto-generated>
//     This code was generated by TargCC.Core.Generators.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;

namespace UpayCard.RiskManagement.Domain.Entities
{
    /// <summary>
    /// Entity class for vwReportWalletTransferData table.
    /// Generated: 2025-12-15 22:04:11
    /// </summary>
    [Table("vwReportWalletTransferData")]
    public partial class VwReportWalletTransferData
    {
        #region Properties

        // Regular Properties
        /// <summary>
        /// Gets or sets the ID.
        /// </summary>
        [Column("ID")]
        [Required]
        public long ID { get; set; }
        /// <summary>
        /// Gets or sets the CustomerID.
        /// </summary>
        [Column("CustomerID")]
        public long? CustomerID { get; set; }
        /// <summary>
        /// Gets or sets the CustomerWalletID.
        /// </summary>
        [Column("CustomerWalletID")]
        public long? CustomerWalletID { get; set; }
        /// <summary>
        /// Enum value for enmBackofficeTransactionType.
        /// </summary>
        [Column("enmBackofficeTransactionType")]
        public string enmBackofficeTransactionType { get; set; }

        /// <summary>
        /// Enum representation of enmBackofficeTransactionType.
        /// </summary>
        [NotMapped]
        public int enmBackofficeTransactionTypeEnum { get; set; }
        /// <summary>
        /// Enum value for enmType_WalletTransactionType.
        /// </summary>
        [Column("enmType_WalletTransactionType")]
        public string enmType_WalletTransactionType { get; set; }

        /// <summary>
        /// Enum representation of enmType_WalletTransactionType.
        /// </summary>
        [NotMapped]
        public int enmType_WalletTransactionTypeEnum { get; set; }
        /// <summary>
        /// Gets or sets the AmountToAccountOwner.
        /// </summary>
        [Column("AmountToAccountOwner")]
        [Required]
        public decimal AmountToAccountOwner { get; set; }
        /// <summary>
        /// Gets or sets the BalanceAfterTransaction.
        /// </summary>
        [Column("BalanceAfterTransaction")]
        public decimal? BalanceAfterTransaction { get; set; }
        /// <summary>
        /// Enum value for enmAccountOwner.
        /// </summary>
        [Column("enmAccountOwner")]
        public string enmAccountOwner { get; set; }

        /// <summary>
        /// Enum representation of enmAccountOwner.
        /// </summary>
        [NotMapped]
        public int enmAccountOwnerEnum { get; set; }
        /// <summary>
        /// Gets or sets the Description.
        /// </summary>
        [Column("Description")]
        [MaxLength(200)]
        public string Description { get; set; }
        /// <summary>
        /// Gets or sets the Reference.
        /// </summary>
        [Column("Reference")]
        [MaxLength(100)]
        public string Reference { get; set; }
        /// <summary>
        /// Gets or sets the WhenRequested.
        /// </summary>
        [Column("WhenRequested")]
        [Required]
        public DateTimeOffset WhenRequested { get; set; }
        /// <summary>
        /// Gets or sets the RequestingUser.
        /// </summary>
        [Column("RequestingUser")]
        [Required]
        [MaxLength(100)]
        public string RequestingUser { get; set; }
        /// <summary>
        /// Gets or sets the CodeForInvoice.
        /// </summary>
        [Column("CodeForInvoice")]
        [Required]
        [MaxLength(300)]
        public string CodeForInvoice { get; set; }
        /// <summary>
        /// Gets or sets the Comments.
        /// </summary>
        [Column("Comments")]
        [MaxLength(198)]
        public string Comments { get; set; }
        /// <summary>
        /// Gets or sets the CreditCardFee.
        /// </summary>
        [Column("CreditCardFee")]
        public decimal? CreditCardFee { get; set; }
        /// <summary>
        /// Gets or sets the Interest.
        /// </summary>
        [Column("Interest")]
        public decimal? Interest { get; set; }
        /// <summary>
        /// Gets or sets the NumberOfPayments.
        /// </summary>
        [Column("NumberOfPayments")]
        public int? NumberOfPayments { get; set; }
        /// <summary>
        /// Gets or sets the CardLast4Numbers.
        /// </summary>
        [Column("CardLast4Numbers")]
        [MaxLength(50)]
        public string CardLast4Numbers { get; set; }

        #endregion

        #region Constructors

        /// <summary>
        /// Initializes a new instance of the <see cref="VwReportWalletTransferData"/> class.
        /// </summary>
        public VwReportWalletTransferData()
        {
        }

        #endregion

        #region Methods

        /// <summary>
        /// Returns a string representation of this VwReportWalletTransferData.
        /// </summary>
        public override string ToString()
        {
            return $"VwReportWalletTransferData";
        }

        /// <summary>
        /// Creates a shallow copy of this VwReportWalletTransferData.
        /// </summary>
        public VwReportWalletTransferData Clone()
        {
            return new VwReportWalletTransferData
            {
                ID = this.ID,
                CustomerID = this.CustomerID,
                CustomerWalletID = this.CustomerWalletID,
                enmBackofficeTransactionType = this.enmBackofficeTransactionType,
                enmType_WalletTransactionType = this.enmType_WalletTransactionType,
                AmountToAccountOwner = this.AmountToAccountOwner,
                BalanceAfterTransaction = this.BalanceAfterTransaction,
                enmAccountOwner = this.enmAccountOwner,
                Description = this.Description,
                Reference = this.Reference,
                WhenRequested = this.WhenRequested,
                RequestingUser = this.RequestingUser,
                CodeForInvoice = this.CodeForInvoice,
                Comments = this.Comments,
                CreditCardFee = this.CreditCardFee,
                Interest = this.Interest,
                NumberOfPayments = this.NumberOfPayments,
                CardLast4Numbers = this.CardLast4Numbers
            };
        }

        /// <summary>
        /// Determines whether the specified object is equal to this VwReportWalletTransferData.
        /// </summary>
        public override bool Equals(object obj)
        {
            if (obj is not VwReportWalletTransferData other)
                return false;


            return base.Equals(obj);
        }

        /// <summary>
        /// Returns a hash code for this instance.
        /// </summary>
        public override int GetHashCode()
        {
            return base.GetHashCode();
        }

        #endregion
    }
}
