// <auto-generated>
//     This code was generated by TargCC.Core.Generators.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;

namespace UpayCard.RiskManagement.Domain.Entities
{
    /// <summary>
    /// Entity class for vwReportCustomerCreditCardTransactionsData table.
    /// Generated: 2025-12-17 13:13:02
    /// </summary>
    [Table("vwReportCustomerCreditCardTransactionsData")]
    public partial class VwReportCustomerCreditCardTransactionsData
    {
        #region Properties

        // Regular Properties
        /// <summary>
        /// Gets or sets the ID.
        /// </summary>
        [Column("ID")]
        public long? ID { get; set; }
        /// <summary>
        /// Gets or sets the TransactionCreditCardID.
        /// </summary>
        [Column("TransactionCreditCardID")]
        public long? TransactionCreditCardID { get; set; }
        /// <summary>
        /// Gets or sets the CustomerWalletID.
        /// </summary>
        [Column("CustomerWalletID")]
        [Required]
        public long CustomerWalletID { get; set; }
        /// <summary>
        /// Gets or sets the WhenDone.
        /// </summary>
        [Column("WhenDone")]
        public DateTimeOffset? WhenDone { get; set; }
        /// <summary>
        /// Gets or sets the CustomerNo.
        /// </summary>
        [Column("CustomerNo")]
        public long? CustomerNo { get; set; }
        /// <summary>
        /// Gets or sets the CustomerID.
        /// </summary>
        [Column("CustomerID")]
        public long? CustomerID { get; set; }
        /// <summary>
        /// Gets or sets the NumberOfPayments.
        /// </summary>
        [Column("NumberOfPayments")]
        public int? NumberOfPayments { get; set; }
        /// <summary>
        /// Gets or sets the TotalPaymentAmount.
        /// </summary>
        [Column("TotalPaymentAmount")]
        public decimal? TotalPaymentAmount { get; set; }
        /// <summary>
        /// Gets or sets the CardLast4Numbers.
        /// </summary>
        [Column("CardLast4Numbers")]
        [MaxLength(50)]
        public string CardLast4Numbers { get; set; }
        /// <summary>
        /// Lookup value for lkpClearingHouse.
        /// </summary>
        [Column("lkpClearingHouse")]
        public int? lkpClearingHouse { get; set; }

        /// <summary>
        /// Display text for lkpClearingHouse (from lookup table).
        /// </summary>
        [NotMapped]
        public string lkpClearingHouseText { get; set; }
        /// <summary>
        /// Lookup value for lkpCardBrand.
        /// </summary>
        [Column("lkpCardBrand")]
        public int? lkpCardBrand { get; set; }

        /// <summary>
        /// Display text for lkpCardBrand (from lookup table).
        /// </summary>
        [NotMapped]
        public string lkpCardBrandText { get; set; }
        /// <summary>
        /// Gets or sets the CreditCardFee.
        /// </summary>
        [Column("CreditCardFee")]
        public decimal? CreditCardFee { get; set; }
        /// <summary>
        /// Gets or sets the Interest.
        /// </summary>
        [Column("Interest")]
        public decimal? Interest { get; set; }
        /// <summary>
        /// Gets or sets the DateDone.
        /// </summary>
        [Column("DateDone")]
        public DateTime? DateDone { get; set; }
        /// <summary>
        /// Gets or sets the MonthDone.
        /// </summary>
        [Column("MonthDone")]
        public DateTime? MonthDone { get; set; }

        #endregion

        #region Constructors

        /// <summary>
        /// Initializes a new instance of the <see cref="VwReportCustomerCreditCardTransactionsData"/> class.
        /// </summary>
        public VwReportCustomerCreditCardTransactionsData()
        {
        }

        #endregion

        #region Methods

        /// <summary>
        /// Returns a string representation of this VwReportCustomerCreditCardTransactionsData.
        /// </summary>
        public override string ToString()
        {
            return $"VwReportCustomerCreditCardTransactionsData";
        }

        /// <summary>
        /// Creates a shallow copy of this VwReportCustomerCreditCardTransactionsData.
        /// </summary>
        public VwReportCustomerCreditCardTransactionsData Clone()
        {
            return new VwReportCustomerCreditCardTransactionsData
            {
                ID = this.ID,
                TransactionCreditCardID = this.TransactionCreditCardID,
                CustomerWalletID = this.CustomerWalletID,
                WhenDone = this.WhenDone,
                CustomerNo = this.CustomerNo,
                CustomerID = this.CustomerID,
                NumberOfPayments = this.NumberOfPayments,
                TotalPaymentAmount = this.TotalPaymentAmount,
                CardLast4Numbers = this.CardLast4Numbers,
                lkpClearingHouse = this.lkpClearingHouse,
                lkpCardBrand = this.lkpCardBrand,
                CreditCardFee = this.CreditCardFee,
                Interest = this.Interest,
                DateDone = this.DateDone,
                MonthDone = this.MonthDone
            };
        }

        /// <summary>
        /// Determines whether the specified object is equal to this VwReportCustomerCreditCardTransactionsData.
        /// </summary>
        public override bool Equals(object obj)
        {
            if (obj is not VwReportCustomerCreditCardTransactionsData other)
                return false;


            return base.Equals(obj);
        }

        /// <summary>
        /// Returns a hash code for this instance.
        /// </summary>
        public override int GetHashCode()
        {
            return base.GetHashCode();
        }

        #endregion
    }
}
