// <auto-generated>
//     This code was generated by TargCC Component Generator.
//     Table: c_SystemDefault
//     Generated: 2025-12-16 10:02:24
// </auto-generated>

import React from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { Box, Typography, Button, CircularProgress, Alert, Card as MuiCard, CardContent, Grid } from '@mui/material';
import { Edit as EditIcon, Delete as DeleteIcon, ArrowBack as ArrowBackIcon } from '@mui/icons-material';
import { useSystemDefault, useDeleteSystemDefault } from '../../hooks/useSystemDefault';


export const SystemDefaultDetail: React.FC = () => {
  const navigate = useNavigate();
  const { id } = useParams<{ id: string }>();
  const { data: entity, isLoading, error } = useSystemDefault(id ? parseInt(id, 10) : null);
  const { mutate: deleteEntity } = useDeleteSystemDefault();

  const handleDelete = () => {
    if (confirm('Are you sure you want to delete this item?')) {
      deleteEntity(parseInt(id!, 10), {
        onSuccess: () => navigate('/systemDefaults'),
      });
    }
  };

  if (isLoading) {
    return <CircularProgress />;
  }

  if (error || !entity) {
    return <Alert severity="error">Failed to load systemDefault</Alert>;
  }

  return (
    <Box sx={{ maxWidth: 800 }}>
      <Box sx={{ mb: 2, display: 'flex', gap: 2 }}>
        <Button
          variant="outlined"
          startIcon={<ArrowBackIcon />}
          onClick={() => navigate('/systemDefaults')}
        >
          Back
        </Button>
        <Button
          variant="contained"
          startIcon={<EditIcon />}
          onClick={() => navigate(`/systemDefaults/${id}/edit`)}
        >
          Edit
        </Button>
        <Button
          variant="outlined"
          color="error"
          startIcon={<DeleteIcon />}
          onClick={handleDelete}
        >
          Delete
        </Button>
      </Box>

      <MuiCard>
        <CardContent>
          <Typography variant="h5" component="h2" gutterBottom>
            SystemDefault Details
          </Typography>
      <Grid container spacing={2}>
        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            TableNameCSystemDefault
          </Typography>
          <Typography variant="body1">
            {entity.tableNameCSystemDefault ? 'Yes' : 'No'}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            Id
          </Typography>
          <Typography variant="body1">
            {entity.id}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            Group
          </Typography>
          <Typography variant="body1">
            {entity.group}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            SettingName
          </Typography>
          <Typography variant="body1">
            {entity.settingName}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            SettingValue
          </Typography>
          <Typography variant="body1">
            {entity.settingValue}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            EnmSystemDefaultType
          </Typography>
          <Typography variant="body1">
            {entity.enmSystemDefaultType}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            UpdatingLoginID
          </Typography>
          <Typography variant="body1">
            {entity.updatingLoginID}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            DeletedBy
          </Typography>
          <Typography variant="body1">
            {entity.deletedBy}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            DeletedOn
          </Typography>
          <Typography variant="body1">
            {(entity.deletedOn ? new Date(entity.deletedOn).toLocaleDateString() : 'N/A')}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            Description
          </Typography>
          <Typography variant="body1">
            {entity.description}
          </Typography>
        </Grid>

      </Grid>

        </CardContent>
      </MuiCard>
    </Box>
  );
};

