// <auto-generated>
//     This code was generated by TargCC
//     Generated for: ccvwComboList_c_ObjectToTranslate (DTO)
//     Generation date: 2025-12-17 17:47:21
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

namespace UpayCard.RiskManagement.Application.DTOs;

/// <summary>
/// Data Transfer Object for ccvwComboList_c_ObjectToTranslate entity.
/// </summary>
/// <remarks>
/// This DTO excludes sensitive fields (encrypted, hashed) and exposes only safe properties.
/// </remarks>
public class CcvwComboListCObjectToTranslateDto
{
    /// <summary>
    /// Gets or sets the ID.
    /// </summary>
    public long ID { get; init; }

    /// <summary>
    /// Gets or sets the TextNS.
    /// </summary>
    public string TextNS { get; init; } = string.Empty;

    /// <summary>
    /// Gets or sets the Text.
    /// </summary>
    public string Text { get; init; } = string.Empty;

}
