// <auto-generated>
//     This code was generated by TargCC
//     Generated for: RiskRule (DTO)
//     Generation date: 2025-12-17 21:49:14
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

namespace UpayCard.RiskManagement.Application.DTOs;

/// <summary>
/// Data Transfer Object for RiskRule entity.
/// </summary>
/// <remarks>
/// This DTO excludes sensitive fields (encrypted, hashed) and exposes only safe properties.
/// </remarks>
public class RiskRuleDto
{
    /// <summary>
    /// Gets or sets the ID.
    /// </summary>
    public long ID { get; init; }

    /// <summary>
    /// Gets or sets the TableName_RiskRule.
    /// </summary>
    public bool? TableName_RiskRule { get; init; }

    /// <summary>
    /// Gets or sets the RuleName.
    /// </summary>
    public string RuleName { get; init; } = string.Empty;

    /// <summary>
    /// Gets or sets the RuleDescription.
    /// </summary>
    public string RuleDescription { get; init; } = string.Empty;

    /// <summary>
    /// Gets or sets the enmMonitoredEntity.
    /// </summary>
    public string enmMonitoredEntity { get; init; } = string.Empty;

    /// <summary>
    /// Gets or sets the ReferenceTable.
    /// </summary>
    public string ReferenceTable { get; init; } = string.Empty;

    /// <summary>
    /// Gets or sets the ReferenceTransactionType.
    /// </summary>
    public string ReferenceTransactionType { get; init; } = string.Empty;

    /// <summary>
    /// Gets or sets the enmThresholdType.
    /// </summary>
    public string enmThresholdType { get; init; } = string.Empty;

    /// <summary>
    /// Gets or sets the ThresholdValue.
    /// </summary>
    public decimal? ThresholdValue { get; init; }

    /// <summary>
    /// Gets or sets the MinimumTransactionAmount.
    /// </summary>
    public decimal? MinimumTransactionAmount { get; init; }

    /// <summary>
    /// Gets or sets the MaximumTransactionAmount.
    /// </summary>
    public decimal? MaximumTransactionAmount { get; init; }

    /// <summary>
    /// Gets or sets the enmBaselineScope.
    /// </summary>
    public string enmBaselineScope { get; init; } = string.Empty;

    /// <summary>
    /// Gets or sets the BaselineReferenceTable.
    /// </summary>
    public string BaselineReferenceTable { get; init; } = string.Empty;

    /// <summary>
    /// Gets or sets the MinimumBaselineCount.
    /// </summary>
    public int? MinimumBaselineCount { get; init; }

    /// <summary>
    /// Gets or sets the enmTimePeriod.
    /// </summary>
    public string enmTimePeriod { get; init; } = string.Empty;

    /// <summary>
    /// Gets or sets the enmAction.
    /// </summary>
    public string enmAction { get; init; } = string.Empty;

    /// <summary>
    /// Gets or sets the ActionDurationDays.
    /// </summary>
    public int? ActionDurationDays { get; init; }

    /// <summary>
    /// Gets or sets the enmBlockedActionType.
    /// </summary>
    public string enmBlockedActionType { get; init; } = string.Empty;

    /// <summary>
    /// Gets or sets the ActionColorID.
    /// </summary>
    public string ActionColorID { get; init; } = string.Empty;

    /// <summary>
    /// Gets or sets the ActionMaxAllowedAmount.
    /// </summary>
    public decimal? ActionMaxAllowedAmount { get; init; }

    /// <summary>
    /// Gets or sets the AlertEmailAddresses.
    /// </summary>
    public string AlertEmailAddresses { get; init; } = string.Empty;

    /// <summary>
    /// Gets or sets the AlertSMSNumbers.
    /// </summary>
    public string AlertSMSNumbers { get; init; } = string.Empty;

    /// <summary>
    /// Gets or sets the CreateTaskForUserID.
    /// </summary>
    public long? CreateTaskForUserID { get; init; }

    /// <summary>
    /// Gets or sets the enmSeverity.
    /// </summary>
    public string enmSeverity { get; init; } = string.Empty;

    /// <summary>
    /// Gets or sets the IsActive.
    /// </summary>
    public bool IsActive { get; init; }

    /// <summary>
    /// Gets or sets the AddedOn.
    /// </summary>
    public DateTime AddedOn { get; init; }

    /// <summary>
    /// Gets or sets the AddedBy.
    /// </summary>
    public string AddedBy { get; init; } = string.Empty;

    /// <summary>
    /// Gets or sets the ChangedOn.
    /// </summary>
    public DateTime? ChangedOn { get; init; }

    /// <summary>
    /// Gets or sets the ChangedBy.
    /// </summary>
    public string ChangedBy { get; init; } = string.Empty;

    /// <summary>
    /// Gets or sets the DeletedOn.
    /// </summary>
    public DateTime? DeletedOn { get; init; }

    /// <summary>
    /// Gets or sets the DeletedBy.
    /// </summary>
    public string DeletedBy { get; init; } = string.Empty;

    /// <summary>
    /// Gets or sets the UpdatingLoginID.
    /// </summary>
    public long? UpdatingLoginID { get; init; }

}
