// <auto-generated>
//     This code was generated by TargCC
//     Generated for: vwReportMonthlyCardFeeData (DTO)
//     Generation date: 2025-12-17 20:20:36
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

namespace UpayCard.RiskManagement.Application.DTOs;

/// <summary>
/// Data Transfer Object for vwReportMonthlyCardFeeData entity.
/// </summary>
/// <remarks>
/// This DTO excludes sensitive fields (encrypted, hashed) and exposes only safe properties.
/// </remarks>
public class vwReportMonthlyCardFeeDataDto
{
    /// <summary>
    /// Gets or sets the ID.
    /// </summary>
    public long ID { get; init; }

    /// <summary>
    /// Gets or sets the Month.
    /// </summary>
    public DateTime? Month { get; init; }

    /// <summary>
    /// Gets or sets the CustomerIdentifier.
    /// </summary>
    public string CustomerIdentifier { get; init; } = string.Empty;

    /// <summary>
    /// Gets or sets the CustomerName.
    /// </summary>
    public string CustomerName { get; init; } = string.Empty;

    /// <summary>
    /// Gets or sets the CardCid.
    /// </summary>
    public string CardCid { get; init; } = string.Empty;

    /// <summary>
    /// Gets or sets the CardLast4Numbers.
    /// </summary>
    public string CardLast4Numbers { get; init; } = string.Empty;

    /// <summary>
    /// Gets or sets the CardCurrency.
    /// </summary>
    public string CardCurrency { get; init; } = string.Empty;

    /// <summary>
    /// Gets or sets the CardClubName.
    /// </summary>
    public string CardClubName { get; init; } = string.Empty;

    /// <summary>
    /// Gets or sets the CardIssuerOrgCode.
    /// </summary>
    public string CardIssuerOrgCode { get; init; } = string.Empty;

    /// <summary>
    /// Gets or sets the FeeAmount.
    /// </summary>
    public decimal? FeeAmount { get; init; }

    /// <summary>
    /// Gets or sets the WhenRequested.
    /// </summary>
    public DateTimeOffset WhenRequested { get; init; }

    /// <summary>
    /// Gets or sets the RequestingUser.
    /// </summary>
    public string RequestingUser { get; init; } = string.Empty;

    /// <summary>
    /// Gets or sets the CustomerEmail.
    /// </summary>
    public string CustomerEmail { get; init; } = string.Empty;

    /// <summary>
    /// Gets or sets the CustomerCellphoneNumber.
    /// </summary>
    public string CustomerCellphoneNumber { get; init; } = string.Empty;

}
