// <auto-generated>
//     This code was generated by TargCC UI Generator.
//     Generator: ReactApi
//     Table: c_AuditIndexed
//     Generated: 2025-12-11 20:26:12
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

import { api } from './client';
import type {
  AuditIndexed,
  CreateAuditIndexedRequest,
  UpdateAuditIndexedRequest,
  AuditIndexedFilters,
} from '../types/AuditIndexed.types';

/**
 * API client for AuditIndexed operations.
 * Base URL: /AuditIndexeds
 */
export const auditIndexedApi = {
  /**
   * Get AuditIndexed by ID.
   */
  getById: async (id: number): Promise<AuditIndexed> => {
    const response = await api.get<AuditIndexed>(`/AuditIndexeds/${id}`);
    return response.data;
  },


  /**
   * Get all AuditIndexeds with optional filters.
   */
  getAll: async (filters?: AuditIndexedFilters): Promise<AuditIndexed[]> => {
    // Use /filter endpoint when filters are provided
    const endpoint = filters && Object.keys(filters).length > 0 ? '/AuditIndexeds/filter' : '/AuditIndexeds';
    const response = await api.get<AuditIndexed[]>(endpoint, {
      params: filters,
    });
    return response.data;
  },


  /**
   * Create new AuditIndexed.
   */
  create: async (data: CreateAuditIndexedRequest): Promise<AuditIndexed> => {
    const response = await api.post<AuditIndexed>('/AuditIndexeds', data);
    return response.data;
  },


  /**
   * Update existing AuditIndexed.
   */
  update: async (id: number, data: UpdateAuditIndexedRequest): Promise<AuditIndexed> => {
    const response = await api.put<AuditIndexed>(`/AuditIndexeds/${id}`, data);
    return response.data;
  },


  /**
   * Delete AuditIndexed.
   */
  delete: async (id: number): Promise<void> => {
    await api.delete(`/AuditIndexeds/${id}`);
  },


  /**
   * Get AuditIndexed by ActiveLoginID.
   */
  getByActiveLoginID: async (activeLoginID: number): Promise<AuditIndexed[]> => {
    const response = await api.get<AuditIndexed[]>(`/AuditIndexeds/by-activeLoginID/${encodeURIComponent(String(activeLoginID))}`);
    return response.data;
  },


  /**
   * Get AuditIndexed by ChangedByUser.
   */
  getByChangedByUser: async (changedByUser: string): Promise<AuditIndexed[]> => {
    const response = await api.get<AuditIndexed[]>(`/AuditIndexeds/by-changedByUser/${encodeURIComponent(String(changedByUser))}`);
    return response.data;
  },


  /**
   * Get AuditIndexed by FieldName.
   */
  getByFieldName: async (fieldName: string): Promise<AuditIndexed[]> => {
    const response = await api.get<AuditIndexed[]>(`/AuditIndexeds/by-fieldName/${encodeURIComponent(String(fieldName))}`);
    return response.data;
  },


  /**
   * Get AuditIndexed by OccurredAt.
   */
  getByOccurredAt: async (occurredAt: Date): Promise<AuditIndexed[]> => {
    const response = await api.get<AuditIndexed[]>(`/AuditIndexeds/by-occurredAt/${encodeURIComponent(String(occurredAt))}`);
    return response.data;
  },


  /**
   * Get AuditIndexed by OriginalID.
   */
  getByOriginalID: async (originalID: number): Promise<AuditIndexed[]> => {
    const response = await api.get<AuditIndexed[]>(`/AuditIndexeds/by-originalID/${encodeURIComponent(String(originalID))}`);
    return response.data;
  },


  /**
   * Get AuditIndexed by RowID.
   */
  getByRowID: async (rowID: number): Promise<AuditIndexed[]> => {
    const response = await api.get<AuditIndexed[]>(`/AuditIndexeds/by-rowID/${encodeURIComponent(String(rowID))}`);
    return response.data;
  },


  /**
   * Get AuditIndexed by TableName.
   */
  getByTableName: async (tableName: string): Promise<AuditIndexed[]> => {
    const response = await api.get<AuditIndexed[]>(`/AuditIndexeds/by-tableName/${encodeURIComponent(String(tableName))}`);
    return response.data;
  },


};
