// <auto-generated>
//     This code was generated by TargCC UI Generator.
//     Generator: ReactApi
//     Table: ccvwComboList_NewCardRequestAPIForDistributor
//     Generated: 2025-12-15 09:25:38
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

import { api } from './client';
import type {
  CcvwComboListNewCardRequestAPIForDistributor,
  CcvwComboListNewCardRequestAPIForDistributorFilters,
} from '../types/CcvwComboListNewCardRequestAPIForDistributor.types';

/**
 * API client for CcvwComboListNewCardRequestAPIForDistributor operations.
 * Base URL: /CcvwComboListNewCardRequestAPIForDistributors
 */
export const ccvwComboListNewCardRequestAPIForDistributorApi = {
  /**
   * Get all CcvwComboListNewCardRequestAPIForDistributors with optional filters.
   */
  getAll: async (filters?: CcvwComboListNewCardRequestAPIForDistributorFilters): Promise<CcvwComboListNewCardRequestAPIForDistributor[]> => {
    // Use /filter endpoint when filters are provided
    const endpoint = filters && Object.keys(filters).length > 0 ? '/CcvwComboListNewCardRequestAPIForDistributors/filter' : '/CcvwComboListNewCardRequestAPIForDistributors';
    const response = await api.get<CcvwComboListNewCardRequestAPIForDistributor[]>(endpoint, {
      params: filters,
    });
    return response.data;
  },


};
