// <auto-generated>
//     This code was generated by TargCC UI Generator.
//     Generator: ReactApi
//     Table: ccvwComboList_CardForPreviousDistributor
//     Generated: 2025-12-11 11:52:11
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

import { api } from './client';
import type {
  CcvwComboListCardForPreviousDistributor,
  CcvwComboListCardForPreviousDistributorFilters,
} from '../types/CcvwComboListCardForPreviousDistributor.types';

/**
 * API client for CcvwComboListCardForPreviousDistributor operations.
 * Base URL: /CcvwComboListCardForPreviousDistributors
 */
export const ccvwComboListCardForPreviousDistributorApi = {
  /**
   * Get all CcvwComboListCardForPreviousDistributors with optional filters.
   */
  getAll: async (filters?: CcvwComboListCardForPreviousDistributorFilters): Promise<CcvwComboListCardForPreviousDistributor[]> => {
    // Use /filter endpoint when filters are provided
    const endpoint = filters && Object.keys(filters).length > 0 ? '/CcvwComboListCardForPreviousDistributors/filter' : '/CcvwComboListCardForPreviousDistributors';
    const response = await api.get<CcvwComboListCardForPreviousDistributor[]>(endpoint, {
      params: filters,
    });
    return response.data;
  },


};
