// <auto-generated>
//     This code was generated by TargCC UI Generator.
//     Generator: ReactApi
//     Table: ccvwComboList_CustomerPartnershipForCustomer
//     Generated: 2025-12-17 21:49:11
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

import { api } from './client';
import type { PagedResult, UseEntityOptions } from '../types/common.types';
import type {
  CcvwComboListCustomerPartnershipForCustomer,
  CcvwComboListCustomerPartnershipForCustomerFilters,
} from '../types/CcvwComboListCustomerPartnershipForCustomer.types';

type UseCcvwComboListCustomerPartnershipForCustomerOptions = UseEntityOptions<CcvwComboListCustomerPartnershipForCustomerFilters>;

/**
 * API client for CcvwComboListCustomerPartnershipForCustomer operations.
 * Base URL: /CcvwComboListCustomerPartnershipForCustomers
 */
export const ccvwComboListCustomerPartnershipForCustomerApi = {
  /**
   * Get all CcvwComboListCustomerPartnershipForCustomers with server-side filtering, sorting, and pagination.
   */
  getAll: async (options?: UseCcvwComboListCustomerPartnershipForCustomerOptions): Promise<PagedResult<CcvwComboListCustomerPartnershipForCustomer>> => {
    const params = new URLSearchParams();

    // Add pagination params
    if (options?.page) params.append('page', options.page.toString());
    if (options?.pageSize) params.append('pageSize', options.pageSize.toString());
    if (options?.sortBy) params.append('sortBy', options.sortBy);
    if (options?.sortDirection) params.append('sortDirection', options.sortDirection);

    // Add filter params
    if (options?.filters) {
      Object.entries(options.filters).forEach(([key, value]) => {
        if (value !== undefined && value !== null && value !== '') {
          params.append(key, value.toString());
        }
      });
    }

    const response = await api.get<PagedResult<CcvwComboListCustomerPartnershipForCustomer>>(`/CcvwComboListCustomerPartnershipForCustomers?${params.toString()}`);
    return response.data;
  },


};
