// <auto-generated>
//     This code was generated by TargCC UI Generator.
//     Generator: ReactApi
//     Table: ccvwComboList_CustomerWallet
//     Generated: 2025-12-11 21:35:45
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

import { api } from './client';
import type {
  CcvwComboListCustomerWallet,
  CcvwComboListCustomerWalletFilters,
} from '../types/CcvwComboListCustomerWallet.types';

/**
 * API client for CcvwComboListCustomerWallet operations.
 * Base URL: /CcvwComboListCustomerWallets
 */
export const ccvwComboListCustomerWalletApi = {
  /**
   * Get all CcvwComboListCustomerWallets with optional filters.
   */
  getAll: async (filters?: CcvwComboListCustomerWalletFilters): Promise<CcvwComboListCustomerWallet[]> => {
    // Use /filter endpoint when filters are provided
    const endpoint = filters && Object.keys(filters).length > 0 ? '/CcvwComboListCustomerWallets/filter' : '/CcvwComboListCustomerWallets';
    const response = await api.get<CcvwComboListCustomerWallet[]>(endpoint, {
      params: filters,
    });
    return response.data;
  },


};
