// <auto-generated>
//     This code was generated by TargCC UI Generator.
//     Generator: ReactApi
//     Table: ExternalCustomer
//     Generated: 2025-12-11 21:18:55
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

import { api } from './client';
import type {
  ExternalCustomer,
  CreateExternalCustomerRequest,
  UpdateExternalCustomerRequest,
  ExternalCustomerFilters,
} from '../types/ExternalCustomer.types';

/**
 * API client for ExternalCustomer operations.
 * Base URL: /ExternalCustomers
 */
export const externalCustomerApi = {
  /**
   * Get ExternalCustomer by ID.
   */
  getById: async (id: number): Promise<ExternalCustomer> => {
    const response = await api.get<ExternalCustomer>(`/ExternalCustomers/${id}`);
    return response.data;
  },


  /**
   * Get all ExternalCustomers with optional filters.
   */
  getAll: async (filters?: ExternalCustomerFilters): Promise<ExternalCustomer[]> => {
    // Use /filter endpoint when filters are provided
    const endpoint = filters && Object.keys(filters).length > 0 ? '/ExternalCustomers/filter' : '/ExternalCustomers';
    const response = await api.get<ExternalCustomer[]>(endpoint, {
      params: filters,
    });
    return response.data;
  },


  /**
   * Create new ExternalCustomer.
   */
  create: async (data: CreateExternalCustomerRequest): Promise<ExternalCustomer> => {
    const response = await api.post<ExternalCustomer>('/ExternalCustomers', data);
    return response.data;
  },


  /**
   * Update existing ExternalCustomer.
   */
  update: async (id: number, data: UpdateExternalCustomerRequest): Promise<ExternalCustomer> => {
    const response = await api.put<ExternalCustomer>(`/ExternalCustomers/${id}`, data);
    return response.data;
  },


  /**
   * Delete ExternalCustomer.
   */
  delete: async (id: number): Promise<void> => {
    await api.delete(`/ExternalCustomers/${id}`);
  },


  /**
   * Get ExternalCustomer by CustomerID.
   */
  getByCustomerID: async (customerID: number): Promise<ExternalCustomer[]> => {
    const response = await api.get<ExternalCustomer[]>(`/ExternalCustomers/by-customerID/${encodeURIComponent(String(customerID))}`);
    return response.data;
  },


  /**
   * Get ExternalCustomer by EnmExternalService.
   */
  getByEnmExternalService: async (enmExternalService: string): Promise<ExternalCustomer[]> => {
    const response = await api.get<ExternalCustomer[]>(`/ExternalCustomers/by-enmExternalService/${encodeURIComponent(String(enmExternalService))}`);
    return response.data;
  },


};
