// <auto-generated>
//     This code was generated by TargCC UI Generator.
//     Generator: ReactApi
//     Table: GovtReport10
//     Generated: 2025-12-17 09:02:40
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

import { api } from './client';
import type { PagedResult, UseEntityOptions } from '../types/common.types';
import type {
  GovtReport10,
  CreateGovtReport10Request,
  UpdateGovtReport10Request,
  GovtReport10Filters,
} from '../types/GovtReport10.types';

type UseGovtReport10Options = UseEntityOptions<GovtReport10Filters>;

/**
 * API client for GovtReport10 operations.
 * Base URL: /GovtReport10s
 */
export const govtReport10Api = {
  /**
   * Get GovtReport10 by ID.
   */
  getById: async (id: number): Promise<GovtReport10> => {
    const response = await api.get<GovtReport10>(`/GovtReport10s/${id}`);
    return response.data;
  },


  /**
   * Get all GovtReport10s with server-side filtering, sorting, and pagination.
   */
  getAll: async (options?: UseGovtReport10Options): Promise<PagedResult<GovtReport10>> => {
    const params = new URLSearchParams();

    // Add pagination params
    if (options?.page) params.append('page', options.page.toString());
    if (options?.pageSize) params.append('pageSize', options.pageSize.toString());
    if (options?.sortBy) params.append('sortBy', options.sortBy);
    if (options?.sortDirection) params.append('sortDirection', options.sortDirection);

    // Add filter params
    if (options?.filters) {
      Object.entries(options.filters).forEach(([key, value]) => {
        if (value !== undefined && value !== null && value !== '') {
          params.append(key, value.toString());
        }
      });
    }

    const response = await api.get<PagedResult<GovtReport10>>(`/GovtReport10s?${params.toString()}`);
    return response.data;
  },


  /**
   * Create new GovtReport10.
   */
  create: async (data: CreateGovtReport10Request): Promise<GovtReport10> => {
    const response = await api.post<GovtReport10>('/GovtReport10s', data);
    return response.data;
  },


  /**
   * Update existing GovtReport10.
   */
  update: async (id: number, data: UpdateGovtReport10Request): Promise<GovtReport10> => {
    const response = await api.put<GovtReport10>(`/GovtReport10s/${id}`, data);
    return response.data;
  },


  /**
   * Delete GovtReport10.
   */
  delete: async (id: number): Promise<void> => {
    await api.delete(`/GovtReport10s/${id}`);
  },


  /**
   * Get GovtReport10 by GovtReport00ID.
   */
  getByGovtReport00ID: async (govtReport00ID: number): Promise<GovtReport10[]> => {
    const response = await api.get<GovtReport10[]>(`/GovtReport10s/by-govtReport00ID/${encodeURIComponent(String(govtReport00ID))}`);
    return response.data;
  },


};
