// <auto-generated>
//     This code was generated by TargCC UI Generator.
//     Generator: ReactApi
//     Table: c_Language
//     Generated: 2025-12-17 08:03:48
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

import { api } from './client';
import type { PagedResult, UseEntityOptions } from '../types/common.types';
import type {
  Language,
  CreateLanguageRequest,
  UpdateLanguageRequest,
  LanguageFilters,
} from '../types/Language.types';

type UseLanguageOptions = UseEntityOptions<LanguageFilters>;

/**
 * API client for Language operations.
 * Base URL: /Languages
 */
export const languageApi = {
  /**
   * Get Language by ID.
   */
  getById: async (id: number): Promise<Language> => {
    const response = await api.get<Language>(`/Languages/${id}`);
    return response.data;
  },


  /**
   * Get all Languages with server-side filtering, sorting, and pagination.
   */
  getAll: async (options?: UseLanguageOptions): Promise<PagedResult<Language>> => {
    const params = new URLSearchParams();

    // Add pagination params
    if (options?.page) params.append('page', options.page.toString());
    if (options?.pageSize) params.append('pageSize', options.pageSize.toString());
    if (options?.sortBy) params.append('sortBy', options.sortBy);
    if (options?.sortDirection) params.append('sortDirection', options.sortDirection);

    // Add filter params
    if (options?.filters) {
      Object.entries(options.filters).forEach(([key, value]) => {
        if (value !== undefined && value !== null && value !== '') {
          params.append(key, value.toString());
        }
      });
    }

    const response = await api.get<PagedResult<Language>>(`/Languages?${params.toString()}`);
    return response.data;
  },


  /**
   * Create new Language.
   */
  create: async (data: CreateLanguageRequest): Promise<Language> => {
    const response = await api.post<Language>('/Languages', data);
    return response.data;
  },


  /**
   * Update existing Language.
   */
  update: async (id: number, data: UpdateLanguageRequest): Promise<Language> => {
    const response = await api.put<Language>(`/Languages/${id}`, data);
    return response.data;
  },


  /**
   * Delete Language.
   */
  delete: async (id: number): Promise<void> => {
    await api.delete(`/Languages/${id}`);
  },


  /**
   * Get Language by Code.
   */
  getByCode: async (code: string): Promise<Language> => {
    const response = await api.get<Language>(`/Languages/by-code/${encodeURIComponent(String(code))}`);
    return response.data;
  },


};
