// <auto-generated>
//     This code was generated by TargCC UI Generator.
//     Generator: ReactApi
//     Table: MCCBFPCashOut
//     Generated: 2025-12-17 08:16:17
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

import { api } from './client';
import type { PagedResult, UseEntityOptions } from '../types/common.types';
import type {
  MCCBFPCashOut,
  CreateMCCBFPCashOutRequest,
  UpdateMCCBFPCashOutRequest,
  MCCBFPCashOutFilters,
} from '../types/MCCBFPCashOut.types';

type UseMCCBFPCashOutOptions = UseEntityOptions<MCCBFPCashOutFilters>;

/**
 * API client for MCCBFPCashOut operations.
 * Base URL: /MCCBFPCashOuts
 */
export const mCCBFPCashOutApi = {
  /**
   * Get MCCBFPCashOut by ID.
   */
  getById: async (id: number): Promise<MCCBFPCashOut> => {
    const response = await api.get<MCCBFPCashOut>(`/MCCBFPCashOuts/${id}`);
    return response.data;
  },


  /**
   * Get all MCCBFPCashOuts with server-side filtering, sorting, and pagination.
   */
  getAll: async (options?: UseMCCBFPCashOutOptions): Promise<PagedResult<MCCBFPCashOut>> => {
    const params = new URLSearchParams();

    // Add pagination params
    if (options?.page) params.append('page', options.page.toString());
    if (options?.pageSize) params.append('pageSize', options.pageSize.toString());
    if (options?.sortBy) params.append('sortBy', options.sortBy);
    if (options?.sortDirection) params.append('sortDirection', options.sortDirection);

    // Add filter params
    if (options?.filters) {
      Object.entries(options.filters).forEach(([key, value]) => {
        if (value !== undefined && value !== null && value !== '') {
          params.append(key, value.toString());
        }
      });
    }

    const response = await api.get<PagedResult<MCCBFPCashOut>>(`/MCCBFPCashOuts?${params.toString()}`);
    return response.data;
  },


  /**
   * Create new MCCBFPCashOut.
   */
  create: async (data: CreateMCCBFPCashOutRequest): Promise<MCCBFPCashOut> => {
    const response = await api.post<MCCBFPCashOut>('/MCCBFPCashOuts', data);
    return response.data;
  },


  /**
   * Update existing MCCBFPCashOut.
   */
  update: async (id: number, data: UpdateMCCBFPCashOutRequest): Promise<MCCBFPCashOut> => {
    const response = await api.put<MCCBFPCashOut>(`/MCCBFPCashOuts/${id}`, data);
    return response.data;
  },


  /**
   * Delete MCCBFPCashOut.
   */
  delete: async (id: number): Promise<void> => {
    await api.delete(`/MCCBFPCashOuts/${id}`);
  },


  /**
   * Get MCCBFPCashOut by Country.
   */
  getByCountry: async (country: string): Promise<MCCBFPCashOut[]> => {
    const response = await api.get<MCCBFPCashOut[]>(`/MCCBFPCashOuts/by-country/${encodeURIComponent(String(country))}`);
    return response.data;
  },


};
