// <auto-generated>
//     This code was generated by TargCC UI Generator.
//     Generator: ReactApi
//     Table: RiskEvent
//     Generated: 2025-12-15 13:53:30
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

import { api } from './client';
import type {
  RiskEvent,
  CreateRiskEventRequest,
  UpdateRiskEventRequest,
  RiskEventFilters,
} from '../types/RiskEvent.types';
import type { ActiveRestrictions } from '../types/ActiveRestrictions.types';

/**
 * API client for RiskEvent operations.
 * Base URL: /RiskEvents
 */
export const riskEventApi = {
  /**
   * Get RiskEvent by ID.
   */
  getById: async (id: number): Promise<RiskEvent> => {
    const response = await api.get<RiskEvent>(`/RiskEvents/${id}`);
    return response.data;
  },


  /**
   * Get all RiskEvents with optional filters.
   */
  getAll: async (filters?: RiskEventFilters): Promise<RiskEvent[]> => {
    // Use /filter endpoint when filters are provided
    const endpoint = filters && Object.keys(filters).length > 0 ? '/RiskEvents/filter' : '/RiskEvents';
    const response = await api.get<RiskEvent[]>(endpoint, {
      params: filters,
    });
    return response.data;
  },


  /**
   * Create new RiskEvent.
   */
  create: async (data: CreateRiskEventRequest): Promise<RiskEvent> => {
    const response = await api.post<RiskEvent>('/RiskEvents', data);
    return response.data;
  },


  /**
   * Update existing RiskEvent.
   */
  update: async (id: number, data: UpdateRiskEventRequest): Promise<RiskEvent> => {
    const response = await api.put<RiskEvent>(`/RiskEvents/${id}`, data);
    return response.data;
  },


  /**
   * Delete RiskEvent.
   */
  delete: async (id: number): Promise<void> => {
    await api.delete(`/RiskEvents/${id}`);
  },


  /**
   * Get RiskEvent by RiskRuleID.
   */
  getByRiskRuleID: async (riskRuleID: number): Promise<RiskEvent[]> => {
    const response = await api.get<RiskEvent[]>(`/RiskEvents/by-riskRuleID/${encodeURIComponent(String(riskRuleID))}`);
    return response.data;
  },


  /**
   * Get ACTIVERESTRICTIONSES for this RISKEVENT.
   */
  getActiveRestrictionses: async (id: number, skip?: number, take?: number): Promise<ActiveRestrictions[]> => {
    const params = new URLSearchParams();
    if (skip !== undefined) params.append('skip', skip.toString());
    if (take !== undefined) params.append('take', take.toString());
    const queryString = params.toString() ? `?${params.toString()}` : '';
    const response = await api.get<ActiveRestrictions[]>(`/RiskEvents/${id}/ACTIVERESTRICTIONSES${queryString}`);
    return response.data;
  },


};
