// <auto-generated>
//     This code was generated by TargCC
//     Generated for: ExternalTransaction (Command)
//     Generation date: 2025-12-17 09:08:26
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using MediatR;
using UpayCard.RiskManagement.Application.Common.Models;

namespace UpayCard.RiskManagement.Application.Features.ExternalTransactions.Commands;

/// <summary>
/// Command to create a new ExternalTransaction.
/// </summary>
public record CreateExternalTransactionCommand : IRequest<Result<long>>
{
    /// <summary>
    /// Gets or sets the TableName_ExternalTransaction.
    /// </summary>
    public bool? TableName_ExternalTransaction { get; init; }

    /// <summary>
    /// Gets or sets the enmExternalService.
    /// </summary>
    public string enmExternalService { get; init; } = string.Empty;

    /// <summary>
    /// Gets or sets the CustomerID.
    /// </summary>
    public long CustomerID { get; init; }

    /// <summary>
    /// Gets or sets the ExternalTransactionIdentifier.
    /// </summary>
    public string ExternalTransactionIdentifier { get; init; }

    /// <summary>
    /// Gets or sets the TransactionCreditCardID.
    /// </summary>
    public long? TransactionCreditCardID { get; init; }

    /// <summary>
    /// Gets or sets the CustomerWalletID.
    /// </summary>
    public long? CustomerWalletID { get; init; }

    /// <summary>
    /// Gets or sets the MarginUsed.
    /// </summary>
    public decimal? MarginUsed { get; init; }

    /// <summary>
    /// Gets or sets the ExecutingCurrency.
    /// </summary>
    public string ExecutingCurrency { get; init; }

    /// <summary>
    /// Gets or sets the ExecutingCurrencyExchangeRate.
    /// </summary>
    public decimal? ExecutingCurrencyExchangeRate { get; init; }

    /// <summary>
    /// Gets or sets the AmountILS.
    /// </summary>
    public decimal? AmountILS { get; init; }

    /// <summary>
    /// Gets or sets the Description.
    /// </summary>
    public string Description { get; init; }

    /// <summary>
    /// Gets or sets the StatusFromExternalService.
    /// </summary>
    public string StatusFromExternalService { get; init; }

    /// <summary>
    /// Gets or sets the enmTransactionStatus_ExternalTransactionStatus.
    /// </summary>
    public string enmTransactionStatus_ExternalTransactionStatus { get; init; }

    /// <summary>
    /// Gets or sets the PaymentApprovalCode.
    /// </summary>
    public string PaymentApprovalCode { get; init; }

    /// <summary>
    /// Gets or sets the WhenPaymentCompleted.
    /// </summary>
    public DateTimeOffset? WhenPaymentCompleted { get; init; }

    /// <summary>
    /// Gets or sets the WhenTransactionCancelled.
    /// </summary>
    public DateTimeOffset? WhenTransactionCancelled { get; init; }

    /// <summary>
    /// Gets or sets the WhenTransactionCompleted.
    /// </summary>
    public DateTimeOffset? WhenTransactionCompleted { get; init; }

    /// <summary>
    /// Gets or sets the AmountRefunded.
    /// </summary>
    public decimal? AmountRefunded { get; init; }

    /// <summary>
    /// Gets or sets the WhenRefunded.
    /// </summary>
    public DateTimeOffset? WhenRefunded { get; init; }

    /// <summary>
    /// Gets or sets the DeletedBy.
    /// </summary>
    public string DeletedBy { get; init; }

    /// <summary>
    /// Gets or sets the DeletedOn.
    /// </summary>
    public DateTime? DeletedOn { get; init; }

    /// <summary>
    /// Gets or sets the UpdatingLoginID.
    /// </summary>
    public long? UpdatingLoginID { get; init; }

    /// <summary>
    /// Gets or sets the ExternalReferenceNo.
    /// </summary>
    public string ExternalReferenceNo { get; init; }

}
