// <auto-generated>
//     This code was generated by TargCC
//     Generated for: ActiveRestrictions (Handler)
//     Generation date: 2025-12-18 07:30:14
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using MediatR;
using Microsoft.Extensions.Logging;
using UpayCard.RiskManagement.Application.Common.Models;
using UpayCard.RiskManagement.Domain.Entities;
using UpayCard.RiskManagement.Domain.Interfaces;
using ActiveRestrictionsEntity = UpayCard.RiskManagement.Domain.Entities.ActiveRestrictions;

namespace UpayCard.RiskManagement.Application.Features.ActiveRestrictions.Commands;

/// <summary>
/// Handles the CreateActiveRestrictionsCommand request.
/// </summary>
public class CreateActiveRestrictionsHandler : IRequestHandler<CreateActiveRestrictionsCommand, Result<long>>
{
    private readonly IActiveRestrictionsRepository _repository;
    private readonly ILogger<CreateActiveRestrictionsHandler> _logger;

    /// <summary>
    /// Initializes a new instance of the <see cref="CreateActiveRestrictionsHandler"/> class.
    /// </summary>
    public CreateActiveRestrictionsHandler(
        IActiveRestrictionsRepository repository,
        ILogger<CreateActiveRestrictionsHandler> logger)
    {
        _repository = repository ?? throw new ArgumentNullException(nameof(repository));
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
    }

    /// <inheritdoc/>
    public async Task<Result<long>> Handle(CreateActiveRestrictionsCommand request, CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(request);

        _logger.LogDebug("Creating new ActiveRestrictions");

        try
        {
            var entity = new ActiveRestrictionsEntity
            {
                TableName_ActiveRestrictions = request.TableName_ActiveRestrictions,
                MaxAllowedAmount = request.MaxAllowedAmount,
                ValidFrom = request.ValidFrom,
                ValidUntil = request.ValidUntil,
                BlockReason = request.BlockReason,
                TriggerRuleID = request.TriggerRuleID,
                TriggerEventID = request.TriggerEventID,
                DeletedOn = request.DeletedOn,
                DeletedBy = request.DeletedBy,
                UpdatingLoginID = request.UpdatingLoginID
            };

            await _repository.AddAsync(entity, cancellationToken);

            _logger.LogInformation("ActiveRestrictions created successfully with ID: {Id}", entity.ID);

            return Result<long>.Success(entity.ID);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error creating ActiveRestrictions");
            throw;
        }
    }
}
