// <auto-generated>
//     This code was generated by TargCC
//     Generated for: c_LoggedAlert (Command)
//     Generation date: 2025-12-17 14:08:20
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using MediatR;
using UpayCard.RiskManagement.Application.Common.Models;

namespace UpayCard.RiskManagement.Application.Features.LoggedAlerts.Commands;

/// <summary>
/// Command to create a new c_LoggedAlert.
/// </summary>
public record CreateLoggedAlertCommand : IRequest<Result<long>>
{
    /// <summary>
    /// Gets or sets the TimeOccurred.
    /// </summary>
    public DateTime? TimeOccurred { get; init; }

    /// <summary>
    /// Gets or sets the FaultNumber.
    /// </summary>
    public int? FaultNumber { get; init; }

    /// <summary>
    /// Gets or sets the SystemName.
    /// </summary>
    public string SystemName { get; init; }

    /// <summary>
    /// Gets or sets the CallingApplication.
    /// </summary>
    public string CallingApplication { get; init; }

    /// <summary>
    /// Gets or sets the AffectedUserID.
    /// </summary>
    public long? AffectedUserID { get; init; }

    /// <summary>
    /// Gets or sets the CallingApplicationVersion.
    /// </summary>
    public string CallingApplicationVersion { get; init; }

    /// <summary>
    /// Gets or sets the CallingFunctionWithinApplication.
    /// </summary>
    public string CallingFunctionWithinApplication { get; init; }

    /// <summary>
    /// Gets or sets the FreeText.
    /// </summary>
    public string FreeText { get; init; }

    /// <summary>
    /// Gets or sets the FaultingAssembly.
    /// </summary>
    public string FaultingAssembly { get; init; }

    /// <summary>
    /// Gets or sets the AssemblyEntryPoint.
    /// </summary>
    public string AssemblyEntryPoint { get; init; }

    /// <summary>
    /// Gets or sets the FaultingClass.
    /// </summary>
    public string FaultingClass { get; init; }

    /// <summary>
    /// Gets or sets the FaultingFunction.
    /// </summary>
    public string FaultingFunction { get; init; }

    /// <summary>
    /// Gets or sets the FaultingFunctionParameters.
    /// </summary>
    public string FaultingFunctionParameters { get; init; }

    /// <summary>
    /// Gets or sets the FaultIdent.
    /// </summary>
    public string FaultIdent { get; init; }

    /// <summary>
    /// Gets or sets the FaultDescription.
    /// </summary>
    public string FaultDescription { get; init; }

    /// <summary>
    /// Gets or sets the MessageSentToUser.
    /// </summary>
    public string MessageSentToUser { get; init; }

    /// <summary>
    /// Gets or sets the ActionSentToUser.
    /// </summary>
    public string ActionSentToUser { get; init; }

    /// <summary>
    /// Gets or sets the c_LoggedLoginID.
    /// </summary>
    public long? c_LoggedLoginID { get; init; }

    /// <summary>
    /// Gets or sets the Thread.
    /// </summary>
    public string Thread { get; init; }

    /// <summary>
    /// Gets or sets the lkpUserIdentityType.
    /// </summary>
    public string lkpUserIdentityType { get; init; }

    /// <summary>
    /// Gets or sets the lkpUserIdentityTypeName.
    /// </summary>
    public int? lkpUserIdentityTypeName { get; init; }

}
