/**
 * Mock Generated Code Utility
 * 
 * Generates realistic C# code examples for different component types.
 * Used to demonstrate code generation capabilities.
 */

/**
 * Generate mock C# code for a given table
 */
export const generateMockCode = (tableName: string) => ({
  entity: `namespace TargCC.Domain.Entities
{
    /// <summary>
    /// ${tableName} entity
    /// Generated by TargCC Core V2
    /// </summary>
    public class ${tableName}
    {
        /// <summary>
        /// Primary key
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// ${tableName} name
        /// </summary>
        public string Name { get; set; } = string.Empty;

        /// <summary>
        /// ${tableName} description
        /// </summary>
        public string? Description { get; set; }

        /// <summary>
        /// Creation timestamp
        /// </summary>
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Last update timestamp
        /// </summary>
        public DateTime? UpdatedAt { get; set; }

        /// <summary>
        /// Soft delete flag
        /// </summary>
        public bool IsDeleted { get; set; }
    }
}`,

  repository: `namespace TargCC.Infrastructure.Repositories
{
    /// <summary>
    /// Repository interface for ${tableName}
    /// </summary>
    public interface I${tableName}Repository
    {
        /// <summary>
        /// Get ${tableName} by ID
        /// </summary>
        Task<${tableName}?> GetByIdAsync(int id);

        /// <summary>
        /// Get all ${tableName}s
        /// </summary>
        Task<IEnumerable<${tableName}>> GetAllAsync();

        /// <summary>
        /// Add new ${tableName}
        /// </summary>
        Task<int> AddAsync(${tableName} entity);

        /// <summary>
        /// Update existing ${tableName}
        /// </summary>
        Task UpdateAsync(${tableName} entity);

        /// <summary>
        /// Delete ${tableName} by ID
        /// </summary>
        Task DeleteAsync(int id);
    }

    public class ${tableName}Repository : I${tableName}Repository
    {
        private readonly IDbConnection _connection;

        public ${tableName}Repository(IDbConnection connection)
        {
            _connection = connection;
        }

        public async Task<${tableName}?> GetByIdAsync(int id)
        {
            const string sql = "SELECT * FROM ${tableName}s WHERE Id = @Id";
            return await _connection.QuerySingleOrDefaultAsync<${tableName}>(sql, new { Id = id });
        }

        public async Task<IEnumerable<${tableName}>> GetAllAsync()
        {
            const string sql = "SELECT * FROM ${tableName}s WHERE IsDeleted = 0";
            return await _connection.QueryAsync<${tableName}>(sql);
        }

        public async Task<int> AddAsync(${tableName} entity)
        {
            const string sql = @"
                INSERT INTO ${tableName}s (Name, Description, CreatedAt)
                VALUES (@Name, @Description, @CreatedAt);
                SELECT CAST(SCOPE_IDENTITY() as int)";
            return await _connection.ExecuteScalarAsync<int>(sql, entity);
        }

        public async Task UpdateAsync(${tableName} entity)
        {
            const string sql = @"
                UPDATE ${tableName}s 
                SET Name = @Name, Description = @Description, UpdatedAt = @UpdatedAt
                WHERE Id = @Id";
            await _connection.ExecuteAsync(sql, entity);
        }

        public async Task DeleteAsync(int id)
        {
            const string sql = "UPDATE ${tableName}s SET IsDeleted = 1 WHERE Id = @Id";
            await _connection.ExecuteAsync(sql, new { Id = id });
        }
    }
}`,

  handler: `namespace TargCC.Application.${tableName}s.Queries
{
    /// <summary>
    /// Query to get ${tableName} by ID
    /// </summary>
    public record Get${tableName}Query(int Id) : IRequest<${tableName}?>;

    public class Get${tableName}QueryHandler 
        : IRequestHandler<Get${tableName}Query, ${tableName}?>
    {
        private readonly I${tableName}Repository _repository;
        private readonly ILogger<Get${tableName}QueryHandler> _logger;

        public Get${tableName}QueryHandler(
            I${tableName}Repository repository,
            ILogger<Get${tableName}QueryHandler> logger)
        {
            _repository = repository;
            _logger = logger;
        }

        public async Task<${tableName}?> Handle(
            Get${tableName}Query request, 
            CancellationToken cancellationToken)
        {
            _logger.LogInformation("Getting ${tableName} {Id}", request.Id);
            return await _repository.GetByIdAsync(request.Id);
        }
    }

    public record GetAll${tableName}sQuery : IRequest<IEnumerable<${tableName}>>;

    public class GetAll${tableName}sQueryHandler 
        : IRequestHandler<GetAll${tableName}sQuery, IEnumerable<${tableName}>>
    {
        private readonly I${tableName}Repository _repository;

        public GetAll${tableName}sQueryHandler(I${tableName}Repository repository)
        {
            _repository = repository;
        }

        public async Task<IEnumerable<${tableName}>> Handle(
            GetAll${tableName}sQuery request, 
            CancellationToken cancellationToken)
        {
            return await _repository.GetAllAsync();
        }
    }
}`,

  controller: `namespace TargCC.API.Controllers
{
    /// <summary>
    /// ${tableName} API controller
    /// </summary>
    [ApiController]
    [Route("api/[controller]")]
    public class ${tableName}Controller : ControllerBase
    {
        private readonly IMediator _mediator;

        public ${tableName}Controller(IMediator mediator)
        {
            _mediator = mediator;
        }

        /// <summary>
        /// Get ${tableName} by ID
        /// </summary>
        [HttpGet("{id}")]
        public async Task<ActionResult<${tableName}>> Get(int id)
        {
            var query = new Get${tableName}Query(id);
            var result = await _mediator.Send(query);
            
            if (result == null)
                return NotFound();
                
            return Ok(result);
        }

        /// <summary>
        /// Get all ${tableName}s
        /// </summary>
        [HttpGet]
        public async Task<ActionResult<IEnumerable<${tableName}>>> GetAll()
        {
            var query = new GetAll${tableName}sQuery();
            var result = await _mediator.Send(query);
            return Ok(result);
        }

        /// <summary>
        /// Create new ${tableName}
        /// </summary>
        [HttpPost]
        public async Task<ActionResult<int>> Create(Create${tableName}Command command)
        {
            var id = await _mediator.Send(command);
            return CreatedAtAction(nameof(Get), new { id }, id);
        }

        /// <summary>
        /// Update ${tableName}
        /// </summary>
        [HttpPut("{id}")]
        public async Task<IActionResult> Update(int id, Update${tableName}Command command)
        {
            if (id != command.Id)
                return BadRequest("ID mismatch");
                
            await _mediator.Send(command);
            return NoContent();
        }

        /// <summary>
        /// Delete ${tableName}
        /// </summary>
        [HttpDelete("{id}")]
        public async Task<IActionResult> Delete(int id)
        {
            await _mediator.Send(new Delete${tableName}Command(id));
            return NoContent();
        }
    }
}`
});


/**
 * Generate array of mock code files for a table
 */
export const mockCodeFiles = (tableName: string) => {
  const code = generateMockCode(tableName);
  
  return [
    { 
      name: `${tableName}.cs`, 
      code: code.entity, 
      language: 'csharp' 
    },
    { 
      name: `I${tableName}Repository.cs`, 
      code: code.repository, 
      language: 'csharp' 
    },
    { 
      name: `Get${tableName}QueryHandler.cs`, 
      code: code.handler, 
      language: 'csharp' 
    },
    { 
      name: `${tableName}Controller.cs`, 
      code: code.controller, 
      language: 'csharp' 
    }
  ];
};
