// <auto-generated>
//     This code was generated by TargCC
//     Generated for: ccvwComboList_CardOrderFromIssuerForOrderedByUser (Handler)
//     Generation date: 2025-12-16 09:26:44
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using MediatR;
using Microsoft.Extensions.Logging;
using UpayCard.RiskManagement.Application.Common.Models;
using UpayCard.RiskManagement.Domain.Entities;
using UpayCard.RiskManagement.Domain.Interfaces;

namespace UpayCard.RiskManagement.Application.Features.CcvwComboListCardOrderFromIssuerForOrderedByUsers.Commands;

/// <summary>
/// Handles the CreateCcvwComboListCardOrderFromIssuerForOrderedByUserCommand request.
/// </summary>
public class CreateCcvwComboListCardOrderFromIssuerForOrderedByUserHandler : IRequestHandler<CreateCcvwComboListCardOrderFromIssuerForOrderedByUserCommand, Result<int>>
{
    private readonly ICcvwComboListCardOrderFromIssuerForOrderedByUserRepository _repository;
    private readonly ILogger<CreateCcvwComboListCardOrderFromIssuerForOrderedByUserHandler> _logger;

    /// <summary>
    /// Initializes a new instance of the <see cref="CreateCcvwComboListCardOrderFromIssuerForOrderedByUserHandler"/> class.
    /// </summary>
    public CreateCcvwComboListCardOrderFromIssuerForOrderedByUserHandler(
        ICcvwComboListCardOrderFromIssuerForOrderedByUserRepository repository,
        ILogger<CreateCcvwComboListCardOrderFromIssuerForOrderedByUserHandler> logger)
    {
        _repository = repository ?? throw new ArgumentNullException(nameof(repository));
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
    }

    /// <inheritdoc/>
    public async Task<Result<int>> Handle(CreateCcvwComboListCardOrderFromIssuerForOrderedByUserCommand request, CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(request);

        _logger.LogDebug("Creating new ccvwComboList_CardOrderFromIssuerForOrderedByUser");

        try
        {
            var entity = new ccvwComboList_CardOrderFromIssuerForOrderedByUser
            {
                ParentID = request.ParentID,
                TextNS = request.TextNS,
                Text = request.Text
            };

            await _repository.AddAsync(entity, cancellationToken);

            _logger.LogInformation("ccvwComboList_CardOrderFromIssuerForOrderedByUser created successfully with ID: {Id}", entity.Id);

            return Result<int>.Success(entity.Id);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error creating ccvwComboList_CardOrderFromIssuerForOrderedByUser");
            throw;
        }
    }
}
