// <auto-generated>
//     This code was generated by TargCC Component Generator.
//     Table: GovtReport99
//     Generated: 2025-12-11 21:18:55
// </auto-generated>

import React from 'react';
import { useNavigate } from 'react-router-dom';
import ExcelJS from 'exceljs';
import { DataGrid, GridColDef, GridActionsCellItem, GridToolbarContainer, GridToolbarColumnsButton, GridToolbarDensitySelector, useGridApiRef } from '@mui/x-data-grid';
import { Button, Box, CircularProgress, Alert, TextField, Paper, MenuItem, Typography } from '@mui/material';
import { Edit as EditIcon, Delete as DeleteIcon, Add as AddIcon, FileDownload as FileDownloadIcon, Clear as ClearIcon } from '@mui/icons-material';
import { useGovtReport99s, useDeleteGovtReport99 } from '../../hooks/useGovtReport99';
import type { GovtReport99, GovtReport99Filters } from '../../types/GovtReport99.types';


export const GovtReport99List: React.FC = () => {
  const navigate = useNavigate();
  const apiRef = useGridApiRef();
  
  // Helper function to format dates as DD/MM/YYYY
  const formatDate = (date: any): string => {
    if (!date) return '';
    const d = new Date(date);
    if (isNaN(d.getTime())) return '';
    const day = d.getDate().toString().padStart(2, '0');
    const month = (d.getMonth() + 1).toString().padStart(2, '0');
    const year = d.getFullYear();
    return `${day}/${month}/${year}`;
  };
  
  const [columnFilters, setColumnFilters] = React.useState<Record<string, string>>({});
  const { data: govtReport99s, isLoading, error } = useGovtReport99s({});
  const { mutate: deleteEntity } = useDeleteGovtReport99();

  // Client-side column filters
  const filteredData = React.useMemo(() => {
    if (!govtReport99s) return govtReport99s;

    // Get active filters
    const activeFilters = Object.entries(columnFilters).filter(([_, value]) => value && value.trim() !== '');
    if (activeFilters.length === 0) return govtReport99s;

    // Apply all filters with AND logic
    return govtReport99s.filter(item => {
      return activeFilters.every(([column, filterValue]) => {
        let itemValue = item[column as keyof typeof item];
        
        // Special handling for date filtering - compare as Date objects
        if (typeof filterValue === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(filterValue)) {
          // Filter value is from date picker (YYYY-MM-DD)
          const filterDate = new Date(filterValue);
          let itemDate: Date | null = null;
          
          if (itemValue instanceof Date) {
            itemDate = itemValue;
          } else if (typeof itemValue === 'string' && /^\d{4}-\d{2}-\d{2}/.test(itemValue)) {
            itemDate = new Date(itemValue);
          }
          
          if (itemDate) {
            // Compare dates (ignore time) - same year, month, and day
            return itemDate.getFullYear() === filterDate.getFullYear() &&
                   itemDate.getMonth() === filterDate.getMonth() &&
                   itemDate.getDate() === filterDate.getDate();
          }
          return false;
        }
        
        // Convert boolean values to readable text
        if (typeof itemValue === 'boolean') {
          itemValue = itemValue ? 'true' : 'false';
        }
        
        return itemValue?.toString().toLowerCase().includes(filterValue.toLowerCase());
      });
    });
  }, [govtReport99s, columnFilters]);

  const handleClearAllFilters = () => {
    setColumnFilters({});
  };

  function CustomToolbar() {
    return (
      <GridToolbarContainer>
        <GridToolbarColumnsButton />
        <GridToolbarDensitySelector />
        <Button
          size="small"
          startIcon={<ClearIcon />}
          onClick={handleClearAllFilters}
        >
          Clear All Filters
        </Button>
      </GridToolbarContainer>
    );
  }

  const handleExportToExcel = async () => {
    // Export only the filtered data visible on screen
    const visibleRows = filteredData || [];

    if (!visibleRows || visibleRows.length === 0) {
      alert('No data to export');
      return;
    }

    // Get visible columns from DataGrid (respects column visibility)
    const visibleColumns = apiRef.current
      ? apiRef.current.getVisibleColumns().map(col => col.field).filter(field => field !== 'actions')
      : Object.keys(visibleRows[0] || {});

    // Filter data to only include visible columns
    const exportData = visibleRows.map(row => {
      const filteredRow: any = {};
      const rowAny = row as any;
      visibleColumns.forEach(col => {
        if (col in rowAny) filteredRow[col] = rowAny[col];
      });
      return filteredRow;
    });

    // Create workbook and worksheet
    const workbook = new ExcelJS.Workbook();
    const worksheet = workbook.addWorksheet('GovtReport99s');

    // Get column names from first row (only visible columns)
    const columnNames = exportData.length > 0 ? Object.keys(exportData[0]) : [];
    worksheet.columns = columnNames.map(name => ({ header: name, key: name, width: 15 }));

    // Add data rows
    exportData.forEach(row => worksheet.addRow(row));

    // Style header row
    const headerRow = worksheet.getRow(1);
    headerRow.font = { bold: true, color: { argb: 'FFFFFFFF' } };
    headerRow.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF4472C4' } };
    headerRow.alignment = { horizontal: 'center', vertical: 'middle' };
    headerRow.height = 20;

    // Auto-fit columns based on content
    worksheet.columns.forEach(column => {
      let maxLength = column.header?.length || 10;
      column.eachCell?.({ includeEmpty: false }, cell => {
        const cellLength = cell.value ? String(cell.value).length : 0;
        maxLength = Math.max(maxLength, cellLength);
      });
      column.width = Math.min(maxLength + 2, 50);
    });

    // Freeze header row
    worksheet.views = [{ state: 'frozen', ySplit: 1 }];

    // Generate Excel file and download
    const buffer = await workbook.xlsx.writeBuffer();
    const blob = new Blob([buffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `GovtReport99s_${new Date().toISOString().split('T')[0]}.xlsx`;
    link.click();
    window.URL.revokeObjectURL(url);
  };

  const columns: GridColDef<GovtReport99>[] = [
    { field: 'tableNameGovtReport99', headerName: 'TableNameGovtReport99', width: 100 },
    { field: 'id', headerName: 'Id', width: 90 },
    { field: 'govtReport00ID', headerName: 'GovtReport00ID', width: 150 },
    { field: 'reporterNumber', headerName: 'ReporterNumber', width: 150 },
    { field: 'reporterIDNumber', headerName: 'ReporterIDNumber', width: 150 },
    { field: 'reportYear', headerName: 'ReportYear', width: 150 },
    { field: 'reportNumber', headerName: 'ReportNumber', width: 150 },
    { field: 'recordType', headerName: 'RecordType', width: 150 },
    { field: 'reportMonth', headerName: 'ReportMonth', width: 150 },
    { field: 'numberOfRowsIn10', headerName: 'NumberOfRowsIn10', width: 150 },
    {
      field: 'actions',
      type: 'actions',
      headerName: 'Actions',
      width: 100,
      getActions: (params) => [
        <GridActionsCellItem
          icon={<EditIcon />}
          label="Edit"
          onClick={() => navigate(`/govtReport99s/${params.id}`)}
        />,
        <GridActionsCellItem
          icon={<DeleteIcon />}
          label="Delete"
          onClick={() => {
            if (confirm('Are you sure?')) {
              deleteEntity(params.id as number);
            }
          }}
        />,
      ],
    },
  ];


  if (isLoading) {
    return <CircularProgress />;
  }

  if (error) {
    return <Alert severity="error">Failed to load govtReport99s</Alert>;
  }

  return (
    <Box sx={{ height: 'calc(100vh - 200px)', width: '100%', display: 'flex', flexDirection: 'column' }}>
      <Box sx={{ mb: 2, display: 'flex', gap: 2 }}>
        <Button
          variant="contained"
          startIcon={<AddIcon />}
          onClick={() => navigate('/govtReport99s/new')}
        >
          Create GovtReport99
        </Button>
        <Button
          variant="outlined"
          startIcon={<FileDownloadIcon />}
          onClick={handleExportToExcel}
        >
          Export to Excel
        </Button>
      </Box>
      <Paper sx={{ p: 2, mb: 2 }}>
        <Box sx={{ display: 'flex', gap: 2, flexWrap: 'wrap', alignItems: 'center' }}>
          <TextField
            select
            label="TableNameGovtReport99"
            size="small"
            sx={{ minWidth: 120 }}
            value={columnFilters['tableNameGovtReport99'] || ''}
            onChange={(e) => setColumnFilters(prev => ({
              ...prev,
              tableNameGovtReport99: e.target.value
            }))}
          >
            <MenuItem value="">All</MenuItem>
            <MenuItem value="true">Yes</MenuItem>
            <MenuItem value="false">No</MenuItem>
          </TextField>
          <TextField
            label="Id"
            size="small"
            sx={{ minWidth: 150 }}
            value={columnFilters['id'] || ''}
            onChange={(e) => setColumnFilters(prev => ({
              ...prev,
              id: e.target.value
            }))}
          />
          <TextField
            label="GovtReport00ID"
            size="small"
            sx={{ minWidth: 150 }}
            value={columnFilters['govtReport00ID'] || ''}
            onChange={(e) => setColumnFilters(prev => ({
              ...prev,
              govtReport00ID: e.target.value
            }))}
          />
          <TextField
            label="ReporterNumber"
            size="small"
            sx={{ minWidth: 150 }}
            value={columnFilters['reporterNumber'] || ''}
            onChange={(e) => setColumnFilters(prev => ({
              ...prev,
              reporterNumber: e.target.value
            }))}
          />
          <TextField
            label="ReporterIDNumber"
            size="small"
            sx={{ minWidth: 150 }}
            value={columnFilters['reporterIDNumber'] || ''}
            onChange={(e) => setColumnFilters(prev => ({
              ...prev,
              reporterIDNumber: e.target.value
            }))}
          />
          <TextField
            label="ReportYear"
            size="small"
            sx={{ minWidth: 150 }}
            value={columnFilters['reportYear'] || ''}
            onChange={(e) => setColumnFilters(prev => ({
              ...prev,
              reportYear: e.target.value
            }))}
          />
          <TextField
            label="ReportNumber"
            size="small"
            sx={{ minWidth: 150 }}
            value={columnFilters['reportNumber'] || ''}
            onChange={(e) => setColumnFilters(prev => ({
              ...prev,
              reportNumber: e.target.value
            }))}
          />
          <TextField
            select
            label="RecordType"
            size="small"
            sx={{ minWidth: 150 }}
            value={columnFilters['recordType'] || ''}
            onChange={(e) => setColumnFilters(prev => ({
              ...prev,
              recordType: e.target.value
            }))}
          >
            <MenuItem value="">All</MenuItem>
            <MenuItem value="Active">Active</MenuItem>
            <MenuItem value="Inactive">Inactive</MenuItem>
            <MenuItem value="Pending">Pending</MenuItem>
          </TextField>
          <TextField
            label="ReportMonth"
            size="small"
            sx={{ minWidth: 150 }}
            value={columnFilters['reportMonth'] || ''}
            onChange={(e) => setColumnFilters(prev => ({
              ...prev,
              reportMonth: e.target.value
            }))}
          />
          <TextField
            label="NumberOfRowsIn10"
            size="small"
            sx={{ minWidth: 150 }}
            value={columnFilters['numberOfRowsIn10'] || ''}
            onChange={(e) => setColumnFilters(prev => ({
              ...prev,
              numberOfRowsIn10: e.target.value
            }))}
          />
          <Button
            variant="outlined"
            size="small"
            onClick={handleClearAllFilters}
          >
            Clear
          </Button>
          <Box sx={{ ml: 'auto', display: 'flex', alignItems: 'center' }}>
            <Typography variant="body2" color="text.secondary">
              Showing {filteredData?.length || 0} of {govtReport99s?.length || 0} rows
            </Typography>
          </Box>
        </Box>
      </Paper>

      <Box sx={{ flex: 1, minHeight: 0 }}>
        <DataGrid
          apiRef={apiRef}
          rows={filteredData || []}
          columns={columns}
          getRowId={(row) => row.id}
          slots={{
            toolbar: CustomToolbar,
          }}
          initialState={{
            pagination: { paginationModel: { pageSize: 10 } },
          }}
          pageSizeOptions={[5, 10, 25, 100]}
          checkboxSelection
          disableRowSelectionOnClick
        />
      </Box>
    </Box>
  );
};

