// <auto-generated>
//     This code was generated by TargCC
//     Generated for: vwReportDistributorObligoBalance (Validator)
//     Generation date: 2025-12-16 21:06:07
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using FluentValidation;

namespace UpayCard.RiskManagement.Application.Features.VwReportDistributorObligoBalances.Commands;

/// <summary>
/// Validator for CreateVwReportDistributorObligoBalanceCommand.
/// </summary>
public class CreateVwReportDistributorObligoBalanceValidator : AbstractValidator<CreateVwReportDistributorObligoBalanceCommand>
{
    /// <summary>
    /// Initializes a new instance of the <see cref="CreateVwReportDistributorObligoBalanceValidator"/> class.
    /// </summary>
    public CreateVwReportDistributorObligoBalanceValidator()
    {
    }
}
