// <auto-generated>
//     This code was generated by TargCC
//     Generated for: ccvwComboList_RiskEvent (Handler)
//     Generation date: 2025-12-15 22:18:50
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using MediatR;
using Microsoft.Extensions.Logging;
using TargCC.Application.Common.Models;
using TargCC.Domain.Entities;
using TargCC.Domain.Interfaces;

namespace TargCC.Application.Features.ccvwComboList_RiskEvents.Commands;

/// <summary>
/// Handles the CreateCcvwComboListRiskEventCommand request.
/// </summary>
public class CreateCcvwComboListRiskEventHandler : IRequestHandler<CreateCcvwComboListRiskEventCommand, Result<int>>
{
    private readonly IccvwComboList_RiskEventRepository _repository;
    private readonly ILogger<CreateCcvwComboListRiskEventHandler> _logger;

    /// <summary>
    /// Initializes a new instance of the <see cref="CreateCcvwComboListRiskEventHandler"/> class.
    /// </summary>
    public CreateCcvwComboListRiskEventHandler(
        IccvwComboList_RiskEventRepository repository,
        ILogger<CreateCcvwComboListRiskEventHandler> logger)
    {
        _repository = repository ?? throw new ArgumentNullException(nameof(repository));
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
    }

    /// <inheritdoc/>
    public async Task<Result<int>> Handle(CreateCcvwComboListRiskEventCommand request, CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(request);

        _logger.LogDebug("Creating new ccvwComboList_RiskEvent");

        try
        {
            var entity = new ccvwComboList_RiskEvent
            {
                TextNS = request.TextNS,
                Text = request.Text
            };

            await _repository.AddAsync(entity, cancellationToken);

            _logger.LogInformation("ccvwComboList_RiskEvent created successfully with ID: {Id}", entity.Id);

            return Result<int>.Success(entity.Id);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error creating ccvwComboList_RiskEvent");
            throw;
        }
    }
}
