// <auto-generated>
//     This code was generated by TargCC
//     Generated for: ccvwComboList_MCCBTransactionForCustomer (Handler)
//     Generation date: 2025-12-17 08:24:01
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using MediatR;
using Microsoft.Extensions.Logging;
using UpayCard.RiskManagement.Application.Common.Models;
using UpayCard.RiskManagement.Domain.Entities;
using UpayCard.RiskManagement.Domain.Interfaces;

namespace UpayCard.RiskManagement.Application.Features.CcvwComboListMCCBTransactionForCustomers.Commands;

/// <summary>
/// Handles the CreateCcvwComboListMCCBTransactionForCustomerCommand request.
/// </summary>
public class CreateCcvwComboListMCCBTransactionForCustomerHandler : IRequestHandler<CreateCcvwComboListMCCBTransactionForCustomerCommand, Result<long>>
{
    private readonly ICcvwComboListMCCBTransactionForCustomerRepository _repository;
    private readonly ILogger<CreateCcvwComboListMCCBTransactionForCustomerHandler> _logger;

    /// <summary>
    /// Initializes a new instance of the <see cref="CreateCcvwComboListMCCBTransactionForCustomerHandler"/> class.
    /// </summary>
    public CreateCcvwComboListMCCBTransactionForCustomerHandler(
        ICcvwComboListMCCBTransactionForCustomerRepository repository,
        ILogger<CreateCcvwComboListMCCBTransactionForCustomerHandler> logger)
    {
        _repository = repository ?? throw new ArgumentNullException(nameof(repository));
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
    }

    /// <inheritdoc/>
    public async Task<Result<long>> Handle(CreateCcvwComboListMCCBTransactionForCustomerCommand request, CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(request);

        _logger.LogDebug("Creating new ccvwComboList_MCCBTransactionForCustomer");

        try
        {
            var entity = new CcvwComboListMCCBTransactionForCustomer
            {
                ParentID = request.ParentID,
                TextNS = request.TextNS,
                Text = request.Text
            };

            await _repository.AddAsync(entity, cancellationToken);

            _logger.LogInformation("ccvwComboList_MCCBTransactionForCustomer created successfully with ID: {Id}", entity.ID);

            return Result<long>.Success(entity.ID);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error creating ccvwComboList_MCCBTransactionForCustomer");
            throw;
        }
    }
}
