// <auto-generated>
//     This code was generated by TargCC Component Generator.
//     Table: GovtReportDistributor
//     Generated: 2025-12-17 13:13:00
// </auto-generated>

import React from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { Box, Typography, Button, CircularProgress, Alert, Card as MuiCard, CardContent, Grid } from '@mui/material';
import { Edit as EditIcon, Delete as DeleteIcon, ArrowBack as ArrowBackIcon } from '@mui/icons-material';
import { useGovtReportDistributor, useDeleteGovtReportDistributor } from '../../hooks/useGovtReportDistributor';


export const GovtReportDistributorDetail: React.FC = () => {
  const navigate = useNavigate();
  const { id } = useParams<{ id: string }>();
  const { data: entity, isLoading, error } = useGovtReportDistributor(id ? parseInt(id, 10) : null);
  const { mutate: deleteEntity } = useDeleteGovtReportDistributor();

  const handleDelete = () => {
    if (confirm('Are you sure you want to delete this item?')) {
      deleteEntity(parseInt(id!, 10), {
        onSuccess: () => navigate('/govtReportDistributors'),
      });
    }
  };

  if (isLoading) {
    return <CircularProgress />;
  }

  if (error || !entity) {
    return <Alert severity="error">Failed to load govtReportDistributor</Alert>;
  }

  return (
    <Box sx={{ maxWidth: 800 }}>
      <Box sx={{ mb: 2, display: 'flex', gap: 2 }}>
        <Button
          variant="outlined"
          startIcon={<ArrowBackIcon />}
          onClick={() => navigate('/govtReportDistributors')}
        >
          Back
        </Button>
        <Button
          variant="contained"
          startIcon={<EditIcon />}
          onClick={() => navigate(`/govtReportDistributors/${id}/edit`)}
        >
          Edit
        </Button>
        <Button
          variant="outlined"
          color="error"
          startIcon={<DeleteIcon />}
          onClick={handleDelete}
        >
          Delete
        </Button>
      </Box>

      <MuiCard>
        <CardContent>
          <Typography variant="h5" component="h2" gutterBottom>
            GovtReportDistributor Details
          </Typography>
      <Grid container spacing={2}>
        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            TableNameGovtReportDistributor
          </Typography>
          <Typography variant="body1">
            {entity.tableNameGovtReportDistributor ? 'Yes' : 'No'}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            Id
          </Typography>
          <Typography variant="body1">
            {entity.id}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            DistributorID
          </Typography>
          <Typography variant="body1">
            {entity.distributorID}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            ReportFullName
          </Typography>
          <Typography variant="body1">
            {entity.reportFullName}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            ReportIdentityNo
          </Typography>
          <Typography variant="body1">
            {entity.reportIdentityNo}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            ReportBirthOrIncorporationDate
          </Typography>
          <Typography variant="body1">
            {(entity.reportBirthOrIncorporationDate ? new Date(entity.reportBirthOrIncorporationDate).toLocaleDateString() : 'N/A')}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            LkpReportGender
          </Typography>
          <Typography variant="body1">
            {entity.lkpReportGender}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            ReportTelephoneAreaCode
          </Typography>
          <Typography variant="body1">
            {entity.reportTelephoneAreaCode}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            ReportTelephonePhoneNumber
          </Typography>
          <Typography variant="body1">
            {entity.reportTelephonePhoneNumber}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            ReportFaxOrEmail
          </Typography>
          <Typography variant="body1">
            {entity.reportFaxOrEmail}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            ReportAddress01Street
          </Typography>
          <Typography variant="body1">
            {entity.reportAddress01Street}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            ReportAddress01House
          </Typography>
          <Typography variant="body1">
            {entity.reportAddress01House}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            ReportAddress01City
          </Typography>
          <Typography variant="body1">
            {entity.reportAddress01City}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            ReportAddress01Zip
          </Typography>
          <Typography variant="body1">
            {entity.reportAddress01Zip}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            ReportFirstName
          </Typography>
          <Typography variant="body1">
            {entity.reportFirstName}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            ReportSurnameOrCompanyname
          </Typography>
          <Typography variant="body1">
            {entity.reportSurnameOrCompanyname}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            ReportCellPhoneAreaCode
          </Typography>
          <Typography variant="body1">
            {entity.reportCellPhoneAreaCode}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            ReportCellPhoneNumber
          </Typography>
          <Typography variant="body1">
            {entity.reportCellPhoneNumber}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            ReportStreetCode
          </Typography>
          <Typography variant="body1">
            {entity.reportStreetCode}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            ReportCityCode
          </Typography>
          <Typography variant="body1">
            {entity.reportCityCode}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            ReportS01FullName
          </Typography>
          <Typography variant="body1">
            {entity.reportS01FullName}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            ReportS01IdentityNo
          </Typography>
          <Typography variant="body1">
            {entity.reportS01IdentityNo}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            ReportS01BirthOrIncorporationDate
          </Typography>
          <Typography variant="body1">
            {(entity.reportS01BirthOrIncorporationDate ? new Date(entity.reportS01BirthOrIncorporationDate).toLocaleDateString() : 'N/A')}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            LkpReportS01GenderReportGender
          </Typography>
          <Typography variant="body1">
            {entity.lkpReportS01GenderReportGender}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            ReportS01TelephoneAreaCode
          </Typography>
          <Typography variant="body1">
            {entity.reportS01TelephoneAreaCode}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            ReportS01TelephonePhoneNumber
          </Typography>
          <Typography variant="body1">
            {entity.reportS01TelephonePhoneNumber}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            ReportS01FaxOrEmail
          </Typography>
          <Typography variant="body1">
            {entity.reportS01FaxOrEmail}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            ReportS01Address01Street
          </Typography>
          <Typography variant="body1">
            {entity.reportS01Address01Street}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            ReportS01Address01House
          </Typography>
          <Typography variant="body1">
            {entity.reportS01Address01House}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            ReportS01Address01City
          </Typography>
          <Typography variant="body1">
            {entity.reportS01Address01City}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            ReportS01Address01Zip
          </Typography>
          <Typography variant="body1">
            {entity.reportS01Address01Zip}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            ReportS01FirstName
          </Typography>
          <Typography variant="body1">
            {entity.reportS01FirstName}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            ReportS01SurnameOrCompanyname
          </Typography>
          <Typography variant="body1">
            {entity.reportS01SurnameOrCompanyname}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            ReportS01CellPhoneAreaCode
          </Typography>
          <Typography variant="body1">
            {entity.reportS01CellPhoneAreaCode}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            ReportS01CellPhoneNumber
          </Typography>
          <Typography variant="body1">
            {entity.reportS01CellPhoneNumber}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            ReportS01StreetCode
          </Typography>
          <Typography variant="body1">
            {entity.reportS01StreetCode}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            ReportS01CityCode
          </Typography>
          <Typography variant="body1">
            {entity.reportS01CityCode}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            ReportS02FullName
          </Typography>
          <Typography variant="body1">
            {entity.reportS02FullName}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            ReportS02IdentityNo
          </Typography>
          <Typography variant="body1">
            {entity.reportS02IdentityNo}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            ReportS02BirthOrIncorporationDate
          </Typography>
          <Typography variant="body1">
            {(entity.reportS02BirthOrIncorporationDate ? new Date(entity.reportS02BirthOrIncorporationDate).toLocaleDateString() : 'N/A')}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            LkpReportS02GenderReportGender
          </Typography>
          <Typography variant="body1">
            {entity.lkpReportS02GenderReportGender}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            ReportS02TelephoneAreaCode
          </Typography>
          <Typography variant="body1">
            {entity.reportS02TelephoneAreaCode}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            ReportS02TelephonePhoneNumber
          </Typography>
          <Typography variant="body1">
            {entity.reportS02TelephonePhoneNumber}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            ReportS02FaxOrEmail
          </Typography>
          <Typography variant="body1">
            {entity.reportS02FaxOrEmail}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            ReportS02Address01Street
          </Typography>
          <Typography variant="body1">
            {entity.reportS02Address01Street}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            ReportS02Address01House
          </Typography>
          <Typography variant="body1">
            {entity.reportS02Address01House}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            ReportS02Address01City
          </Typography>
          <Typography variant="body1">
            {entity.reportS02Address01City}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            ReportS02Address01Zip
          </Typography>
          <Typography variant="body1">
            {entity.reportS02Address01Zip}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            ReportS02FirstName
          </Typography>
          <Typography variant="body1">
            {entity.reportS02FirstName}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            ReportS02SurnameOrCompanyname
          </Typography>
          <Typography variant="body1">
            {entity.reportS02SurnameOrCompanyname}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            ReportS02CellPhoneAreaCode
          </Typography>
          <Typography variant="body1">
            {entity.reportS02CellPhoneAreaCode}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            ReportS02CellPhoneNumber
          </Typography>
          <Typography variant="body1">
            {entity.reportS02CellPhoneNumber}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            ReportS02StreetCode
          </Typography>
          <Typography variant="body1">
            {entity.reportS02StreetCode}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            ReportS02CityCode
          </Typography>
          <Typography variant="body1">
            {entity.reportS02CityCode}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            EnmReportS01EntityTypeGovtReportEntityType
          </Typography>
          <Typography variant="body1">
            {entity.enmReportS01EntityTypeGovtReportEntityType}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            EnmReportS02EntityTypeGovtReportEntityType
          </Typography>
          <Typography variant="body1">
            {entity.enmReportS02EntityTypeGovtReportEntityType}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            DeletedBy
          </Typography>
          <Typography variant="body1">
            {entity.deletedBy}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            DeletedOn
          </Typography>
          <Typography variant="body1">
            {(entity.deletedOn ? new Date(entity.deletedOn).toLocaleDateString() : 'N/A')}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            UpdatingLoginID
          </Typography>
          <Typography variant="body1">
            {entity.updatingLoginID}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            LkpIdentityNoType
          </Typography>
          <Typography variant="body1">
            {entity.lkpIdentityNoType}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            IsPublicBenefitCompany
          </Typography>
          <Typography variant="body1">
            {entity.isPublicBenefitCompany ? 'Yes' : 'No'}
          </Typography>
        </Grid>

      </Grid>

        </CardContent>
      </MuiCard>
    </Box>
  );
};

