// <auto-generated>
//     This code was generated by TargCC
//     Generated for: ccvwComboList_Country (Handler)
//     Generation date: 2025-12-17 08:16:14
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using MediatR;
using Microsoft.Extensions.Logging;
using UpayCard.RiskManagement.Application.Common.Models;
using UpayCard.RiskManagement.Domain.Entities;
using UpayCard.RiskManagement.Domain.Interfaces;

namespace UpayCard.RiskManagement.Application.Features.CcvwComboListCountries.Commands;

/// <summary>
/// Handles the CreateCcvwComboListCountryCommand request.
/// </summary>
public class CreateCcvwComboListCountryHandler : IRequestHandler<CreateCcvwComboListCountryCommand, Result<long>>
{
    private readonly ICcvwComboListCountryRepository _repository;
    private readonly ILogger<CreateCcvwComboListCountryHandler> _logger;

    /// <summary>
    /// Initializes a new instance of the <see cref="CreateCcvwComboListCountryHandler"/> class.
    /// </summary>
    public CreateCcvwComboListCountryHandler(
        ICcvwComboListCountryRepository repository,
        ILogger<CreateCcvwComboListCountryHandler> logger)
    {
        _repository = repository ?? throw new ArgumentNullException(nameof(repository));
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
    }

    /// <inheritdoc/>
    public async Task<Result<long>> Handle(CreateCcvwComboListCountryCommand request, CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(request);

        _logger.LogDebug("Creating new ccvwComboList_Country");

        try
        {
            var entity = new CcvwComboListCountry
            {
                ISO3166Alpha2 = request.ISO3166Alpha2,
                TextNS = request.TextNS,
                Text = request.Text
            };

            await _repository.AddAsync(entity, cancellationToken);

            _logger.LogInformation("ccvwComboList_Country created successfully with ID: {Id}", entity.ID);

            return Result<long>.Success(entity.ID);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error creating ccvwComboList_Country");
            throw;
        }
    }
}
