// <auto-generated>
//     This code was generated by TargCC
//     Generated for: Task (Handler)
//     Generation date: 2025-12-16 21:06:07
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using MediatR;
using Microsoft.Extensions.Logging;
using UpayCard.RiskManagement.Application.Common.Models;
using UpayCard.RiskManagement.Domain.Entities;
using UpayCard.RiskManagement.Domain.Interfaces;

namespace UpayCard.RiskManagement.Application.Features.Tasks.Commands;

/// <summary>
/// Handles the CreateTaskCommand request.
/// </summary>
public class CreateTaskHandler : IRequestHandler<CreateTaskCommand, Result<int>>
{
    private readonly ITaskRepository _repository;
    private readonly ILogger<CreateTaskHandler> _logger;

    /// <summary>
    /// Initializes a new instance of the <see cref="CreateTaskHandler"/> class.
    /// </summary>
    public CreateTaskHandler(
        ITaskRepository repository,
        ILogger<CreateTaskHandler> logger)
    {
        _repository = repository ?? throw new ArgumentNullException(nameof(repository));
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
    }

    /// <inheritdoc/>
    public async Task<Result<int>> Handle(CreateTaskCommand request, CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(request);

        _logger.LogDebug("Creating new Task");

        try
        {
            var entity = new Task
            {
                TableName_Task = request.TableName_Task,
                CustomerID = request.CustomerID,
                enmTask = request.enmTask,
                enmStatus = request.enmStatus,
                Description = request.Description,
                HandlerComments = request.HandlerComments,
                ReferenceTable = request.ReferenceTable,
                ReferenceTableID = request.ReferenceTableID,
                AddedBy = request.AddedBy,
                AddedOn = request.AddedOn,
                ChangedBy = request.ChangedBy,
                ChangedOn = request.ChangedOn,
                DeletedBy = request.DeletedBy,
                DeletedOn = request.DeletedOn,
                UpdatingLoginID = request.UpdatingLoginID,
                HandledByUserID = request.HandledByUserID,
                WhenStatusChanged = request.WhenStatusChanged
            };

            await _repository.AddAsync(entity, cancellationToken);

            _logger.LogInformation("Task created successfully with ID: {Id}", entity.Id);

            return Result<int>.Success(entity.Id);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error creating Task");
            throw;
        }
    }
}
