// <auto-generated>
//     This code was generated by TargCC
//     Generated for: ccvwComboList_MCCBTransaction (Query)
//     Generation date: 2025-12-17 09:34:36
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using MediatR;
using UpayCard.RiskManagement.Application.Common.Models;
using UpayCard.RiskManagement.Application.DTOs;
using UpayCard.RiskManagement.Domain.Common;

namespace UpayCard.RiskManagement.Application.Features.ccvwComboList_MCCBTransactions.Queries;

/// <summary>
/// Query to retrieve all ccvwComboList_MCCBTransactions with server-side filtering, sorting, and pagination.
/// </summary>
public record GetCcvwComboListMCCBTransactionsQuery : IRequest<Result<PagedResult<CcvwComboListMCCBTransactionDto>>>
{
    /// <summary>
    /// Gets or initializes the filters to apply.
    /// </summary>
    public CcvwComboListMCCBTransactionFilters? Filters { get; init; }

    /// <summary>
    /// Gets or initializes the page number (1-based). Default is 1.
    /// </summary>
    public int Page { get; init; } = 1;

    /// <summary>
    /// Gets or initializes the page size. Default is 100.
    /// </summary>
    public int PageSize { get; init; } = 100;

    /// <summary>
    /// Gets or initializes the field to sort by. Default is "Id".
    /// </summary>
    public string? SortBy { get; init; } = "Id";

    /// <summary>
    /// Gets or initializes the sort direction. Default is "asc".
    /// </summary>
    public string SortDirection { get; init; } = "asc";
}

/// <summary>
/// CcvwComboListMCCBTransaction filters class for filtering queries.
/// </summary>
public class CcvwComboListMCCBTransactionFilters
{
    // TODO: Add filter properties based on table columns
    // Example: public string? Name { get; set; }
}
