// <copyright file="EntityGeneratorTests.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

namespace TargCC.Core.Tests.Unit.Generators.Entities;

using Microsoft.Extensions.Logging;
using Moq;
using TargCC.Core.Generators.Entities;
using TargCC.Core.Interfaces.Models;
using TargCC.Core.Tests.TestHelpers;
using Xunit;

/// <summary>
/// Unit tests for EntityGenerator class.
/// Tests complete entity class generation orchestration.
/// </summary>
public class EntityGeneratorTests
{
    private readonly Mock<ILogger<EntityGenerator>> _mockLogger;
    private readonly EntityGenerator _generator;

    public EntityGeneratorTests()
    {
        _mockLogger = new Mock<ILogger<EntityGenerator>>();
        _generator = new EntityGenerator(_mockLogger.Object);
    }

    #region GenerateAsync - Basic Tests

    [Fact]
    public async Task GenerateAsync_SimpleTable_GeneratesCompleteEntityClass()
    {
        // Arrange
        var table = new TableBuilder()
            .WithName("Customer")
            .WithColumns(
                ColumnBuilder.CreateIdColumn(),
                ColumnBuilder.CreateNameColumn(),
                new ColumnBuilder()
                    .WithName("Email")
                    .AsNvarchar(100)
                    .NotNullable()
                    .Build())
            .WithPrimaryKey("ID")
            .Build();

        var schema = new DatabaseSchemaBuilder()
            .WithTable(table)
            .Build();

        // Act
        var result = await _generator.GenerateAsync(table, schema, "TestNamespace");

        // Assert
        Assert.NotNull(result);
        Assert.Contains("namespace TestNamespace", result);
        Assert.Contains("public partial class Customer", result);
        Assert.Contains("public int ID", result);
        Assert.Contains("public string Name", result);
        Assert.Contains("public string Email", result);
    }

    [Fact]
    public async Task GenerateAsync_IncludesAutoGeneratedHeader()
    {
        // Arrange
        var table = TableBuilder.CreateSimpleTable();
        var schema = new DatabaseSchemaBuilder()
            .WithTable(table)
            .Build();

        // Act
        var result = await _generator.GenerateAsync(table, schema, "TestNamespace");

        // Assert
        Assert.Contains("// <auto-generated>", result);
        Assert.Contains("This code was generated by TargCC.Core.Generators", result);
        Assert.Contains("// </auto-generated>", result);
    }

    [Fact]
    public async Task GenerateAsync_IncludesRequiredUsings()
    {
        // Arrange
        var table = TableBuilder.CreateSimpleTable();
        var schema = new DatabaseSchemaBuilder()
            .WithTable(table)
            .Build();

        // Act
        var result = await _generator.GenerateAsync(table, schema, "TestNamespace");

        // Assert
        Assert.Contains("using System;", result);
        Assert.Contains("using System.Collections.Generic;", result);
        Assert.Contains("using System.ComponentModel.DataAnnotations;", result);
        Assert.Contains("using System.ComponentModel.DataAnnotations.Schema;", result);
    }

    [Fact]
    public async Task GenerateAsync_IncludesClassDocumentation()
    {
        // Arrange
        var table = TableBuilder.CreateSimpleTable("Customer");
        var schema = new DatabaseSchemaBuilder()
            .WithTable(table)
            .Build();

        // Act
        var result = await _generator.GenerateAsync(table, schema, "TestNamespace");

        // Assert
        Assert.Contains("/// <summary>", result);
        Assert.Contains("Entity class for Customer table", result);
        Assert.Contains("/// </summary>", result);
    }

    [Fact]
    public async Task GenerateAsync_IncludesTableAttribute()
    {
        // Arrange
        var table = TableBuilder.CreateSimpleTable("Customer");
        var schema = new DatabaseSchemaBuilder()
            .WithTable(table)
            .Build();

        // Act
        var result = await _generator.GenerateAsync(table, schema, "TestNamespace");

        // Assert
        Assert.Contains("[Table(\"Customer\")]", result);
    }

    [Fact]
    public async Task GenerateAsync_NullTable_ThrowsArgumentNullException()
    {
        // Arrange
        var schema = new DatabaseSchemaBuilder().Build();

        // Act & Assert
        await Assert.ThrowsAsync<ArgumentNullException>(() =>
            _generator.GenerateAsync(null!, schema, "TestNamespace"));
    }

    [Fact]
    public async Task GenerateAsync_NullSchema_ThrowsArgumentNullException()
    {
        // Arrange
        var table = TableBuilder.CreateSimpleTable();

        // Act & Assert
        await Assert.ThrowsAsync<ArgumentNullException>(() =>
            _generator.GenerateAsync(table, null!, "TestNamespace"));
    }

    [Fact]
    public async Task GenerateAsync_NullNamespace_ThrowsArgumentNullException()
    {
        // Arrange
        var table = TableBuilder.CreateSimpleTable();
        var schema = new DatabaseSchemaBuilder().Build();

        // Act & Assert
        var ex = await Assert.ThrowsAsync<ArgumentNullException>(() =>
            _generator.GenerateAsync(table, schema, null!));
        Assert.NotNull(ex);
    }

    [Fact]
    public async Task GenerateAsync_EmptyNamespace_ThrowsArgumentException()
    {
        // Arrange
        var table = TableBuilder.CreateSimpleTable();
        var schema = new DatabaseSchemaBuilder().Build();

        // Act & Assert
        var ex = await Assert.ThrowsAsync<ArgumentException>(() =>
            _generator.GenerateAsync(table, schema, string.Empty));
        Assert.NotNull(ex);
    }

    [Fact]
    public async Task GenerateAsync_WhiteSpaceNamespace_ThrowsArgumentException()
    {
        // Arrange
        var table = TableBuilder.CreateSimpleTable();
        var schema = new DatabaseSchemaBuilder().Build();

        // Act & Assert
        var ex = await Assert.ThrowsAsync<ArgumentException>(() =>
            _generator.GenerateAsync(table, schema, "   "));
        Assert.NotNull(ex);
    }

    #endregion

    #region GenerateAsync - Properties

    [Fact]
    public async Task GenerateAsync_IncludesAllProperties()
    {
        // Arrange
        var table = new TableBuilder()
            .WithName("Customer")
            .WithColumns(
                ColumnBuilder.CreateIdColumn(),
                ColumnBuilder.CreateNameColumn(),
                new ColumnBuilder()
                    .WithName("Email")
                    .AsNvarchar(100)
                    .Build(),
                new ColumnBuilder()
                    .WithName("Phone")
                    .AsNvarchar(20)
                    .Build())
            .WithPrimaryKey("ID")
            .Build();

        var schema = new DatabaseSchemaBuilder()
            .WithTable(table)
            .Build();

        // Act
        var result = await _generator.GenerateAsync(table, schema, "TestNamespace");

        // Assert
        Assert.Contains("public int ID", result);
        Assert.Contains("public string Name", result);
        Assert.Contains("public string Email", result);
        Assert.Contains("public string Phone", result);
    }

    [Fact]
    public async Task GenerateAsync_PrefixedColumns_HandledCorrectly()
    {
        // Arrange
        var table = new TableBuilder()
            .WithName("User")
            .WithColumns(
                ColumnBuilder.CreateIdColumn(),
                new ColumnBuilder()
                    .WithName("eno_Password")
                    .WithPrefix(ColumnPrefix.OneWayEncryption)
                    .AsVarchar(64)
                    .Build(),
                new ColumnBuilder()
                    .WithName("lkp_Status")
                    .WithPrefix(ColumnPrefix.Lookup)
                    .AsVarchar(50)
                    .Build())
            .WithPrimaryKey("ID")
            .Build();

        var schema = new DatabaseSchemaBuilder()
            .WithTable(table)
            .Build();

        // Act
        var result = await _generator.GenerateAsync(table, schema, "TestNamespace");

        // Assert
        Assert.Contains("PasswordHashed", result);
        Assert.Contains("Status", result);
        Assert.Contains("StatusText", result);
    }

    #endregion

    #region GenerateAsync - Methods

    [Fact]
    public async Task GenerateAsync_IncludesConstructor()
    {
        // Arrange
        var table = TableBuilder.CreateSimpleTable("Customer");
        var schema = new DatabaseSchemaBuilder()
            .WithTable(table)
            .Build();

        // Act
        var result = await _generator.GenerateAsync(table, schema, "TestNamespace");

        // Assert
        Assert.Contains("public Customer()", result);
    }

    [Fact]
    public async Task GenerateAsync_IncludesToString()
    {
        // Arrange
        var table = TableBuilder.CreateSimpleTable("Customer");
        var schema = new DatabaseSchemaBuilder()
            .WithTable(table)
            .Build();

        // Act
        var result = await _generator.GenerateAsync(table, schema, "TestNamespace");

        // Assert
        Assert.Contains("public override string ToString()", result);
    }

    [Fact]
    public async Task GenerateAsync_IncludesClone()
    {
        // Arrange
        var table = TableBuilder.CreateSimpleTable("Customer");
        var schema = new DatabaseSchemaBuilder()
            .WithTable(table)
            .Build();

        // Act
        var result = await _generator.GenerateAsync(table, schema, "TestNamespace");

        // Assert
        Assert.Contains("public Customer Clone()", result);
    }

    [Fact]
    public async Task GenerateAsync_IncludesEquals()
    {
        // Arrange
        var table = TableBuilder.CreateSimpleTable("Customer");
        var schema = new DatabaseSchemaBuilder()
            .WithTable(table)
            .Build();

        // Act
        var result = await _generator.GenerateAsync(table, schema, "TestNamespace");

        // Assert
        Assert.Contains("public override bool Equals(object obj)", result);
    }

    [Fact]
    public async Task GenerateAsync_IncludesGetHashCode()
    {
        // Arrange
        var table = TableBuilder.CreateSimpleTable("Customer");
        var schema = new DatabaseSchemaBuilder()
            .WithTable(table)
            .Build();

        // Act
        var result = await _generator.GenerateAsync(table, schema, "TestNamespace");

        // Assert
        Assert.Contains("public override int GetHashCode()", result);
    }

    #endregion

    #region GenerateAsync - Relationships

    [Fact]
    public async Task GenerateAsync_WithRelationships_IncludesNavigationProperties()
    {
        // Arrange
        var customerTable = new TableBuilder()
            .WithName("Customer")
            .WithIdColumn()
            .Build();

        var orderTable = new TableBuilder()
            .WithName("Order")
            .WithIdColumn()
            .AddColumn(ColumnBuilder.CreateForeignKeyColumn("CustomerID"))
            .Build();

        var relationship = new Relationship
        {
            Name = "FK_Order_Customer",
            ParentTable = "Customer",
            ParentColumn = "ID",
            ChildTable = "Order",
            ChildColumn = "CustomerID",
        };

        customerTable.Relationships = new List<Relationship> { relationship };

        var schema = new DatabaseSchemaBuilder()
            .WithTable(customerTable)
            .WithTable(orderTable)
            .Build();

        // Act
        var result = await _generator.GenerateAsync(customerTable, schema, "TestNamespace");

        // Assert
        Assert.Contains("public virtual ICollection<Order> Orders", result);
    }

    #endregion

    #region GenerateAllAsync Tests

    [Fact]
    public async Task GenerateAllAsync_MultipleTables_GeneratesAllEntities()
    {
        // Arrange
        var customerTable = new TableBuilder()
            .WithName("Customer")
            .WithIdColumn()
            .Build();

        var orderTable = new TableBuilder()
            .WithName("Order")
            .WithIdColumn()
            .Build();

        var schema = new DatabaseSchemaBuilder()
            .WithTable(customerTable)
            .WithTable(orderTable)
            .Build();

        // Act
        var result = await _generator.GenerateAllAsync(schema, "TestNamespace");

        // Assert
        Assert.NotNull(result);
        Assert.Equal(2, result.Count);
        Assert.Contains("Customer", result.Keys);
        Assert.Contains("Order", result.Keys);

        Assert.Contains("public partial class Customer", result["Customer"]);
        Assert.Contains("public partial class Order", result["Order"]);
    }

    [Fact]
    public async Task GenerateAllAsync_EmptySchema_ReturnsEmptyDictionary()
    {
        // Arrange
        var schema = new DatabaseSchemaBuilder().Build();

        // Act
        var result = await _generator.GenerateAllAsync(schema, "TestNamespace");

        // Assert
        Assert.NotNull(result);
        Assert.Empty(result);
    }

    [Fact]
    public async Task GenerateAllAsync_NullSchema_ThrowsArgumentNullException()
    {
        // Act & Assert
        await Assert.ThrowsAsync<ArgumentNullException>(() =>
            _generator.GenerateAllAsync(null!, "TestNamespace"));
    }

    [Fact]
    public async Task GenerateAllAsync_NullNamespace_ThrowsArgumentNullException()
    {
        // Arrange
        var schema = new DatabaseSchemaBuilder().Build();

        // Act & Assert
        var ex = await Assert.ThrowsAsync<ArgumentNullException>(() =>
            _generator.GenerateAllAsync(schema, null!));
        Assert.NotNull(ex);
    }

    [Fact]
    public async Task GenerateAllAsync_EmptyNamespace_ThrowsArgumentException()
    {
        // Arrange
        var schema = new DatabaseSchemaBuilder().Build();

        // Act & Assert
        var ex = await Assert.ThrowsAsync<ArgumentException>(() =>
            _generator.GenerateAllAsync(schema, string.Empty));
        Assert.NotNull(ex);
    }

    [Fact]
    public async Task GenerateAllAsync_WhiteSpaceNamespace_ThrowsArgumentException()
    {
        // Arrange
        var schema = new DatabaseSchemaBuilder().Build();

        // Act & Assert
        var ex = await Assert.ThrowsAsync<ArgumentException>(() =>
            _generator.GenerateAllAsync(schema, "   "));
        Assert.NotNull(ex);
    }

    #endregion

    #region Integration Tests

    [Fact]
    public async Task GenerateAsync_ComplexEntity_GeneratesAllComponents()
    {
        // Arrange
        var table = new TableBuilder()
            .WithName("Customer")
            .WithColumns(
                ColumnBuilder.CreateIdColumn(),
                ColumnBuilder.CreateNameColumn(),
                new ColumnBuilder()
                    .WithName("Email")
                    .AsNvarchar(100)
                    .NotNullable()
                    .Build(),
                new ColumnBuilder()
                    .WithName("eno_Password")
                    .WithPrefix(ColumnPrefix.OneWayEncryption)
                    .AsVarchar(64)
                    .Build(),
                new ColumnBuilder()
                    .WithName("lkp_Status")
                    .WithPrefix(ColumnPrefix.Lookup)
                    .AsVarchar(50)
                    .Build(),
                new ColumnBuilder()
                    .WithName("agg_OrderCount")
                    .WithPrefix(ColumnPrefix.Aggregate)
                    .AsInt()
                    .Build(),
                new ColumnBuilder()
                    .WithName("AddedOn")
                    .AsDateTime()
                    .Build())
            .WithPrimaryKey("ID")
            .Build();

        var schema = new DatabaseSchemaBuilder()
            .WithTable(table)
            .Build();

        // Act
        var result = await _generator.GenerateAsync(table, schema, "TestNamespace");

        // Assert - File structure
        Assert.Contains("// <auto-generated>", result);
        Assert.Contains("namespace TestNamespace", result);

        // Assert - Class definition
        Assert.Contains("public partial class Customer", result);

        // Assert - Properties
        Assert.Contains("public int ID", result);
        Assert.Contains("public string Name", result);
        Assert.Contains("public string Email", result);
        Assert.Contains("PasswordHashed", result);
        Assert.Contains("Status", result);
        Assert.Contains("StatusText", result);
        Assert.Contains("OrderCountAggregate", result);

        // Assert - Methods
        Assert.Contains("public Customer()", result);
        Assert.Contains("public override string ToString()", result);
        Assert.Contains("public Customer Clone()", result);
        Assert.Contains("public override bool Equals(object obj)", result);
        Assert.Contains("public override int GetHashCode()", result);

        // Assert - Helper methods
        Assert.Contains("SetPassword", result);
    }

    #endregion
}
