// <copyright file="EntityConfigurationGeneratorTests.cs" company="Doron">
// Copyright (c) Doron. All rights reserved.
// </copyright>

using System.Globalization;
using FluentAssertions;
using Microsoft.Extensions.Logging;
using Moq;
using TargCC.Core.Generators.Data;
using TargCC.Core.Interfaces.Models;
using TargCC.Core.Tests.TestHelpers;
using Xunit;

namespace TargCC.Core.Tests.Unit.Generators.Data;

/// <summary>
/// Tests for EntityConfigurationGenerator.
/// </summary>
public class EntityConfigurationGeneratorTests
{
    private readonly Mock<ILogger<EntityConfigurationGenerator>> _loggerMock;
    private readonly EntityConfigurationGenerator _generator;

    /// <summary>
    /// Initializes a new instance of the <see cref="EntityConfigurationGeneratorTests"/> class.
    /// </summary>
    public EntityConfigurationGeneratorTests()
    {
        _loggerMock = new Mock<ILogger<EntityConfigurationGenerator>>();
        _generator = new EntityConfigurationGenerator(_loggerMock.Object);
    }

    #region Constructor Tests

    [Fact]
    public void Constructor_WithValidLogger_CreatesInstance()
    {
        // Arrange & Act
        var generator = new EntityConfigurationGenerator(_loggerMock.Object);

        // Assert
        generator.Should().NotBeNull();
    }

    [Fact]
    public void Constructor_WithNullLogger_ThrowsArgumentNullException()
    {
        // Arrange, Act & Assert
        var act = () => new EntityConfigurationGenerator(null!);
        act.Should().Throw<ArgumentNullException>()
            .WithParameterName("logger");
    }

    #endregion

    #region Basic Generation Tests

    [Fact]
    public async Task GenerateAsync_WithNullTable_ThrowsArgumentNullException()
    {
        // Arrange, Act & Assert
        var act = async () => await _generator.GenerateAsync(null!);
        await act.Should().ThrowAsync<ArgumentNullException>()
            .WithParameterName("table");
    }

    [Fact]
    public async Task GenerateAsync_WithSimpleTable_GeneratesBasicConfiguration()
    {
        // Arrange
        var table = new TableBuilder().WithName("Customer")
            .WithColumn("ID", "int", isPrimaryKey: true, isIdentity: true)
            .WithColumn("Name", "nvarchar", maxLength: 100, isNullable: false)
            .WithColumn("Email", "nvarchar", maxLength: 100)
            .Build();

        // Act
        var result = await _generator.GenerateAsync(table);

        // Assert
        result.Should().NotBeNullOrEmpty();
        result.Should().Contain("public class CustomerConfiguration : IEntityTypeConfiguration<Customer>");
        result.Should().Contain("public void Configure(EntityTypeBuilder<Customer> builder)");
        result.Should().Contain("builder.ToTable(\"Customer\");");
        result.Should().Contain("builder.HasKey(e => e.ID);");
    }

    [Fact]
    public async Task GenerateAsync_IncludesAutoGeneratedHeader()
    {
        // Arrange
        var table = new TableBuilder().WithName("Customer")
            .WithColumn("ID", "int", isPrimaryKey: true)
            .Build();

        // Act
        var result = await _generator.GenerateAsync(table);

        // Assert
        result.Should().Contain("// <auto-generated>");
        result.Should().Contain("generated by TargCC"); // Flexible - ignores spacing and full version
        result.Should().Contain("Changes to this file may cause incorrect behavior");
        result.Should().Contain(DateTime.Now.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture));
    }

    [Fact]
    public async Task GenerateAsync_IncludesNamespaceAndUsings()
    {
        // Arrange
        var table = new TableBuilder().WithName("Customer")
            .WithColumn("ID", "int", isPrimaryKey: true)
            .Build();

        // Act
        var result = await _generator.GenerateAsync(table);

        // Assert
        result.Should().Contain("using Microsoft.EntityFrameworkCore;");
        result.Should().Contain("using Microsoft.EntityFrameworkCore.Metadata.Builders;");
        result.Should().Contain("using TargCC.Domain.Entities;");
        result.Should().Contain("namespace TargCC.Infrastructure.Data.Configurations;");
    }

    #endregion

    #region Property Configuration Tests

    [Fact]
    public async Task GenerateAsync_WithRequiredProperty_ConfiguresAsRequired()
    {
        // Arrange
        var table = new TableBuilder().WithName("Customer")
            .WithColumn("ID", "int", isPrimaryKey: true)
            .WithColumn("Name", "nvarchar", maxLength: 100, isNullable: false)
            .Build();

        // Act
        var result = await _generator.GenerateAsync(table);

        // Assert
        result.Should().Contain("builder.Property(e => e.Name)");
        result.Should().Contain(".IsRequired()");
        result.Should().Contain(".HasMaxLength(100)");
    }

    [Fact]
    public async Task GenerateAsync_WithMaxLengthProperty_ConfiguresMaxLength()
    {
        // Arrange
        var table = new TableBuilder().WithName("Customer")
            .WithColumn("ID", "int", isPrimaryKey: true)
            .WithColumn("Email", "nvarchar", maxLength: 255)
            .WithColumn("Phone", "varchar", maxLength: 20)
            .Build();

        // Act
        var result = await _generator.GenerateAsync(table);

        // Assert
        result.Should().Contain("builder.Property(e => e.Email)");
        result.Should().Contain(".HasMaxLength(255)");
        result.Should().Contain("builder.Property(e => e.Phone)");
        result.Should().Contain(".HasMaxLength(20)");
    }

    [Fact]
    public async Task GenerateAsync_WithDecimalProperty_ConfiguresPrecisionAndScale()
    {
        // Arrange
        var table = new TableBuilder().WithName("Product")
            .WithColumn("ID", "int", isPrimaryKey: true)
            .WithColumn("Price", "decimal", precision: 18, scale: 2)
            .WithColumn("Tax", "decimal", precision: 10, scale: 4)
            .Build();

        // Act
        var result = await _generator.GenerateAsync(table);

        // Assert
        result.Should().Contain("builder.Property(e => e.Price)");
        result.Should().Contain(".HasPrecision(18, 2)");
        result.Should().Contain("builder.Property(e => e.Tax)");
        result.Should().Contain(".HasPrecision(10, 4)");
    }

    [Fact]
    public async Task GenerateAsync_WithDefaultValue_ConfiguresDefaultValue()
    {
        // Arrange
        var table = new TableBuilder().WithName("Customer")
            .WithColumn("ID", "int", isPrimaryKey: true)
            .WithColumn(c => c.WithName("IsActive").WithDataType("bit").WithDefaultValue("1").Build())
            .WithColumn(c => c.WithName("CreatedDate").WithDataType("datetime").WithDefaultValue("GETDATE()").Build())
            .Build();

        // Act
        var result = await _generator.GenerateAsync(table);

        // Assert
        result.Should().Contain("builder.Property(e => e.IsActive)");
        result.Should().Contain(".HasDefaultValue(true)");
        result.Should().Contain("builder.Property(e => e.CreatedDate)");
        result.Should().Contain(".HasDefaultValueSql(\"GETDATE()\")");
    }

    [Fact]
    public async Task GenerateAsync_WithNullableProperty_ConfiguresAsOptional()
    {
        // Arrange
        var table = new TableBuilder().WithName("Customer")
            .WithColumn("ID", "int", isPrimaryKey: true)
            .WithColumn("Phone", "nvarchar", maxLength: 20, isNullable: true)
            .WithColumn("Email", "nvarchar", maxLength: 100, isNullable: true)
            .Build();

        // Act
        var result = await _generator.GenerateAsync(table);

        // Assert
        result.Should().Contain("builder.Property(e => e.Phone)");
        result.Should().NotContain("IsRequired().*Phone");
        result.Should().Contain("builder.Property(e => e.Email)");
        result.Should().NotContain("IsRequired().*Email");
    }

    #endregion

    #region Primary Key Tests

    [Fact]
    public async Task GenerateAsync_WithSinglePrimaryKey_ConfiguresHasKey()
    {
        // Arrange
        var table = new TableBuilder().WithName("Customer")
            .WithColumn("ID", "int", isPrimaryKey: true, isIdentity: true)
            .WithColumn("Name", "nvarchar", maxLength: 100)
            .Build();

        // Act
        var result = await _generator.GenerateAsync(table);

        // Assert
        result.Should().Contain("builder.HasKey(e => e.ID);");
    }

    [Fact]
    public async Task GenerateAsync_WithCompositePrimaryKey_ConfiguresCompositeKey()
    {
        // Arrange
        var table = new TableBuilder().WithName("OrderItem")
            .WithColumn("OrderID", "int", isPrimaryKey: true)
            .WithColumn("ProductID", "int", isPrimaryKey: true)
            .WithColumn("Quantity", "int")
            .Build();

        // Act
        var result = await _generator.GenerateAsync(table);

        // Assert
        result.Should().Contain("builder.HasKey(e => new { e.OrderID, e.ProductID });");
    }

    [Fact]
    public async Task GenerateAsync_WithIdentityPrimaryKey_ConfiguresValueGeneration()
    {
        // Arrange
        var table = new TableBuilder().WithName("Customer")
            .WithColumn("ID", "int", isPrimaryKey: true, isIdentity: true)
            .Build();

        // Act
        var result = await _generator.GenerateAsync(table);

        // Assert
        result.Should().Contain("builder.Property(e => e.ID)");
        result.Should().Contain(".ValueGeneratedOnAdd()");
    }

    #endregion

    #region Index Configuration Tests

    [Fact]
    public async Task GenerateAsync_WithUniqueIndex_ConfiguresUniqueIndex()
    {
        // Arrange
        var table = new TableBuilder().WithName("Customer")
            .WithColumn("ID", "int", isPrimaryKey: true)
            .WithColumn("Email", "nvarchar", maxLength: 100)
            .WithIndex("IX_Customer_Email", isUnique: true, new[] { "Email" })
            .Build();

        // Act
        var result = await _generator.GenerateAsync(table);

        // Assert
        result.Should().Contain("builder.HasIndex(e => e.Email)");
        result.Should().Contain(".IsUnique()");
        result.Should().Contain(".HasDatabaseName(\"IX_Customer_Email\")");
    }

    [Fact]
    public async Task GenerateAsync_WithNonUniqueIndex_ConfiguresIndex()
    {
        // Arrange
        var table = new TableBuilder().WithName("Customer")
            .WithColumn("ID", "int", isPrimaryKey: true)
            .WithColumn("LastName", "nvarchar", maxLength: 100)
            .WithIndex("IX_Customer_LastName", isUnique: false, new[] { "LastName" })
            .Build();

        // Act
        var result = await _generator.GenerateAsync(table);

        // Assert
        result.Should().Contain("builder.HasIndex(e => e.LastName)");
        result.Should().NotContain("IsUnique()");
        result.Should().Contain(".HasDatabaseName(\"IX_Customer_LastName\")");
    }

    [Fact]
    public async Task GenerateAsync_WithCompositeIndex_ConfiguresCompositeIndex()
    {
        // Arrange
        var table = new TableBuilder().WithName("Customer")
            .WithColumn("ID", "int", isPrimaryKey: true)
            .WithColumn("FirstName", "nvarchar", maxLength: 50)
            .WithColumn("LastName", "nvarchar", maxLength: 50)
            .WithIndex("IX_Customer_Name", isUnique: false, new[] { "FirstName", "LastName" })
            .Build();

        // Act
        var result = await _generator.GenerateAsync(table);

        // Assert
        result.Should().Contain("builder.HasIndex(e => new { e.FirstName, e.LastName })");
        result.Should().Contain(".HasDatabaseName(\"IX_Customer_Name\")");
    }

    [Fact]
    public async Task GenerateAsync_ExcludesPrimaryKeyIndex()
    {
        // Arrange
        var table = new TableBuilder().WithName("Customer")
            .WithColumn("ID", "int", isPrimaryKey: true)
            .WithIndex("PK_Customer", isUnique: true, new[] { "ID" }, isPrimaryKey: true)
            .Build();

        // Act
        var result = await _generator.GenerateAsync(table);

        // Assert
        result.Should().NotContain("builder.HasIndex(e => e.ID)");
        result.Should().NotContain("PK_Customer");
    }

    #endregion

    #region Relationship Configuration Tests

    [Fact]
    public async Task GenerateAsync_WithOneToManyRelationship_ConfiguresRelationship()
    {
        // Arrange
        var customerTable = new TableBuilder().WithName("Customer")
            .WithColumn("ID", "int", isPrimaryKey: true)
            .WithColumn("Name", "nvarchar", maxLength: 100)
            .Build();

        var orderTable = new TableBuilder().WithName("Order")
            .WithColumn("ID", "int", isPrimaryKey: true)
            .WithColumn("CustomerID", "int", isForeignKey: true)
            .Build();

        var relationship = new Relationship
        {
            Name = "FK_Order_Customer",
            ParentTable = "Customer",
            ParentColumn = "ID",
            ChildTable = "Order",
            ChildColumn = "CustomerID",
            DeleteAction = "NO ACTION"
        };

        customerTable.Relationships.Add(relationship);

        // Act
        var result = await _generator.GenerateAsync(customerTable);

        // Assert
        result.Should().Contain("builder.HasMany(e => e.Orders)");
        result.Should().Contain(".WithOne(o => o.Customer)");
        result.Should().Contain(".HasForeignKey(o => o.CustomerID)");
        result.Should().Contain(".OnDelete(DeleteBehavior.NoAction)");
    }

    [Fact]
    public async Task GenerateAsync_WithCascadeDelete_ConfiguresCascade()
    {
        // Arrange
        var customerTable = new TableBuilder().WithName("Customer")
            .WithColumn("ID", "int", isPrimaryKey: true)
            .Build();

        var relationship = new Relationship
        {
            Name = "FK_Order_Customer",
            ParentTable = "Customer",
            ParentColumn = "ID",
            ChildTable = "Order",
            ChildColumn = "CustomerID",
            DeleteAction = "CASCADE"
        };

        customerTable.Relationships.Add(relationship);

        // Act
        var result = await _generator.GenerateAsync(customerTable);

        // Assert
        result.Should().Contain(".OnDelete(DeleteBehavior.Cascade)");
    }

    [Fact]
    public async Task GenerateAsync_WithSetNullDelete_ConfiguresSetNull()
    {
        // Arrange
        var customerTable = new TableBuilder().WithName("Customer")
            .WithColumn("ID", "int", isPrimaryKey: true)
            .Build();

        var relationship = new Relationship
        {
            Name = "FK_Order_Customer",
            ParentTable = "Customer",
            ParentColumn = "ID",
            ChildTable = "Order",
            ChildColumn = "CustomerID",
            DeleteAction = "SET NULL"
        };

        customerTable.Relationships.Add(relationship);

        // Act
        var result = await _generator.GenerateAsync(customerTable);

        // Assert
        result.Should().Contain(".OnDelete(DeleteBehavior.SetNull)");
    }

    [Fact]
    public async Task GenerateAsync_WithMultipleRelationships_ConfiguresAll()
    {
        // Arrange
        var customerTable = new TableBuilder().WithName("Customer")
            .WithColumn("ID", "int", isPrimaryKey: true)
            .Build();

        var orderRelationship = new Relationship
        {
            Name = "FK_Order_Customer",
            ParentTable = "Customer",
            ParentColumn = "ID",
            ChildTable = "Order",
            ChildColumn = "CustomerID"
        };

        var addressRelationship = new Relationship
        {
            Name = "FK_Address_Customer",
            ParentTable = "Customer",
            ParentColumn = "ID",
            ChildTable = "Address",
            ChildColumn = "CustomerID"
        };

        customerTable.Relationships.Add(orderRelationship);
        customerTable.Relationships.Add(addressRelationship);

        // Act
        var result = await _generator.GenerateAsync(customerTable);

        // Assert
        result.Should().Contain("builder.HasMany(e => e.Orders)");
        result.Should().Contain("builder.HasMany(e => e.Addresses)");
    }

    #endregion

    #region Special Column Tests

    [Fact]
    public async Task GenerateAsync_WithEncryptedColumn_ConfiguresAsString()
    {
        // Arrange
        var table = new TableBuilder().WithName("Customer")
            .WithColumn("ID", "int", isPrimaryKey: true)
            .WithColumn("ent_CreditCard", "nvarchar", maxLength: 500)
            .Build();

        // Act
        var result = await _generator.GenerateAsync(table);

        // Assert
        result.Should().Contain("builder.Property(e => e.CreditCard)");
        result.Should().Contain(".HasMaxLength(500)");
        result.Should().Contain(".HasColumnName(\"ent_CreditCard\")");
    }

    [Fact]
    public async Task GenerateAsync_WithHashedColumn_ConfiguresAsString()
    {
        // Arrange
        var table = new TableBuilder().WithName("Customer")
            .WithColumn("ID", "int", isPrimaryKey: true)
            .WithColumn("eno_Password", "varchar", maxLength: 64)
            .Build();

        // Act
        var result = await _generator.GenerateAsync(table);

        // Assert
        result.Should().Contain("builder.Property(e => e.PasswordHashed)");
        result.Should().Contain(".HasMaxLength(64)");
        result.Should().Contain(".HasColumnName(\"eno_Password\")");
    }

    [Fact]
    public async Task GenerateAsync_WithLookupColumn_ConfiguresBothColumns()
    {
        // Arrange
        var table = new TableBuilder().WithName("Customer")
            .WithColumn("ID", "int", isPrimaryKey: true)
            .WithColumn("lkp_Status", "varchar", maxLength: 10)
            .Build();

        // Act
        var result = await _generator.GenerateAsync(table);

        // Assert
        result.Should().Contain("builder.Property(e => e.StatusCode)");
        result.Should().Contain(".HasColumnName(\"lkp_Status\")");
    }

    [Fact]
    public async Task GenerateAsync_WithCalculatedColumn_ConfiguresAsReadOnly()
    {
        // Arrange
        var table = new TableBuilder().WithName("Customer")
            .WithColumn("ID", "int", isPrimaryKey: true)
            .WithColumn("clc_FullName", "nvarchar", maxLength: 200)
            .Build();

        // Act
        var result = await _generator.GenerateAsync(table);

        // Assert
        result.Should().Contain("builder.Property(e => e.FullName)");
        result.Should().Contain(".HasColumnName(\"clc_FullName\")");
    }

    [Fact]
    public async Task GenerateAsync_WithAggregateColumn_ConfiguresAsComputed()
    {
        // Arrange
        var table = new TableBuilder().WithName("Customer")
            .WithColumn("ID", "int", isPrimaryKey: true)
            .WithColumn("agg_OrderCount", "int")
            .Build();

        // Act
        var result = await _generator.GenerateAsync(table);

        // Assert
        result.Should().Contain("builder.Property(e => e.OrderCount)");
        result.Should().Contain(".HasColumnName(\"agg_OrderCount\")");
    }

    #endregion

    #region Complex Scenarios

    [Fact]
    public async Task GenerateAsync_WithComplexTable_GeneratesCompleteConfiguration()
    {
        // Arrange
        var table = new TableBuilder().WithName("Customer")
            .WithColumn("ID", "int", isPrimaryKey: true, isIdentity: true)
            .WithColumn("Name", "nvarchar", maxLength: 100, isNullable: false)
            .WithColumn("Email", "nvarchar", maxLength: 100, isNullable: false)
            .WithColumn("Phone", "varchar", maxLength: 20)
            .WithColumn("ent_CreditCard", "nvarchar", maxLength: 500)
            .WithColumn("eno_Password", "varchar", maxLength: 64)
            .WithColumn(c => c.WithName("agg_OrderCount").WithDataType("int").WithDefaultValue("0").Build())
            .WithColumn(c => c.WithName("IsActive").WithDataType("bit").WithDefaultValue("1").Build())
            .WithColumn(c => c.WithName("CreatedDate").WithDataType("datetime").WithDefaultValue("GETDATE()").Build())
            .WithIndex("IX_Customer_Email", isUnique: true, new[] { "Email" })
            .WithIndex("IX_Customer_Phone", isUnique: false, new[] { "Phone" })
            .Build();

        var relationship = new Relationship
        {
            Name = "FK_Order_Customer",
            ParentTable = "Customer",
            ParentColumn = "ID",
            ChildTable = "Order",
            ChildColumn = "CustomerID",
            DeleteAction = "NO ACTION"
        };

        table.Relationships.Add(relationship);

        // Act
        var result = await _generator.GenerateAsync(table);

        // Assert
        result.Should().NotBeNullOrEmpty();
        result.Should().Contain("public class CustomerConfiguration");
        result.Should().Contain("builder.ToTable(\"Customer\")");
        result.Should().Contain("builder.HasKey(e => e.ID)");
        result.Should().Contain("builder.Property(e => e.Name)");
        result.Should().Contain("builder.Property(e => e.Email)");
        result.Should().Contain("builder.Property(e => e.CreditCard)");
        result.Should().Contain("builder.Property(e => e.PasswordHashed)");
        result.Should().Contain("builder.HasIndex(e => e.Email)");
        result.Should().Contain("builder.HasMany(e => e.Orders)");
    }

    [Fact]
    public async Task GenerateAsync_WithTableWithoutRelationships_GeneratesWithoutRelationshipConfiguration()
    {
        // Arrange
        var table = new TableBuilder().WithName("Customer")
            .WithColumn("ID", "int", isPrimaryKey: true)
            .WithColumn("Name", "nvarchar", maxLength: 100)
            .Build();

        // Act
        var result = await _generator.GenerateAsync(table);

        // Assert
        result.Should().NotContain("HasMany");
        result.Should().NotContain("WithOne");
    }

    [Fact]
    public async Task GenerateAsync_WithTableWithoutIndexes_GeneratesWithoutIndexConfiguration()
    {
        // Arrange
        var table = new TableBuilder().WithName("Customer")
            .WithColumn("ID", "int", isPrimaryKey: true)
            .WithColumn("Name", "nvarchar", maxLength: 100)
            .Build();

        // Act
        var result = await _generator.GenerateAsync(table);

        // Assert
        result.Should().NotContain("HasIndex");
    }

    #endregion

    #region Logging Tests

    [Fact]
    public async Task GenerateAsync_LogsInformationMessages()
    {
        // Arrange
        var table = new TableBuilder().WithName("Customer")
            .WithColumn("ID", "int", isPrimaryKey: true)
            .Build();

        // Act
        await _generator.GenerateAsync(table);

        // Assert
        // LoggerMessage.Define checks IsEnabled before logging
        _loggerMock.Verify(
            x => x.IsEnabled(LogLevel.Information),
            Times.AtLeastOnce,
            "Logger should check if Information level is enabled for performance");
    }

    #endregion
}
