// <auto-generated>
//     This code was generated by TargCC Component Generator.
//     Table: ImportTransactionLoad
//     Generated: 2025-12-11 11:52:13
// </auto-generated>

import React from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { Box, Typography, Button, CircularProgress, Alert, Card, CardContent, Grid } from '@mui/material';
import { Edit as EditIcon, Delete as DeleteIcon, ArrowBack as ArrowBackIcon } from '@mui/icons-material';
import { DataGrid, GridColDef } from '@mui/x-data-grid';
import { useImportTransactionLoad, useDeleteImportTransactionLoad } from '../../hooks/useImportTransactionLoad';
import { useImportTransactionLoadImportTransactionLoadRows } from '../../hooks/useImportTransactionLoad';
import type { ImportTransactionLoad } from '../../types/ImportTransactionLoad.types';
import type { ImportTransactionLoadRow } from '../../types/ImportTransactionLoadRow.types';


export const ImportTransactionLoadDetail: React.FC = () => {
  const navigate = useNavigate();
  const { id } = useParams<{ id: string }>();
  const { data: entity, isLoading, error } = useImportTransactionLoad(id ? parseInt(id, 10) : null);
  const { mutate: deleteEntity } = useDeleteImportTransactionLoad();
  const { data: importTransactionLoadRows, isLoading: importTransactionLoadRowsLoading } = useImportTransactionLoadImportTransactionLoadRows(id ? parseInt(id, 10) : null);

  const handleDelete = () => {
    if (confirm('Are you sure you want to delete this item?')) {
      deleteEntity(parseInt(id!, 10), {
        onSuccess: () => navigate('/importTransactionLoads'),
      });
    }
  };

  if (isLoading) {
    return <CircularProgress />;
  }

  if (error || !entity) {
    return <Alert severity="error">Failed to load importTransactionLoad</Alert>;
  }

  return (
    <Box sx={{ maxWidth: 800 }}>
      <Box sx={{ mb: 2, display: 'flex', gap: 2 }}>
        <Button
          variant="outlined"
          startIcon={<ArrowBackIcon />}
          onClick={() => navigate('/importTransactionLoads')}
        >
          Back
        </Button>
        <Button
          variant="contained"
          startIcon={<EditIcon />}
          onClick={() => navigate(`/importTransactionLoads/${id}/edit`)}
        >
          Edit
        </Button>
        <Button
          variant="outlined"
          color="error"
          startIcon={<DeleteIcon />}
          onClick={handleDelete}
        >
          Delete
        </Button>
      </Box>

      <Card>
        <CardContent>
          <Typography variant="h5" component="h2" gutterBottom>
            ImportTransactionLoad Details
          </Typography>
      <Grid container spacing={2}>
        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            TableNameImportTransactionLoad
          </Typography>
          <Typography variant="body1">
            {entity.tableNameImportTransactionLoad ? 'Yes' : 'No'}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            Id
          </Typography>
          <Typography variant="body1">
            {entity.id}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            DistributorID
          </Typography>
          <Typography variant="body1">
            {entity.distributorID}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            WhenInitialized
          </Typography>
          <Typography variant="body1">
            {new Date(entity.whenInitialized).toLocaleDateString()}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            InitiatedByUserID
          </Typography>
          <Typography variant="body1">
            {entity.initiatedByUserID}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            WhenCompleted
          </Typography>
          <Typography variant="body1">
            {new Date(entity.whenCompleted).toLocaleDateString()}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            LoadsRequested
          </Typography>
          <Typography variant="body1">
            {entity.loadsRequested}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            LoadsApproved
          </Typography>
          <Typography variant="body1">
            {entity.loadsApproved}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            Comments
          </Typography>
          <Typography variant="body1">
            {entity.comments}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            DeletedBy
          </Typography>
          <Typography variant="body1">
            {entity.deletedBy}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            DeletedOn
          </Typography>
          <Typography variant="body1">
            {new Date(entity.deletedOn).toLocaleDateString()}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            UpdatingLoginID
          </Typography>
          <Typography variant="body1">
            {entity.updatingLoginID}
          </Typography>
        </Grid>

      </Grid>

        </CardContent>
      </Card>

      <Card sx={{ mt: 2 }}>
        <CardContent>
          <Typography variant="h6" gutterBottom>
            ImportTransactionLoadRows
          </Typography>
          <Box sx={{ height: 400, width: '100%' }}>
            <DataGrid
              rows={importTransactionLoadRows || []}
              columns={[
                { field: 'tableNameImportTransactionLoadRow', headerName: 'TableNameImportTransactionLoadRow', width: 150 },
                { field: 'id', headerName: 'Id', width: 100 },
                { field: 'importTransactionLoadID', headerName: 'ImportTransactionLoadID', width: 100 },
                { field: 'customerPhoneNumber', headerName: 'CustomerPhoneNumber', width: 150 },
                { field: 'enmCurrency', headerName: 'EnmCurrency', width: 150 },
              ]}
              loading={importTransactionLoadRowsLoading}
              pageSizeOptions={[5, 10, 25]}
              initialState={{
                pagination: { paginationModel: { pageSize: 5 } },
              }}
            />
          </Box>
        </CardContent>
      </Card>
    </Box>
  );
};

