// ------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of TargCC.Core.Generators
//     Copyright (c) 2024-2025 TargCC. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

namespace TargCC.Core.Generators.Project.Models;

/// <summary>
/// Options for project generation.
/// </summary>
public class ProjectGenerationOptions
{
    /// <summary>
    /// Gets or sets the project name (e.g., "MyApp", "OrderSystem").
    /// </summary>
    public required string ProjectName { get; set; }

    /// <summary>
    /// Gets or sets the root namespace for the project.
    /// </summary>
    public string? RootNamespace { get; set; }

    /// <summary>
    /// Gets or sets the output directory where the solution will be created.
    /// </summary>
    public required string OutputDirectory { get; set; }

    /// <summary>
    /// Gets or sets the database connection string.
    /// </summary>
    public required string ConnectionString { get; set; }

    /// <summary>
    /// Gets or sets the target framework (default: net8.0).
    /// </summary>
    public string TargetFramework { get; set; } = "net8.0";

    /// <summary>
    /// Gets or sets a value indicating whether to include unit tests project.
    /// </summary>
    public bool IncludeTests { get; set; } = true;

    /// <summary>
    /// Gets or sets a value indicating whether to use nullable reference types.
    /// </summary>
    public bool EnableNullable { get; set; } = true;

    /// <summary>
    /// Gets or sets a value indicating whether to enable implicit usings.
    /// </summary>
    public bool ImplicitUsings { get; set; } = true;

    /// <summary>
    /// Gets or sets the C# language version.
    /// </summary>
    public string LangVersion { get; set; } = "latest";

    /// <summary>
    /// Gets or sets the architecture type.
    /// </summary>
    public ArchitectureType Architecture { get; set; } = ArchitectureType.CleanArchitecture;

    /// <summary>
    /// Gets or sets the list of table names to include. If empty, all tables are included.
    /// </summary>
    public List<string> IncludeTables { get; set; } = new();

    /// <summary>
    /// Gets or sets the list of table names to exclude.
    /// </summary>
    public List<string> ExcludeTables { get; set; } = new();

    /// <summary>
    /// Gets the effective root namespace.
    /// </summary>
    public string EffectiveNamespace => RootNamespace ?? ProjectName;
}

/// <summary>
/// Supported architecture types.
/// </summary>
public enum ArchitectureType
{
    /// <summary>
    /// Clean Architecture with Domain, Application, Infrastructure, API layers.
    /// </summary>
    CleanArchitecture,

    /// <summary>
    /// Simple 3-tier architecture.
    /// </summary>
    ThreeTier,

    /// <summary>
    /// Minimal API structure.
    /// </summary>
    MinimalApi
}
