// ------------------------------------------------------------------------------
// <auto-generated>
//     This file is part of TargCC.Core.Generators
//     Copyright (c) 2024-2025 TargCC. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable

using TargCC.Core.Interfaces.Models;

namespace TargCC.Core.Generators.Project.Models;

/// <summary>
/// Represents information about a generated project.
/// </summary>
public class ProjectInfo
{
    /// <summary>
    /// Gets or sets the project name.
    /// </summary>
    public required string Name { get; set; }

    /// <summary>
    /// Gets or sets the project type.
    /// </summary>
    public required ProjectType Type { get; set; }

    /// <summary>
    /// Gets or sets the relative path from solution root.
    /// </summary>
    public required string RelativePath { get; set; }

    /// <summary>
    /// Gets or sets the project GUID.
    /// </summary>
    public Guid ProjectGuid { get; set; } = Guid.NewGuid();

    /// <summary>
    /// Gets or sets the target framework.
    /// </summary>
    public string TargetFramework { get; set; } = "net8.0";

    /// <summary>
    /// Gets or sets the output type (Library, Exe).
    /// </summary>
    public string OutputType { get; set; } = "Library";

    /// <summary>
    /// Gets or sets the root namespace.
    /// </summary>
    public string? RootNamespace { get; set; }

    /// <summary>
    /// Gets or sets the namespace for this specific project (may differ from RootNamespace).
    /// </summary>
    public string? Namespace { get; set; }

    /// <summary>
    /// Gets or sets the database connection string.
    /// </summary>
    public string? ConnectionString { get; set; }

    /// <summary>
    /// Gets or sets the list of tables for complete project generation.
    /// </summary>
    public List<Table>? Tables { get; set; }

    /// <summary>
    /// Gets or sets the list of project references.
    /// </summary>
    public List<string> ProjectReferences { get; set; } = new();

    /// <summary>
    /// Gets or sets the list of NuGet package references.
    /// </summary>
    public List<PackageReference> PackageReferences { get; set; } = new();

    /// <summary>
    /// Gets the csproj file name.
    /// </summary>
    public string CsprojFileName => $"{Name}.csproj";

    /// <summary>
    /// Gets the full csproj path relative to solution.
    /// </summary>
    public string CsprojPath => Path.Combine(RelativePath, CsprojFileName);
}

/// <summary>
/// Project types in Clean Architecture.
/// </summary>
public enum ProjectType
{
    /// <summary>
    /// Domain layer - entities, value objects, domain events.
    /// </summary>
    Domain,

    /// <summary>
    /// Application layer - use cases, CQRS handlers, DTOs.
    /// </summary>
    Application,

    /// <summary>
    /// Infrastructure layer - data access, external services.
    /// </summary>
    Infrastructure,

    /// <summary>
    /// API layer - controllers, middleware, configuration.
    /// </summary>
    Api,

    /// <summary>
    /// Unit tests project.
    /// </summary>
    Tests
}

/// <summary>
/// Represents a NuGet package reference.
/// </summary>
public class PackageReference
{
    /// <summary>
    /// Gets or sets the package name.
    /// </summary>
    public required string Name { get; set; }

    /// <summary>
    /// Gets or sets the package version.
    /// </summary>
    public required string Version { get; set; }

    /// <summary>
    /// Gets or sets a value indicating whether to include assets.
    /// </summary>
    public bool IncludeAssets { get; set; } = true;

    /// <summary>
    /// Gets or sets private assets configuration.
    /// </summary>
    public string? PrivateAssets { get; set; }
}
