// <auto-generated>
//     This code was generated by TargCC
//     Generated for: Lead (Handler)
//     Generation date: 2025-12-16 09:26:47
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using MediatR;
using Microsoft.Extensions.Logging;
using UpayCard.RiskManagement.Application.Common.Models;
using UpayCard.RiskManagement.Domain.Entities;
using UpayCard.RiskManagement.Domain.Interfaces;

namespace UpayCard.RiskManagement.Application.Features.Leads.Commands;

/// <summary>
/// Handles the CreateLeadCommand request.
/// </summary>
public class CreateLeadHandler : IRequestHandler<CreateLeadCommand, Result<int>>
{
    private readonly ILeadRepository _repository;
    private readonly ILogger<CreateLeadHandler> _logger;

    /// <summary>
    /// Initializes a new instance of the <see cref="CreateLeadHandler"/> class.
    /// </summary>
    public CreateLeadHandler(
        ILeadRepository repository,
        ILogger<CreateLeadHandler> logger)
    {
        _repository = repository ?? throw new ArgumentNullException(nameof(repository));
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
    }

    /// <inheritdoc/>
    public async Task<Result<int>> Handle(CreateLeadCommand request, CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(request);

        _logger.LogDebug("Creating new Lead");

        try
        {
            var entity = new Lead
            {
                TableName_Lead = request.TableName_Lead,
                lkpLeadOrigin = request.lkpLeadOrigin,
                FirstName = request.FirstName,
                LastName = request.LastName,
                email = request.email,
                CellPhone = request.CellPhone,
                Subject = request.Subject,
                Message = request.Message,
                Comment = request.Comment,
                WhenOpened = request.WhenOpened,
                enmStatus = request.enmStatus,
                WhenStatusChanged = request.WhenStatusChanged,
                AddedBy = request.AddedBy,
                AddedOn = request.AddedOn,
                ChangedBy = request.ChangedBy,
                ChangedOn = request.ChangedOn,
                DeletedBy = request.DeletedBy,
                DeletedOn = request.DeletedOn,
                UpdatingLoginID = request.UpdatingLoginID
            };

            await _repository.AddAsync(entity, cancellationToken);

            _logger.LogInformation("Lead created successfully with ID: {Id}", entity.Id);

            return Result<int>.Success(entity.Id);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error creating Lead");
            throw;
        }
    }
}
