// <auto-generated>
//     This code was generated by TargCC Component Generator.
//     Table: CustomerPerformance
//     Generated: 2025-12-17 07:52:23
// </auto-generated>

import React from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { Box, Typography, Button, CircularProgress, Alert, Card as MuiCard, CardContent, Grid } from '@mui/material';
import { Edit as EditIcon, Delete as DeleteIcon, ArrowBack as ArrowBackIcon } from '@mui/icons-material';
import { useCustomerPerformance, useDeleteCustomerPerformance } from '../../hooks/useCustomerPerformance';


export const CustomerPerformanceDetail: React.FC = () => {
  const navigate = useNavigate();
  const { id } = useParams<{ id: string }>();
  const { data: entity, isLoading, error } = useCustomerPerformance(id ? parseInt(id, 10) : null);
  const { mutate: deleteEntity } = useDeleteCustomerPerformance();

  const handleDelete = () => {
    if (confirm('Are you sure you want to delete this item?')) {
      deleteEntity(parseInt(id!, 10), {
        onSuccess: () => navigate('/customerPerformances'),
      });
    }
  };

  if (isLoading) {
    return <CircularProgress />;
  }

  if (error || !entity) {
    return <Alert severity="error">Failed to load customerPerformance</Alert>;
  }

  return (
    <Box sx={{ maxWidth: 800 }}>
      <Box sx={{ mb: 2, display: 'flex', gap: 2 }}>
        <Button
          variant="outlined"
          startIcon={<ArrowBackIcon />}
          onClick={() => navigate('/customerPerformances')}
        >
          Back
        </Button>
        <Button
          variant="contained"
          startIcon={<EditIcon />}
          onClick={() => navigate(`/customerPerformances/${id}/edit`)}
        >
          Edit
        </Button>
        <Button
          variant="outlined"
          color="error"
          startIcon={<DeleteIcon />}
          onClick={handleDelete}
        >
          Delete
        </Button>
      </Box>

      <MuiCard>
        <CardContent>
          <Typography variant="h5" component="h2" gutterBottom>
            CustomerPerformance Details
          </Typography>
      <Grid container spacing={2}>
        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            TableNameCustomerPerformance
          </Typography>
          <Typography variant="body1">
            {entity.tableNameCustomerPerformance ? 'Yes' : 'No'}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            Id
          </Typography>
          <Typography variant="body1">
            {entity.id}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            CustomerID
          </Typography>
          <Typography variant="body1">
            {entity.customerID}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            NumberOfActivePrepaidCards
          </Typography>
          <Typography variant="body1">
            {entity.numberOfActivePrepaidCards}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            PrepaidCardBalanceSum
          </Typography>
          <Typography variant="body1">
            {entity.prepaidCardBalanceSum?.toFixed(2) ?? 'N/A'}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            PrepaidCardAmountLoadedTodayAggregate
          </Typography>
          <Typography variant="body1">
            {entity.prepaidCardAmountLoadedTodayAggregate?.toFixed(2) ?? 'N/A'}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            PrepaidCardAmountLoadedThisMonthAggregate
          </Typography>
          <Typography variant="body1">
            {entity.prepaidCardAmountLoadedThisMonthAggregate?.toFixed(2) ?? 'N/A'}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            PrepaidCardLoadCountTodayAggregate
          </Typography>
          <Typography variant="body1">
            {entity.prepaidCardLoadCountTodayAggregate}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            PrepaidCardLoadCountThisMonthAggregate
          </Typography>
          <Typography variant="body1">
            {entity.prepaidCardLoadCountThisMonthAggregate}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            PrepaidCardAmountLoadedLast6MonthsAggregate
          </Typography>
          <Typography variant="body1">
            {entity.prepaidCardAmountLoadedLast6MonthsAggregate?.toFixed(2) ?? 'N/A'}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            PrepaidCardTotalAmountLoadedAggregate
          </Typography>
          <Typography variant="body1">
            {entity.prepaidCardTotalAmountLoadedAggregate?.toFixed(2) ?? 'N/A'}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            PrepaidCardTotalLoadCountAggregate
          </Typography>
          <Typography variant="body1">
            {entity.prepaidCardTotalLoadCountAggregate}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            WalletBalanceRaw
          </Typography>
          <Typography variant="body1">
            {entity.walletBalanceRaw?.toFixed(2) ?? 'N/A'}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            WalletBalanceCommitted
          </Typography>
          <Typography variant="body1">
            {entity.walletBalanceCommitted?.toFixed(2) ?? 'N/A'}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            WalletBalanceWorking
          </Typography>
          <Typography variant="body1">
            {entity.walletBalanceWorking?.toFixed(2) ?? 'N/A'}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            WalletWithdrawalAmtViaCreditCardTodayAggregate
          </Typography>
          <Typography variant="body1">
            {entity.walletWithdrawalAmtViaCreditCardTodayAggregate?.toFixed(2) ?? 'N/A'}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            WalletWithdrawalAmtViaCreditCardThisMonthAggregate
          </Typography>
          <Typography variant="body1">
            {entity.walletWithdrawalAmtViaCreditCardThisMonthAggregate?.toFixed(2) ?? 'N/A'}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            WalletWithdrawalAmtViaBankTodayAggregate
          </Typography>
          <Typography variant="body1">
            {entity.walletWithdrawalAmtViaBankTodayAggregate?.toFixed(2) ?? 'N/A'}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            WalletWithdrawalAmtViaBankThisMonthAggregate
          </Typography>
          <Typography variant="body1">
            {entity.walletWithdrawalAmtViaBankThisMonthAggregate?.toFixed(2) ?? 'N/A'}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            WalletWithdrawalAmtViaChangerTodayAggregate
          </Typography>
          <Typography variant="body1">
            {entity.walletWithdrawalAmtViaChangerTodayAggregate?.toFixed(2) ?? 'N/A'}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            WalletWithdrawalAmtViaChangerThisMonthAggregate
          </Typography>
          <Typography variant="body1">
            {entity.walletWithdrawalAmtViaChangerThisMonthAggregate?.toFixed(2) ?? 'N/A'}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            WalletWithdrawalCountViaCreditCardTodayAggregate
          </Typography>
          <Typography variant="body1">
            {entity.walletWithdrawalCountViaCreditCardTodayAggregate}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            WalletWithdrawalCountViaCreditCardThisMonthAggregate
          </Typography>
          <Typography variant="body1">
            {entity.walletWithdrawalCountViaCreditCardThisMonthAggregate}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            WalletWithdrawalCountViaBankTodayAggregate
          </Typography>
          <Typography variant="body1">
            {entity.walletWithdrawalCountViaBankTodayAggregate}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            WalletWithdrawalCountViaBankThisMonthAggregate
          </Typography>
          <Typography variant="body1">
            {entity.walletWithdrawalCountViaBankThisMonthAggregate}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            WalletWithdrawalCountViaChangerTodayAggregate
          </Typography>
          <Typography variant="body1">
            {entity.walletWithdrawalCountViaChangerTodayAggregate}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            WalletWithdrawalCountViaChangerThisMonthAggregate
          </Typography>
          <Typography variant="body1">
            {entity.walletWithdrawalCountViaChangerThisMonthAggregate}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            WalletTransferPaidAmtTodayAggregate
          </Typography>
          <Typography variant="body1">
            {entity.walletTransferPaidAmtTodayAggregate?.toFixed(2) ?? 'N/A'}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            WalletTransferPaidAmtThisMonthAggregate
          </Typography>
          <Typography variant="body1">
            {entity.walletTransferPaidAmtThisMonthAggregate?.toFixed(2) ?? 'N/A'}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            WalletTransferPaidCountTodayAggregate
          </Typography>
          <Typography variant="body1">
            {entity.walletTransferPaidCountTodayAggregate}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            WalletTransferPaidCountThisMonthAggregate
          </Typography>
          <Typography variant="body1">
            {entity.walletTransferPaidCountThisMonthAggregate}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            WalletTotalTransferPaidAmountAggregate
          </Typography>
          <Typography variant="body1">
            {entity.walletTotalTransferPaidAmountAggregate?.toFixed(2) ?? 'N/A'}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            WalletTotalTransferPaidCountAggregate
          </Typography>
          <Typography variant="body1">
            {entity.walletTotalTransferPaidCountAggregate}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            LastTimeEnteredCustomerApplication
          </Typography>
          <Typography variant="body1">
            {(entity.lastTimeEnteredCustomerApplication ? new Date(entity.lastTimeEnteredCustomerApplication).toLocaleDateString() : 'N/A')}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            LastTimeLoadedCard
          </Typography>
          <Typography variant="body1">
            {(entity.lastTimeLoadedCard ? new Date(entity.lastTimeLoadedCard).toLocaleDateString() : 'N/A')}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            LastTimeDidWalletTransfer
          </Typography>
          <Typography variant="body1">
            {(entity.lastTimeDidWalletTransfer ? new Date(entity.lastTimeDidWalletTransfer).toLocaleDateString() : 'N/A')}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            DeletedBy
          </Typography>
          <Typography variant="body1">
            {entity.deletedBy}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            DeletedOn
          </Typography>
          <Typography variant="body1">
            {(entity.deletedOn ? new Date(entity.deletedOn).toLocaleDateString() : 'N/A')}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            UpdatingLoginID
          </Typography>
          <Typography variant="body1">
            {entity.updatingLoginID}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            WalletTransferPaidCountLast7DaysAggregate
          </Typography>
          <Typography variant="body1">
            {entity.walletTransferPaidCountLast7DaysAggregate}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            WalletDepositAmtViaCreditCardThisMonthAggregate
          </Typography>
          <Typography variant="body1">
            {entity.walletDepositAmtViaCreditCardThisMonthAggregate?.toFixed(2) ?? 'N/A'}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            WalletDepositAmtViaCreditCardTodayAggregate
          </Typography>
          <Typography variant="body1">
            {entity.walletDepositAmtViaCreditCardTodayAggregate?.toFixed(2) ?? 'N/A'}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            WalletDepositAmtViaBankTodayAggregate
          </Typography>
          <Typography variant="body1">
            {entity.walletDepositAmtViaBankTodayAggregate?.toFixed(2) ?? 'N/A'}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            WalletDepositAmtViaBankThisMonthAggregate
          </Typography>
          <Typography variant="body1">
            {entity.walletDepositAmtViaBankThisMonthAggregate?.toFixed(2) ?? 'N/A'}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            WalletDepositAmtViaChangerTodayAggregate
          </Typography>
          <Typography variant="body1">
            {entity.walletDepositAmtViaChangerTodayAggregate?.toFixed(2) ?? 'N/A'}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            WalletDepositAmtViaChangerThisMonthAggregate
          </Typography>
          <Typography variant="body1">
            {entity.walletDepositAmtViaChangerThisMonthAggregate?.toFixed(2) ?? 'N/A'}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            WalletDepositCountViaCreditCardTodayAggregate
          </Typography>
          <Typography variant="body1">
            {entity.walletDepositCountViaCreditCardTodayAggregate}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            WalletDepositCountViaCreditCardThisMonthAggregate
          </Typography>
          <Typography variant="body1">
            {entity.walletDepositCountViaCreditCardThisMonthAggregate}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            WalletDepositCountViaBankTodayAggregate
          </Typography>
          <Typography variant="body1">
            {entity.walletDepositCountViaBankTodayAggregate}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            WalletDepositCountViaBankThisMonthAggregate
          </Typography>
          <Typography variant="body1">
            {entity.walletDepositCountViaBankThisMonthAggregate}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            WalletDepositCountViaChangerTodayAggregate
          </Typography>
          <Typography variant="body1">
            {entity.walletDepositCountViaChangerTodayAggregate}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            WalletDepositCountViaChangerThisMonthAggregate
          </Typography>
          <Typography variant="body1">
            {entity.walletDepositCountViaChangerThisMonthAggregate}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            WalletTransferReceivedAmtTodayAggregate
          </Typography>
          <Typography variant="body1">
            {entity.walletTransferReceivedAmtTodayAggregate?.toFixed(2) ?? 'N/A'}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            WalletTransferReceivedAmtThisMonthAggregate
          </Typography>
          <Typography variant="body1">
            {entity.walletTransferReceivedAmtThisMonthAggregate?.toFixed(2) ?? 'N/A'}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            WalletTransferReceivedCountTodayAggregate
          </Typography>
          <Typography variant="body1">
            {entity.walletTransferReceivedCountTodayAggregate}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            WalletTransferReceivedCountThisMonthAggregate
          </Typography>
          <Typography variant="body1">
            {entity.walletTransferReceivedCountThisMonthAggregate}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            WalletTotalTransferReceivedAmountAggregate
          </Typography>
          <Typography variant="body1">
            {entity.walletTotalTransferReceivedAmountAggregate?.toFixed(2) ?? 'N/A'}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            WalletTotalTransferReceivedCountAggregate
          </Typography>
          <Typography variant="body1">
            {entity.walletTotalTransferReceivedCountAggregate?.toFixed(2) ?? 'N/A'}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            WalletTransferPaidAmtLast7DaysAggregate
          </Typography>
          <Typography variant="body1">
            {entity.walletTransferPaidAmtLast7DaysAggregate?.toFixed(2) ?? 'N/A'}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            TotalTransferredToWallet1MonthAggregate
          </Typography>
          <Typography variant="body1">
            {entity.totalTransferredToWallet1MonthAggregate?.toFixed(2) ?? 'N/A'}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            TotalTransferredToWallet6MonthsAggregate
          </Typography>
          <Typography variant="body1">
            {entity.totalTransferredToWallet6MonthsAggregate?.toFixed(2) ?? 'N/A'}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            TotalTransferredToWalletAggregate
          </Typography>
          <Typography variant="body1">
            {entity.totalTransferredToWalletAggregate?.toFixed(2) ?? 'N/A'}
          </Typography>
        </Grid>

      </Grid>

        </CardContent>
      </MuiCard>
    </Box>
  );
};

