// <auto-generated>
//     This code was generated by TargCC Component Generator.
//     Table: GovtReportPayment
//     Generated: 2025-12-18 08:11:22
// </auto-generated>

import React, { useEffect } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { useForm } from 'react-hook-form';
import { TextField, Button, Box, CircularProgress, Checkbox, FormControlLabel } from '@mui/material';
import { useGovtReportPayment, useCreateGovtReportPayment, useUpdateGovtReportPayment } from '../../hooks/useGovtReportPayment';
import type { CreateGovtReportPaymentRequest, UpdateGovtReportPaymentRequest } from '../../types/GovtReportPayment.types';


export const GovtReportPaymentForm: React.FC = () => {
  const navigate = useNavigate();
  const { id } = useParams<{ id: string }>();
  const govtReportPaymentId = id && id !== 'new' ? Number(id) : undefined;
  const isEdit = !!govtReportPaymentId;

  const { data: existingGovtReportPayment, isPending: isLoadingEntity } = useGovtReportPayment(govtReportPaymentId || null);

  const {
    register,
    handleSubmit,
    reset,
    formState: { errors },
  } = useForm<CreateGovtReportPaymentRequest>({
    defaultValues: {
    },
  });

  // Update form when data loads
  useEffect(() => {
    if (existingGovtReportPayment) {
      reset(existingGovtReportPayment);
    }
  }, [existingGovtReportPayment, reset]);

  const { mutate: createEntity, isPending: isCreating } = useCreateGovtReportPayment();
  const { mutate: updateEntity, isPending: isUpdating } = useUpdateGovtReportPayment();

  const isSubmitting = isCreating || isUpdating;

  const onSubmit = (data: CreateGovtReportPaymentRequest) => {
    if (isEdit && govtReportPaymentId) {
      updateEntity(
        { id: govtReportPaymentId, data: data as UpdateGovtReportPaymentRequest },
        { onSuccess: () => navigate('/govtReportPayments') }
      );
    } else {
      createEntity(data, { onSuccess: () => navigate('/govtReportPayments') });
    }
  };

  if (isEdit && isLoadingEntity) {
    return <CircularProgress />;
  }

  return (
    <Box component="form" onSubmit={handleSubmit(onSubmit)} sx={{ maxWidth: 600 }}>
      <FormControlLabel
        control={<Checkbox {...register('tableNameGovtReportPayment')} />}
        label="TableNameGovtReportPayment"
      />

      <TextField
        label="GovtReport00ID"
        type="number"
        fullWidth
        margin="normal"
        {...register('govtReport00ID', { maxLength: { value: 8, message: 'Maximum length is 8' } })}
        error={!!errors.govtReport00ID}
        helperText={errors.govtReport00ID?.message}
      />

      <TextField
        label="PaymentDay"
        type="date"
        fullWidth
        margin="normal"
        InputLabelProps={{ shrink: true }}
        {...register('paymentDay', { maxLength: { value: 8, message: 'Maximum length is 8' } })}
        error={!!errors.paymentDay}
        helperText={errors.paymentDay?.message}
      />

      <TextField
        label="EntityID"
        type="number"
        fullWidth
        margin="normal"
        {...register('entityID', { maxLength: { value: 8, message: 'Maximum length is 8' } })}
        error={!!errors.entityID}
        helperText={errors.entityID?.message}
      />

      <TextField
        label="EnmEntityTypeAccountOwner"
        type="text"
        fullWidth
        margin="normal"
        {...register('enmEntityTypeAccountOwner', { maxLength: { value: 50, message: 'Maximum length is 50' } })}
        error={!!errors.enmEntityTypeAccountOwner}
        helperText={errors.enmEntityTypeAccountOwner?.message}
      />

      <TextField
        label="TotalAmount"
        type="number"
        fullWidth
        margin="normal"
        {...register('totalAmount', { maxLength: { value: 9, message: 'Maximum length is 9' } })}
        error={!!errors.totalAmount}
        helperText={errors.totalAmount?.message}
      />

      <TextField
        label="NumberOfTransactions"
        type="number"
        fullWidth
        margin="normal"
        {...register('numberOfTransactions', { maxLength: { value: 4, message: 'Maximum length is 4' } })}
        error={!!errors.numberOfTransactions}
        helperText={errors.numberOfTransactions?.message}
      />

      <TextField
        label="DeletedBy"
        type="text"
        fullWidth
        margin="normal"
        {...register('deletedBy', { maxLength: { value: 100, message: 'Maximum length is 100' } })}
        error={!!errors.deletedBy}
        helperText={errors.deletedBy?.message}
      />

      <TextField
        label="DeletedOn"
        type="date"
        fullWidth
        margin="normal"
        InputLabelProps={{ shrink: true }}
        {...register('deletedOn', { maxLength: { value: 8, message: 'Maximum length is 8' } })}
        error={!!errors.deletedOn}
        helperText={errors.deletedOn?.message}
      />

      <TextField
        label="UpdatingLoginID"
        type="number"
        fullWidth
        margin="normal"
        {...register('updatingLoginID', { maxLength: { value: 8, message: 'Maximum length is 8' } })}
        error={!!errors.updatingLoginID}
        helperText={errors.updatingLoginID?.message}
      />



      <Box sx={{ mt: 2, display: 'flex', gap: 2 }}>
        <Button type="submit" variant="contained" disabled={isSubmitting}>
          {isEdit ? 'Update' : 'Create'}
        </Button>
        <Button variant="outlined" onClick={() => navigate('/govtReportPayments')}>
          Cancel
        </Button>
      </Box>
    </Box>
  );
};

