// <auto-generated>
//     This code was generated by TargCC Component Generator.
//     Table: OrderItem
//     Generated: 2025-12-07 16:44:36
// </auto-generated>

import React from 'react';
import { useNavigate } from 'react-router-dom';
import * as XLSX from 'xlsx';
import { DataGrid, GridColDef, GridActionsCellItem } from '@mui/x-data-grid';
import { Button, Box, CircularProgress, Alert, TextField, Paper, IconButton } from '@mui/material';
import { Edit as EditIcon, Delete as DeleteIcon, Add as AddIcon, FileDownload as FileDownloadIcon, Clear as ClearIcon, Search as SearchIcon } from '@mui/icons-material';
import { useOrderItems, useDeleteOrderItem } from '../../hooks/useOrderItem';
import type { OrderItem, OrderItemFilters } from '../../types/OrderItem.types';


export const OrderItemList: React.FC = () => {
  const navigate = useNavigate();
  const [filters, setFilters] = React.useState<OrderItemFilters>({});
  const [localFilters, setLocalFilters] = React.useState<OrderItemFilters>({});
  const { data: orderItems, isLoading, error } = useOrderItems(filters);
  const { mutate: deleteEntity } = useDeleteOrderItem();

  const handleApplyFilters = () => {
    setFilters(localFilters);
  };

  const handleClearFilters = () => {
    setLocalFilters({});
    setFilters({});
  };

  const handleExportToExcel = () => {
    if (!orderItems || orderItems.length === 0) {
      alert('No data to export');
      return;
    }

    const ws = XLSX.utils.json_to_sheet(orderItems);
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, 'OrderItems');
    XLSX.writeFile(wb, `OrderItems_${new Date().toISOString().split('T')[0]}.xlsx`);
  };

  const columns: GridColDef<OrderItem>[] = [
    { field: 'id', headerName: 'Id', width: 90 },
    { field: 'orderID', headerName: 'OrderID', width: 150 },
    { field: 'productID', headerName: 'ProductID', width: 150 },
    { field: 'quantity', headerName: 'Quantity', width: 150 },
    { field: 'unitPrice', headerName: 'UnitPrice', width: 150 },
    { field: 'lineTotal', headerName: 'LineTotal', width: 150 },
    {
      field: 'actions',
      type: 'actions',
      headerName: 'Actions',
      width: 100,
      getActions: (params) => [
        <GridActionsCellItem
          icon={<EditIcon />}
          label="Edit"
          onClick={() => navigate(`/orderItems/${params.id}`)}
        />,
        <GridActionsCellItem
          icon={<DeleteIcon />}
          label="Delete"
          onClick={() => {
            if (confirm('Are you sure?')) {
              deleteEntity(params.id as number);
            }
          }}
        />,
      ],
    },
  ];


  if (isLoading) {
    return <CircularProgress />;
  }

  if (error) {
    return <Alert severity="error">Failed to load orderItems</Alert>;
  }

  return (
    <Box sx={{ height: 'calc(100vh - 200px)', width: '100%', display: 'flex', flexDirection: 'column' }}>
      <Box sx={{ mb: 2, display: 'flex', gap: 2 }}>
        <Button
          variant="contained"
          startIcon={<AddIcon />}
          onClick={() => navigate('/orderItems/new')}
        >
          Create OrderItem
        </Button>
        <Button
          variant="outlined"
          startIcon={<FileDownloadIcon />}
          onClick={handleExportToExcel}
        >
          Export to Excel
        </Button>
      </Box>
      <Paper sx={{ p: 2, mb: 2 }}>
        <Box sx={{ display: 'flex', gap: 2, flexWrap: 'wrap', alignItems: 'center' }}>
          <TextField
            label="OrderID"
            type="number"
            size="small"
            sx={{ minWidth: 200 }}
            value={localFilters.orderID ?? ''}
            onChange={(e) => setLocalFilters(prev => ({
              ...prev,
              orderID: e.target.value ? Number(e.target.value) : undefined
            }))}
            onKeyDown={(e) => {
              if (e.key === 'Enter') {
                handleApplyFilters();
              }
            }}
          />
          <TextField
            label="ProductID"
            type="number"
            size="small"
            sx={{ minWidth: 200 }}
            value={localFilters.productID ?? ''}
            onChange={(e) => setLocalFilters(prev => ({
              ...prev,
              productID: e.target.value ? Number(e.target.value) : undefined
            }))}
            onKeyDown={(e) => {
              if (e.key === 'Enter') {
                handleApplyFilters();
              }
            }}
          />
          <Button
            variant="contained"
            color="primary"
            onClick={handleApplyFilters}
            size="small"
          >
            Apply Filters
          </Button>
          <Button
            variant="outlined"
            onClick={handleClearFilters}
            size="small"
          >
            Clear
          </Button>
        </Box>
      </Paper>

      <Box sx={{ flex: 1, minHeight: 0 }}>
        <DataGrid
          rows={orderItems || []}
          columns={columns}
          initialState={{
            pagination: { paginationModel: { pageSize: 10 } },
          }}
          pageSizeOptions={[5, 10, 25, 100]}
          checkboxSelection
          disableRowSelectionOnClick
        />
      </Box>
    </Box>
  );
};

