// <auto-generated>
//     This code was generated by TargCC
//     Generated for: ActiveRestrictions (Command)
//     Generation date: 2025-12-17 17:47:19
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using MediatR;
using UpayCard.RiskManagement.Application.Common.Models;

namespace UpayCard.RiskManagement.Application.Features.ActiveRestrictionses.Commands;

/// <summary>
/// Command to create a new ActiveRestrictions.
/// </summary>
public record CreateActiveRestrictionsCommand : IRequest<Result<long>>
{
    /// <summary>
    /// Gets or sets the TableName_ActiveRestrictions.
    /// </summary>
    public bool? TableName_ActiveRestrictions { get; init; }

    /// <summary>
    /// Gets or sets the MaxAllowedAmount.
    /// </summary>
    public decimal? MaxAllowedAmount { get; init; }

    /// <summary>
    /// Gets or sets the ValidFrom.
    /// </summary>
    public DateTime ValidFrom { get; init; }

    /// <summary>
    /// Gets or sets the ValidUntil.
    /// </summary>
    public DateTime? ValidUntil { get; init; }

    /// <summary>
    /// Gets or sets the BlockReason.
    /// </summary>
    public string BlockReason { get; init; }

    /// <summary>
    /// Gets or sets the TriggerRuleID.
    /// </summary>
    public long? TriggerRuleID { get; init; }

    /// <summary>
    /// Gets or sets the TriggerEventID.
    /// </summary>
    public long? TriggerEventID { get; init; }

    /// <summary>
    /// Gets or sets the DeletedOn.
    /// </summary>
    public DateTime? DeletedOn { get; init; }

    /// <summary>
    /// Gets or sets the DeletedBy.
    /// </summary>
    public string DeletedBy { get; init; }

    /// <summary>
    /// Gets or sets the UpdatingLoginID.
    /// </summary>
    public long? UpdatingLoginID { get; init; }

}
