// <auto-generated>
//     This code was generated by TargCC Component Generator.
//     Table: vwCustomerCardStatusData
//     Generated: 2025-12-11 14:19:37
// </auto-generated>

import React from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { Box, Typography, Button, CircularProgress, Alert, Card, CardContent, Grid } from '@mui/material';
import { Edit as EditIcon, Delete as DeleteIcon, ArrowBack as ArrowBackIcon } from '@mui/icons-material';
import type { VwCustomerCardStatusData } from '../../types/VwCustomerCardStatusData.types';


export const VwCustomerCardStatusDataDetail: React.FC = () => {
  const navigate = useNavigate();
  const { id } = useParams<{ id: string }>();
  // VIEWs are read-only - Detail page not applicable
  const isLoading = false;
  const error = null;
  const entity = null;

  if (isLoading) {
    return <CircularProgress />;
  }

  if (error || !entity) {
    return <Alert severity="error">Failed to load vwCustomerCardStatusData</Alert>;
  }

  return (
    <Box sx={{ maxWidth: 800 }}>
      <Box sx={{ mb: 2, display: 'flex', gap: 2 }}>
        <Button
          variant="outlined"
          startIcon={<ArrowBackIcon />}
          onClick={() => navigate('/vwCustomerCardStatusDatas')}
        >
          Back
        </Button>
      </Box>

      <Card>
        <CardContent>
          <Typography variant="h5" component="h2" gutterBottom>
            VwCustomerCardStatusData Details
          </Typography>
      <Grid container spacing={2}>
        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            Id
          </Typography>
          <Typography variant="body1">
            {entity.id}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            CustomerID
          </Typography>
          <Typography variant="body1">
            {entity.customerID}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            HasCard
          </Typography>
          <Typography variant="body1">
            {entity.hasCard ? 'Yes' : 'No'}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            IsraelIDNumber
          </Typography>
          <Typography variant="body1">
            {entity.israelIDNumber}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            Email
          </Typography>
          <Typography variant="body1">
            {entity.email}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            CellphoneNumber
          </Typography>
          <Typography variant="body1">
            {entity.cellphoneNumber}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            CardClubID
          </Typography>
          <Typography variant="body1">
            {entity.cardClubID}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            Cid
          </Typography>
          <Typography variant="body1">
            {entity.cid}
          </Typography>
        </Grid>

        <Grid item xs={12} sm={6}>
          <Typography variant="subtitle2" color="text.secondary">
            CardLast4Numbers
          </Typography>
          <Typography variant="body1">
            {entity.cardLast4Numbers}
          </Typography>
        </Grid>

      </Grid>

        </CardContent>
      </Card>
    </Box>
  );
};

