// <auto-generated>
//     This code was generated by TargCC
//     Generated for: vwReportCustomerWalletBalanceData (Handler)
//     Generation date: 2025-12-16 10:51:41
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using MediatR;
using Microsoft.Extensions.Logging;
using UpayCard.RiskManagement.Application.Common.Models;
using UpayCard.RiskManagement.Domain.Entities;
using UpayCard.RiskManagement.Domain.Interfaces;

namespace UpayCard.RiskManagement.Application.Features.VwReportCustomerWalletBalanceDatas.Commands;

/// <summary>
/// Handles the CreateVwReportCustomerWalletBalanceDataCommand request.
/// </summary>
public class CreateVwReportCustomerWalletBalanceDataHandler : IRequestHandler<CreateVwReportCustomerWalletBalanceDataCommand, Result<int>>
{
    private readonly IVwReportCustomerWalletBalanceDataRepository _repository;
    private readonly ILogger<CreateVwReportCustomerWalletBalanceDataHandler> _logger;

    /// <summary>
    /// Initializes a new instance of the <see cref="CreateVwReportCustomerWalletBalanceDataHandler"/> class.
    /// </summary>
    public CreateVwReportCustomerWalletBalanceDataHandler(
        IVwReportCustomerWalletBalanceDataRepository repository,
        ILogger<CreateVwReportCustomerWalletBalanceDataHandler> logger)
    {
        _repository = repository ?? throw new ArgumentNullException(nameof(repository));
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
    }

    /// <inheritdoc/>
    public async Task<Result<int>> Handle(CreateVwReportCustomerWalletBalanceDataCommand request, CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(request);

        _logger.LogDebug("Creating new vwReportCustomerWalletBalanceData");

        try
        {
            var entity = new vwReportCustomerWalletBalanceData
            {
                ID = request.ID,
                CustomerID = request.CustomerID,
                EffectiveDate = request.EffectiveDate,
                BalanceOnEffectiveDate = request.BalanceOnEffectiveDate,
                PresentRawBalance = request.PresentRawBalance,
                PresentCommittedBalance = request.PresentCommittedBalance,
                CustomerText = request.CustomerText
            };

            await _repository.AddAsync(entity, cancellationToken);

            _logger.LogInformation("vwReportCustomerWalletBalanceData created successfully with ID: {Id}", entity.Id);

            return Result<int>.Success(entity.Id);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error creating vwReportCustomerWalletBalanceData");
            throw;
        }
    }
}
