// <auto-generated>
//     This code was generated by TargCC
//     Generated for: RequestedTransaction (Handler)
//     Generation date: 2025-12-18 08:27:26
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using MediatR;
using Microsoft.Extensions.Logging;
using UpayCard.RiskManagement.Application.Common.Models;
using UpayCard.RiskManagement.Domain.Entities;
using UpayCard.RiskManagement.Domain.Interfaces;

namespace UpayCard.RiskManagement.Application.Features.RequestedTransactions.Commands;

/// <summary>
/// Handles the CreateRequestedTransactionCommand request.
/// </summary>
public class CreateRequestedTransactionHandler : IRequestHandler<CreateRequestedTransactionCommand, Result<long>>
{
    private readonly IRequestedTransactionRepository _repository;
    private readonly ILogger<CreateRequestedTransactionHandler> _logger;

    /// <summary>
    /// Initializes a new instance of the <see cref="CreateRequestedTransactionHandler"/> class.
    /// </summary>
    public CreateRequestedTransactionHandler(
        IRequestedTransactionRepository repository,
        ILogger<CreateRequestedTransactionHandler> logger)
    {
        _repository = repository ?? throw new ArgumentNullException(nameof(repository));
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
    }

    /// <inheritdoc/>
    public async Task<Result<long>> Handle(CreateRequestedTransactionCommand request, CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(request);

        _logger.LogDebug("Creating new RequestedTransaction");

        try
        {
            var entity = new RequestedTransaction
            {
                TableName_RequestedTransaction = request.TableName_RequestedTransaction,
                InitiatingCustomerID = request.InitiatingCustomerID,
                TargetCustomerID = request.TargetCustomerID,
                TargetCustomerEmailOrPhone = request.TargetCustomerEmailOrPhone,
                TargetCustomerName = request.TargetCustomerName,
                CustomerTransactionDescription = request.CustomerTransactionDescription,
                DefiningAmount = request.DefiningAmount,
                CreditCardID = request.CreditCardID,
                AmountPaidByCreditCard = request.AmountPaidByCreditCard,
                NumberOfPaymentsByCreditCard = request.NumberOfPaymentsByCreditCard,
                FirstPaymentAmountByCreditCard = request.FirstPaymentAmountByCreditCard,
                OtherPaymentsAmountByCreditCard = request.OtherPaymentsAmountByCreditCard,
                AmountPaidByBit = request.AmountPaidByBit,
                AmountPaidByWallet = request.AmountPaidByWallet,
                TotalAmountPaidByPayer = request.TotalAmountPaidByPayer,
                AmountReceivedByReceiver = request.AmountReceivedByReceiver,
                lkpDefiningAmountCurrency_Currency = request.lkpDefiningAmountCurrency_Currency,
                PrepaidCardID = request.PrepaidCardID,
                DistributorID = request.DistributorID,
                CodeToGiveChanger = request.CodeToGiveChanger,
                LoggedAlertID = request.LoggedAlertID,
                ErrorText = request.ErrorText,
                DeletedBy = request.DeletedBy,
                DeletedOn = request.DeletedOn,
                UpdatingLoginID = request.UpdatingLoginID,
                SecurityCodeApproved = request.SecurityCodeApproved,
                InitiatingCustomerEmailOrPhone = request.InitiatingCustomerEmailOrPhone,
                InitiatingCustomerName = request.InitiatingCustomerName,
                ExchangeRateToILSUsed = request.ExchangeRateToILSUsed,
                TargetNonCustomerID = request.TargetNonCustomerID,
                GroupRequestedTransactionID = request.GroupRequestedTransactionID,
                ReceivingCustomerID = request.ReceivingCustomerID,
                PayingCustomerID = request.PayingCustomerID,
                RepExchangeRateToILS = request.RepExchangeRateToILS,
                DefiningAmountILS = request.DefiningAmountILS
            };

            await _repository.AddAsync(entity, cancellationToken);

            _logger.LogInformation("RequestedTransaction created successfully with ID: {Id}", entity.ID);

            return Result<long>.Success(entity.ID);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error creating RequestedTransaction");
            throw;
        }
    }
}
