// <auto-generated>
//     This code was generated by TargCC Component Generator.
//     Table: c_Language
//     Generated: 2025-12-15 13:48:29
// </auto-generated>

import React, { useEffect } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { useForm } from 'react-hook-form';
import { TextField, Button, Box, CircularProgress } from '@mui/material';
import { useLanguage, useCreateLanguage, useUpdateLanguage } from '../../hooks/useLanguage';
import type { CreateLanguageRequest, UpdateLanguageRequest } from '../../types/Language.types';


export const LanguageForm: React.FC = () => {
  const navigate = useNavigate();
  const { id } = useParams<{ id: string }>();
  const languageId = id && id !== 'new' ? Number(id) : undefined;
  const isEdit = !!languageId;

  const { data: existingLanguage, isPending: isLoadingEntity } = useLanguage(languageId || null);

  const {
    register,
    handleSubmit,
    reset,
    formState: { errors },
  } = useForm<CreateLanguageRequest>({
    defaultValues: {
    },
  });

  // Update form when data loads
  useEffect(() => {
    if (existingLanguage) {
      reset(existingLanguage);
    }
  }, [existingLanguage, reset]);

  const { mutate: createEntity, isPending: isCreating } = useCreateLanguage();
  const { mutate: updateEntity, isPending: isUpdating } = useUpdateLanguage();

  const isSubmitting = isCreating || isUpdating;

  const onSubmit = (data: CreateLanguageRequest) => {
    if (isEdit && languageId) {
      updateEntity(
        { id: languageId, data: data as UpdateLanguageRequest },
        { onSuccess: () => navigate('/languages') }
      );
    } else {
      createEntity(data, { onSuccess: () => navigate('/languages') });
    }
  };

  if (isEdit && isLoadingEntity) {
    return <CircularProgress />;
  }

  return (
    <Box component="form" onSubmit={handleSubmit(onSubmit)} sx={{ maxWidth: 600 }}>
      <TextField
        label="Code"
        type="text"
        fullWidth
        margin="normal"
        {...register('code', { maxLength: { value: 50, message: 'Maximum length is 50' } })}
        error={!!errors.code}
        helperText={errors.code?.message}
      />

      <TextField
        label="Name"
        type="text"
        fullWidth
        margin="normal"
        {...register('name', { maxLength: { value: 50, message: 'Maximum length is 50' } })}
        error={!!errors.name}
        helperText={errors.name?.message}
      />

      <TextField
        label="NameLoc"
        type="text"
        fullWidth
        margin="normal"
        {...register('nameLoc', { maxLength: { value: 100, message: 'Maximum length is 100' } })}
        error={!!errors.nameLoc}
        helperText={errors.nameLoc?.message}
      />

      <TextField
        label="Culture"
        type="text"
        fullWidth
        margin="normal"
        {...register('culture', { maxLength: { value: 10, message: 'Maximum length is 10' } })}
        error={!!errors.culture}
        helperText={errors.culture?.message}
      />



      <Box sx={{ mt: 2, display: 'flex', gap: 2 }}>
        <Button type="submit" variant="contained" disabled={isSubmitting}>
          {isEdit ? 'Update' : 'Create'}
        </Button>
        <Button variant="outlined" onClick={() => navigate('/languages')}>
          Cancel
        </Button>
      </Box>
    </Box>
  );
};

