// <auto-generated>
//     This code was generated by TargCC Component Generator.
//     Table: ccvwComboList_UIText
//     Generated: 2025-12-15 09:25:39
// </auto-generated>

import React from 'react';
import { Box, Alert } from '@mui/material';


export const CcvwComboListUITextDetail: React.FC = () => {
  return (
    <Box sx={{ maxWidth: 800 }}>
      <Alert severity="info">
        CcvwComboListUIText is a VIEW (read-only). Detail view is not applicable.
        Please use the List view to see the data.
      </Alert>
    </Box>
  );
};

