// <auto-generated>
//     This code was generated by TargCC
//     Generated for: ExternalCustomer (Command)
//     Generation date: 2025-12-16 09:26:46
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using MediatR;
using UpayCard.RiskManagement.Application.Common.Models;

namespace UpayCard.RiskManagement.Application.Features.ExternalCustomers.Commands;

/// <summary>
/// Command to create a new ExternalCustomer.
/// </summary>
public record CreateExternalCustomerCommand : IRequest<Result<int>>
{
    /// <summary>
    /// Gets or sets the TableName_ExternalCustomer.
    /// </summary>
    public bool? TableName_ExternalCustomer { get; init; }

    /// <summary>
    /// Gets or sets the CustomerID.
    /// </summary>
    public long CustomerID { get; init; }

    /// <summary>
    /// Gets or sets the enmExternalService.
    /// </summary>
    public string enmExternalService { get; init; } = string.Empty;

    /// <summary>
    /// Gets or sets the ExternalCustomerIdentifier.
    /// </summary>
    public string ExternalCustomerIdentifier { get; init; }

    /// <summary>
    /// Gets or sets the WhenCustomerDetailsUpdatedAtExternalService.
    /// </summary>
    public DateTimeOffset? WhenCustomerDetailsUpdatedAtExternalService { get; init; }

    /// <summary>
    /// Gets or sets the WhenDocumentationRecdFromExternalService.
    /// </summary>
    public DateTimeOffset? WhenDocumentationRecdFromExternalService { get; init; }

    /// <summary>
    /// Gets or sets the enmExternalCustomerStatus.
    /// </summary>
    public string enmExternalCustomerStatus { get; init; }

    /// <summary>
    /// Gets or sets the StatusDescription.
    /// </summary>
    public string StatusDescription { get; init; }

    /// <summary>
    /// Gets or sets the LastLoggedAlertID.
    /// </summary>
    public long? LastLoggedAlertID { get; init; }

    /// <summary>
    /// Gets or sets the Comments.
    /// </summary>
    public string Comments { get; init; }

    /// <summary>
    /// Gets or sets the WhenLastUsed.
    /// </summary>
    public DateTimeOffset? WhenLastUsed { get; init; }

    /// <summary>
    /// Gets or sets the AddedBy.
    /// </summary>
    public string AddedBy { get; init; } = string.Empty;

    /// <summary>
    /// Gets or sets the AddedOn.
    /// </summary>
    public DateTime AddedOn { get; init; }

    /// <summary>
    /// Gets or sets the ChangedBy.
    /// </summary>
    public string ChangedBy { get; init; }

    /// <summary>
    /// Gets or sets the ChangedOn.
    /// </summary>
    public DateTime? ChangedOn { get; init; }

    /// <summary>
    /// Gets or sets the DeletedBy.
    /// </summary>
    public string DeletedBy { get; init; }

    /// <summary>
    /// Gets or sets the DeletedOn.
    /// </summary>
    public DateTime? DeletedOn { get; init; }

    /// <summary>
    /// Gets or sets the UpdatingLoginID.
    /// </summary>
    public long? UpdatingLoginID { get; init; }

}
