// <auto-generated>
//     This code was generated by TargCC Component Generator.
//     Table: ccvwComboList_RiskRule
//     Generated: 2025-12-17 08:03:52
// </auto-generated>

import React from 'react';
import { Box, Alert } from '@mui/material';


export const CcvwComboListRiskRuleDetail: React.FC = () => {
  return (
    <Box sx={{ maxWidth: 800 }}>
      <Alert severity="info">
        CcvwComboListRiskRule is a VIEW (read-only). Detail view is not applicable.
        Please use the List view to see the data.
      </Alert>
    </Box>
  );
};

