// <auto-generated>
//     This code was generated by TargCC
//     Generated for: vwReportCustomerWalletBalanceForLawyer (Handler)
//     Generation date: 2025-12-16 09:26:48
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using MediatR;
using Microsoft.Extensions.Logging;
using UpayCard.RiskManagement.Application.Common.Models;
using UpayCard.RiskManagement.Domain.Entities;
using UpayCard.RiskManagement.Domain.Interfaces;

namespace UpayCard.RiskManagement.Application.Features.VwReportCustomerWalletBalanceForLawyers.Commands;

/// <summary>
/// Handles the CreateVwReportCustomerWalletBalanceForLawyerCommand request.
/// </summary>
public class CreateVwReportCustomerWalletBalanceForLawyerHandler : IRequestHandler<CreateVwReportCustomerWalletBalanceForLawyerCommand, Result<int>>
{
    private readonly IVwReportCustomerWalletBalanceForLawyerRepository _repository;
    private readonly ILogger<CreateVwReportCustomerWalletBalanceForLawyerHandler> _logger;

    /// <summary>
    /// Initializes a new instance of the <see cref="CreateVwReportCustomerWalletBalanceForLawyerHandler"/> class.
    /// </summary>
    public CreateVwReportCustomerWalletBalanceForLawyerHandler(
        IVwReportCustomerWalletBalanceForLawyerRepository repository,
        ILogger<CreateVwReportCustomerWalletBalanceForLawyerHandler> logger)
    {
        _repository = repository ?? throw new ArgumentNullException(nameof(repository));
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
    }

    /// <inheritdoc/>
    public async Task<Result<int>> Handle(CreateVwReportCustomerWalletBalanceForLawyerCommand request, CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(request);

        _logger.LogDebug("Creating new vwReportCustomerWalletBalanceForLawyer");

        try
        {
            var entity = new vwReportCustomerWalletBalanceForLawyer
            {
                ID = request.ID,
                CustomerID = request.CustomerID,
                EffectiveDate = request.EffectiveDate,
                PresentRawBalance = request.PresentRawBalance,
                enmCustomerType = request.enmCustomerType
            };

            await _repository.AddAsync(entity, cancellationToken);

            _logger.LogInformation("vwReportCustomerWalletBalanceForLawyer created successfully with ID: {Id}", entity.Id);

            return Result<int>.Success(entity.Id);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error creating vwReportCustomerWalletBalanceForLawyer");
            throw;
        }
    }
}
