// <auto-generated>
//     This code was generated by TargCC
//     Generated for: CustomerWallet (Query)
//     Generation date: 2025-12-27 21:28:28
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using MediatR;
using UpayCard.RiskManagement.Application.Common.Models;
using UpayCard.RiskManagement.Application.DTOs;
using UpayCard.RiskManagement.Domain.Common;

namespace UpayCard.RiskManagement.Application.Features.CustomerWallets.Queries;

/// <summary>
/// Query to retrieve all CustomerWallets with server-side filtering, sorting, and pagination.
/// </summary>
public record GetCustomerWalletsQuery : IRequest<Result<PagedResult<CustomerWalletDto>>>
{
    /// <summary>
    /// Gets or initializes the filters to apply.
    /// </summary>
    public CustomerWalletFilters? Filters { get; init; }

    /// <summary>
    /// Gets or initializes the page number (1-based). Default is 1.
    /// </summary>
    public int Page { get; init; } = 1;

    /// <summary>
    /// Gets or initializes the page size. Default is 100.
    /// </summary>
    public int PageSize { get; init; } = 100;

    /// <summary>
    /// Gets or initializes the field to sort by. Default is "Id".
    /// </summary>
    public string? SortBy { get; init; } = "Id";

    /// <summary>
    /// Gets or initializes the sort direction. Default is "asc".
    /// </summary>
    public string SortDirection { get; init; } = "asc";
}

/// <summary>
/// CustomerWallet filters class for filtering queries.
/// </summary>
public class CustomerWalletFilters
{
    // TODO: Add filter properties based on table columns
    // Example: public string? Name { get; set; }
}
