// <auto-generated>
//     This code was generated by TargCC
//     Generated for: GovtReportPayment (Command)
//     Generation date: 2025-12-17 21:20:41
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using MediatR;
using UpayCard.RiskManagement.Application.Common.Models;

namespace UpayCard.RiskManagement.Application.Features.GovtReportPayments.Commands;

/// <summary>
/// Command to create a new GovtReportPayment.
/// </summary>
public record CreateGovtReportPaymentCommand : IRequest<Result<long>>
{
    /// <summary>
    /// Gets or sets the TableName_GovtReportPayment.
    /// </summary>
    public bool? TableName_GovtReportPayment { get; init; }

    /// <summary>
    /// Gets or sets the GovtReport00ID.
    /// </summary>
    public long? GovtReport00ID { get; init; }

    /// <summary>
    /// Gets or sets the PaymentDay.
    /// </summary>
    public DateTime? PaymentDay { get; init; }

    /// <summary>
    /// Gets or sets the TotalAmount.
    /// </summary>
    public decimal? TotalAmount { get; init; }

    /// <summary>
    /// Gets or sets the NumberOfTransactions.
    /// </summary>
    public int? NumberOfTransactions { get; init; }

    /// <summary>
    /// Gets or sets the DeletedBy.
    /// </summary>
    public string DeletedBy { get; init; }

    /// <summary>
    /// Gets or sets the DeletedOn.
    /// </summary>
    public DateTime? DeletedOn { get; init; }

    /// <summary>
    /// Gets or sets the UpdatingLoginID.
    /// </summary>
    public long? UpdatingLoginID { get; init; }

}
